### ISSUE TITLE
챕터 1 전체 기획서 보완

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#101]
- #58 
위 내용을 보완할 것 같습니다

- #77 
- #75 

위 작업을 하면서 바뀐 사항들을 주로 보완할 거 같습니다.

***
시스템 기획 / 레벨 디자인은 추가 보완이 필요한 상태여서 이 부분은 기획자 판단하에 제외하여 간단하게 진행했습니다.

이제 챕터1 전체 기획은 보완하지 않고, 시스템 기획과 레벨 디자인 등이 확립된 후에 초반에 만들었던 **총 기획서로 편입**하여 하나로 관리할 계획입니다.

[현재 진행정도에 맞게 살짝 수정한 챕터 1 기획서](https://drive.google.com/file/d/1xhWt5d1B7U1AeXoc6ZrO3eCUi3zrDTKN/view?usp=drive_link)

***

주요 수정 내역
- 챕터 1 사건 플로우 보완
- 맵 배경 설정, 나온 레벨디자인 크기에 맞게 수정
- 등장 NPC 캐릭터 '마마고' 추가
- 기본 시스템 논의했던 방안대로 수정 (소지품 삭제 등)
- UI 퍼즐 시스템 속 미니 퍼즐 형태 고려중
- 챕터 1 플레이어 목표 정리 + 게임 진행 플로우 = 위 사건 플로우 보완 맞추어 수정

**Comment by fkdl0048** [comment]
전체적으로 만들어진 기획을 하나로 합쳐서 보니까 되게 이해가 잘 되네요

다음 주 진행 상황에선 기획서 토대로 실제 결과물이 나오니 그 때 회의 때 같이 이야기 해보면서 맞춰보면 좋을 것 같습니다
