### ISSUE TITLE
세계관 보완 작업

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#102]
- #14 

위 내용을 현재까지 진행된 사항에 맞추어 보완할 예정입니다.

***

[세계관 보완 완료](https://drive.google.com/file/d/19hduwLBHaMFFXZFN0UG4VJElcjwTiof9/view?usp=drive_link)

- 약간의 워딩 수정
- 탄생의 역사 수정
- 마을 지도 변경 내역 추가
- 용어 정리 추가
- 떨어지는 게임에 대한 세계관 설명 추가
- 거주민에 대한 내용 개선 및 추가
- 캐릭터에 대한 능력 설명 추가
- 컨셉상 달라진 부분 삭제
- 엔딩과의 연결 및 게임 메시지 부분 추가 및 수정 (보완 필요)

**Comment by fkdl0048** [comment]
# 피드백

너무 좋습니다. 메인 기획문서로 병합해도 될 것 같습니다.
