### ISSUE TITLE
캐릭터 추가 기획 (마마고)

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#103]
마마고 컴퍼니에서 일할 캐릭터인 마마고 캐릭터를 기획합니다.

***

[마마고 기획](https://drive.google.com/file/d/1mfoE6_ZdmVQ0pvq3ypDIXoG1nhUdmLSg/view?usp=drive_link)

네이버 번역기인 파파고를 컨셉으로 하여, 마마고를 기획했습니다.
마마고는 파파고와 달리 분홍색의 깃털을 가진 암컷 앵무새인데,
마마고 컴퍼니라는 기업의 CEO로서, 다른 앵무새와 달리 신중한 편입니다.
(보통 미디어 매체에서 앵무새는 개그 캐릭, 수다쟁이로 묘사하는 것에 정반대)

***

엑스트라 NPC (외형 위주)를 기획할 때는 표 대신 간단하게 구글 ppt를 활용할 예정입니다.
엑스트라 NPC는 작품에서 주요한 역할을 맞지 않고, 마을 인원수 채우는 느낌이 강함.
(딱 엑스트라)

**Comment by fkdl0048** [comment]
# 피드백

- 성장 배경, 이주 배경에서 원래 거주하고 있다가 라플리에 의해 생긴 건물에 거주하게 되는걸까요?
  - 개인적인 생각으로 라플리에 의해 생성된 주민이라는 설정이면 더 매력적일 수 있다..?
  - 상점 NPC라서 좀 더 스토리보단? 하나의 장치로 존재하는게 좋을 수 있을 것 같습니다.
- 디자인 너무 좋습니다..(피드백은 아니지만..)

**Comment by wooyn730** [comment]
신중하고 올백머리에 정장이라면 아예 카리스마 있는 눈도 좋을 것 같습니다

저는 분홍 올백머리를 들으니 왠지 오버워치 자리야가 떠오르네요..!!

> 그 중에서는 앵무새가 아닌데 앵무새인 척 하는 직원 또한 있습니다

ㄴ 이 부분 너무 제 취향입니다 소소하게 재밌을 것 같아요 ^_^👍

**Comment by CreatorLDH** [comment]
피드백 감사합니다.

정안님
1. 일단 본래 존재하던 캐릭터인데, 라플리에 의해 생긴 건물에 상주하게 되었다는 설정을 넣긴 했습니다.
2. 일단 캐릭터 이해를 돋기 위한 배경 설정으로 부여한 요소라서, 게임 내에서 표현은 거의 없을 거 같습니다.  NPC 분류가 상인이라!

우연님
1. 카리스마 눈 좋습니다!!! 
4. 기존 파파고 머리가 올백 느낌같아서 그랬는데, 자리야도 어찌보면 좋은 레퍼런스네요.
