### ISSUE TITLE
로그라이크 시스템 속 몬스터 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#104]
약 2마리의 일반 몹과 보스 몹 기획 예정입니다.

시간나면 로그라이크 시스템에 대한 생각도 추가할 계획입니다.

[몬스터 기획](https://drive.google.com/file/d/1GrXR3VqZata0Xc0QYm2sgtXQx5KOIgKN/view?usp=drive_link)

아이디에이션이 부족한 거 같아 추가적인 의견 환영합니다.

정리)
1. 깨진 픽셀 그래픽을 가진 도형 형체의 몬스터
2. 깨진 픽셀 그래픽을 가진 보스 몬스터, 이 몬스터는 자신의 형태를 변형할 수 있음
3. 월-E를 이미테이션한 캐릭터
4. 게임 갤러그 활용
5. 게임 핀볼 활용
6. 마인크래프트 히로빈 / 포트리스 등
7. 1~3번 혼합

**Comment by CreatorLDH** [comment]
+ 어제 끝내려고 했는데, 과제 이슈로 오늘 끝낸 점 양해 부탁드립니다요~

**Comment by fkdl0048** [comment]
회의 때 이야기 했지만 정리하고자..

게임이 분해되면서 섞인 몬스터(미씽노)와 같은 망가진, 이상한 몬스터 컨셉 좋은 것 같습니다~
