### ISSUE TITLE
캐릭터 컨셉 아트 제작 (NPC-2)

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#114]
트루커, 미카엘 캐릭터 아이디어 스케치

이번주에 좀 많이 정신없었어서 Issue 세우는걸 깜빡했습니다. 다음 버전부턴 꼬박꼬박 올리도록 하겠습니다

**Comment by royalbluesm** [comment]
이번주 할당량이었던 캐릭터 2인의 작업이 늦어질 것 같아, 다음주에 엑스트라 캐릭터와 같이(11/13) 한꺼번에 작업물 올리도록 하겠습니다.

**Comment by CreatorLDH** [comment]
이따 정확히 어떤 캐릭터를 구상해 나갈 지 잠시 생각해 보아요!
