### ISSUE TITLE
팩맘 사운드 리소스 제작

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#116]
#118 에 따라 팩맘 사운드 리소스 제작해봤습니다.

![팩맘 사운드 소스 정리](https://github.com/GG-Studio-990001/GameOver/assets/145998609/9699c4a5-e650-41c5-845e-f4886b4db28b)

팀원 분들이 보기 편하게 제가 작업한 소스들 표시해봤습니다.

- [3번 배경음](https://drive.google.com/file/d/1unaYJOskVmNwjqGKvlYDOLumTTlCXSA5/view?usp=drive_link) : 원본 아웃트로 참고해서 너무 비슷하지는 않게, 망가진 듯한 사운드를 만들어보려고 했습니다.

- [6번 효과음](https://drive.google.com/file/d/1S1bqlZ3Ug0CEUPrN8S0jDSEfRZlCaIRS/view?usp=drive_link) : 영상 봐도 효과음 길이를 어떻게 해야할 지 모르겠어서 일단 팩맘이 유령에 닿고 사라지는 타이밍에 맞춰서 작업했습니다.
8비트 사운드로 간단하게 느낌을 표현해보려고 했습니다.

- [7번 효과음](https://drive.google.com/file/d/1qCKU6uLz4mlJq3KeeRMGGMgBNY-HpxFA/view?usp=drive_link) : 타이밍 + 경고음 같은 느낌의 사운드를 표현해보려고 했습니다. 같은 소스로 10초 동안 울려도 괜찮을 것 같아서 이렇게 작업해봤습니다.

- [8번 효과음](https://drive.google.com/file/d/1FteesUX2jfyhMLEQpD1o1OLpU5tXK5wi/view?usp=drive_link) : 일단 제작해보긴 해봤는데 비주얼적인 게 없다보니 제가 임의로 상상하면서 해봤습니다. 고전 게임 패러디이기도 하고 코인 소리가 너무 화려하면 이상할 것 같아서 깔끔하게 만들어보려고 했습니다. 

- [9번 효과음](https://drive.google.com/file/d/1_JtBDgm_o1uKuYyYwdo1VagJnBIz2TLM/view?usp=drive_link) : 주인공이다보니 특별하고 마법스러운 느낌을 표현해보려고 했습니다. 

- [10번 효과음](https://drive.google.com/file/d/1IEFa5VgfNF-FKFCTjkJtT8dZcQTv6ZmL/view?usp=drive_link) : 동호님이 문서에 써주신 팩맨 플레이 사운드 13초의 사운드를 가져왔습니다. 컨셉 사운드 때 올렸던 사운드와 동일합니다!

- 13번 효과음 : 먼지 유령 대화 효과음이여서 동물의 숲 주민 목소리로 해보고싶어서 비슷하게 만들어봤는데
이왕 만드는거 메세지도 넣고싶어서 [Don't forget me](https://drive.google.com/file/d/1dLrB0bM6QICUwryqi654CveJpGKCwzG1/view?usp=drive_link), [remember your emotions](https://drive.google.com/file/d/14yBBr8_rlCf5mKfXNfI3u6zon5gNJlE7/view?usp=drive_link) 알파벳을 녹음해서
사운드 제작 해봤습니다. 들어보니 너무 알파벳 같기도 하고 .. 괜찮은가요?

이번주 제작해보면서 느낀 점인데 팩맘 완성이 가까워지면,, 그 때 제대로 손볼 수 있을 것 같습니다..! 
아직 세세한 타이밍이라던지 효과음이 몇 초 정도 필요한 지가 안 나온 상황이기 때문에 지금은 사운드가 짜잔- 할 수가 없네여..ㅠ

원하시는 사운드가 있으시거나 하고싶은 말 있으시면 언제든 피드백 주시면 감사하겠습니다 -!!

**Comment by CreatorLDH** [comment]
너무 고생하셨습니다!!

3번 : 저는 맘에 듭니다!

6번 : 잡혀서 발생하는 효과음이군요.
더불어 유령이 잡혀서 스폰 장소로 돌아갈 때 발생하는 효과음도 부탁드릴게요!

설명 : 유령과 라플리가 팩맘에게 잡힐 경우 다시 스폰 지점으로 돌아가게 됩니다. 그 과정에서 잡히는 장소와 스폰 장소와의 거리에 따라 효과음의 길이가 달라질 수 있기에 짧은 효과음으로 하여 루프해도 좋게 설정하면 좋을 거 같습니다.

다만,  지금 스폰 방식이 다시 스폰 장소로 캐릭터 스스로 이동해서 가는 방식이 아닌 자동(순간이동) 느낌으로 구현된다면 6번 효과음에서 살짝 수정을 가미하면 사용할 수 있을 거 같습니다.

일단 보류하겠습니다!

7번 : 임의로 설정해보고 판단해야할 거 같습니다.

8번 : 기화님 말 들어보니, 화려하면 이상할 거 같기도 하네요. 갑자기 떠오른 레퍼런스는 소닉 시리즈에서 동전 흘릴 때 소리입니다.
https://www.youtube.com/watch?v=5KbjYN7-9aE
https://youtu.be/7GMFzaexJTY?si=z0wjepQNINoe2H55&t=15

9번 : 임의로 설정해보고 판단해야할 거 같습니다. 왜냐하면 연속적으로 들릴 가능성이 높기에!! 테스트가 필요할 거 같아요!

10번 : 좋습니다. 추가로 13초 이후에 팩맨이 죽는 15초 경에 효과음도 필요할 거 같습니다. (연계 활용하면 좋을 거 같아요)

13번 : 오 좋습니다. 뭔가 피치, 높낮이를 낮춘 버전도 예시로 만들어주실 수 있을까요?

**Comment by Songkihwa** [comment]
피드백 감사합니다 동호님!

웬만한 효과음 모두 지금 당장 단언할 수 없는 부분들이라 일단 동호님이 말씀해주신 사항들은 다 이해했습니다!

8번은 레퍼런스 보고 다시 만들어보도록 하겠습니다.

10번의 연장선인 팩맨이 죽는 효과음을 6번으로 쓰는 건 어떠실까요? 사실 그 타이밍으로 작업했던거라서요 ㅎㅎ

13번 피치, 높낮이 낮춘 버전들도 가능합니다. 각각의 음 피치를 낮춰달라는 말씀이실까요? 아니면 다양한 버전을 만들어달라는 말씀이실까요?

**Comment by CreatorLDH** [comment]
앗 6번 내용을 10번으로 고려해보겠습니다! (한 번 넣어보고 그래야겠어요!)

13번 넵넵 한 번 낮은 음 버전으로 나오면 어떨 지 궁금합니다.
