### ISSUE TITLE
팩맘 리소스 문서 제작 

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#118]
- #117 
에서 사용할 리소스 (사운드, 이미지) 등을 정리할 계획입니다.

[팩맘 리소스 문서](https://docs.google.com/spreadsheets/d/1ovY4M_BvA1QaQbKgb54nNpdA0RWv1022/edit?usp=drive_link&ouid=104039457643560044631&rtpof=true&sd=true)

수정 사항이나 추가 사항 발생 시 바로 수정 후 노티드 하겠습니다.
아트랑 사운드 나누었으면, 하단에서 시트 변경 하시면 됩니다.

**Comment by Songkihwa** [comment]
작업 하시느라 고생 많으셨습니다 :) 리소스 문서 확인 했습니다!
시간이 많진 않아서 할 수 있는 대로 작업해보고 올리도록 하겠습니다. ㅠㅠ

**Comment by wooyn730** [comment]
1. 팩맘 이동 모션은 입을 벌렸다가 닫는 걸 말씀하시는 건가요?

2. 청소기 든 팩맘은 상하좌우 버전을 주시는지, 회전시키면 되는지 궁금합니다.
(이왕이면 청소기 포함 정사각형 이미지였으면 좋겠습니다!!!!
직사각형이면 골목길 회전 처리가 곤란합니다)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/664d3446-f4bd-4263-bfe9-67b3fac5bf05) 이런..

3. 먼지 유령이나 라플리는 몸통과 눈을 분리해서 주시면 되겠습니다. (눈 상하좌우 4개)

4. 먼지 유령/라플리 기본과 디버프는 2개씩 조금 다르게 주시면 되겠습니다. (애니메이션 주기 위해)
![Ghost_Vulnerable_Blue_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/598b418c-1a1d-4753-a27c-edf9fa7a7028)
![Ghost_Vulnerable_Blue_02](https://github.com/GG-Studio-990001/GameOver/assets/80298207/eca6e3d8-5000-4151-bada-b2250c3d7602)

5. 원본 팩맨의 리소스를 제가 가지고 있으니 아트분이 보시고
웬만하면 트레이싱하시면 편할 것 같습니다.

6. 맵은 하나로 그리기보다 타일 그리기 추천드립니다.
이것도 필요한 타일 이미지 드리면 트레이싱 하시면 좋을 것 같습니다.
(OK하시면 5, 6은 같이 문서로 정리해드리겠습니다.)

7. 폰트도 정해서 말씀해주시면 좋겠습니다.
(제 생각엔 대충 [요런 픽셀 폰트](https://www.dafont.com/retro-gaming.font)?)

++
효과음 문서는 급한 거 아니니까 프로토타입 완성하고 작성하면 동호님과 기화님이 더 편하지 않을까 생각합니다..
팩맘은 패러디가 강한 미니게임이지만 다른 게임들은 효과음을 미리 작성하는게 더 힘드실수도 ㅠ

**Comment by CreatorLDH** [comment]
### **우연님 코멘트에 대한 피드백**
***
1. 네 맞습니다.
2. 회전으로 생각하고 있습니다. 
3~6 : 체크해주셔서 감사합니다. 
7. Retro Gaming.ttf 보니까 괜찮네요 저작권 관련 확인 잠깐 해보니 무료 상업용이라 되어 있는 거 같습니다.

**Comment by CreatorLDH** [comment]
++ 리소스 아트 문서 내 손글씨는 폰트로 대체하겠습니다. 감사합니다.

**Comment by wooyn730** [comment]
![iMRxbytea9QJWQ9jAq6_AIJe2OP-rVQN_g-YJ6FguhVNJYiSl9GZHhFSCHHdUgR_XoAQLVDO_pTHBUIUIkPYsQ.png](https://github.com/GG-Studio-990001/GameOver/assets/80298207/ff31a5d9-dc1e-4942-8f0d-92e6e58a605c)

모든 텍스트가 이렇게 픽셀 폰트인지
아니면 다 손글씨st 폰트인지
혼합해서 사용할건지 궁금합니다

**Comment by CreatorLDH** [comment]
모든 텍스트를 픽셀 관련 폰트로 진행합시다!! 
원본과 최대한 비슷한 폰트로 진행하고 싶습니다. 

일단 우연님이 찾아주신 폰트와, 저도 시간내서 함 찾아보고 찾을 폰트와 비교해서 진행해보죠! (아트분들의 의견 및 추천 받습니다)

**Comment by wooyn730** [comment]
@yanggang3 팩맨 원본 리소스 드립니다 (찐 원본인지는 모르겠지만..)

### 팩맨
![Pacman_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/38970828-d0d0-4b27-9cc3-b1734bed9469)
![Pacman_02](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d36f483f-b728-4efd-9e24-ba047c6e2b12)
![Pacman_03](https://github.com/GG-Studio-990001/GameOver/assets/80298207/931ea8c3-7d5f-4182-a027-014cfd1ad0ed)
![Pacman_Death_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b16bdc68-a626-4dbc-8222-b77a009e3a8c)

### 유령 디버프
![Ghost_Vulnerable_Blue_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/4d4dcfd4-f23a-4f9c-9a0b-f4a508abc6e1)
![Ghost_Vulnerable_Blue_02](https://github.com/GG-Studio-990001/GameOver/assets/80298207/1704a952-1705-4442-acd1-b1d697befc73)
![Ghost_Vulnerable_White_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/841b9d27-e6b7-417b-becd-fe9be35b8c8e)
![Ghost_Vulnerable_White_02](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e707c6a4-2f42-40b9-b6ef-c54dda98bd1b)

### 유령 몸&눈
![Ghost_Body_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/beea75b7-cbc4-4067-bde7-664587f38721)
![Ghost_Body_02](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f27013ac-e154-4774-84c0-d0193beea31d)
(크롬 테마 흰색이면 잘 안보이겠지만 위에 흰 몸통 있어요..)
![Ghost_Eyes_Down](https://github.com/GG-Studio-990001/GameOver/assets/80298207/329e0926-a25a-45da-85bd-58a47489058e)
![Ghost_Eyes_Left](https://github.com/GG-Studio-990001/GameOver/assets/80298207/cfac8edc-6b32-4d6c-87c4-2c2ecae508ae)
![Ghost_Eyes_Right](https://github.com/GG-Studio-990001/GameOver/assets/80298207/1c0c864e-9436-4752-a6d8-fd3a679311c5)
![Ghost_Eyes_Up](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3c09c737-fb79-45b2-9ec8-d2fc05c1f077)

### 작은거=코인 / 큰거=청소기아이템
![Pellet_Large](https://github.com/GG-Studio-990001/GameOver/assets/80298207/13c647a0-bef5-4751-8b73-cec25bb2bba1)
![Pellet_Small](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e32c9de6-a392-489b-8354-fd23c8732fb4)

### 맵 타일
![Wall_28](https://github.com/GG-Studio-990001/GameOver/assets/80298207/2dd0762c-3d8e-4f08-abee-e8f05544de1d)
![Wall_31](https://github.com/GG-Studio-990001/GameOver/assets/80298207/5aee5dfc-287a-4873-8804-4dc5d0dcbe0c)
![Wall_33](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e1e8c32a-6400-4389-9192-c7a3ebb78850)
![Wall_37](https://github.com/GG-Studio-990001/GameOver/assets/80298207/584f19b2-99a9-4d3c-a786-31f47bd77f8d)
![Wall_00](https://github.com/GG-Studio-990001/GameOver/assets/80298207/649eccdd-c3df-4312-b4fc-1d799362c6f6)
![Wall_01](https://github.com/GG-Studio-990001/GameOver/assets/80298207/7e5a8bc4-96ca-4505-9ae0-d9f513c75b5f)
![Wall_05](https://github.com/GG-Studio-990001/GameOver/assets/80298207/961bc2bb-bfc4-4896-9d32-4b293ec84732)
![Wall_12](https://github.com/GG-Studio-990001/GameOver/assets/80298207/ab64be75-d5c5-4e1d-a281-de06aff7007a)
![Wall_13](https://github.com/GG-Studio-990001/GameOver/assets/80298207/2057e1e4-2c05-41af-bbf0-296ccb76eed6)
![Wall_21](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e91c08ef-3e97-4c0a-b6df-8d335df539a3)

작은데 괜찮으신가요..
원래 구드에 폴더 만들어서 넣어서 드릴려했는데
나중에 뭐가 더 편한지 말씀해주세요!

그리고 아래처럼 한장에 다 넣은 아틀라스 이미지로 받고싶은데 이렇게 작업 해보셨나요??
![이미지](https://t1.daumcdn.net/cfile/tistory/2702D93C567BC00606)

**Comment by yanggang3** [comment]
@wooyn730 앗 확인했습니다!
혹시 이 아틀라스 이미지를 유니티로 제작해야 하는 걸까요..?
제가 픽셀 작업은 처음이라 만약 하면 포토샵으로 작업하려고 했습니다!
그리고 저 이미지 크기는 어떻게 되는걸까요?!

**Comment by wooyn730** [comment]
@yanggang3 
### 아틀라스 이미지

*UI 이미지 리소스는 게임을 구동하는데 필요한 자원을 절약하기 위해 한 화면에 빈번하게 출력될 리소스들을 적절히 한 장씩 묶어 사용합니다. 이렇게 여러 개의 이미지를 하나로 묶은 리소스를 아틀라스(Atlas)라고 부릅니다. [출처](https://blog.naver.com/PostView.nhn?blogId=semgames&logNo=222045204709&categoryNo=212&parentCategoryNo=0)*

하나의 png에 여러개의 이미지를 담아서 주시면 됩니다. (저 팬더처럼)
우선 같은 것들끼리 (팩맨 모음, 라플리 모음, 타일 모음) 받아볼게요!

받으면 제가 유니티 내에서 잘라서 사용할 예정입니다!

세화님 작업은 포토샵이나 [픽셀 찍는 사이트](https://www.piskelapp.com/p/create/sprite) 등 사용해보시고 편한 걸로 작업해주세요 (민지님은 어떤 프로그램으로 작업하시는지 모르겠네요?? 얘기 나눠보셔도 좋을 듯)

### 사이즈

배경은 24x24(맵 타일, 코인과 청소기), 그 외는 16x16(유령, 팩맨 등)입니다.
근데 라플리나 팩맘은 디테일이 추가되면 16x16으로 못담을 것 같긴 합니다...

작업하시다가 최소 이 사이즈로 작업해야한다 싶으면 말씀해주세요!
같이 사이즈 조율해봅시다

**Comment by fkdl0048** [comment]
![Grass](https://github.com/GG-Studio-990001/GameOver/assets/84510455/5955ae95-04fd-4f0a-a9bf-15ffb4784039)

쉽게 이런식으로 한 파일에 맵 타일의 경우를 넣어주시면 됩니다.

**Comment by fkdl0048** [comment]
https://www.retrogamedeconstructionzone.com/2020/01/graphics-in-early-arcade-games-tilemaps.html

이 내용이 가장 이해가 잘 되실 것 같아요

**Comment by yanggang3** [comment]
@wooyn730 
설명 감사합니다! 작업하는데 우선 포토샵 아님 에이스프라이트를 써보려고 합니다! 그리고 사이즈 크기는 32x32면 너무 무거워질까요..?

**Comment by fkdl0048** [comment]
개인적으로 에이스프라이트를 추천드리고 32x32로 작업하셔도 됩니다.

크기는 유니티에서 현재 우연님이 작업하신 환경으로 다시 변환이 가능합니다!

**Comment by fkdl0048** [comment]
여기까지는 제 생각이고,, 우연님 말씀을 들어봐야 하긴 하겠네요

**Comment by yanggang3** [comment]
네! 감사합니다!

**Comment by wooyn730** [comment]
괜찮을것 같슫니다!
