### ISSUE TITLE
[Bug] Node과 유령의 물리 충돌

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#119]
# BUG: Pellet과 유령의 물리 충돌 버그

## Description

유령과 Node(발판) 사이 물리 충돌이 있음.

발판은 유령의 이동방향을 정해주기 위해 들어간 시스템

유령과 발판이 충돌 감지는 되어야하지만, 유령과 발판은 물리 충돌이 일어나면 안됨

isTrigger가 체크 되어있으면 충돌 감지 O, 물리 충돌 X로 알고 있음

발판은 콜라이더가 있고 isTrigger 체크, 유령은 콜라이더와 rigidbody가 있고 isTrigger 체크 X

*몇분에게 물어봐서 설정을 조금 바꿔보는 시도를 해봤지만 실패*

## Solution

팩맨 프로젝트를 다운받아서 뜯어보거나 동영상 다시 볼 예정...

아니면 정안님께 도움을 받을수도 ^_^

## ETC

- #86 참고

**Comment by wooyn730** [comment]
고치긴 했는데 팩맨 프로젝트 뜯어봐도 왜인지 모르겠어서 그냥 처음부터 다시...^^
inspector은 틀린거 없는 거 확실한데 말이죠

n시간 동안 다시 만든 것보다 왜 오류가 났었는지 못찾은게 더 슬프네요 ..............................................................

**Comment by fkdl0048** [comment]
해결이 된건가요 그럼..?

**Comment by wooyn730** [comment]
넴 해결은 했는데 이전게 왜 안된건지는 모르겠어요...

**Comment by fkdl0048** [comment]
크헉...

**Comment by wooyn730** [comment]
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
