### ISSUE TITLE
캐릭터 컨셉 아트 제작 (NPC-3)

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#122]
#114 에 이어서 NPC 캐릭터 2인과 엑스트라 마마고의 아이디어 스케치 작업
메인 시스템 담당
[NPC 3인 아이디어 스케치 ](https://drive.google.com/file/d/1J5cTtnX0P31DCMTPY0k22KzN6xXFJodz/view?usp=drive_link)
수정요청, 피드백 적극 환영합니다~

**Comment by CreatorLDH** [comment]
특히 마을 사람들 부분은 부족한 부분이 많았던 기획 사항이었는데도 잘해주셔서 너무나도 감사드립니다!

트루커
- 옆면이여서 애매한건지 모르겠지만, 해달(수달) 모티브 캐릭인 점을 좀 더 부각했으면 좋을 거 같습니다. (복슬복슬한 털을 강조한다던지, 털주머니에 무언가 찬 듯한 느낌을 준다던지!)
- 꼬리를 추가해주세요 ㅎㅎ (강조는 추후 인게임에서의 행동양식으로 보여질 겁니다!)
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/9296ceb5-f372-4ff5-9713-f465b2af64dd)


미카엘
- 딱 중성적인 천사 그 느낌 만족스럽니다.
- 창백한 피부로 해주신 점 더욱 맘에 듭니다. 감사합니다.
- 설교 시와 화남에 대한 표정 표현해주셔서 감사합니다. 약간 미소년스러운 캐릭터여서 그런지 화남에 느낌보다는 경멸같은 느낌이 강한 거 같습니다. 사이코처럼 표현하면 어떨까라는 생각도 듭니다. 

![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/9173716b-4602-4fd1-936f-594658502cab)

마마고
- 부리 색을 특별하게 해볼까요? 기존 파파고는 윗부리가 초록색 계열 아랫부리가 노란색 계열인 점을 보아 이 점을 활용해 다른 앵무새들과 차별점을 도출할 수 있을 거 같습니다.
- 왕관은 뭔가 CEO 느낌보다는, 왕족, 권력, 여왕 이런 느낌이 나는 거 같아서, 지적인 느낌을 줄 수 있는 안경을 추가해보는 거 어떨까요?

![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/7672d02b-31e8-405a-bcfc-06fe8af6e10d)
요런 안경은 뇌절이려나요? 뭔가 과거 할리우드 영화에서 늙은 교장여선생님이 저런 거 쓰고 나오시는 거 같은데.. 

안경 애매할 거 같으면, 다른 장신구 계열 고려해보고 있겠습니다.

너무 감사합니다.

**Comment by wooyn730** [comment]
저도 전반적으로 동호님과 유사한 생각을 했습니다!

**트루커**

귀여움을 좀 더 어필하기 위해 복실한 털이나 포동한 볼살이 표현되면 좋을 것 같습니다

**미카엘**

살짝 싸한 인상? 싸이코같은 인상?이 조금 보이면 좋겠습니다

**마마고**

파란 나비넥타이는 귀여운 꼬마신사? 느낌이라 나비넥타이 빼고 안경 추가하면 올드하고 좀 더 카리스마 있어보이지 않을까 싶습니다. 

저는 외알안경(모노클)도 좋겠고 끈 달린 안경도 좋습니다!!

**Comment by royalbluesm** [comment]
@CreatorLDH @wooyn730
 
**트루커**
의인화의 정보를 줄이고 조금 더 동물적인 특성을 강조하도록 하겠습니다!

**미카엘**
보내주신 레퍼런스 강렬하네요... 조금 더 싸이코스러운 캐릭터성이 살도록 수정해보겠습니다.

**마마고**
나비넥타이, 모노클 부분 수정하도록 하겠습니다! 피드백 감사드립니다~

**Comment by CreatorLDH** [comment]
미카엘 : 네넵! 자신만의 트리거가 작동되었을 때 그러한 싸이코스러운 면모가 보이면 좋을 거 같습니다! 실생활에서는 딱 지금 민지님이 그려주신 이미지가 좋아요!

**Comment by fkdl0048** [comment]
@royalbluesm 수정도 이번 주 Task로 가능하실까요? 주 마다 피드백 한 내용에 대한 결과물이 보여지면 좋을 것 같습니다.

**Comment by royalbluesm** [comment]
> @royalbluesm 수정도 이번 주 Task로 가능하실까요? 주 마다 피드백 한 내용에 대한 결과물이 보여지면 좋을 것 같습니다.

확인했습니다! 추가하겠습니다~
