### ISSUE TITLE
컨셉 아트 세계관

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#123]
저번주 두 작업#78 디테일 추가, 수정, 완성도 올리기.

전 스케치https://drive.google.com/file/d/1eqL_gdjo6t-Y3z34Z-TwDJf3gB3grUBy/view?usp=drivesdk

현재 스케치https://drive.google.com/file/d/1Ju5k91C14tKPjM79QDrKGTpuhCIcAca4/view?usp=drivesdk

저번주 작업에서 디테일 추가하고 완성도를 올리는 작업을 했습니다.
완성은 아니지만 좀 더 시간을 드리면 더 열심히 하겠습니다.!
그리고 이번주 학과 행사(~11/17)로 또 작업기한을 못 지켰는데 정말 죄송합니다.
그럼 회의 때 뵙겠습니다.

**Comment by royalbluesm** [comment]
마리오의 ?박스나 3D 도트 조각 등 디테일한 오브젝트가 들어간 덕분에 그림이 뭘 전하고자 하는지 확실히 사는 것 같습니다. 저는 개인적으로 이 그림이 리소스홀과 리소스마운틴의 메인 비주얼을 드러내는 일러스트레이션이니 기한을 좀 넉넉하게 잡고 퀄리티에 힘을 줬으면 하는 의견이네요! 완성본이 기대됩니다~ 

그리고 추가적인 요청사항인데 구글 드라이브에 파일 올리실 때 파일명에 파일 정보를 적어주시면 좋을 것 같아요! 리소스 마운틴_작업중_1113 이런 느낌으로 정리해주시면 여러모로 편리할 것 같습니다~

**Comment by CreatorLDH** [comment]
확실히 나아진 거 같습니다. 도트, 3D 등 여러 그래픽이 혼재되어 있어 주는 오잉?함이 맘에 듭니다. 

어떻게 완성될 지 궁금하네요. 피드백은 뽑기 기계가 어느 부분 살짝 묻혀 있고 깨져서 뽑기 공이 조금 밖으로 새어 나온 연출도 있으면 어떨지라는 생각이 듭니다.
다른 오브젝트들은 모두 금이 가거나 깨진 연출이 있기에!!

개인적으로 한 곳에 너무 많은 오브젝트가 쏠려도 좋지 않을 거 같으니 저희가 구글PPT로 알려드린 것들을 모두 넣을 필요 없다는 점 다시 한번 말씀드립니다!

감사합니다.
