### ISSUE TITLE
[Ch1]Feat: Dialogue System

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#125]
# Feat: MSC01, Dialogue System 

상호작용을 통한 대화시스템 설계 yarm Spinner  와 연계

<details><summary>레거시</summary>
<p>

## 1차

DialogueUIView 설계하여 Presenter와 연결

## 2차

(작업중..)

대사 테이블 Data, yarm spinner관련 데이터 저장

대사 애니메이션 View 호출은 따로 Feat개발

++ 우연님과 yarm을 어떻게 다룰 것 인지

## 3차

대화 시스템의 경우 UI는 달라질 수 있어도 시스템은 그대로 유지하는 것으로 생각해야 해서 메인시스템에서 분리하여 Internal System UI으로 변경

작업 내용 구체화

</p>
</details> 

## 1차 빌드 수정사항

- #185 

대화 중 사용자 키 입력 제한 (Input System 제한 하는 방법으로)

**Comment by fkdl0048** [comment]
vscode로 많이 사용하는 것 같습니다!

익스텐션에 yarn 검색하시면 나오는 걸 깔아도 좋을 것 같은데 천천히 알려드릴께요!

**Comment by CreatorLDH** [comment]
아 확인했습니다~ 감사합니다

**Comment by fkdl0048** [comment]
- [구문 설명](https://docs.yarnspinner.dev/beginners-guide/syntax-basics) 
  - 기획용
- [테스트 용](https://try.yarnspinner.dev/)
  - 직접 넣어서 테스트 가능
  
  @CreatorLDH 예제 내용입니다!

**Comment by fkdl0048** [comment]
## 답변

>  임의로 함수이름과 함수 인수를 설정했습니다. 이에 따른 부가 설명 또한 자세히 주석으로 남겨놀 계획입니다.

함수 이름과 인수로 표현된 값은 변경될 수 있습니다. (주석으로 원하는 기능에 대해서 기술하는 것이 좋습니다!)

> ex. BGM 변경, 캐릭터 좌표 이동, 대화창 갱신 간격, 컷씬 on/off 등 임의로 작성했습니다.

예시처럼 작성하시면 너무 좋습니다! (사용법은 추후 변경 예정)

> 유니티 내 컴포넌트 및 변수 등을 가져와서 yarn 내에서 제가 활용할 수 있는 지 궁금합니다.

어느정도 오픈 수준인가에 따라 다르지만 가능합니다! 위처럼 함수 형태가 가장 좋은 방법입니다.

> 정안님이 만든 함수를 추후 제가 지속적으로 이용하는 방식인지, 제가 먼서 임의로 함수를 그때그때마다 요청하는 게 편하신지... (왜냐하면, 함수명이나 변수명은 통일이 되어야 작업상 편하기 때문에 서로 작업간 통일해야할 거 같아서)

대략적인 기능을 제작을 먼저 하고 필요에 따라 추가하는 방식입니다.

필수적인 -> BGM변경, 카메라 흔들림

대신 위에 적어주신 캐릭터 이동, 애니메이션, 컷씬은 다른 방식으로 작동합니다. 

이 부분은 하나의 연출이기 때문에 대화 시스템이 아닌 TimeLine으로 제작하기에 전혀 다른 방식이라 함수 형태가 아닌 더 다양한 영역으로 가능합니다.

캐릭터가 하늘에서 춤추면서 눈덩이 던지고 눈사람만들고 막 막 뭐 하고 뭐 하고 (마치 애니메이션 제작하는 방식)

그에 반해 대화형에서는 함수로 동작해야 하는 예를 들어 역전재판의 글씨 효과나 이후 비쥬얼 노벨에서 많이 활용될 듯한 이미지 움직임 등을 생각하시면 됩니다.

지금 chapter1에선 많은 함수는 사용되지 않을 것 같고 대부분 타임라인으로 연출할 것 같습니다.

> tags에 대한 재설명 및 저번 주에 노드로 구현방법 보여주신 거 다시 알려주시면 감사하겠습니다. + 공부할 자료 더 있으면 받습니다:D

- [자료1](https://docs.yarnspinner.dev/getting-started/editing-with-vs-code)
- [자료2](https://docs.yarnspinner.dev/getting-started/editing-with-vs-code/installing-the-extension)

vscode에서 노드형식으로 연결하는 방식입니다.

동호님이 말씀해주신대로 jump문으로 구분하는 것이 좋습니다 (조금만 만져보면 이해하실 듯 합니닷)

>  파일을 어떻게 분류해서 드리는 것이 좋을 지 고민중입니다.

제 생각엔 NPC한 명당 1파일로 구분하는 것이 좋아 보입니다.

챕터 하나에 한 NPC로 구분하여서 만들면 갈끔할 것 같습니다. vscode로 보면 생각보다 깔끔합니다. 그래프 뷰라

> 큰 사건이나 연출은 따로 파일을 구성할 계획입니다. 

마찬가지로 연출은 대화랑 전혀 다른 영역입니다.

연출에 들어가는 대화는 따로 작성해야 합니다!

편하게 캐릭터가 조정해서 대화를 건다 -> (대화시스템)

캐릭터 조정이 불가능하고 연출이 들어간다 -> (타임라인)

> 유저의 자유 행동 시점에는 유저의 행동에 따라 NPC가 말하는 텍스트가 달라지는데, 이를 다중IF 문으로 잠시짠 상태입니다. 하지만, Jump 구문과 연계해서 짜는 게 더 효율적이라 판단해 수정 예정입니다.

좋습니다.

> 그래서 파일 개수를 [ 큰 사건 및 연출마다의 개별 파일 / 사건 분기 및 자유행동 시점의 NPC마다의 개별 파일 / NPC 외 오브젝트 상호작용 대사 파일] 총 3개의 대분류 후 소분류해서 드리는 게 편할까요? 고민입니다.

위 내용과 동일합니다.

논외로 주신 파일에서 타임라인 연출을 함수로 짜주셨는데 작성하신 내용처럼 글처럼 적어서 (나름 개발자 스토리 보드?) 이를 타임라인으로 구성할 것 같습니다.

**Comment by fkdl0048** [comment]
- 2023-01-01 timeline에 맞춰서 수정
