### ISSUE TITLE
컨셉아트 디자인

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#13]
# 컨셉아트 디자인

원하는 디자인, 화풍, 색감, 구조등등 

ex_1) 쓰레기산을 배경으로 하고 (블랙앤 화이트 색감) 게임 팩을 줍고 있는 주민
ex_2) 사이드뷰, 레이어로 쓰레기 산을 구분하고 여러 게임 요소들을 보여줌 (메이플 소멸의 여로/ 사진 첨부)

*많이 적어 줄수록 좋습니다. *

- @yanggang3 
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998716/c452e95b-ae09-49b0-ab03-4aed4becf5c0)

- @royalbluesm 
![concept01](https://github.com/GG-Studio-990001/GameOver/assets/144519956/a7729fd1-79d2-4dbb-8a1b-c0ca81354257)
![concept2](https://github.com/GG-Studio-990001/GameOver/assets/144519956/9e3dd9d9-f395-4da8-8754-bc8dc5d6540d)
![게임심마니](https://github.com/GG-Studio-990001/GameOver/assets/144519956/a86029d9-bd30-4181-932d-48df76f22102)

**Comment by fkdl0048** [comment]
![image](https://github.com/fkdl0048/ToDo/assets/84510455/77de8765-6c8a-453a-97f9-b618c71b3e4d)

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/e218376c-46ca-47de-aab9-e37d9f1189b0)

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/029bfa9a-8792-43d5-b5a0-abb3ca8b3f07)

**Comment by Songkihwa** [comment]
첫 번째 사진보다 좀 더 멀리보는 시점으로 드넓은 사막같은 대지에 쓰레기 섬 하나 툭 있다는 걸 표현해봐도 좋을 것 같아요.
그 뒤에 확대해서 세밀하게 그려보는 식으로 진행해도 괜찮을 것 같습니다ㅎㅎ

디스토피아적이고 어두운 분위기 하니까 생각났는데 웹툰 노네임드, 꿈의 기업 화풍 분위기를 가져와도 좋을 것 같다는 생각이 들어요.

![image](https://github.com/GG-Studio-990001/GameOver/assets/145998609/509f955e-6929-42a6-9b7e-17f16f2cf689)

**Comment by fkdl0048** [comment]
<img src="https://github.com/GG-Studio-990001/GameOver/assets/84510455/93335e7a-bea2-4d93-b12a-5ba6ea59722f" width="500" height="300">

<img src="https://github.com/GG-Studio-990001/GameOver/assets/84510455/f11473cf-7790-45db-b407-d6f24e6904e2" width="500" height="300">

**Comment by CreatorLDH** [comment]
https://docs.google.com/presentation/d/154eVu5T6PH_6afxZmWBojlJAw92KFuPjlb2r_wdOclA/edit?usp=sharing

**Comment by CreatorLDH** [comment]
https://docs.google.com/presentation/d/154eVu5T6PH_6afxZmWBojlJAw92KFuPjlb2r_wdOclA/edit?usp=sharing

더 세계관이나 그런 게 확립되고나서 집중적으로 의견 드리려고 했는데,
시간이 애매해서 일단 구글 ppt로 1~2개 아이디어 보내드려볼게요!!!!

레퍼런스 느낌보다는, 이런 구도의 이런 컨셉아트가 있으면 나쁘지 않을 거 같다는 의견입니다.

**Comment by fkdl0048** [comment]
저도 마지막 지도 아트 그림 너무 좋습니다
