### ISSUE TITLE
[Bug] ArgumentNullException: Value cannot be null. Parameter name: _unity_self

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#131]
# BUG: ArgumentNullException: Value cannot be null. Parameter name: _unity_self

## Description

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b25a7c5f-bb0f-4aa4-8782-751c28ef2f87)

## Solution

구글링 고고..

**Comment by fkdl0048** [comment]
오류 보니까 Editor라서 아마 방금 언급된 하이어라키 꾸미는 라이브러리에서 나오는 것 같은데여..?

**Comment by wooyn730** [comment]
근데 껐다 키니까 오류가 안떠서 보는 중입니다.. 근데 자동빌드는 실패떠요

**Comment by fkdl0048** [comment]
저도 내일 작업할 때 한번 보겠읍니다

**Comment by fkdl0048** [comment]
제쪽에서는 확인이 안되는데 본문에 오류 뜨는 트리거 같이 기재해주시겠어요

**Comment by wooyn730** [comment]
저도 어제 픽스 하려고 했는데 뭐 해도 같은 오류가 안뜨더라고요...?
근데 액션은 실패해서 문제가 있는 것 같긴 해요..

**Comment by wooyn730** [comment]
껐다 키니까 오류가 두 번 다시 등장하지 않았습니다...

빌드 실패는 다른 문제였다고 합니다

**Comment by fkdl0048** [comment]
@wooyn730   우연님 이거 해결된 날짜랑 마일스톤 지정해주세요!
