### ISSUE TITLE
[Pacmom] Map

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#137]
- #120 

### 원본
![팩맨](https://i.namu.wiki/i/iMRxbytea9QJWQ9jAq6_AIJe2OP-rVQN_g-YJ6FguhVNJYiSl9GZHhFSCHHdUgR_XoAQLVDO_pTHBUIUIkPYsQ.png)

### 구현
![스크린샷 2023-11-13 013644](https://github.com/GG-Studio-990001/GameOver/assets/80298207/25ce2d21-b267-49e2-b712-242497a13815)
현재 맵

![스크린샷 2023-11-13 014003](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e086c48d-e914-4944-8eff-0b17bce08097)
코인 배치 예시 (코인 하나 잘못 찍음..)

### 기획
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/633bb61e-bc5b-4901-83a5-3a227c382543)

### 달라진 이유
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d51e1148-20ca-4a44-8ef4-ef0e6637e9cd)

유령과 팩맘, 라플리가 지나가는 길은 꼭 1칸이어야하는데 스케치 상엔 애매한 부분이 있어서 임의로 처리했습니다.

통로가 너무 많아진 것 같긴 합니다..

피드백 부탁드림니다

**Comment by CreatorLDH** [comment]
1칸이라는 규칙이 있었군요. 인지했습니다. 

통로가 많으면 상대적으로 잘 활용할 유저에게는 이점이 될 거 같네요. 팩맘이 알고리즘적으로 잘 이용할까도 의문이구요.
(실제 팩맨 플레이에서는, 유령이 팩맨을 따라가는 과정에서 자연스레 통로로 가는 경우가 대다수)

본래 생각대로 하면 아래 수정 예시중에 **3번**이 좋을 거 같습니다!!!

지금 짜주신 것도 전 그대로도 맘에 듭니다.

좀 더 고민해보고 내일 회의 때 다시 말씀드릴게요~ 감사합니다.

***
혹여나 수정한다면 예시안

1)
<img width="515" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/0c173629-21cb-4c32-81e7-8d568cd66804">

2)
<img width="520" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/1a2d2efe-cd15-4eb9-8463-811070a96f7c">

3)
<img width="524" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/7c2066b6-1816-4fbd-86af-3d44607343ea">

**Comment by wooyn730** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/11726dc4-2f23-4105-a28e-5177e7d4e6ec)

지금 팩맘 맵이 가로로 짝수칸이라 세로에 가운데 1칸짜리 통로를 뚫는게 불가능하긴 합니다 ^_ㅜ..

이따 회의 때 봬용

**Comment by CreatorLDH** [comment]
앗 알겠습니다!

**Comment by CreatorLDH** [comment]
오 좋습니다 맘에 들어용! 따라한 거 같지만, 차별점이 있는 느낌이라 좋습니다!

**Comment by wooyn730** [comment]
위에 청소기 아이템 위치 한번 찍어주십셔

나중에 다른 수정사항 있으면 반영하겠습니다~

**Comment by CreatorLDH** [comment]
임의로 찍었습니다!
<img width="355" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/d7102c7d-5ebe-43a0-b7cc-8601195ba4cd">
