### ISSUE TITLE
팩맘 사운드 리소스 제작_2

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#140]
#118 파일을 참고하여 #116 에 이어 사운드 리소스를 제작했습니다. 

[1번 배경음](https://drive.google.com/file/d/10j_xLJlPYQSpO-yA5MD3xnRT5yhsutYP/view?usp=drive_link) : 팩맘 청소 모드에 진입할 때 사용되는 배경음으로 동호님의 요청사항에 따라서 청소기 소리, 8비트 효과음들을 섞어봤는데 좀 심심한 느낌이 들어서 약간의 음악과 함께 청소기의 등장으로 분위기를 확 반전 시킬 수 있는 사운드로 제작해봤습니다. 
일단 제 의도는 이랬는데 조금 과한 것 같기도 하네요 팀원분들 의견 궁금합니다! 

- [1번 배경음 코인 추가](https://drive.google.com/file/d/1doY4siBNeBsgpShro0C4JQ8Hv9JR1z72/view?usp=drive_link) 제가 임의로 코인 소리를 집어 넣었는데 팩맘이 코인을 빨아들이면서 나는 소리는 이런 느낌일 것 같아서 같이 첨부합니다.

[2번 배경음](https://drive.google.com/file/d/118iMdC8V3yIuFMblOIEzeSrpJnrQsPWH/view?usp=drive_link) : 팩맘 시작 인트로로 제가 저번에 제작한 팩맨 플레이 영상 속 B버전의 인트로를 활용했습니다. 

[8번 효과음](https://drive.google.com/file/d/1bhaKyH7lKNbjPNLPxpx2eu00iYSfgiNm/view?usp=drive_link) : 코인 떨어뜨리는 효과음으로 동호님이 #116 에서 주신 피드백을 참고해서 수정해봤습니다. 
제 상상력을 가미해서 앞에 부딪치는 소리도 넣어보고, 코인 떨어지면서 튕기면서 재생성 되는 듯한 느낌으로 제작해봤습니다. 
근데 이것도 만들다보니까 제 상상력이 많이 들어가있어서 동호님이 상상한 사운드가 맞을진 모르겠네요ㅠㅠ 피드백 환영합니다!

[11번 효과음](https://drive.google.com/file/d/1tUiVd-_SVhYdHzm1nVf2bNl8bHlJAiz2/view?usp=drive_link) :  팩맨 입이 움직이는 효과음입니다. [루프](https://drive.google.com/drive/folders/1Eb2eVUHV-GQv0pKCRoKtVqgvROIZ2tDC?usp=drive_link)해서 들으면 이렇습니다! 
원본 소리가 뭔가 귀를 찌르듯이 아프기도 해서 저는 부드럽게 만들어봤습니다.

[12번 효과음](https://drive.google.com/file/d/17iaxXQesRVzYhXa7fnV3vC2Ae8J26T00/view?usp=drive_link) : 라플리 등장음으로 라플리가 처음 팩맘에 접속했을 때 나오는 짧은 효과음인데, 
옛날 게임처럼 게이지가 차거나 화면이 빨려들어가는 식의 화면 전환부터 팩맘 게임 화면 접속까지의 사운드를 상상해보며 제작해봤습니다. 

13번 효과음 : 먼지 유령 대화 효과음인데 #116 에서 받은 피드백 참고해서 [낮은 피치](https://drive.google.com/file/d/1y6POJpsjdiGGQ8NemwiaAeKg9sFl5foV/view?usp=drive_link)로 수정해보기도 하고
다른 모듈레이션을 추가해서 [좀 더 지지직한 대화 사운드](https://drive.google.com/file/d/1PPQiqOznARg6ivExQtES0mtPygbP908f/view?usp=drive_link) 도 제작해봤습니다.

모든 피드백 환영합니다 -! 원하시는 사운드가 있거나, 레퍼런스가 있다면 언제든지 알려주세요 :)

@CreatorLDH 동호님 답변 주시면 감사하겠습니다!

1. 9번 라플리 코인 획득 효과음과 5번 라플리 코인 대량 흡수음에서 서로 같은 획득음이 들어갈 것 같아서 일단은 보류하는 게 좋을 것 같은데 
어떻게 생각하실까요? 일단 팩맘 완성에 다다른 후 딱 맞는 사운드 넣으면 좋을 것 같다는 생각이 듭니다..!!

2. 4번의 팩맘 진입 배경음 같은 경우 제가 생각할 때 팩맘 게임 규모에 비해 사운드가 많아질 것 같다는 생각이 들어서, 
배경음이 없는 게 나을 것 같기도 합니다. 사운드 넣어보고나서 배경음의 요소가 필요하다고 느껴지면 
필수 사운드들에 맞춰서 배경음을 제작해서 넣는 건 어떨까요? 

3. 실례가 안된다면 혹시 15번 효과음에 대해 조금 더 설명해주실 수 있으실까요? 
영상에서 유령들의 움직임 소리처럼 해달라는 말씀이실까요? 느낌만 간단하게 얘기해주셔도 제작하는데 도움이 될 것 같습니당ㅎㅎ

**Comment by CreatorLDH** [comment]
### **피드백**

**1번 :** 좋습니다. 
10초 이상의 분량으로 설계해주실 수 있을까요!!!
진입할 때 음 너무 좋구요, 그 이후에 반복되는 8비트음을 계속 사용해도 좋을 거 같아요. 청소모드가 10초 지속이기에, 10초 이상 분량이 필요합니다. 그 과정에서 청소기를 추가 획득하면 지속 시간이 길어지기에 참고 부탁드립니다!
(10초 이상의 음으로 만들어서 주시면 감사하겠습니다)

**질문)** 혹시 모르니 20초 이상으로 길게 만들어서, 10초 이후 아무때나 BGM이 끊겨도 자연스러울 수 있게 만드는게 가능한가요?

**참고)** 현재 기획 방향이 지속 시간 확장으로 설정되어 있는데, 윗 질문이 구현하기 어렵거나 자연스럽게 만들기 어렵다면 10초 길이로 통일되고 시스템적으로 '지속시간 갱신'으로 만드는 방안도 고려해볼게요.

**2번** 좋습니다.
다만 걱정되는 점은 1번을 듣고 2번을 들으니 2개의 배경음이 자연스러울까 걱정이 조오오오금 드는데, 어차피 공존되는 음악도 아니고 연결해서 나오는 것도 아니니 괜찮을 거 같습니다.

**8번** 효과음 
기존 10번 + 팩맨이 죽는 거 포함 이후에 생성될 효과음이기에, 이 부분을 고려해야할 거 같습니다(자연스럽게). 지금 기화님이 만들어주신 플로우 또한 좋습니다. 그렇다면, 기존 10번에 대한 내용을 보류해야한다고 생각합니다. 

하지만, 이미테이션 적인 부분을 생각했을 때는 보류하기 어려워요..

그래서 기존 10번 이후에 발생된다는 점을 빠르게 인지시켜드리지 못해서 죄송하고, 이 점 유의해주시면 감사하겠습니다.  

뒷 부분에 작게 떨어지는 부분(약 1.5~1.8초)은 생략해도 좋을 거 같습니다. (적은 동전이 떨어지는 소리 부분 축소하는 느낌!) 생성되는 듯한 사운드 추가해주신 거 같은데 좋은 거 같아요.(부딪히는 소리여도, 생성 느낌을 줄 수 있을 거 같아요). 

약간 깨진 느낌이 들기도 하는데, 반복적으로 듣다 보니 아닌 거 같습니다ㅎ

**11번** 효과음
좋습니다. 루프 링크가 잘못된 거 같은데, 일단 찾아서 들었습니다 감사해요!

**12번** 효과음
느낌은 좋습니다. 하지만, 실제로 넣는 과정에서 길이 축소 요청이 들어갈 가능성이 높습니다. 길어지진 않을 거 같아요.

추가로 해주신, 화면 전환 효과음도 잘 들었습니다. 미니 게임으로 화면 전환이 되든, 다른 맵으로 화면 전환이 되든 자주 발생될 거 같습니다. 일단 미니 게임 한정으로 위 효과음으로 쓰는 건 좋은 거 같습니다. 라플리가 해당 미니 게임으로 '로드'된다는 느낌을 주는 거 같기에 맘에 들어욧!

+ 뒤에 터지는 부분 효과음을 짧게 간략한 뿅 버전으로 추가로 만들어 주실 수 있을까요? 비교해서 듣고 싶네요!

나중에 픽스 작업을 해야할 거 같습니다. 
픽스된 것은 따로 리소스 문서에 체크를 하고 폴더를 분리해보고 한 번 넣어보면서 비교하면 좋을 거 같아요.

**13번** 효과음
낮은 피치 : 기존보다는 지금이 더 좋아요. 길게 짧게 조정이 가능하죠? 추가로 죄송하지만, 살짝 조금 피치를 더 올린 버전도 듣고 싶어요! ;-:
지지직 : 지지직이 살짝 느껴지는데, 게임 내에서 잘 표현될 지는 모르겠습니다.

+ 2명의 유령을 포함할 거라서, 유령을 구분하는 것을 피치로 생각하고 있습니다.

***

### **답변**

1. 9번 라플리 획득하는 효과음은 코인 1개를 획득하는 음이고, 플레이어가 동전을 얻는 속도 및 개수에 따라 소리의 속도 및 주기가 달라질 것이라 생각합니다. (같은 음의 짧은 동전 소리의 반복)

코인 대량 획득음은 "팩맘 구체화 버전, 종료 연출 내에 들어갈 효과음"입니다! 그래서 다르다고 생각했습니다. (이 점 구체화 시, 추가로 엑셀 설명 기입하지 않은 점 사과드립니다.)

그래서 5번 같은 경우는 구현 과정에 따라 보류가 달라질 거 같습니다.
해당 효과음이 나가는 기준을, 코인과 라플리가 '충돌'되었을 때라고 가정하겠습니다.
종료 연출 때 코인 오브젝트가 실제로 게임 내에서 자동으로 움직여 라플리와 충돌시키고 사라지게끔 구현을 했다면, 자연스럽게 게임에서 코인 먹을 때처럼 소리가 날 것이라 생각합니다. (코인이 라플리 쪽으로 벽을 무시한 채 이동한다는 알고리즘을 활용 시)

이런 제 생각은 실제 구현을 하지 않은, 기획자의 생각이기에 실 구현될 지는 모르겠습니다. 혹여나 하나의 '연출'로 생각하고, 개발자분이 만든 연출 모션(유니티 타임라인)이라면 5번이 따로 필요하지 않을까 생각했습니다.

이 점은 월요일 회의 시간에 우연님에게 잠시 이야기하고 확답드리겠습니다:D

2. 동의합니다. 대화할 때 나타나는 소리와, 라플리가 등장하는 음으로 잘 꾸밀 수 있을 것으로 생각합니다. 그러나, 추후 게임의 완성도를 높이는 과정에서 기화님 의견대로 추가될 수 있을 것이라 생각하기에 삭제보단, 보류하겠습니다.

 3. 앗 너무 제 머릿 속이 팩맨을 따라하는 게임이니까,팩맨 부분만 주면 되겠지라고 쉽게 생각한 거 같습니다. 기화님 말대로, 유령들의 움직임 소리를 요청드렸습니다. 코인이 필드 내에 거의 존재하지 않을 시 배경음이 없는 게임이므로, 유령의 소리라든지 라플리의 걷는 소리 (이건 요청하지 않았던 내용, 팩맨에서의 팩맨은 이동 소리가 없기에) 등이 필요할 것이라 생각했습니다.

그래서 기화님이 만들어주신, 11번 효과음을 팩맘(기본 모드)의 이동 효과음으로 같이 처리를 하는 방안도 고려하게 되더라구요. 

결론은 "먼지 유령이 움직이는 소리를 표현해주시면 감사하겠습니다"
기존 팩맨처럼 똑같이 구현해도 좋고, 먼지 부스러지는 소리처럼 구성해 주셔도 좋습니다.

***

### **기타**

추후 시간을 내서, 제가 다시 첨부터 들어보고 폴더 만들어서 옮기거나 요청드리겠습니다.
+ 사운드 피드백 과정에서 사운드 용어로 풀면 더 이해가 될 거 같다는 부분이 있으시면, 사운드 용어 공부를 도전해 보겠습니다 :D

팩맨 게임 자체가 배경음이 없기에, 많은 효과음을 지속적으로 발생하여 음악적인 느낌을 주었다고 생각합니다.
그래서 이런 부분을 가져가고 싶었기에, 효과음에 대한 요청이 많아진 점 양해 부탁드립니다.
정말로 딱 필요한 부분만을 요청드리고 싶지만, 다양한 효과음이 아우려져 나타나는 멜로디를 머릿 속에서 크게 상상이 되지 않기에 이렇게 요청되었습니다ㅜㅜ 추후 실 구현과정에서 직접 넣어보거나 임의(어도비 오디션 활용 예정)로 구성하여 들으면서 조정해 나가겠습니다.

항상 감사합니다.

**Comment by royalbluesm** [comment]
효과음과 음악 다 너무 좋은데, 특히 좋았던 건 11번이네요~ 고전게임들 음악은 제작 시 기술적인 문제로 듣다 보면 귀가 아픈 것들도 종종 있는데 그런 점을 캐치해서 부드럽게 보완해주신것 세심하네요!!

**Comment by wooyn730** [comment]
잘 들었습니다! 기획적인 부분은 동호님이 코멘트를 잘 남겨주셨네요

저는 조금 걱정되는 부분이 사운드가 너무 고퀄이고 입체적이라
![이미지](https://i.namu.wiki/i/iMRxbytea9QJWQ9jAq6_AIJe2OP-rVQN_g-YJ6FguhVNJYiSl9GZHhFSCHHdUgR_XoAQLVDO_pTHBUIUIkPYsQ.png)
요런 느낌이 아니라

![이미지2](https://store.nintendo.co.kr/media/catalog/product/cache/8e3c84988db1fdb90470f4d01453d879/a/0/a029553804bfbbc9c6f525ca4ce949a125fc47189f9c179c4c1cde14c3cb3abe.jpg)
![이미지3](https://i.namu.wiki/i/5jrVb4qT14i1YDQAOndp-gcG1WCi52MuPy0SFLZqqk4g7uedgRJSW9OMxoM5SSABNwbCa_dC0GS6Rs9e4ibJ5w.webp)
살짝 이런 느낌..?

더 힘을 빼고 플랫하고 단조롭게? 가도 괜찮다고 생각합니다... (특히 8번 같은 효과음이요)

아트도 같이 봐야 어울리는지 확실히 알겠지만요

**Comment by fkdl0048** [comment]
저도 우연님과 마찬가지로 걱정되는 건 2D게임에 3D 사운드인 부분이 걱정되는데 그게 매력적일 수 있겠다는 느낌도 받고 있어서 제작 해보고 판단해야 할 것 같습니다.

수정은 대부분 조금씩 적용되면 변경되는 부분이 발생할 것 같습니다.

**Comment by Songkihwa** [comment]
**@CreatorLDH 동호님 피드백 답변**

피드백 해주셔서 감사합니다 동호님 !! 구체적으로 해주셔서 도움이 많이 돼요ㅎㅎ

1번 효과음 : 10초 이상 분량 설계 가능합니다. 20초 이상으로 길게 만들어서 아무때나 끊겨도 자연스럽게 만드는 건 조금 힘들 것 같습니다ㅠㅠ 혹시라도 유티니 내에서 언제나 음악이 끊겨도 페이드 아웃이 구현 가능한지 알아봐야할 것 같습니다! 

2번 효과음 : 따로 따로 작업하다보니 결이 조금 달라진 것 같긴 합니다 ㅠㅠ 
동호님 말씀대로 같이 나오는 음악은 아니라 크게 문제가 될 것 같진 않지만 혹시라도 문제가 된다면 사운드 결을 수정해보도록 하겠습니다!

8번 효과음 : 뒷 부분 작게 떨어지는 부분 생략하고 좀 더 보완 해보겠습니다.

11번 효과음 : 아이코 제가 링크를 잘못 걸었군요.. 죄송합니다 ㅠㅠ

12번 효과음 : 거의 모든 효과음은 제가 임의로 생각했기 때문에.. 앞으로 두 번은 더 다시 작업해야한다고 생각하고 있습니닷 ...
뒤에 터지는 부분을 다른 짧은 사운드로 바꿔달라는 말씀이실까요?

13번 효과음 : 길게 짧게 조정 가능합니다. 중간 피치로 한번 더 들려드릴게요!

- 답변의 답변
 1. 9번은 코인을 1개 획득하는 음이고 5번은 종료 연출음이라는 말씀이시죠?! 
저는 게임이 종료될 때 어쨌든 라플리가 코인을 획득하기 때문에 9번의 코인 획득음이 대량으로 들어가야한다고 생각한 것 같아요..!
조금 어렵네요 ㅠㅠ 일단은 구현해보고 나 뒤에 사운드 제작해보는 방향으로 가면 좋을 것 같습니다.
 
 2. 사실 다른 분들 의견처럼 지금도 사운드가 과한 감도 있어서 .. ㅠㅠ 배경음까지 있으면 조금 더 과할 것 같긴 합니다. 

 3. 기존 팩맨과는 다르게 먼지 부스러지는 소리처럼 한번 제작해보도록 하겠습니다 !

- 기타 : 네네! 아니면 저랑 같이 얘기해보면서 정리해도 좋을 것 같아요. 사운드 용어 공부는 괜찮습니다! 소통에 어려움은 없어서요ㅎㅎ '
팩맨보다 맵이 커졌고 요소가 추가됐기 때문에 효과음이 많아지는건 당연한거라고 생각합니다. 저는 괜찮습니다!!
항상 기획하시느라 고생이 많으십니다!!ㅠㅠ

------------

**@royalbluesm  민지님 피드백 답변**

우왓 좋게 들어주셔서 감사합니다 !! 열심히 신시사이저로 이리저리 사운드 만져본 보람이 있네요..!! ㅎㅎ

------------

**@wooyn730 우연님 피드백 답변**

피드백 감사합니다 우연님! 저도 1번부터 만들면서 느꼈는데 제 사운드가 좀 과한 것 같더라구요 ... 욕심이 생겨서 못 덜어낸 것 같네요 ㅠㅠ
좀 더 단순한 사운드일 필요가 있는 것 같아요.

------------

**@fkdl0048 정안님 피드백 답변**

피드백 감사합니다 정안님!  그래도 8비트 사운드 위주로 사용해서 결이 너무 다르진 않을테지만 제가 이것저것 쌓긴한것 같으네요 ..ㅠㅠ
한번 적용해보면 수정할 사항들이 더 잘 보일 것 같아서 차차 수정해나가도록 하겠습니다!
