### ISSUE TITLE
메인 시스템 작업-스타일프레임 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#143]
**스타일프레임 제작**
화면 해상도(비율, 도트 수)를 결정하고 미리 인게임 뷰가 어떨지 스타일프레임을 만들어보겠습니다.
스타일프레임은 보통 모션그래픽에서 쓰는 용어인데 완성본을 만들기 전에 제작하는 하나의 정지된 화면을 뜻합니다!
해상도 미리보기 정도로 생각해주시면 되겠습니다. 
[스타일프레임 1(320x180)](https://drive.google.com/file/d/1sK1JGZenUjqwa0Z23DhuhSmsqmyZ9ga7/view?usp=drive_link)
탑다운 뷰에 맞게 플레이어 도트를 조금 수정했고, 전체 해상도(픽셀 수) 설정해봤습니다. 어떤 것 같나요? 저는 이정도 디테일함이면 적절하다 생각합니다

**지난 주 작업 수정**
#122 피드백 참고하여 작업물 수정하겠습니다.
[NPC 캐릭터(마을사람들) 아이디어 스케치 3 수정본](https://drive.google.com/file/d/1_wLeqEuVPFdfWZsOEfHGOlD8UZGs0r2f/view?usp=drive_link)

**Comment by fkdl0048** [comment]
**스타일프레임** 좋은 정보 감사합니다 ^^

**Comment by wooyn730** [comment]
스타일프레임 생각보다 퀄리티 좋고 귀여워서 놀랐습니다!! 멋져요 ^_^

트루커는 한층 귀여워져서 좋아요! 근데 개인적으로는 더더 귀여워도 괜찮을 것 같습니다.

마마고는 수정 전이랑 후랑 색이 다 좋네요...

**Comment by fkdl0048** [comment]
### 스타일 프레임

느낌 너무 좋습니다.

특히 2D에서 3D객체인 쓰레기 산을 표현하기 위해 저렇게 하얀 아웃라인을 준 표현도 되게 좋은 아이디어 같아요

인 게임에서는 맵 타일을 사용하게 될 텐데 가능하다면 바닥 관련 타일의 퀄리티를 조금 올릴 수 있을까요?

그레이스케일이라 표현이 가능한지 잘 모르겠습니다.(가능하다고 해도 더 이상해지지 않을지.. 걱정)

지금의 느낌도 좋지만, 더 좋아질 수 있는 방향이 있다면 1챕터에 한에서는 더 좋은 퀄리티가 나오면 너무 좋을 것 같아요

*1챕터를 가장 먼저 보기 때문에 퀄리티를 매우 올리고 싶다는 생각*

그리고 해상도 관련해서 현재 320x180인데, 사용될 해상도가 (1920x1080)이니 4정도로 나눠서 480x270으로 가능할까요?

**Comment by CreatorLDH** [comment]
### **스타일 프레임**
현재 레벨 디자인 및 기타 작업중인데, 해당 프레임을 보니 좀 수정할 게 생각나네요 (제 작업)
그 정도로 개인적으로 느낌이 좋습니다.

참고하겠습니다.

### **캐릭터**
고생하셨습니다. 마마고 바뀐 색감이의 색 배치가 독특하다고 생각해 인게임내에서는 잘 구현될 지 몰라도, 일러스트 내에서는 개성점으로 작용될 거 같아 너무 좋습니다.

다른 캐릭터도 추가 의견 없습니다. 고생하셨습니다.

**Comment by CreatorLDH** [comment]
+ 스타일 프레임 내 대화 UI 스타일 맘에 듭니다 고생하셨습니다.

**Comment by royalbluesm** [comment]
피드백 감사합니다! 좋은 말씀 많이 들어서 의욕이 나네요^^
@fkdl0048 타일 퀄리티는 만들어봐야 알 것 같은데... 아마 실제로 적용하게 된다면 약간 울퉁불퉁한 돌바닥 느낌이 나도록 작업할 것 같네요 너무 과하지는 않게!! 1챕터 한번 멋있게 만들어 보겠습니다~

**Comment by Songkihwa** [comment]
헉 스타일프레임 너무 귀여워요 .. 당장이라도 게임 하고싶어지는 ..!!
