### ISSUE TITLE
서브시스템_팩맘 아트 리소스 제작

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#145]
라플리
https://drive.google.com/file/d/1HRfn3Feu-soXpSQFdhu6ylPIETy3r3fB/view?usp=drive_link

팩맘
https://drive.google.com/file/d/1LhAwDKHznV4kYqZI9GA_64n62C6METVK/view?usp=drive_link

ver.2(청소하는 주부의 느낌을 더해봤습니다..)
https://drive.google.com/file/d/1LSG2F81kpxuZrfSHvhjlhu1wlvEFDx7c/view?usp=drive_link

먼지유령(디버프&몸,눈 포함)
https://drive.google.com/file/d/1SvpgLWc_hylHduG3WtbNmj_3RtGhUGTn/view?usp=drive_link

인게임 예시
![인게임](https://github.com/GG-Studio-990001/GameOver/assets/145998716/2751443c-59d1-4f08-b869-bf3ac9585c15)

@wooyn730 우선 캐릭터 따로 16픽셀로 제작해보았는데, 이렇게 드리면 될까요?!
아직 맵타일과 코인/ 청소기(아이템)는 제작 중에 있습니다.. 빨리 하겠습니다.!

**Comment by CreatorLDH** [comment]
고생하셨습니다!

**Comment by CreatorLDH** [comment]
고생하셨습니다!

라플리는 아직 디버프받은 이미지는 만들어지지 않은 것이죠? (검정 머리랑 붉은 빛 머리가 있는데, 개인적으로는 민지님이 만들어주신 컨셉 아트에 맞게 붉은 빛-갈색빛이 좋을 거 같습니다)

팩맘 이미지는 다른 분들 의견이 필요할 거 같아요.
뭔가 둘 다 괜찮은데, ver2는 공포물 느낌도 나고, 아 공포물 느낌이면 좋은건가 고민이 되고 그러네요 ㅋㅎㅋㅎ
(입이 빨개서 그런거 같네요!, 그래도 청소하는 주부 느낌, '엄마', 아주머니 느낌이 그나마 더 드는 건 ver2 같아요)

먼지 유령 디자인 좋습니다. 
디버프 때는 파랗게 되는 걸로 하면 좋을 거 같아요. 
더불어 먼지유령 다른 친구 색감은 기존 먼지 유령에서 채도를 바꾸거나 색감 차이 조금만 주시면 좋을 거 같습니다!
(디버프 색은 동일할 거에요!)

그 디버프 색에 맞추어 추후 라플리의 디버프 또한 고려해주시면 감사하겠습니다.

**Comment by yanggang3** [comment]
@CreatorLDH 피드백 감사합니다!
디버프받은 라플리를 붉은 머리(#990011)로 하고, 평범할 때에는 검정머리로 하려 했는데 괜찮을까요..?

**Comment by CreatorLDH** [comment]
@yanggang3 

기존 캐릭터의 헤어색이 붉은 머리(#990011)이므로 해당 머리색으로 사용되어야할 거 같습니다.
디버프일 때는 기존 먼지 유령들이 받는 효과를 라플리 또한 받는 것이므로.
라플리 또한 파란 모습으로 설정하거나, 먼지 유령이 디버프 상태일 때 눈이 뱅글뱅글 도는 것으로 표현해주신 것처럼 라플리 또한 통일감을 가져가면 좋을 거 같습니다.
(기존 먼지 유령 디버프처럼 파란 느낌으로 처리하거나, 너무 이상해지는 느낌이 강하면 눈이 뱅글뱅글 도는 것처럼의 차이를 주셔도 됩니다. 그래도 스마트폰에 블루필터 설정하는 것처럼의 약간의 파란 끼라도 있으면 어떨지 생각이 듭니다)

**Comment by wooyn730** [comment]
고생하셨습니다!!! 저는 작은 도트에 디테일을 어떻게 살릴지 걱정됐는데 결과물이 멋지네요 ㅎㅎ

1.이미지 배치

![스크린샷 2023-11-21 001244](https://github.com/GG-Studio-990001/GameOver/assets/80298207/1595b0d7-0054-4ed6-a9a7-25a5464a24b6)
![스크린샷 2023-11-21 001234](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3d824ae0-bb56-41ad-8b7c-a53fdbb33f20)
라플리랑 팩맘 16으로 자르니까 딱 맞아요! 좋아요!

![스크린샷 2023-11-21 001251](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b299124a-1275-4ee3-8fc4-231602f22aa9)
먼지유령은 딱 안맞네요!!! 라플리랑 팩맘처럼 부탁드려요

++
나중에 수정사항 다 반영된 후에는 이슈 마지막 이미지처럼 다 하나의 이미지에 넣어서 주셔도 좋을 것 같아요

2.파일명

저희 파일명 쓰는 방식을 정해야하는데 이건 다음 회의 시간 안건으로 말해봐야겠어요
암튼 한글은 nono...

3.먼지유령

유령 완전 귀엽슴다~
똥글뱅이 눈도 좋네요!
디버프 때 파랑/빨강 대비도 조아용

동호님 의견처럼 다른 유령은 색이 약간 다르면 좋겠네요!

(색깔 이야기는 개인 의견)
근데 팩맘 / 먼지유령 / 라플리의 색은 확실히 분리되면 좋겠어요
캐릭터들이 작고 16픽셀짜리니까 색으로 구분되는게 보기 좋을 것 같아요

![이미지](https://i.namu.wiki/i/iMRxbytea9QJWQ9jAq6_AIJe2OP-rVQN_g-YJ6FguhVNJYiSl9GZHhFSCHHdUgR_XoAQLVDO_pTHBUIUIkPYsQ.png)
팩맨도 보면 유령과 팩맨이 겹치는 색이 없고, 디버프 때도 짙은 파랑과 흰색을 사용하고, 코인도 눈에 잘 띄게 밝은 색 + 어두운 배경을 설정한 것 처럼요

4.라플리
라플리 흑백이 아니라 컬러 있는 버전이면 디폴트가 빨간머리+살구색 피부가 되려나요?
*글구 990011 아니고 990001.. (비슷하지만)*

저도 디버프 먼지유령이랑 비슷하게 받으면 좋을 것 같아요 (비슷한 톤이 된다거나..)

근데 위에서 말한 것처럼 기본 색은 구분되면 좋을 것 같슴다

5.팩맘

2번째 버전이 진짜 팩'맘' 같은 느낌이 들긴 하네요 ㅋㅋ
립스틱 넘 좋아요
16비트에서도 머리랑 청소기 표현을 잘 해주셨네요!!! ㅎㅎ

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0e474079-42a9-449b-9f6c-ebcf4a42ed65)
가능하면 위 아래일 때 청소기가 잘 보이는 모습도 해주시면 좋을 것 같은데 안되면 괜찮습니댜
