### ISSUE TITLE
컨셉 사운드 디자인

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#15]
레퍼런스에 따라 사운드 디자인 기획

@wooyn730 @fkdl0048 @2ehdgh17 @royalbluesm  @yanggang3

컨셉 사운드로 생각하신 아이디어가 있으시다면 알려주세요!

(아래 코멘트 달아주세요!)

이렇게 올리는게 맞는지 모르겠지만 일단 컨셉 사운드 작업물 올리겠습니다! 
제가 어떻게 작업했는지 워킹노트도 작성해보았으니 참고하시면 도움이 되실 것 같습니다.

이번주는 급하게 먼저 제출해야할 작업물이 있었어서 더 완성도 있고 깊이있게 작업하지 못한 것 같아서 아쉽네요 ㅠㅠ
그래도 제가 생각한 분위기는 최대한 표현해보려고 했으니 들어보시고 팀원분들 생각은 어떠신지 회의 때 피드백 마구 주시면 감사하겠습니다.

[컨셉 사운드 제작 워킹 노트 1006.pdf](https://github.com/GG-Studio-990001/GameOver/files/12828757/1006.pdf)

https://github.com/GG-Studio-990001/GameOver/assets/145998609/fb87e037-8c4d-4656-ac97-5e1fc2aab876

**Comment by fkdl0048** [comment]
- 기화님 아이디어

무덤의 마을의 광활함이 주는 엠비언스 사운드

바람, 희미하게 들리는 게임 BGM 사운드

**Comment by fkdl0048** [comment]
아이디어

정말 나중나중의 이야기지만 테마마다 다른 종류의 악기를 사용해서 성격을 강화하는 것도 좋아보입니다!

**Comment by wooyn730** [comment]
맞아요 하나에 매몰되지 않고 넓은 시야를 가지도록 조심해야할 것 같아요! (특히 저)

저도 오늘 사운드 회의 참석해보니까 함께 만들어갈 게임이 아주아주 기대가 됩니다 ^_^

**Comment by Songkihwa** [comment]
언더테일처럼 라이트모티프를 가지고 게임에 일관성을 더해주면서 진행하는 식도 좋을 것 같네요~!! 

이번주는 일단 제가 생각한대로 간단하게만 컨셉 사운드를 한번 제작해볼 에정이지만 
앞으로 만들어나갈 사운드들은 팀원분들과 많은 이야기 나누면서 만들어나가고 싶어요.

좋은 아이디어 너무 감사합니다! 앞으로도 생각나는 거 있으시면 언제든지 적어주세요 저에게 큰 힘이 될 것 같습니다ㅎㅎ

**Comment by Songkihwa** [comment]
이렇게 올리는게 맞는지 모르겠지만 일단 컨셉 사운드 작업물 올리겠습니다! 
제가 어떻게 작업했는지 워킹노트도 작성해보았으니 참고하시면 도움이 되실 것 같습니다.

이번주는 급하게 먼저 제출해야할 작업물이 있었어서 더 완성도 있고 깊이있게 작업하지 못한 것 같아서 아쉽네요 ㅠㅠ
그래도 제가 생각한 분위기는 최대한 표현해보려고 했으니 들어보시고 팀원분들 생각은 어떠신지 회의 때 피드백 마구 주시면 감사하겠습니다.

[컨셉 사운드 제작 워킹 노트 1006.pdf](https://github.com/GG-Studio-990001/GameOver/files/12828757/1006.pdf)


https://github.com/GG-Studio-990001/GameOver/assets/145998609/fb87e037-8c4d-4656-ac97-5e1fc2aab876

**Comment by fkdl0048** [comment]
틀자마자 메인화면이 생각나는 것 같아요 (타이틀 화면)

너무 좋습니다.. 저는 저번에 아이디어로 말씀해주신 작게 들리는 게임 사운드 (삑삑)이런 사운드도 들리면 좋을 것 같아요!
