### ISSUE TITLE
[Ch1 Main] 사건에 따른 레벨 디자인 구체화

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#151]
- #75 
- #77 

위 내용을 참고하여, 사건(시간)에 따른 레벨 디자인 구체화를 작성할 계획

- #152 
를 참고하여 문서 확장 예정

[레벨디자인 구체화](https://drive.google.com/file/d/1E-civEjuBg3Bd7TEQ6_6hmwo3uED5Vy_/view?usp=drive_link)

확장은 이따 UI 퍼즐 다 끝나고 시간 조금되면 해보겠습니다~

배경 오브젝트에 대한 내용 추후 추가 예정.
(배경 그래픽에 대한 내용)

**Comment by royalbluesm** [comment]
동호님 혹시 배경 오브젝트 부분 끝나시면 여기나 디코쪽으로 멘션한번 주시면 감사하겠습니다!

**Comment by CreatorLDH** [comment]
@royalbluesm 

앗 민지님 이 이슈 참고해주시면 감사하겠습니다
- #161
