### ISSUE TITLE
[Ch1 SubB] UI 퍼즐 시스템 구체화

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#152]
- #77 
- #151 
- #148 

위 내용을 확인하여 UI 퍼즐 내용에 대한 확장 예정

[정확히 어떤 퍼즐과 기능들이 활용되는지 구체화해서 작성했습니다.](https://drive.google.com/file/d/1kjfSuDZIDs_L88ZWHB2INHBbtdaxdPxF/view?usp=drive_link)

작성해보니 여러 UI가 필요할 거 같네요. (SLG 장르의 부가 UI 들 등)
추후 픽스되면, 똑같이 리소스 문서 등을 제작하여 알려드리겠습니다.

**Comment by fkdl0048** [comment]
회의 때 따로 정리 요청하셔서 여기에 올립니다.

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/551914af-c713-41ad-b1fe-86aa5ad2c132)

퍼즐은 좀 더 생각을 해보겠읍니다..
