### ISSUE TITLE
서브시스템_팩맘 아트 리소스 제작2

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#157]
#145 에 이어 리소스 디자인을 조금 바꾸고 타일맵 제작을 했습니다.
https://drive.google.com/file/d/1F9UNytLISU7Dc6yWsD2AvXmr5vsNPav2/view?usp=drive_link

우연님이 제작하신 맵에 리소스를 얹힌 일부 이미지입니다.
![인게임 이미지(일부)](https://github.com/GG-Studio-990001/GameOver/assets/145998716/49207f9f-5558-42cf-bbe9-f7458f4aa82d)

타일맵을 24 x 24, 그 외 아이템과 캐릭터는 16 x 16픽셀로 작업하였고,
또 수정할 가능성이 높아보여(특히 타일맵) 아틀란스 이미지는 아직 따로 제작하지 않았습니다.,
그리고 집 느낌보단 벽이 벽같지 않아 수정해야할 것 같습니다.!
봐주셔서 감사합니다.

**Comment by CreatorLDH** [comment]
고생하셨습니다.

요청 사항
- 먼지 유령 나머지 한 마리는 기존 회색빛의 먼지 유령에서 약간의 채도나 명암을 조금씩 바꾼 버전이면 좋을 거 같습니다. 
- 청소기 디자인 좋습니다. 다른 분들도 청소기로 인식되는 지 한 번 의견주시면 좋을 거 같아요
- 라플리 표정 바뀌게 해주셔서 감사합니다. 다만, 게임 특성상 간단한 변화로는 유저가 알아차리기 힘들 거 같아서, 저번에 요청드린 것처럼 얼굴에 파란 끼가 있게끔 하거나 색에 대한 변화 또한 있으면 좋을 거 같습니다. (현실적이지 않더라도, 게임적 허용으로 넘어가야 해요!)
