### ISSUE TITLE
[Ch1 SubA] 팩맘 리소스 정리 및 팩맘 보완 작업

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#159]
- #141 

위 내용과 기존 사운드 피드백 포함해서 정리합니다.

더불어 사운드 리소스 파일(엑셀) 보완하겠습니다.
=> 좀 더 보기 편하게!
***

[231121 팩맘 세부 기획서 ](https://drive.google.com/file/d/18W1j2arXDdbi9J6_Cx6TQRxfe71wtZCj/view?usp=drive_link)
[리소스 문서](https://docs.google.com/spreadsheets/d/1ovY4M_BvA1QaQbKgb54nNpdA0RWv1022/edit?usp=drive_link&ouid=104039457643560044631&rtpof=true&sd=true)

**문서 변경점**
- 청소기 아이템 지속상황에 따른 사운드 변화 내용 추가
- 대화 텍스트 수정 및 자잘한 텍스트 수정
- 맵 타일에 관한 내용 추가
- 라플리 구현 내용에 따라 불필요 부분 삭제 및 수정 (모션 및 캐릭터 도트 디자인 예시 등)

**사운드 리소스 변경점**
- 구현 여부와 관련 링크업 추가
- 1번 변경에 따른 16번 추가 및 수정
- 12번 효과음 분할하여 17번 추가
- 4번 보류, 5번 삭제
- 자잘한 사운드 설명 보완

- #116 에서의 6번을 10번 뒤로 연결해서 써보겠다고 코멘트가 마무리 되었는데, 다시 들어보니 연결이 될까하는 생각이 들었습니다. (일단 10번(+기존 6번을 작업했던 결과물, 보류로 나아가겠습니다)

=> 더불어 그 당시 보류했던 6번 효과음에 대한 재작업이 필요할 거 같습니다. (6, 15 연계됩니다)

**아트 리소스 변경점**
- 현재 라플리 도트 디자인이 나옴에 따라, 걷는 모션에 대한 요청 사항 삭제

아트도 이번 사운드처럼, 완료 혹은 픽스에 따라 칸 추가하여 관리 예정 (좀 더 디자인 나오면)

감사합니다.

**Comment by yanggang3** [comment]
@CreatorLDH 
더 구체적으로 보완 작업해주셔서 감사합니다! 
라플리가 유령이랑 만날때 어떻게 유머를 나타내야할 지 좀 더 생각해보겠습니다..!ㅎㅎ
궁금한 점
1. 먼지유령 말풍선은 텍스트 길이 따라 달라진다고 하셨는데, 제일 짧은 대사가 "퇴근이다",나 "으아아악"인 4글자이고
제일 긴 대사는 "돈을 많이 모으면 본사에서 특별 보너스도 준다고 하니까 파이팅이야 자네!"
맞을까요?
2. 라플리 말풍선(대사는 없지만 ...?나 ...!같은 느낌표현)과 먼지유령 말풍선은 다르게 제작할 예정인데 괜찮을지!
3. UI 중에 라플리 코인 개수 ui랑 팩맘 코인 개수 ui랑 통일시켜도 될지입니다!
