### ISSUE TITLE
메인 시스템-스타일프레임 제작②

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#160]
**스타일프레임 제작②**
#143 에 이어서 스타일프레임을 추가로 4~5장 작업합니다.
동호님의 이번 주 레벨 디자인 이슈가 클로즈되면 기획 내용 보고 비주얼적 토대가 될 부분 작업하는 걸로 하겠습니다. 

>>동호님과 의논 후, 추가적으로 제작하는 건 3장으로 충분하다고 판단. (GG타운 입구, 플로야드 1, 위험구역)
[스타일프레임 pdf](https://drive.google.com/file/d/1Um397eebj1a3BvISFtjr6LBCAtJM2Iq3/view?usp=drive_link)
전체적인 느낌은, 민둥하게 각진 듯하면서 분위기가 있는 도트게임의 분위기를 최대한 살리기 위해 단순화된 부분이 있습니다. pdf 참고해주시면 감사하겠습니다.

**Comment by CreatorLDH** [comment]
피드백
***

스타일 프레임이 실질적으로 활용되는 게임 내 배경이미지가 아닌 점을 고려해서 진행하겠습니다.

1) GG 타운 입구
쌓여있는 경계와 그 뒤에 색을 다르게 연출하신 점 맘에 듭니다.

표현하시기 어려울수도 있겠지만,본래 입구에는 의도적으로 쌓은 담벽이 존재하며

**Comment by CreatorLDH** [comment]
피드백
***

스타일 프레임이 실질적으로 활용되는 게임 내 배경이미지가 아닌 점을 고려하여 진행하겠습니다.

**1) GG 타운 입구**
쌓여있는 경계와 그 뒤에 색을 다르게 연출하신 점 맘에 듭니다.

표현하시기 어려울수도 있겠지만,본래 입구에는 의도적으로 쌓은 담벽이 존재합니다.
이 담벽은 지금 표현해주신 이 부분(대충 쌓은 것)과 사뭇 달랐으면 좋겠습니다.
<img width="332" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/15a1b5f9-667b-4113-beef-ee4875eff89c">

해당 담벽 사이에는 실제로 마을로 이동되는 구간이므로 
<img width="181" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/fb386a5e-a7ff-4173-aaa6-b4d935401520">

이러한 연출이 보여서 '저기 무언가 가는 통로가 있겠다'하는 호기심을 유발시키면 어떨까 생각이 듭니다.

해당 스타일 프레임 너무 맘에 드는데, 기획 상 아래 부분에도 저런 벽이 필요합니다. (술래잡기 퍼즐을 가진 NPC가 숨을 곳) 하지만 그러면, 너무 플레이어가 움직이는 공간이 너무 적어지지 않을까하는 걱정도 듭니다.

**2) 플로야드1**
현재 기획상 선형적 구조에는 맞지 않은 지형 구조인 거 같습니다.
플로야드1에서 추가로 맵에 들어가서 나오는 퍼즐 풀이용 맵으로 활용하면 좋을 거 같습니마단, 개발 비용(시간, 타일)을 고려를 좀 해야겠습니다.

GG TOWN 입구 그 다음 맵이므로, 연결되는 느낌이 있었으면 좋을 거 같습니다. 

**3) 위험구역**
대박.. 넘 맘에 듭니다. 다만, 실질적으로 활용될 시에 플레이어가 움직이는 구역을 고려해서 축소가 필요해 보입니다.
플로야드1의 더미 크기여도 좋으며, GG TOWN 입구의 상단 부분에 배치하면 맵 하나 뚝딱될 거 같습니다.

고생하셨습니다.

**Comment by royalbluesm** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/144519956/c4af8f29-65dd-4acc-bcc6-1a57e91023f8)
질문이 있습니다만(사실 이걸 먼저 여쭤봤어야 했는데 "느낌"만 보자는 느낌으로 작업하긴 했습니다^^;) 이미지 상에 나온 ①이 하나의 화면인건가요 ②가 하나의 화면인 건가요? 처음엔 ①인줄 알았는데 상당히 볼륨이 작아져버려서 임의로 ②로 작업했었습니다 .

**Comment by CreatorLDH** [comment]
"느낌" 잘 확인했습니다. 그래서 너무 감사드려요!!! (느낌은 만족!)

아아아아아... 저 (1) 표시에 맞춘 것으로 하셨구나!!!! 이런, 소통의 오류가 발생했나 보네요!!

빨간색 박스 표시한 것에 대한 설명을 우측에 텍스트로 기입한 거였습니다!! (추가 설명 느낌)
1이 하나의 화면이고! 2는 추가 설명이 필요한 부분을 체크한 곳이었습니다...

;-:..

**Comment by fkdl0048** [comment]
개인적인 바람으로는 저 담벽 표현이 너무 좋은데, 재활용이 가능하다면(아트 리소스 제작측면에서) 조금 더 게임 덩어리 표현이 있으면 좋을 것 같습니다.

게임적인 오브젝트들이 뭉쳐서 만들어진 덩어리 형태로 제작되어 재활용 된다면 세계관이나 분위기 연출등에 더 활용이 될 것 같습니다.

**Comment by royalbluesm** [comment]
오브젝트 제작 시에는 저 느낌을 살리되 게임 요소가 잘 보이도록 작업하겠습니다! 피드백 감사합니다 ~
