### ISSUE TITLE
[Ch1 Main][Ch1 SubB] 레벨 디자인 - UI 퍼즐 연결 및 보완

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#161]
- #152 
- #151 

해당 내용을 가지고, 연결 작업할 예정입니다.

리소스 문서까지는 가지 않을 거 같은데, 혹여나 시간이 많이 남으면 도전하겠습니다. (차주에 피드백받고 진행하겠습니다)

***

[UI 퍼즐 + 레벨 디자인 + 맵 디자인 요소](https://drive.google.com/file/d/18hfoJwuiY0CU7zqUT-ao9xHkniuNbku2/view?usp=drive_link)

변경점
- 문서 2개를 하나로 묶음
- 맵 디자인 전체 수정 및 플로우 재작성
- 마마고 컴퍼니에 대한 레벨 디자인 간단 추가 등

@fkdl0048 
혹여나 시간 남으시면...
1) 타일 빈 공간에 넣고 싶은 요소들이 있다면 알려주세요! (예시는 본 문서에 첨부되어 있습니다.)
2) 18p에 간단한 블럭 옮기기 퍼즐 만들었는데, 이에 대해 다른 구조의 아이디어가 있으시면 부탁드립니다!
좀 크게 만들면, 다른 게임이나 미디어 속 자료 참고하면 좋은데 작고 금방 끝나게끔 구성중이라!!!

+ 한붓그리기 전선 퍼즐은 간단한 형태이며, 참고 자료가 많기에 추후 디밸롭 예정입니다.

**Comment by CreatorLDH** [comment]
팩맘 보완 작업이 일찍 종료됨에 따라 시작 날짜와 종료 날짜 변경
11월 23일 ~ 24일 => 11월 22일 ~ 23일

**Comment by fkdl0048** [comment]
## 피드백

- 플로야드의 라플리가 떨어짐으로서 생긴 흔적이 쓰레기 산을 기준으로 벽에서 조금 흘러내린 느낌일까요?
- UI를 안쓰기 위해 자판가까이 갔을 때 마마고가 상품에 대한 설명을 말풍선으로 해주는 부분이 너무 마음에 드네욥!

## 요청사항

- 타일 빈 공간 오브젝트는 최대한 게임 분위기에 맞는다면 뭐든지 상관 없을 것 같습니다.  (~~이스터에그로 많이 남겨도 되고~~)
  - 좋은 방법은 저번 세계관 컨셉아트 리소스 문서를 @royalbluesm 민지님에게 드리고 좀 더 민지님 선에서 자유롭게 그리시는 것이 좋을 것 같습니다.
  - 따라서 필수적으로 들어가야 하는 요소를 제외하고 저번 스타일프레임과 같이 몇 개의 반복적인 요소를 제외하고 명암처리가 더 깔끔해보이긴 합니다. (너무 많은 요소가 있다면 복잡할 것 같다는 생각, 시선의 분산)
  - 그래도 아이디어를 내보자면 단순 2BIT(2프레임)정도의 고전 게임과 같이 2프레임 애니메이션(뚝뚝 끊키는) 마치 포켓몬 아주 옜날 애니메이션같은 느낌도 좋을 것 같습니다. 풀이나 빛, 물등에 애니메이션 처리
  - 바닥을 제외한 경계를 표현하기 위한 울타리나 높낮이를 표현할 수 있는 타일이 필요할 것 같은데 해당 게임적 배경에 맞게 설계하는 것이 관건일 것 같습니다.
- 저는 현재 퍼즐 전부 만족합니다. 1챕터는 정말 튜토리얼 챕터라 너무 어렵지만 않게 (팩맘과 같이) 가볍게 설계 되는 것이 좋을 것 같습니다!

**Comment by fkdl0048** [comment]
@CreatorLDH 추가로 민지님 작업전에 따로 스타일 프레임에 대해서 맵 디자인 1~4, 위험지역 중 어디 부분을 할 건지, 그리고 디테일한 부분이나 궁금한 부분을 이야기 하면 좋을 것 같습니다!

**Comment by royalbluesm** [comment]
문서 확인했습니다. 생각보다 각 맵 간의 질감이나 디자인 차이가 크지 않아 (1)GG타운 입구, (2)플로야드 1, (3)플로야드 위험구역 정도로 3개만 만들어도 괜찮을 것 같은데 어떠신가요?

**Comment by CreatorLDH** [comment]
괜찮습니다. 

민지님이 말씀하신 것처럼 큰 차이가 없기에 3개만 만드셔도 충분할 거 같습니다.
대부분 파여있거나 쌓여있는 리소스 더미들의 차이로 맵의 구조가 달라지는 느낌이라서!!! 감사합니다.

차주에는 필요 리소스와 같은 내용을 열심히 고려해보겠습니다.

**Comment by royalbluesm** [comment]
![styleframe2](https://github.com/GG-Studio-990001/GameOver/assets/144519956/aa7f8166-12a5-4dcc-b0ae-6aa5ae33cbe2)
플로야드(1) 작업중인데 스케일감 이정도로 적당할까요?

**Comment by CreatorLDH** [comment]
네 스케일감 (라플리와 배경과의 크기 비율 맞죠?) 괜찮습니다.

<img width="298" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/def8d972-ee9e-4e19-a717-cf4989e0791e">

쌓인 리소스 무더기들 배치 참고부탁드립니다! (이해하시기 어려우면 추가 코멘트 남겨주세요!)

**Comment by royalbluesm** [comment]
아이고 제가 번호를 잘못적었네요 GG타운 입구쪽입니다!! 그리고 그 밝기 관련해서인데, 구멍 아래로 떨어진 상황이니 살짝 어둡게 작업하고는 있는데 설정상 밝기가 어떻게 될까요? 지하여도 낮과 밤이 있는 설정이라면 낮처럼 설정해도 괜찮을 것 같은데...

**Comment by CreatorLDH** [comment]
넵! 낮과 밤이 있습니다. 현재 설정상, 심마니들의 활동 시간은 14:00 ~ 19:00로 되어잇어서 낮으로 구성해도 좋을 거 같습니다.

그래서 밝은 느낌이 드는 회색조로 구성하시는 게 좋을 거 같습니다.

구멍아래로 떨어진 것이 동굴이나 어느 깊숙한 지역으로 들어가는 구멍이 아닌, 실제 하늘에서 비랑 우박이 내리는 것처럼 내려온 것임을 알려드립니다!
