### ISSUE TITLE
[Pacmom] 팩맘 구현

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#162]
## 관련 issues
- #117 
- #120 

## 움직임

기본적으로 갈림길마다 발판을 설치해두고, 발판을 밟으면 가능한 위치 중 하나로 이동 (팩맘, 먼지유령 공통)

**이동 우선순위**
기본 상태
1. 먼지유령이나 라플리가 짧은 거리 이내에 있다면 멀어지는 방향으로 이동
2. 코인이 많은 쪽으로 이동

청소 상태
1. 먼지유령이나 라플리 중 가장 가까운 거리에 있는 것과 가까워지는 방향으로 이동
2. (먼지유령과 라플리를 모두 잡았다면) 코인이 많은 쪽으로 이동

우선 라플리와의 거리만 생각해서 구현해둘 듯

## 애니메이션

기본적으로 입을 벌리고 닫는 애니메이션을 일정 주기로 loop

청소기를 먹으면 청소기를 든 스프라이트로 변경

목숨 0개 시 죽은 스프라이트로 변경

## 코인

라플리와 동일한 방식 (코인 스크립트에서 layer 체크 후 충돌 처리)

## 충돌

코인, 청소기, 라플리(보통 상태일 때), 라플리(청소 상태일 때) 처리

**Comment by fkdl0048** [comment]
생각해보니 코인의 경우 object pool을 활용하는게 좋아보입니다

**Comment by wooyn730** [comment]
지금도 게임 중에는 따로 코인을 생성, 파괴하지 않고 활성화/비활성화만 해주는데 오브젝트 풀링을 사용하는 거랑 차이가 있나요??

**Comment by fkdl0048** [comment]
헉 그럼 상관 없을 것 같습니다!

**Comment by fkdl0048** [comment]
- 우연님 입원 이슈로 Task 변경
