### ISSUE TITLE
팩맘 사운드 리소스 제작_3

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#168]
#159 내용과 동호님의 피드백에 따른 사운드 리소스 재작업

------

동호님이 코멘트로 주셨던 피드백에 따라서 사운드 리소스를 재작업 해봤습니다.

- 먼저[ 8번과 10번 효과음](https://drive.google.com/file/d/1IXw86v2UDTdCoW6qN-XjgCK8wP18sD8f/view?usp=drive_link)을 연계해서 만들어보았습니다. 
팩맘과 라플리, 유령과의 접촉 시에 발생하는 효과음 뒤에 바로 팩맘이 유령과 부딪힘에 따라 코인이 떨어지는 소리입니다.

> 동호님이 들려주셨던 코인 떨어지는 소리와 비슷하게 해보려고 했는데 조금 어렵네요..! 
> 이 느낌이 맞을 지 모르겠어요 피드백 주시면 계속 고쳐나가보겠습니다.

- [12번 라플리 등장음](https://drive.google.com/file/d/1Jjb062RBASS6iu3aFjHFd-qBiz3rJjB5/view?usp=drive_link)을 17번과 함께 분할했습니다. 본래와 똑같습니다.

>  근데 제가 물어본다는 걸 깜빡했었는데 혹시 터지는 부분 짧게 간략한 뿅? 이라는 소리가 뭘까요?! 사운드를 더짧게 바꿔달라는 말씀일까요?!

- [13번 효과음 1](https://drive.google.com/file/d/1CjH0lOqmeFbKyvIZeRroDGTC00eHSeZs/view?usp=drive_link) 말풍선 속 먼지 유령의 대화 효과음입니다. 동호님이 요청하신대로 마지막 파일에서 피치를 조금 더 올려보았습니다. 
- [13번 효과음 2 ](https://drive.google.com/file/d/1g_zufy-nUTAw1TIcs5gBV_PVMfNFE63X/view?usp=drive_link)이건 살짝 동물의 숲 느낌이 나긴 하지만 이런 느낌도 괜찮을 것 같아서 다시 만들어봤습니다~!
- [13번 효과음 3](https://drive.google.com/file/d/1D1K6xBb-yQQzswKG9m7qK2-NqoR1_frZ/view?usp=drive_link) 앞에 것들을 듣다보니 뭔가 괴물에 더 어울리는 소리인 것 같아서 제가 생각한 먼지 같은 느낌으로 사운드를 다시 만들어봤습니다!
- [13번 효과음3-1 ](https://drive.google.com/file/d/1YNNm--VhAXOYL9LHrv5YpuiKzEUo-rT5/view?usp=drive_link)3번의 피치 조정본 입니다. 

> 들어보시고 피드백도 해주시고 뭐가 괜찮은 지 한번 골라주세요!

- [14번 효과음](https://drive.google.com/file/d/1YNNm--VhAXOYL9LHrv5YpuiKzEUo-rT5/view?usp=drive_link) 잡힌 후 회귀하는 효과음입니다. 8비트랑 어울리게 전자음같은 뾰로록 같은 소리로 해봤습니다.

- [15번 효과음](https://drive.google.com/file/d/1SRVQ3czOKvtF2fPjBz-R29Yp3NE5LoDH/view?usp=drive_link) 먼지 유령의 이동음입니다. 먼지 유령이 움직이는 소리를 표현해봤는데 바스락거리는 소리는 묻힐 것 같아서 뭔가 하찮은 느낌의 먼지랑 어울리는 느낌으로 만들어봤습니다.

- [16번 배경음 ](https://drive.google.com/file/d/1Ngbpqn_xNm8bcxAFLAxKkJKEnNmGmOOp/view?usp=drive_link) 팩맘 청소모드에 사용되는 배경음으로 원래 작업했던 번호는 1번 이였습니다. 동호님이 요청해주셨던 노래를 10초 내내 깔아봤습니다!
- [16번 배경음 분할](https://drive.google.com/file/d/1iSpMrmKFGqiVqhXBAcXZq7mdCRWUdz-v/view?usp=drive_link) 청소기 켜지는 효과음을 빼고 노래와 청소기 소리만 다시 업로드 합니다.

- [17번 효과음](https://drive.google.com/file/d/1ORsLSLKdvFV_pBDl9f9uv3hlkUyjzeqy/view?usp=drive_link) 원래 12번 효과음을 분할해서 다시 올렸습니다!

피드백 환영입니다 !!

-----------------

러프하게 컨셉 사운드도 하나 제작해봤습니다!! 오늘 그냥 후다닥 만들어본거라 좀 우당탕탕 사운드긴 합니다 ,,
상점에서 흘러나올 것 같은 음악을 생각하면서 만들었습니닷 느낌 봐주시면 좋을 것 같아요!

[1203 컨셉 사운드](https://drive.google.com/file/d/1gFuRjqFqaiHrrKF-XJfQoKRXXcVgXvjb/view?usp=drive_link)

**Comment by CreatorLDH** [comment]
### **피드백**
***

너무 고생하셨습니다.

**8번 / 10번**
- 소리가 나오는 주기나 간격은 맘에 듭니다!
- 다만, 소리가 너무 쨍해서 잘 어울릴까가 걱정이네요!! 
- 그래도 저번보다는 동전 느낌이 들어서 좋습니다.
- 인게임에 적용해보고 판단하는 것도 나쁘지 않을 거 같아요
- 실구현 때 사용된다면, 분리해서 주어야 합니다!

**12번**
- 네! 사운드가 짧은 버전도 있었으면 좋겠어요 ㅎㅎ

**13번**
-저는 1번과 3번의 피치 조정본이 좋은 거 같습니다!
-기화님 말대로 그런 느낌도 없지 않아서, 추가로 만들어주신 점 너무 감사합니다.
- 작업 효율상 수정 요청 대신 인게임 넣은 후에 판단해볼게요!
- 더불어, 미니게임 상에서 넘 어울리지 않다는 느낌이 나면 인게임 텍스트 대화음 소리를 적용시키는 것처럼 다른 방안을 고려해보겠습니다.

**14번**
- 링크가 잘못되어서 구드에서 들었습니다!
- 해당 소리 루프되어서 사용할 거 같아요! 거리에 따라 루프 횟수가 증가합니다!
- 이 점 고려 한 번 같이 해주시고, 괜찮다면 사용해봅시다!

**15번**
- 맵에서 지속적으로 들릴 소리라서, 볼륨은 설정해주신 기존 음보다 작게 들어갈 거 같아요 (유니티 내 조정)
- 루프되며 들릴 것이라 다른 피드백처럼, 지금 머릿속에서 엄청나게 잘 상상되지 않네요...ㅠㅠㅠ

**공통**
- 저번에도 말씀드렸다시피 원본 팩맨 게임은 여러 사운드 효과음이 중첩되어서 마치 배경음처럼 들리게끔 구성된 게임입니다! 그래서 저희 게임도 이렇게 많은 효과음들이 겹치면서 조화롭길 바라는 마음에 많은 효과음을 요청드린 것이었습니다!
- 그래서, 인게임에 직접적으로 넣어보고 판단할 요소가 많아진 거 같아 피드백을 디테일하게 드리기 어렵네요!
- (제가 음악적인 부분이 약해서... 더욱 그럴 수도 있습니다! 양해 부탁드려요!)

**16번**
- 전 노래 10초내내 까는 거 넘 좋아요.
- 분할 : 굿.

**17번**
- 굿.

**1203 컨셉 사운드**
- 후다다닥 만든 게 이정도라니 미쳤습니다.
- 중간에 끊기거나 그런 부분이 있지만, 당연히 러프고 후다닥 만든 것이니 ... bb
- 마마고 컴퍼니는 IT 회사 계열 + 게임 회사 느낌의 BGM을 생각하고 있었습니다.
- 그래서 다른 타이쿤 게임의 레퍼런스를 참조중이었어요!
- 해당 컨셉 사운드를 마마고 컴퍼니에 사용하지 않더라도, 다른 상점 건물들도 많기에 활용가치는 매우 높아보입니다. 감사합니다.

***

### **주저리**

CH1 일반 배경음과 마마고 컴퍼니의 배경음이 다르다!는 느낌을 유저에게 팍 주고 싶습니다.
일반 배경음을 주구장창 듣다가, 퍼즐을 풀고 마마고 컴퍼니에 처음 들어갔을 때 "무음 (연출)"이 나타납니다.

추가로 마마고 컴퍼니 내 문제 또한 해결하면, 그제서야 맵의 불이 켜지고 마마고 컴퍼니만의 사운드가 등장합니다.
이 상황에서 유저에게 성공 + 여긴 뭐지? + 회사인가? 이런저런 느낌을 주고 싶네요.

**Comment by wooyn730** [comment]
기화님 조만간 팩맘 사운드 적용하려고 하는데요,
그 전에 구드에 있는 파일명 수정해주시면 감사하겠습니다~~~

**Comment by Songkihwa** [comment]
제가 과제 제출이랑 기말고사 공부 때문에 지금 당장은 정리하기가 어려울 것 같아요ㅠㅠ 혹시 언제까지 바꿔드리면 될까요?

**Comment by wooyn730** [comment]
다음주 중에도 괜찮아요~

원하는 기한은 딱히 없고 정리해주시면 이후에 사운드 적용하겠습니다~~

**Comment by Songkihwa** [comment]
일단 이번주 작업부터 완성해보고 파일명 변경 작업 가능할 것 같습니다ㅠ 이번주에 시간이 안 나면 다음주에 진행하도록 하겠습니다 ㅠㅠ

**Comment by Songkihwa** [comment]
@wooyn730 우연님 저 시험 끝나서 구드에 파일명 바꿔놨습니다~! 번호는 동호님 전체 리소스 문서에 있는 번호에 맞게 매겼습니다!

**Comment by wooyn730** [comment]
확인했씁니다! 적용해볼게요~~

리소스 문서 다시 한 번 자세히 봐야하는데 이름 안바뀐건 적용 안하는 거겠죠?

리소스 파일들 이름에 k만 빼서 수정해놓겠습니다..! (pacmom으로 쓰는 중이라..)
