### ISSUE TITLE
메인 시스템-스타일프레임 제작③

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#169]
**이전 작업**
#143 #160

**상세**
스타일프레임을 규격에 맞게 수정하고 리소스를 정안님께 전달한다.

[프리뷰](https://drive.google.com/file/d/19mi3t045zQXNHgWUDuhn05TpsIs8C-bP/view?usp=sharing)
수정한 스타일프레임 리소스 뜯어서 전달해드리려고 하는데, 위 프리뷰 보시고 컨펌 한 번 부탁드립니다! 

**파일**
[메인 시스템 리소스](https://drive.google.com/drive/folders/1M35mzeAQpWuwIldsYO8jZCoGZuuzZyt7?usp=drive_link)

**Comment by CreatorLDH** [comment]
1번과 2번 맵 연결된 부분을 이렇게 보니까,
챕터 1을 단편적으로 끊어낸 방식만을 추구하기 보다 다양하게 구사할 수 있도록 해야겠네요!

잘 보았습니다. 감사합니다.

혹여나 본편 디자인으로 나아가게 된다면,
- 리소스를 치우기 위해 쌓인 부분과 의도적으로 리소스를 담벽처럼 만든 부분에 차이를 어떻게 줄 지 더 고민해야 겠어요!
- 우측 상단에 떨어져서 생긴 저 구역은, 퍼즐로 움직일 오브젝트도 들어가야 해서 모양 수정이 될 가능성이 높습니다!

죠습니다:D
