### ISSUE TITLE
메인 시스템-도트 스프라이트 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#170]
**상세**
프로토타입용, 플레이어 캐릭터의 2~3프레임 애니메이션을 작업하고 정안님께 전달한다.

**파일**
common(정지), walk(걷기) 작업 완료
[png 시퀀스 파일](https://drive.google.com/drive/folders/1_xDJpuxXu8bCkysdfGIAbJjagd-w28oM?usp=drive_link)

**Comment by fkdl0048** [comment]
다음 주 회의 전까지 적용해서 가겠습니다~ (피드백은 그때!)
