### ISSUE TITLE
Feat: MSC01 Charter

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#176]
# Feat: MSC01 Charter

캐릭터 관련 기능 전부 모아서 정리

## 현재까지 구현된 기능
- 움직임
- 애니메이션
- 상호작용

**Comment by fkdl0048** [comment]
@CreatorLDH 동호님 혹시 이동이 이해한 바로는 대각선 이동이 제한된다고 이해했는데, 둘 중에 어떤 게 더 좋을까요?

회의 때 이야기해도 좋습니다!

### 4방향
![CutSene gif](https://github.com/GG-Studio-990001/GameOver/assets/84510455/3c9653cc-16dd-44cd-b1f9-3efbe2ccfec2)

### 8방향
![CutSene gif](https://github.com/GG-Studio-990001/GameOver/assets/84510455/da1504bf-2374-4f39-94a0-75470c809d89)

**Comment by CreatorLDH** [comment]
원래 4방향으로 나아가려고 생각했습니다만, 로그라이크 장르를 생각하니 8방향으로 해야 플레이 경험이 더 좋을 거 같습니다.
