### ISSUE TITLE
[Char] 기타 NPC 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#186]
- #166 

여기서 표현했던 기타 NPC 기획을 진행할 예정
다른 NPC 기획처럼, 구체적으로 진행하지 않고 캐릭터 디자인적 요소만 제공할 예정.

***
[기타 NPC](https://drive.google.com/file/d/1CYHPpIpGB4pyLh5nrYQ987R2LbAyJq0l/view?usp=drive_link)
***
### **챕터 1 기타 NPC의 역할은** 
1.	게임 내 퍼즐 및 유머 요소를 이끌어갈 보조 NPC
2.	게임 맵 내 빈 공간을 채워주는 역할
3.	챕터 1 이후 등장 가능성 낮음
- 그러므로, 빠르게 만들어서 활용가능한 복붙캐로 생각하고 있습니다.
- 그래서 민지님의 개인적인 디자인을 사용해도 크게 상관없습니다.

그래서 본 문서는 기타 NPC 중 경비 심마니 2명에 대한 간단한 기획과 함께 기타 NPC 들에 대한 레퍼런스를 정리합니다.
본 주요 NPC 기획과 다르게, 자세한 문서는 생략합니다.

**Comment by Songkihwa** [comment]
작업하시느라 고생하셨습니닷! 진돗개와 비글로 NPC 성향 다르게 표현하는 거 좋은 것 같아요! 근육질 진돗개 귀여울 것 같네요 ..ㅎㅎ
기타 심마니 NPC는 광부처럼 표현해봐도 좋을 것 같네용ㅎㅎ
