### ISSUE TITLE
[Ch1 Main] 배경음 제작_1

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#187]
챕터1 지역에 따른 배경음 제작 

-------

#166 을 참고하여 [마마고 컴퍼니의 배경음](https://drive.google.com/file/d/1_PAe2ShvJ-b4XKyf1ybHFpjdZebIadIn/view?usp=drive_link)을 제작해봤습니다.

> 근데 파일명 이렇게 하는 거 맞나요 ...?? 

마마고 컴퍼니 배경음의 요청사항으로 다른 곳과는 느낌이 확 달랐으면 좋겠다고 하셨는데,

[동호님께서 첨부해주신 참고 영상](https://youtu.be/hnTua-TOSVE?si=uOsquB4JNKkDzeq1&t=76)에서 주로 8비트 사운드로 연주되더라구요
제가 전에 만들었던 곡도 그렇고 챕터 1의 맵 BGM은 8비트 사운드를 주로 쓰게될 것 같아서 
영상처럼 만들면 느낌이 확 달라지진 않을 것 같다는 생각이 들어서 8비트 사운드보다는 좀 더 입체적인 신시사이저를 주로 사용해봤습니다!

동호님이 첨부해주신 영상에선 분위기, 느낌을 참고해서 작업 진행해봤는데
아무래도 사운드가 비슷하진 않아서 동호님이 생각한 것과는 다를 수도 있다는 걱정이 드네요..ㅠㅠ 
**편하게 피드백 주시면 언제라도 다르게 고쳐보겠습니다 !!**

아무래도 회사다 보니까 컴퓨터 키보드를 뚜들기는게 상상이 되어서 키보드 소리도 넣고
전체적으로 평화롭고 너무 신나지 않게, 일상적이고, 루프해도 이상하지 않게 작업해봤습니다.

피드백 환영입니다 수정 언제나 가능해요 -!!

**Comment by fkdl0048** [comment]
와 진짜 따듯해요.. 너무 완성도가 높아서.. 피드백 할 수 있는 게 없습니다..

혹시 제목이 있을까요?

**Comment by wooyn730** [comment]
느낌이 정말정말 좋은데요?!
도각거리는 키보드 소리를 넣은 것도 정말 마음에 들어요 ^_^

---

네이밍은 항상 어렵죠...
저라면 분류_(번호_)배경음/효과음 요렇게 할 거 같네요?
우리 게임에서는 재방문요소가 있으니 챕터는 명시 안해도 될 거 같아요

예를 들면 이렇게..
(한 서브시스템에 BGM이 여러개가 될 지는 모르겠네요)
Mamago_BGM
Pacmom_01_SFX

그냥 의견 중 하나입니다 (저도 잘 묘름 ㅠㅠ)
점점 작업물이 많아지면 자연스럽게 네이밍에 필요한 규칙이 생길거 같긴 합니다 ㅎㅎ

---

저도 이런 BGM 만들어주실 때 임시라도 제목 붙여주시면 좋을 것 같아요~!~

**Comment by CreatorLDH** [comment]
너무 고생하셨습니다!

키보드 소리 넣으신 거 좋은 거 가타요!!
처음 소리를 들었을 때는, 키보드 소리에 오히려 더 집중되지 않을까 생각했는데 듣다보니 자연스레 조절해주신 거 같아 전 맘에 듭니다!

> 8비트 사운드보다는 좀 더 입체적인 신시사이저
너무 좋은 결정입니다! 추후 다른 장르에서도 지속적으로 해당 BGM이 들리기 때문에 좋습니다~

**Comment by Songkihwa** [comment]
**정안님**

좋게 들어주셔서 감사합니다 !!
제목 .. 제목이 어렵네요 .. . 한번 생각해볼게요 ㅠㅠㅋㅋㅋ

------
**우연님**

거슬리지 않는 키보드 소리 찾아서 넣었는데 좋다니까 다행이네여 ㅠㅠ ㅎㅎ
오 네이밍은 우연님이 말씀해주신 네이밍이 좋을 것 같아요! 
임시라도 제목 ... 붙여보도록 하겠습니다...

**<제목>** 
Our Day by Day 입니다..
언제라도 마마고 컴퍼니를 들어가면 하루하루 열심히 살아가는 마마고 컴퍼니 직원들을 볼 수 있으니 ..
그게 마치 우리같은 .. 어쩌구 .. 그런 느낌 .. 아무튼 하루하루 빠이팅 하자는 뜻입니다. ...

------
**동호님**

좋게 들어주셔서 감사합니다ㅎㅎ 
적용해보고 또 수정사항이 있을 수도 있으니 언제든지 말씀해주세요 !

**Comment by yanggang3** [comment]
처음 듣고 너무 좋아서 놀랐어요..!
신나지 않은데도 편안하고 기분이 되게 좋아지는 멜로디인 것 같습니다!
신시사이저?인 전자음악소리랑 옛날식키보드 소리가 조화로워서 더 독특한 분위기가 나는 것 같습니다!
너무 수고하셨어요..
