### ISSUE TITLE
[Ch1 Main][Ch1 SubB] 맵 디자인 보완 + 퍼즐 구체화

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#188]
- #161 

해당 내용을 보완하고 퍼즐을 구체화한다.

내용 분리 / 가독성을 위해 분리함.

1. 맵 디자인 + 사건 분기에 따른 레벨 디자인
2. 퍼즐 구체화

+ 맵 구조의 변경이 있을 예정 

***

[퍼즐 구체화 문서](https://drive.google.com/file/d/1Fa4QFEDbRcA4DAxfi-nqtO4TUIl0P0u6/view?usp=drive_link)

[맵 및 사건 분기 레벨디자인 합본](https://drive.google.com/file/d/16d63wu_ECGCg0egbGiTIM7TWt7B53NOP/view?usp=drive_link)

**Comment by fkdl0048** [comment]
- 기믹 자체는 완성도가 높은데 실제 구현이 어떻게 그려질 지 궁금하네요!
  - 목재나 코인의 의도를 숨기면서도 자연스럽게 유저가 얻을 수 있게..
  - 걱정되는 부분은 3회 맵 이동 후 목재나 시간 적인 요소를 그래픽으로 잘 보여줘야 할 것 같습니다. (이 부분은 제작하면서 해결될 것 같습니다.)

그 외 피드백은 없습니다..

기획문서도 시간이 지나면서 점점 퀄리티도 올라가고 이해할 수 있게 작성하신 부분이 너무 잘 보이네요!

**Comment by wooyn730** [comment]
궁금한 점

> 3개가 된 블록은 터지며 사라짐. 이런 방식을 활용하면, 끝내 SLG UI를 얻을 수 있음

이 부분은 UI가 박스에 들어있고, 닿아있는 블록이 터지면 박스가 부서져서 안에 있는 UI를 획득하는 느낌인가요?
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b1162580-01fb-4954-bc31-9fd56ec5613d)

아니면 주변 블록들을 치워서 UI에 직접 접근하는 방식??

---

![스크린샷 2023-12-10 170158](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3df0a539-4cd5-4b45-93ce-c8eb1ec398e7)
![스크린샷 2023-12-10 170234](https://github.com/GG-Studio-990001/GameOver/assets/80298207/1a0508c0-1f9a-4d5d-8c24-2238c8362cee)
이런 부분들은 이해하기 쉽게 잘 설명해주셔서 좋네요!

---

저도 실제 구현될 것이 궁금하고 기대되네요!
수고하셨습니다!!

**Comment by CreatorLDH** [comment]
의견 감사합니다.

정안님
- 시간적인 요소를 알려주는 UI로 기존 SLG UI 레퍼런스를 참조하여 요청드릴 계획입니다!
- 특히 석재나 코인은 시각적인 UI가 뒷받침되고 있어서 자연스레 플레이를 도출할 수 있다고 생각하지만, 목재는 자연스레 유도할 방안이 크지 않아서 대화 텍스트를 활용하거나 기타 UX 적인 부분 고려해보겠습니다:D
- 넵 일단 분기에 따라 자동세이브가 되게끔 생각하고 있습니다! (세이브 텍스트 연출 재생)

우연님
- 넵. 주변 블록들을 없애서 자연스레 다가가는 방식으로 생각하고 있습니다.

**Comment by royalbluesm** [comment]
전에 비해 문서 가독성이 조금 좋아진 것 같아서 좋아요 ㅎㅎ

1. SLG, 레이싱 UI를 결합하는 부분에 있어서 조금 고난이 예상되네요 허허 막상 이미지로 보니까 굉장히 이질적인데... 이 이질적임을 살리면서도 예쁜 화면을 구성하는 것이 제법 난이도가 있을 것 같습니다 살려줘~~
2. 퍼즐 완성도 너무 좋은데요? 대중성 있고 게이머라면 한번쯤 해봤을 법한 게임들에 담긴 미니게임들이라 큰 어려움 없이 해낼 수 있을 것 같습니다. 
3. 레벨디자인 시각화할 때 저번처럼 커뮤니케이션 미스가 일어나지 않게 동호님과 소회의 한 번 가지면 좋을 것 같습니다. (소회의라 쓰고 드로잉쇼라 읽는다~)
4. 문서 보다가 생각난 건데 UI 등 맵에서 아이템을 습득할 때 반짝이라든지 이런 아이템 아이콘을 정해놓는 게 좋을 것 같습니다. (언더테일마냥 모든 필드드랍 아이템에 도트가 들어간 스타일이 아닌, 포켓몬처럼 몬스터볼로 통일하는 형식에 가까움) 단 하나로 전부 통일하지는 말고 UI면 UI, 언어팩이면 언어팩, 아이템이면 아이템...이런식으로 구분짓는 게 좋을 것 같네요.

**Comment by CreatorLDH** [comment]
피드백들 감사합니다:D 참고하겠습니다.

**Comment by fkdl0048** [comment]
동호님 분기를 설정관련해서 세이브 로드 및 대화에 관련되게 보고 있는데,

(“챕터”.”전체NPC의 대화가 바뀌는 순간”.”일부NPC의 대화가 바뀌는 순간”)

이 방식에서 Chapter, 저장되는 소 챕터(세이브 포인트), 대화가 바뀌는 순간

이렇게 하는 건 어떠신가요?

데이터를 다룰 때 지금 세이브 지점과 동호님이 작성하신 챕터 구분 양식과 통일되게 했을 때로 생각해봤습니다.

더 좋은 방식이 있으면 좋을 것 같은데 일단 이렇게 생각했어요

그리고 인덱스를 0부터 시작할 수 있나요? (0, 0, 0)

**Comment by fkdl0048** [comment]
생각해보니 (챕터, 맵 번호, 사건 분기) 이렇게 다뤄도 좋을 것 같네요

**Comment by fkdl0048** [comment]
동호님 추가적으로 

- https://github.com/GG-Studio-990001/GameOver/issues/83

여기에 스토리보드나 Main쪽 관련있는 기획 이슈 넣어주실 수 있나요? 최신본으로 업데이트 해주시면 감사하겠습니다!

**Comment by CreatorLDH** [comment]
이번 주차까지 반영하여 수정했습니다!

**Comment by fkdl0048** [comment]
감사합니다! 분기 기능은 지금 제작중인데 마무리 되는대로 Yarn쪽이랑 연동해서 회의때 말씀드린 부분 전달드리겠습니다
