### ISSUE TITLE
[Ch1 SubA][Pacmom] 먼지유령 구현

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#189]
# [Ch1 SubA][Pacmom] 먼지유령 구현

제목은 이렇지만 라플리&팩맘 개발과 리팩터링, 테스트 코드 병행...

## 움직임

**[기본 상태]**
랜덤 이동, 팩맘이 가까이 있으면 쫓아감

**[청소 상태]**
랜덤 이동, 팩맘이 가까이 있으면 도망감, 속도 느려짐

랜덤 이동: 
기본적으로 갈림길마다 발판을 설치해두고, 발판을 밟으면 가능한 위치 중 하나로 이동 (팩맘, 먼지유령 공통)

**=> 완료**

## 애니메이션

**[기본 상태]**
- 몸통
   - 2개 스프라이트 일정 주기로 반복
- 눈
   - 이동하는 방향에 맞는 눈알 스프라이트

**[청소 상태]**
- 몸통(눈 포함)
   - 2개 스프라이트 일정 주기로 반복 
   - ~청소 시간이 끝나가면 4개의 스프라이트 반복~

**=> 완료**

## 충돌

라플리: 물리적 부딪힘
팩맘(보통): 팩맘 먹음, 팩맘 목숨이 남으면 각자 위치로 초기화 / 팩맘 죽으면 게임 오버, 팩맘 코인 뺏기
팩맘(청소): 먹힘, 위치 초기화
코인: 통과
청소기: 통과

**=> 완료**

## 참고 자료

[타일맵 콜라이더 설정](https://docs.unity3d.com/kr/2018.4/Manual/class-TilemapCollider2D.html)

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/a5d24132-59cb-4ef5-b00c-143fd9066643)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/24c8dbf3-bad7-4088-8d0f-a6f6982996b8)

[코루틴](https://wergia.tistory.com/226)

**Comment by wooyn730** [comment]
다음 마일스톤에서 작업 예정

[사유]
객체지향적으로 코드를 짜지 않았더니 테스트 코드가 엉망이 됨.....ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
리팩터링을 병행하며 테스트 코드 갈아엎는 중..................................

**Comment by fkdl0048** [comment]
뭔가 전 코드리뷰에서 요구사항을 보고 걱정하긴 했지만, 필연적으로 발생할 수 밖에 없는 사건이라고 생각하시면 좋습니다 ㅎ..
