### ISSUE TITLE
[Ch1 SubA] 리소스 제작

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#190]
#167 에 적용된 모습 보고 수정/보완작업
------------------------

#202의 내용 바탕으로 리소스 수정작업하였습니다.
@wooyn730 우연님이 적용해주시고 다른 분들 의견 반영해서 가장 나은 디자인 정하고 완료할 생각입니다!

타일맵-바닥
https://drive.google.com/file/d/194p1IO2DCVWyjJ8hhefXZLFrSwFknirn/view?usp=drive_link

타일맵-벽1(바닥없는 버전)
https://drive.google.com/file/d/1kOTuFO2Q1BvX_ZyysESGo_eitqn8lt02/view?usp=drive_link
타일맵-벽2(붉은 색감 줄인 버전)
https://drive.google.com/file/d/1ToD-omKsqnyxJUyPARRohvvNgTWXzFfd/view?usp=drive_link
타일맵-벽3(흑백버전)
https://drive.google.com/file/d/1XSY6J5_EMEtiQJrgM1xy7pYqbbCnE0Wt/view?usp=drive_link

먼지유령(아마 최종..!)
https://drive.google.com/file/d/1LbQZngfGMGj1ZTXhFMgE5ma7bz1Q7MKO/view?usp=drive_link

라플리(최종)
https://drive.google.com/file/d/1KZlo-Ukj-NXbe-GwOD1FUQnBRJjAYtE6/view?usp=drive_link

팩맘(최종)
https://drive.google.com/file/d/1RZVeY7y0VNUySqwDs5Q8j4IVaeXBUeil/view?usp=drive_link

**Comment by wooyn730** [comment]
## 타일 적용

### 붉은 벽
![스크린샷 2023-12-11 204333](https://github.com/GG-Studio-990001/GameOver/assets/80298207/c998b7e2-bf5f-4fe4-ae0c-950fc6111dc3)
![스크린샷 2023-12-11 204343](https://github.com/GG-Studio-990001/GameOver/assets/80298207/67fdd749-6eaf-489e-a9bb-99db9bc5fd0d)
![스크린샷 2023-12-11 204350](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3c23382e-1329-4104-bfc6-fbda505a914d)
![스크린샷 2023-12-11 204358](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3fbbea44-827d-4e95-b88b-88ddd6919cf9)

### 갈색 벽
![스크린샷 2023-12-11 205233](https://github.com/GG-Studio-990001/GameOver/assets/80298207/4b7ac313-2b85-4265-be0d-f4dfdc42eee9)
![스크린샷 2023-12-11 205241](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f8a0e52f-8ecb-4994-a0be-30d54660694d)
![스크린샷 2023-12-11 205249](https://github.com/GG-Studio-990001/GameOver/assets/80298207/50ea8755-caa6-418a-af32-e588144e649b)
![스크린샷 2023-12-11 205300](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d4aed287-b855-48a1-94ae-e38e49dd7025)

(검은 벽은 아직)

**Comment by wooyn730** [comment]
## 타일 피드백

*회의 직전이라 급해서 음슴체로 적습니다!!!!!!!!!!!!!*

1.
이전에 맵의 가장자리에 분홍색 선?을 주기로 한 것에서 빼기로 결정했었음
![스크린샷 2023-12-11 204156](https://github.com/GG-Studio-990001/GameOver/assets/80298207/6d1e567a-57c5-471d-a9aa-7facb4ea8ecf)
(이전)

![스크린샷 2023-12-11 204159](https://github.com/GG-Studio-990001/GameOver/assets/80298207/abb73362-3ce8-4755-a335-ef17e180071f)
(이후)

따라서 3개의 타일은 필요가 없어짐
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/a904300f-b803-4036-a5ef-1d20ac8b155e)


2.
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/5cee5b88-ec5f-4248-851d-51f6f2cfc500)
가운데 방의 벽은 양끝 분홍색 선이 들어간 걸 사용하기 때문에
네모 모서리 타일이 한 픽셀 부족하게 보임

![스크린샷 2023-12-11 205802](https://github.com/GG-Studio-990001/GameOver/assets/80298207/ddddc4b5-44d1-45be-a5b4-b47260d1a7dd)
해당 타일을 수정해줘야함

3.
방문 타일이 아직 없음

**Comment by CreatorLDH** [comment]
무언가 타일과 벽의 색에 따라 분위기가 완전 달라지네요.

마인크래프트를 많이 해서 그런가 사막 사원 느낌이 나는 것도 있고, 학교 느낌도 있고 다른 분들의 의견이 필요한 부분이겠군요!

개인적으로 검정 바닥 타일은 제 눈이 이상한지 눈에 피로감을 강하게 주는 느낌이네요.
