### ISSUE TITLE
[Char]챕터 1 주요 NPC 도트 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#191]
**상세**
주요 NPC 5명의 도트를 제작합니다.

**작업물**
[Default 도트 프리뷰](https://drive.google.com/file/d/1nKC6hMvARJ8GWYgZeajUn3sWLvCLAXnz/view?usp=drive_link)

피드백후 개별 파일 구드에 올리겠습니다

**Comment by CreatorLDH** [comment]
고생하셨습니다!!!

어머,, 트루커와 미카엘은 도트 스타일로 등장하지 않는데 작업해주셨군요. 
(리소스 요청 문서를 더 가독성있게 수정해야겠군요, 분류별로 색을 넣는다거나!)

;-: 고생하셨습니다. 
다 맘에 들어요.

수정 요청을 드리자면,
R2-Mon이 뭔가 기계스러운 느낌보다는 몬스터스러운 느낌이 강한 거 같아요. 
구도 때문인지, 눈의 위치때문에 더욱 그런 것처럼 보이는 지.. 음
도트 표현의 한계인지 모르겠네요.

<img width="141" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/096cfa74-fbb5-4535-8e14-80e48c249fe2">
<img width="175" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/b5a22325-b5e3-45f2-b14b-c37202e3f269">

눈의 모양(사각형 -> 톱니모양(도트땜에 어려울까요?))을 바꾸거나, 혹은 눈 주변 색을 조정해도 좋을 거 같아요! (지금은 너무 어두운 색이라 선색이랑도 차이가 안나기도 하고, 저 흰색 눈에 시선이 자꾸 가네요!)

두리뭉술한 의견이라 너무 죄송합니다!
