### ISSUE TITLE
[Ch1] 스토리보드 및 연출 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#193]
인트로 연출부터 아웃트로 연출까지의 내용을 임의로 기획해본다.
스토리보드를 직접 만들어서할 지, 애니메이팅 툴을 이용할 지는 미래의 내가 잘 할 것이다.

[스토리보드](https://drive.google.com/file/d/18RIBV_WwJhOdksjoE_k91Rpn-apCrVTF/view?usp=drive_link)

대사나 이런 것들은 수정될 가능성이 높습니다
뇌절도 많습니다.

연출적인 부분을 확립하고, 캐릭터의 동선과 그에 따른 리소스들을 임의로 확립하기 위해 만들었습니다.

**Comment by wooyn730** [comment]
잘 읽었습니다!!!
스토리보드를 보니 게임이 머릿속에 잘 그려지네요!! 너무 좋아요

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9747adb6-f0e3-437a-a2ec-488153c45850)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/fb9f48a3-ecc9-46c4-bedc-63e0b2454562)
라플리는 중성적인 특징을 가진 캐릭터니까 '양' 같은 호칭을 빼도 좋을 것 같습니다~
아니면 이영싫의 [아모르](https://namu.wiki/w/%EC%95%84%EB%AA%A8%EB%A5%B4(%EC%9D%B4%EB%9F%B0%20%EC%98%81%EC%9B%85%EC%9D%80%20%EC%8B%AB%EC%96%B4))처럼 캐릭터마다 라플리를 다른 성별로 생각해서 부르는 것도 재밌겠네요
('양', '군'을 혼용해서 부른다던가 / 하지만 영어 번역하면 어차피 호칭은 빠질지도..?)

**Comment by Songkihwa** [comment]
우와! 너무 고생하셨습니다
이거 보니까 우리 게임이 더 기대되는 것 가타요 ...

사운드 관련입니다 --!

혹시 1번 BGM이라하면 제가 전에 만들었던 엠비언스 사운드를 얘기하는 거 맞을까요? 

2번 BGM 같은 경우는 활기차다는게 뭔가 잘 안 그려져서
나중에 작업 시에 동호님이 원하시는 느낌의 레퍼런스를 보여주시면 작업이 수월할 것 같습니다 !!

> 이건 그냥 제 생각인데 대사나 주변 느낌을 보자면 활기찬 느낌보다는 살짝 긴장감을 이끌거나 고조되는 음악 느낌이 들어가도 좋을 것 같다는 생각이 살짝쿵 듭니닷 ㅎㅎ

**Comment by CreatorLDH** [comment]
피드백 감사합니다.

***

**우연님** 
- 중성적인 느낌 강조를 위해 호칭 부분 접수했습니다~
- 차주 이슈부터 확인하고 적용하겠습니다. 굿

**기화님**
앗 해당 스토리보드 문서는 연출적인 부분을 최대한 이해시키는 것이 주 목적이었기에 그런 설명을 자세히 쓰지 않았습니다!
금주 리소스 문서 보완 및 정리할 때 반영할 것이며
추가 설명 해드리겠습니다!

1번 BGM이라 기술했던 부분은
<img width="643" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/9189b912-71eb-4d09-b09a-ea66f0665a8d">
리소스 문서 내 이 부분입니다.
좀 분위기가 어둡고, 신비로운 느낌을 가졌습니다.

그래서 컷씬이 등장함에 따라 분위기를 반전시키고 싶고, 극이 유머스럽게 연출되어야 하니
2번 BGM을 활기차거나, 유머스러운 상황에 분위기 반전용으로 사용되는 배경음으로 고려했습니다.

해당 2번 BGM은 극중 유머스러운 분위기로의 반전이 등장하는 부분에 주로 사용될 것입니다.

추후에, 레퍼런스나 관련 내용 정리해서 드릴게요!
지금 사운드, 아트 작업물들이랑 정리해논 리소스 문서, 제가 작성한 문서들을 머릿속에서 합치고 있어서!!
좀만 기다려 주시면 감사하겠습니다:D

**Comment by fkdl0048** [comment]
너무 재밌네요 마마고 너무 매력적인 것 같아요

이 부분까지 연출만 제대로 만들어진다면? 게임 자체가 매력적일 것 같습니다!

**Comment by royalbluesm** [comment]
캐릭터들이 살아 움직이는걸 보니까 훨씬 친근해졌네요 ~~
중간에 컷씬이 들어간다면 컷씬 스타일을 어떻게 해야할 지 고민이 필요할 것 같습니다...(여기서 캐릭터 비주얼을 너무 구체화한다면 추후 비주얼노벨 챕터로 전환했을 때 신선함이 덜할 것 같아서...)
