### ISSUE TITLE
온라인 비정기 아트/플밍 회의, 2023-12-05 [20:00]

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#196]
# 온라인 비정기 아트/플밍 회의, 2023-12-05 [20:00]

## 비정기 회의를 위한 짧은 회의

(온라인 정기 회의 후 2023-12-04 23시 넘어서 진행함)

### 회의 내용
- 코인 -> 비눗방울 이야기 동호님과 꼭 이야기 나누길 바람!!!
- 아이디어가 추가되거나 조금 방향이 달라지게 되면 그리게 된 생각과 과정을 이슈에 적어주면 좋을 것 같음
- **아트**
   - 청소기는 입 다물고 있는 버전만
   - 입 다문 청소기 X 버전 필요
   - 라플리 눈 감는 스프라이트 추가
   - 기절 모션 2장 정도 추가 (청소기 X)
   - 라플리 빈공간 X 버전
- **플밍 (이동 방향에 따른 스프라이트)**
   - 라플리는 좌우반전 적용
   - 팩맘은 상하좌우 회전 (근데 머리카락이랑 청소기 고려해야함)
   - 먼지유령은 눈알 교체
- #167 *참고*

### 준비사항

- **세화**
   - 타일맵 여백 없는 버전과 비눗방울, 청소기 아틀라스 이미지
   - 오후 4시 전까지 전달
- **우연**
   - 타일맵과 비눗방울, 청소기 적용
   - 시간 여유 되면 팩맘 회전과 라플리 좌우반전, 팩맘 청소기 버전 구현

### 회의 내용

적용한 거 보고 같이 이야기 나눠봄

- **[타일맵]**
   - 더 필요한 타일에 대해 요청 (가운데 방 입구, 빨간 타일, 분홍 없는 ㄱ자 타일 등)
   - 격자무늬(바닥)의 크기, 벽의 색에 대한 팀원들 의견 구하기
- **[라플리]**
   - 라플리 크기 약간 줄임 (pixel per unit 10)
   - 눈 뜨고 감는 애니메이션 적용
   - 눈 뜬 스프라이트의 눈에 붉은 끼가 돌아서 검은 버전으로 요청
   - 눈 뜨고 감는 거, 살짝 점프하는 것에 대한 팀원들 의견 구하기
- **그 외**
   - 먼지유령과 팩맘 스프라이트 변경 사항은 없음
   - 먼지유령 빨강디버프, 파랑디버프 어떻게 적용할건지 이야기 필요
   - 코인과 전체적인 이미지에 대한 동호님 의견 필요
   - 세화 고민되는 부분에 대해 앞으로 이슈에 명시하여 코멘트 받기로 함
   - 우연 회전 버그 수정, 타일맵 픽셀 잘 보이게 하는 작업 진행할 예정

++
- 동호님 시험 끝나는 수요일 이후로 동호/세화/우연 비정기 회의 추진 예정
   - 그 전에 일부 스프라이트 보완(세화) 후 적용(우연)하려고 함
- 팩맘 아트, 플밍 모두에게 이득이 되는 회의였음!!!
- 다음 비정기 회의(동호/세화/우연)는 세화가 회의록 써보기로 함 ^_^

**Comment by yanggang3** [comment]
@wooyn730 수정본 구드에 올려두었습니다! 천천히 확인해주세요!

**Comment by wooyn730** [comment]
@yanggang3 
확인했습니다!!
이번에 준 방식 넘넘넘넘 좋아요 ^_^b 완벽

질문이랑 요청!
1. 먼지유령 스프라이트는 안 바뀐거 맞죠?
2. 스프라이트 다르면 파일명 바꿔주세요!! (뒤에 숫자 01, 02 이렇게 붙인다던가.. 안헷갈리게)
3. ㅁ맨 오른쪽은 눈 감은 라플리같은데 얘는 몬가요?
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/674c053b-0f5d-4886-baac-575fafc2d0aa)

**Comment by yanggang3** [comment]
@wooyn730 
 1.넵! 먼지유령은 따로 바뀐 점 앖습니다!
2. 아 어제 올린 리소스파일이랑 오늘 수정본 파일이름이 헷갈리다고 하신거 맞나요? 
3. 눈 뜬 움직임도 넣으면 재미있을 것 같아 추가로 만들어본건데 어색하면 안 넣으셔도 됩니다.!

**Comment by wooyn730** [comment]
1. 넵!
2. 네 맞아용
3. 이따가 적용한 거 같이 한 번 보고 이야기 합시다~

**Comment by fkdl0048** [comment]
회의 고생하셨습니다!

적용된 모습을 보고 싶었는데 감사함니다..! 피드백은 바닥 타일의 격자 무늬가 더 크면 좋을 것 같습니다. 코인의 경우에도 색이 비슷해서 다른 방식을 생각해도 좋을 것 같아요.

**Comment by fkdl0048** [comment]
오히려 바닥타일과 벽이 합쳐진 타일이 아니라 바닥 타일 1개로 밑 레이어로 깔고 벽 타일(바다타일이 없는) 만 제작한다면 리소스도 절약되고 좀 더 다양한 시도도 해볼 수 있을 것 같습니다!

**Comment by wooyn730** [comment]
ㄴ 그러네요!! 정말 좋은 의견입니다

**Comment by yanggang3** [comment]
감사합니다! 참고해서 더 수정하겠습니다!

**Comment by CreatorLDH** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/608c5a30-c26f-4e3f-8d77-4894f69a4d0f)

이렇게 붙는 거 넘 조아욤

**Comment by yanggang3** [comment]
@CreatorLDH 동호님!팩맘 중간과정 같이 얘기해보면 조을 것 같은데 혹시 이번주 중에 시간 가능하실까요?!짧게 회의해보면 좋을 것 같아서요.!

**Comment by CreatorLDH** [comment]
@yanggang3 토요일 이른 _저녁~밤,_ 일요일 종일 가능합니다!__

**Comment by yanggang3** [comment]
@CreatorLDH 넵 그럼 일요일 오후 8시..에 뵈어요!

**Comment by fkdl0048** [comment]
주도적으로 회의가 진행되는 모습이라니... 눈물 납니다.. 더 열심히 할께요 ㅠ
