### ISSUE TITLE
온라인 비정기 기획/아트/플밍 회의, 2023-12-10 [20:00]

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/GameOver#202]
팩맘 시스템 중간과정 같이 검토해보기
앞으로의 마무리 방향도 같이 의논하기
캐릭터/아이템
https://drive.google.com/drive/folders/1QglEZMH7AWyeT7I1ubiMkbrvY0_Y-RJA?usp=drive_link

타일맵
https://drive.google.com/drive/folders/1DIs89qR0Iyzvu9nF5_cY-ERPjLQPLOSj?usp=drive_link

***

### **회의록**

**1. 플레이 시연 (팩맘)**
- 팩맘 플레이, 청소기 모드, 라플리 디버프 모션 등 확인

**2. 팩맘 타일에 대한 이야기**
- 지금도 괜찮다.
- 디밸롭은 내년 디밸롭 기간에 진행해도 됩니다.
- 타 우선순위 작업에 맞게 진행하시는 게 현명할 듯.

**3. 청소 모드의 종료 타이밍을 알려주는 연출**
- 빨간색 불빛을 활용하는 것보다는, 청소 모드의 팩맘이 들고 있는 청소기가 깜빡거리는 것으로 수정

**4. 디버프 스프라이트 이야기**
- 파란색 + 빨간색 중간 혼합이 아닌 다른 색을 사용하거나 파란색만을 사용하기. 
- 다른 색으로 새로 준비해서 진행하기

**5. 타일 맵 크기에 대한 이야기**
- 타일 간격이 더 커졌으면 좋겠다는 의견
- 정기 회의 때 다른 팀원분 의견을 더 받기

**6. 벽과 땅의 타일 색 이야기**
- 벽의 색과 팩맘의 입 라플리의 머리의 색이 비슷해서 수정하는 건 어떤가라는 의견
- 코인과 바닥 타일 색의 비슷하다는 의견
- 세화님이 색이 바뀐 버전을 정기회의 전까지 가져오겠다고 하심.

**7. 라플리 모션**
- 라플리 움직이는 모션 좋음.
- 디버프 상태 시 눈 돌아가는 모션, 좋음. 작아서 잘 보일까가 의문.

**8. 팩맘 청소 모드**
- 청소 모드면, 주변 코인을 추가로 획득하는 것 강조.
- 주변 범위 흡수 애니메이션 보다는, 먼저 충돌 범위를 크게 해서 먹게끔 구현

**9. 팩맘 난이도 조정**
- QA 작업 진행 후 더 의견 드리기
- 이동 속도 차이로 난이도 조절

**10. 레이어 분리**
- 벽이랑 바닥을 따로 제공 (스프라이트 용량 절약)

**11. 폰트** 
- 저번에 우연님이 정해준 폰트 (픽셀 느낌 폰트)

**12. 추가 아트 요청**
- 라플리가 처음 팩맘에 접속했을 때 생기는 자잘한 연출

**Comment by wooyn730** [comment]
날짜 지정해주세여~~
다른 건 설정 좋아요 ^_^b

**Comment by wooyn730** [comment]
## [우연 안건]

- #196

1. 리소스 적용한 거 받고 피드백 받기
2. 저번 비정기회의 코멘트에 정안님이 말하신 벽/타일 분리 방식 어떤지
3. 양쪽 통로 막는 걸로 픽스해도 될 지
   ![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/bb7dbe56-5307-4ef0-8b0e-9438d6af0582)
4. 이 부분 구현 이야기 (그냥 청소기 자체가 깜빡 거리는 것도 괜찮을 것 같음)
   ![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0af580dd-7b89-4c52-9baf-d915a0dd3e20) ([참고](https://drive.google.com/file/d/1jBxmw1QGBBYZ0xH0HVgafxEoQop8KwKU/view))
5. 저번 회의록에 남겨둔 의견 받고 싶은 것들 이야기
   - 격자무늬(바닥)의 크기, 벽의 색
   - 라플리 눈 뜨고 감는 거, 살짝 점프하는 것
   - 먼지유령 빨강디버프, 파랑디버프 어떻게 적용할건지
   - 청소기든 팩맘 스프라이트가 코인을 빨아들이는 느낌이 없다는 의견
   - 코인의 형태 (바닥과 유사한 노랑색이라)
   - 가운데 방 문 타일

**Comment by wooyn730** [comment]
## [리소스]

1. 그냥 보면 괜찮은데 적용하려니까 이상하게 보임 머지...?
![스크린샷 2023-12-10 173341](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f007bb48-ac68-48ea-8674-fc649656deab)

2. 가운데 방 문 타일은 아직 미정인지??

**Comment by yanggang3** [comment]
@wooyn730 2. 이번 회의 때 얘기하고 제작할 예정입니다!
3. 둘 다 적용해보고 더 나은걸로 하기 위해.. 나중에는 하나만 쓰일 예정입니다
4. 헉 원래 첫번째가 맞는건데 잘못 제작했네요.. 다시 드릴게요!

**Comment by CreatorLDH** [comment]
안건 정리해주셔서 감사합니다:D

**Comment by wooyn730** [comment]
스크린샷 남김니다
수고하셨습니다~

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/cfaaafae-bd53-48f9-ab0f-714e4e87b168)
