### ISSUE TITLE
[Ch1 SubA] 팩맘 문서 가독성 강화 작업

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#209]
- #159 
- #202

위 내용 및 추가되거나 수정된 부분을 보완한다.
그리고 가독성을 강화한다.

[변경사항](https://drive.google.com/file/d/1sqWvf8AqyZ5hjDqxPf3tvnfir0tm_5v4/view?usp=drive_link)
- 초반 페이지별 분량 및 이미지
- 청소기 아이템 내용 수정 (회의 내용 근간)
- 오탈자 작업
- #213 에서 팩맘 내 대화 텍스트 전달 예정
- 팩맘 청소 모드 우선순위 변경 (기존 먼지유령을 먼저 잡으려고 하고, 라플리를 잡으려 함 => 동일하게 거리가 가까우면)
- 기타 자잘한 거 손봄.

**Comment by yanggang3** [comment]
@CreatorLDH 
더 구체적으로 보완 작업해주셔서 감사합니다! 
라플리가 유령이랑 만날때 어떻게 유머를 나타내야할 지 좀 더 생각해보겠습니다..!ㅎㅎ
궁금한 점
1. 먼지유령 말풍선은 텍스트 길이 따라 달라진다고 하셨는데, 제일 짧은 대사가 "퇴근이다",나 "으아아악"인 4글자이고
제일 긴 대사는 "돈을 많이 모으면 본사에서 특별 보너스도 준다고 하니까 파이팅이야 자네!"
맞을까요?
2. 라플리 말풍선(대사는 없지만 ...?나 ...!같은 느낌표현)과 먼지유령 말풍선은 다르게 제작할 예정인데 괜찮을지!
3. UI 중에 라플리 코인 개수 ui랑 팩맘 코인 개수 ui랑 통일시켜도 될지입니다!

**Comment by CreatorLDH** [comment]
@yanggang3 @wooyn730 

아마 우연님이 하시는 텍스트 구현 방식에 따라 달라질 거 같습니다.
제가 아는 방법으로는 기본 말풍선 이미지를 만들어주면, 유니티 내 입력 텍스트의 길이에 따라 알아서 말풍선 크기가 변경되는 시스템이 있습니다. 그래서 이런 방법을 활용하는 게  팩맘에서는 하나씩 만들지 않아도 되니 괜찮지 않을까 생각이 들었습니다. 

[요런 방식으로 알고 있습니다.](https://velog.io/@minjujuu/Unity-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EA%B8%B8%EC%9D%B4%EC%97%90-%EB%94%B0%EB%9D%BC-%EB%A7%90%ED%92%8D%EC%84%A0-%EB%8A%98%EC%96%B4%EB%82%98%EB%8F%84%EB%A1%9D-%ED%95%98%EA%B8%B0)

하지만, 우연님의 구현방법에 따라 세화님이 우연님께 드려야하는 방식의 변화가 있을 거 같습니다.
일단 초기에는 **텍스트가 없는 말풍선**을 요구해 활용도를 높이려고 했습니다.

1. 대화 텍스트는 달라질 예정입니다. 금주 작업으로 확정시켜서 다시 드릴 예정입니다.  Yarn 파일 형식으로 우연님께 드리려고 했는데, 세화님이 대사 텍스트를 넣어 만들 가능성 또한 있기에 추가로 txt 파일로도 첨부해 놓겠습니다. 
2. 네 좋습니다. 라플리의 대사 말풍선을 만들지 않으셔도 되고,
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/e245d5d2-b8e5-4175-b135-2aeafde58337)
이런 형식처럼 느낌표 이미지로만 처리해도 좋습니다. 편하신 방법으로 나아가주시면 좋을 거 같습니다.
3. 해당 UI는 게임 내 텍스트 및 동전 아이콘으로 이루어지므로 동전 이미지만 따로 만드셔도 될 거 같습니다. 여기서 세화님이  텍스트 자체를 써주셔서 UI를 만들어주신다면 통일시켜도 좋습니다.

우연님
- 말풍선 시스템 구현 방식에 대한 질문 및 구현 시 필요한 리소스에 대한 의견있으시면 받습니다.

**Comment by wooyn730** [comment]
네 동호님이 걸어주신 하이퍼링크 방식으로 구현할 예정입니다

먼지유령 말풍선은 빈 것 하나만 주셔도 되겠습니다

추후 현지화(번역) 고려하여
텍스트를 직접 채우시는 건 지양해주시는 게 좋습니다~~

---

구현 관련 질문은 추후 생기면 코멘트 남기겠습니다

**Comment by CreatorLDH** [comment]
그럼 Yarn 파일로 주말내에 보내드리겠습니다:D
