### ISSUE TITLE
[ALL] 전체 리소스 통합 문서 제작

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#210]
- #195 
- #166 

위 리소스 문서들을 하나로 통합하고, 가독성을 높이고, 시트별 분리를 한다.
시간이 남으면 함수 사용 예정. (쓸 일이 없던...?)

***

[통합본 ](https://docs.google.com/spreadsheets/d/1qADbMgGr5qWYUAd0y9Pf-xomFG3YAUpK/edit?usp=drive_link&ouid=104039457643560044631&rtpof=true&sd=true)

1. 사운드 내 효과음은 추후 재활용 여지가 매우 큽니다!
2. 기존 리소스 문서들을 다 합쳤습니다! 여기만 보면 됩니다!
3. 레퍼런스가 부족한 부분이 많습니다! 조금씩 채워서 보강 예정입니다!

특히 사운드는
장르를 패러디하는 부분이 많으므로, 해당 장르 격 게임 하나를 정하고
해당 게임에서 사용되는 효과음들을 레퍼런스로 한 번에 드리겠습니다.

지금 생각중인 것은
- SLG 장르의 에오탄, 라오킹 등
- 2D 도트 탑뷰에 포켓몬스터 DP 
- 항상 레퍼인 언더테일

입니닷!

로그라이크 기획 완료되면 추가 수정 들어갈게요!

**Comment by wooyn730** [comment]
수고하셨습니다! 통합본이 있으니까 좋네요

나중에 자료가 방대해질 걸 생각하면 아트 / 사운드는 분리해도 좋을 것 같기도 하고,
구현 여부나 구현 링크 같은 건 작업자가 직접 편집하도록 해도 좋을 것 같습니다~~

++
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d19c4a62-197f-4466-af2f-788c96b1c1ff)
그리고 이 링크를 누르면 아무것도 안뜨네요..

**Comment by CreatorLDH** [comment]
앗 저는 넘어가는데.. 무슨 문제지 [원본](https://i.namu.wiki/i/_PQKTNZ29AG348b8Kl4P79ciDFdKgXEYK5vLJT-s80Lwqh3iJB72BuUk30348cUFJFsGDw2PFXVSyfNYEFuNUw.mp4)

해당 레퍼런스는 저번 기획/아트/플밍 회의 이후에 요청했던 사항에 따른 레퍼런스여서
현재 파티클로 만들어주신 거에 적합한 레퍼런스는 아닙니다:D

다른 이슈 코멘트로 남긴 것처럼 입장 연출 시 라플리 이미지에 '불투명도' 조정을 해서 나아가는 게 어떨지 의견드립니다

**Comment by wooyn730** [comment]
저 링크 눌러도 안보이네요...😂

불투명도 적용 해보겠습니다.
따봉만 눌렀는데 코멘트도 남길 걸 그랬네요!!

의견을 여쭤보시는 거라면 투명도 변화가 2D 픽셀 느낌에 맞는지는 모르겠습니다.
(팩맘 죽으면 코인이 라플리에게로 이동하는 부분도 마찬가지...)

하지만 라플리는 팩맘에 속한 친구가 아니니 괜찮을 것 같기도 합니다...
적용해봐야 알 것 같아요!

**Comment by CreatorLDH** [comment]
아 해당 링크가 위키 쪽으로 넘어가는 이미지 링크여서 그런건가 싶습니다. 
(참고안하셔도 되는 레퍼이니 넘어가셔도 될 거 같습니다) ㅜㅜㅜㅜㅜ

_**닥터스트레인지의 포탈**처럼,
흰색으로 이루어진 작은 포탈에서 뿅 등장하는 느낌이면 어떨까요?_
(무시해도 됩니다)

물론 지금은 파티클 느낌으로 해주셨지만... ㅎ

아니면 파티클 효과와 함께 **순간이동**처럼 등장하는 것도 좋을 거 같습니다. 
2D 픽셀 느낌을 강조하려면, 우연님말처럼 '투명도 변화'를 사용하는 것보다 다른 방법을 활용하는 것이 나을 거 같긴 합니다.
아마 구현 난이도가 순간이동처럼 파티클과 함께 등장하는 것이 더욱 용이해보이므로, **일단 순간이동으로 만들어 보고 한 번 보는 것도 좋을 거 같습니다!**

***

라플리에게 코인이 이동하며 흡수되는 부분은 빠르게 게임을 끝내는 조건(동전이 필드에 남아있지 않는 경우)을 강제로 달성시키기 위해 처음 고안했습니다! 위 과정에서 자석처럼 필드에 남아있던 모든 코인이 한 번에 라플리에게 흡수되면, 진행 속도면에서도 좋을 거 같고, 보여지는 화면에서 멋있을 거(?) 같다는 생각이었습니다!

현재 남은 코인이 하나씩 사라지는 걸로 임의 제작해주셨는데,
어찌보면 위 방법이 고전 게임에서 주로 사용하던 방식이라 기존 팩맘의 결과 비슷할 거 같습니다.
(그래서 처음 보았을 때, 오오 했어요!)
(흡수되는 연출은 고전에서 조금 지난, 컬러가 나온 시절부터 주로 보였던 연출인 거 같네요)

하지만, 좀 특별한 존재(그래서 UI 위치도 다르게 설정했음)이므로 괜찮지 않을까 싶습니다!

### **매번 고생많으십니다! 감사합니다!**

**Comment by wooyn730** [comment]
오 저는 포탈 좋은 아이디어 같은데요?!!!

순간이동/투명도 변화 두가지 버전 다 한번 작업해보겠습니다.

흡수하는 부분도 조만간 작업 시작해볼게요~~

++
제가 팩맘만 계속 작업하다 보니 이질적인 부분이 신경쓰였네요
특별한 존재니까 그게 맞는건데 말이죠 ㅋㅋ
앞으로의 서브시스템들도 라플리만의 특별한 특징을 잘 살리면 좋겠네요!

**Comment by royalbluesm** [comment]
문서 작성 수고하셨습니다~! 그럼 앞으로 리소스 제작 시 직접 작업 완료 체크하면 되는건가요?
