### ISSUE TITLE
[Char]챕터 1 주요 NPC 이동 스프라이트 애니메이션 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#211]
**상세**
플레이어 및 CH1 NPC 4명(파머, 달러, R2-Mon, 마마고)의 걷기 애니메이션 스프라이트를 제작합니다.

**파일**
[캐릭터 스프라이트](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=sharing)

**비고**
NPCCharacterSprite_이름_Common은 정지된 디폴트 자세, Walk이 걷기 파일입니다. 번호가 4까지 있을 경우 4프레임이고, 번호가 없는 경우는 움직임과 정지만 있는 2프레임 애니메이션입니다. 혹시 이해안되는 부분 있으면 설명해드리겠습니다!

**Comment by CreatorLDH** [comment]
너무 고생하셨습니다! 나중에 정안님이 스프라이트 연결지어서 보여주신다면 더욱 잘 느낄(?) 거 같아요!
그럼에도 스프라이트 하나씩 다 보았는데, 좋습니다!!! 수고하셨어요!

질문 하나 드리자면,
R2-Mon 우리의 에어프라이기는 기본 자세와 걷는 자세 때 무엇이 변하는 지!?!!? 궁금합니다.
(제가 못 느끼는 거일수도 있고... 주륵)

**Comment by wooyn730** [comment]
![스크린샷 2023-12-17 013935](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b98b9cf8-1bf8-4a42-8058-83d8de6fac2a)
팩맘처럼 이렇게 같은 아트끼리 한 장에 배치해둔 아틀라스 이미지로 주시면 좋을 것 같습니다!
(정안님이 말씀하셨는지 모르겠지만 보시면 99% 확률로 요청하실듯.. ㅎㅎ)

<br>

그리고 파일명 맨 앞의 NPCCharacterSprite는 없어도 괜찮을 것 같습니다!
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/ebd1b83e-6383-4884-9357-aa9aa6a7d87f)
파일명이 길면 미리보기로 다 안보여서 적용할 때 헷갈릴 거 같아요
(라플리 파일명도 마찬가지)

<br>

스프라이트는 귀엽고 좋아요 
좋아서 딱히 피드백할 말이 없네요 ㅎ_ㅎ
빨리 적용한 모습이 보고싶어요

**Comment by royalbluesm** [comment]
@CreatorLDH 우리 에프는 바퀴로 굴러간다는 느낌이라 몸체 애니메이션이 없을 것 같아서, 땀수건이 흔들리는 모션 쪼끔 넣었습니다 ㅎㅎ
@wooyn730 아틀라스 이미지에 대해 좀 알아봤습니다! 나루호도... 파일 수정해서 올렸습니다 ^-^ 저도 빨리 적용한 모습 보고싶어요!!!

**Comment by CreatorLDH** [comment]
땀수건 흔들리는 거였군요! 인게임 적용하고 나서, 혹여나 디테일 수정 사항이 발생되면 다시 말씀드릴게요!
넘 고생많으셨습니다

**Comment by yanggang3** [comment]
헉 캐릭터들 움직임마다 디테일이 조금씩 달라지는 걸 잘 표현하신것 같아요.. 마마고 너무 귀여워요..!
잘 보고 갑니다!!

**Comment by royalbluesm** [comment]
@fkdl0048 문제가 하나 있는데... 라플리도 그렇고 다른 친구들도 그렇고 가로 비율이 일정하지가 않습니다. 그래서 조정한다 해도 4x5 이런식으로 딱딱 나눌순 없을것 같은데, 이 경우 사이즈별로 아틀라스 이미지를 따로 만들어야 할까요?

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/feb3228e-3492-4ec0-ba5b-cb388a1ef8f5)

이 빨간선을 기준으로

**Comment by fkdl0048** [comment]
아아 위에 보니까 안되나보네엽

**Comment by fkdl0048** [comment]
각 각 스프라이트를 정해진 픽셀에서 중앙으로 위치하게 통일하면 되긴 할 것 같은데 어렵나요?

**Comment by royalbluesm** [comment]
음... 차라리 도트를 수정해서 가로길이를 맞추거나 하는게 좋을것같네요 1픽셀씩 차이나는거라 그럼 수정된 버전으로 드리겠습니다 좀 걸릴수도 있을것같네요 ㅜㅜ!!

**Comment by fkdl0048** [comment]
네네 알겠습니다. 1챕터는 계속 아틀라스 방식을 사용하는거라 모든 스프라이트 제작하실 때 움직임 생각하고 픽셀을 통일하면 좋을 것 같네요!

**Comment by royalbluesm** [comment]
https://drive.google.com/file/d/1lcH2ynH-ru_oWA87mPDfFIJ6xJCrtYu2/view?usp=drive_link
혹시 이 파일로 적용한번 해보고 어색하지 않은지 봐주시겠어요? 동일한 크기의 4x5로 나누고 좌측하단으로 정렬시켜놨는데 이러면 잘 적용될 것 같기도 하네요

**Comment by fkdl0048** [comment]
5분만 주시면 바로 보내드리겠읍니다

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/cd32807d-3583-424d-ba69-15d025499df1)

![CutSene gif](https://github.com/GG-Studio-990001/GameOver/assets/84510455/f39cc099-f3fa-43c5-9b47-e4eb415120fe)

**Comment by fkdl0048** [comment]
잘 되네엽

**Comment by royalbluesm** [comment]
(2,5)번 라플리가 쪼끔 어긋나있는것만 수정하면 되겠네요 그럼 이부분 반영해서 최종본 올리도록 하겠습니다~

**Comment by royalbluesm** [comment]
[최종본](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=sharing)
이걸로 적용해주시면 될것같습니다!

**Comment by fkdl0048** [comment]
++ 가능하면 본문 수정 후 본문 수정되었다고 코멘트만 달아주시면 더 좋습니다!

**Comment by fkdl0048** [comment]
- #228 

정기회의 관련 수정요청 사항입니다. (*디스코드로 자세히 말씀드리겠습니다.*)

- 라플리 움직임 애니메이션 발 어색
- 그림자 추가에 관한 아이디어
- NPC 진도 사이즈 업
- 배경, NPC 도트 사이즈 통일
- Extra A, Dollor 스프라이트 시트 수정 요청
