### ISSUE TITLE
[Ch1] 대화 리소스 제작

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#213]
- #194

정안님과 따로 질문거리에 대한 답변을 받은 후, 위 이슈를 참고하여

Main ~ SubB까지의 대화 리소스를 한 번 만들어 보는 것에 도전(?) 한다.

[추가추가추가하고 있습니다:D](https://drive.google.com/drive/folders/1cttUDNdzOOwWTIMZE61NSJaQWZr4bhEc?usp=drive_link)

***

이미 플밍분들이 먼저 열심히 공부했겠지만,
[함수 제작 관련](https://docs.yarnspinner.dev/using-yarnspinner-with-unity/creating-commands-functions)
요런 거 보면서 유니티 컴포넌트와 연계된 함수를 어찌 짜서 드릴까라는 생각이 들었지만,
오히려 방해가 될 수 있을 거 같다는 생각에

저번에 말씀드린 것처럼 필요한 것들을 다 주석으로 설명 달아 놓고 있습니다.

**Comment by CreatorLDH** [comment]
@wooyn730 

[대화 데이터 폴더](https://drive.google.com/drive/folders/1aimpBipCY2UK6BVP23tefyojaS9it-iK?usp=drive_link)

일단 팩맘 관련 대화 리소스들을 모아서 썼는데,
이렇게 하면 좋을 거 같다라는 의견 주시면 감사할 거 같습니다.

지금은 랜덤 재생될 것들을 하나의 title로 묶어서 어찌 구현했습니다.
(돌려보니 랜덤으로 나오게끔은 성공했는데, 하하)

**Comment by wooyn730** [comment]
확인했습니다!

추후 적용해보면서 필요하면 코멘트 남기겠습니다
