### ISSUE TITLE
온라인 정기 회의, 2023-12-18 [22:00]

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#218]
# 온라인 정기 회의, 2023-12-11 [22:00] 

- 진행상황 공유
- 다음 일정 공유, 마일스톤 설정

***

### 회의록

정안 이슈로 인해, @CreatorLDH 제가 집도합니다. ^^7

**진행상황 공유**
- 기획) 리소스 문서, 아트나 사운드분들 작업 후 작업 완료 체크 권장(강제X) 
- 기획) 여러 보완 작업 및 리소스 문서 작성에 대한 내용 전달
- 기획) 대화 리소스 관련 내용 전달

- 플밍) 팩맘 구현 상황 전달 (게임 상황, UI)
추후 팩맘 빌드 파일 목요일쯤에 올려주기로 함
팩맘 현재 상태 난이도 easy해서 추후 밸런스 조정 필요함

- 아트) (SubA-팩맘) 기존 수정 작업 및 UI 제작 (인게임 예시 이미지 보여줌)
UI 텍스트 크기 줄이기 요청
- 아트) 캐릭터 모션 제작 
실제 움직이는 거 보고나서 추가 피드백
플밍에서 잘 사용할 수 있도록, 파일(그림들 모여있게)에 대한 피드백

- 사운드) 플로야드 메인 BGM 제작 

**다음일정**
- 플밍) 팩맘 사운드, 인트로 및 아웃트로 연출 시작, 기타 프로그래밍 구현 작업
- 기획) 대화리소스 추가 제작, 리소스 문서 보완, 로그라이크 기획 재진행
- 아트) 기존 리소스 보완 작업(방문, 눈돌아가는 거, 포탈) +@
- 아트) 기타 NPC 제작 (회의끝나고 기획이 노티드)
- 사운드) 플로야드 배경음_1 수정, 플로야드 배경음_2 (시간남으면 + 몸 괜찮아지면)

**Comment by wooyn730** [comment]
- 다음 회의는 1월 1일!
- 1월 초 대면 만남 빠른 시일 내로 일정 정하기

**Comment by fkdl0048** [comment]
죄송합니다.. 시험 3개를 감당하지 못하고 눈 만 잠깐 감는다고 했던 게... 일어나보니 11시네요.. 관련 사항은 꼭 다시 정리하겠습니다.

*정말 죄송합니다..*
