### ISSUE TITLE
[Char]CH1 기타 NPC 캐릭터 스프라이트 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#220]
**상세**
기타 NPC의 도트 스프라이트를 제작합니다.

**파일**
[캐릭터 스프라이트 폴더](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=sharing)에 넣어뒀습니다. 일단 비글은 2프레임, 엑스트라 캐릭터는 4프레임으로 좌우이동만 제작했습니다

**Comment by royalbluesm** [comment]
엑스트라 NPC의 걷기 모션은 4방향 다 필요한건가요? (걷는 모션 하나만 제작하여 좌우반전시켜 사용해도 괜찮은지...)

**Comment by fkdl0048** [comment]
필요한 NPC는 @CreatorLDH 동호님이 답변해듀시면 될 것 같고 모션은 반전시켜서 사용하는거 좋습니다! 2가지만 제작해도 될 것 같아요

**Comment by CreatorLDH** [comment]
@royalbluesm 

고생하셨습니다
- 엑스트라 A,B만 걷는 모션이 필요하기에 잘 해주신 거 같습니다. 정안님 말씀처럼 나아가시면 좋을 거 같습니다.

피드백
- 진도(하얀 개)는 몸짓이 좀 있으면 합니다. 물론 도트 그래픽 상의 한계일 수도 있습니다. 인게임 상에 적용시킬 때 일반 캐릭터보다 scale을 크게 하면 되려나요?
(인게임상 크기 비교 진도 > 라플리 = 비글)
=> 이 부분도 추후 정리를 해보겠습니다.
- 비글 프레임 적게 해주신 점 잘해주셨습니다. 비글은 연결되는 모션이 없고 추가 스프라이트(동작 변화, 순간이동처럼 연출)를 활용한 움직임 변화만 있습니다.  (정적으로 움직임)
- 우리 멍멍이들 무기 넘 잘해주셨습니다~!

**Comment by royalbluesm** [comment]
@CreatorLDH 크기 수정한 진도, 비글 같은 폴더에 올려뒀습니다!
