### ISSUE TITLE
[Ch1 SubA][Pacmom] 사운드 적용

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#222]
정안님이 만들어두신 SoundSystem 사용

사운드 최적화 방식 같이 이야기 해보면 좋을 듯

[참고](https://blog.naver.com/PostView.naver?blogId=ckdduq2507&logNo=222113891105)

++
추후 오프닝&엔딩 연출과 보완 관련 이슈도 생성 예정

++
사운드 적용 플레이 영상 [링크](https://drive.google.com/file/d/1gBL_yv-0u7-wlvN8hPJOAwL3gqAe-JLp/view?usp=drive_link)

**Comment by wooyn730** [comment]
@2ehdgh17 

[문서](https://docs.google.com/spreadsheets/d/1qADbMgGr5qWYUAd0y9Pf-xomFG3YAUpK/edit#gid=11350587)

1) 문서에 임시로 개발 적용 칸 추가해뒀습니다
(저 안 헷갈리려고 +플레이할 때 안들리는건지 아직 안넣은건지 알 수 있게 하려고)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/7fce392c-fb9f-4f54-a441-c8cadd632792)

2) 12번 구현 링크는 Loop 말고 1번만 되는 걸로 바꿔주세요 (현재 제목 Pacmom_SFX_12_2)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/c59d0af7-f9da-42b9-ab73-65898484ef0f)

3) 아래 말고 위에 두 개 처럼 제목으로 걸어놓는 건 어떻게 하는 건가요?
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0f97062f-19ee-4cfa-8a4b-64061e620ea0)

4) 7잡힌후회귀는 아직 구현은 안했지만 아예 loop된 긴 버전으로 주시면 가운데 방으로 돌아왔을 때 음악 정지하는 방식으로 사용하는 게 나을 것 같습니다.

5) 5먼지유령이동음은 어떨 때 넣나요? 움직이는 내내 두마리 다 loop로 들리나요..?
(시끄러울 거 같은 너낌)

---

아래는 빌드 플레이 시 체크해주시면 좋겠는거 쪼금

1) 팩맘이 먼지유령에게 잡히면 11기절음, 9코인떨구기가 동시에 들릴텐데 잘 들리는지
2) 소리 밸런스 (라플리 코인 소리가 크고, 청소기 소리가 작은 듯)

**Comment by CreatorLDH** [comment]
확인은 어제 모바일로 확인했는데, PC나 노트북 작업 시간이 없어서 코멘트는 지금 남깁니다!

1. 개발적용 확인했습니다. 감사합니다.
2. **변경했습니다**
3. 구드 엑셀에 링크를 붙혀넣기한 순간 자동으로 뜨더라구요
<img width="293" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/f6468d2f-16d1-418d-903d-a8a84ee2599d">
아래꺼들은 과거 설정해논 것이기에, 파란 링크인 거 같습니다. **바꿔놓았습니다.**

4. 좋습니다. @Songkihwa 노티드합니다.
<img width="1157" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/3772b048-a886-44c4-a6a7-30367dd3ef10">

5. 일단 그렇게 적용하고, 상대적으로 유령들의 이동 소리를 작게 설정하는 것으로 생각하고 있습니다. 원작처럼 다른 효과음 (ex. 코인 먹는 효과음, 팩맨 효과음 등)이 없을 상태에서는 유령들의 이동소리만이 주로 들리므로 비슷하게 가져가고자 했습니다.
- 추후 테스트하며 조절 피드백 넣겠습니다.

***

[해당 빌드본](https://drive.google.com/file/d/1ip9RhmCJxpuhYgkal2M2nKuQ5wlngdZA/view?usp=drive_link) 에서는 소리가 들리지 않습니다.

제가 못 찾는 것일 수 있으니, 다시 노티드 해주시면 내일중으로 해당 상황 피드백 드리겠습니다.
감사합니다:D

**Comment by wooyn730** [comment]
빌드 아직 안 올린 거 맞습니다

사실 저 날 올리려고 했는데
빌드했더니 임시 메인씬에서 다른씬으로 안넘어가길래
어차피 휴가니까 휴가 끝나면 정안님한테 물어보고 다시 빌드하려고 했었어요..

아마 1월 1일에 올라갈 예정...^_^

**Comment by Songkihwa** [comment]
@wooyn730 SFX 7번 Loop 버전으로 바꿔서 올렸습니당 10초 정도로 올렸는데 더 길어야되거나 짧아야한다면 언제든지 알려주세요!
