### ISSUE TITLE
[Ch1] 대화 리소스 추가 제작

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#225]
- #213 

추가로 대화 리소스를 만든다!!

***

- [x] 기존 리소스 중 intro 하나의 파일 title 수정
- [x] NPC 리소스 추가 8명 (파머, R2-Mon, 비글, 진도, NPC1,2,3, 마마고)
- [x] 연출 리소스 모두 제작

이제 아이템과 같은 상호작용 및 나레이션 대사만 필요한 거 같습니다.. 메이비.
그리고 간단한 연출에 대한 것 포함이요.

**Comment by fkdl0048** [comment]
조금 살펴봤는데 실제 적용된 모습이 기대가 되네요.. 적용하면서 생긴 이슈는 다음 주(쉬는 날 빼고) 마무리 되는 대로 보내드리도록 하겠습니다!

작업 고생하셨습니다~!
