### ISSUE TITLE
코드 리뷰 조사

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#23]
# 코드 리뷰

## 정의

코드 리뷰란 다른 사람이 작성한 코드를 검토하며 궁금한 부분에 대해 질문을 하거나, 버그가 있는 부분을 알려주거나, 더 효율적으로 개선할 수 있는 부분을 찾아 피드백을 주며 서로의 코드를 개선해나가는 과정이다.
잘잘못을 따지는 것이 아닌 서로의 코드를 더 좋게 만들 수 있는지 보는 과정이다.

## 사용 이유

- 버그와 장애의 사전 예방이 일부 가능하다
- 개발 내 정해진 컨벤션 규칙을 유지할 수 있다
- 코드의 품질을 향상할 수 있다
    - 코드 리뷰를 하게 되면 스스로 코드를 작성할 때 ‘좋은 코드’에 대해 한 번 더 생각하는 계기가 된다
- 배움과 지식을 공유할 수 있다
    - 개발에도 경험을 통해야만 알 수 있는 지식이 있으며, 코드 리뷰는 그런 지식들을 배울 수 있는 좋은 매개체이다
- 상호간의 책임감을 높일 수 있다

## 사용 방법

코드 리뷰에는 여러가지 Tool들이 있지만, 이번 프로젝트에서 사용할 예정인 Github로 코드 리뷰를 진행하는 방법에 대해 알아보았다.

### 코드 리뷰 요청
1. 브랜치를 파서 작업 후 커밋&푸쉬
2. Pull Requst(PR) 만들기 
    - 리뷰를 받기 위해 내가 한 작업에 대해 적기
    - 제목: 작업 요약, 내용: 작업한 내용과 중점적으로 확인 받았으면 하는 부분
3. Reviewers에서 리뷰 요청할 사람 선택
4. Create Pull Request

### 코드 리뷰 진행
1. 코드 리뷰를 요청받았다면 PR 내의 Flies changed 탭에 들어가 리뷰하기
2. 코드 줄 맨 앞 공간을 클릭 또는 드래그하여 해당 줄에 대한 의견 나누기
    - Add single comment ⇒ 바로 의견 남겨짐
    - Start a review ⇒ 작성자에게 보이지 않는 임시 등록 상태가 되고 나중에 리뷰를 완료하면 작성한 의견들이 한번에 등록됨
3. Finish your review 버튼을 통해 리뷰 끝마치기
    - 주로 리뷰를 끝냈다는 코멘트, 응원과 격려의 말, 코드에 대한 추가적인 이야기를 덧붙임
4. Submit review
    - Commnet: 일반적인 피드백
    - Approve: 이제 합쳐도 괜찮을 것 같음
    - Request changes: 확실하게 코드를 수정하고 넘어가야 함

### 이후
- 코드 리뷰를 받으면 PR 페이지에 리뷰들이 남겨지게 되고, 대화를 하면서 개선 방향을 찾아 나가거나 바로 의견을 수렴하여 코드를 수정한다
- 반영된 부분은 Resolve conversation을 클릭하여 처리 완료됨을 표시한다
- 리뷰 후 코드가 더 수정되었다면 Re-quest review도 가능하다
- 리뷰어가 PR을 승인하고 병합 가능한 시점이 온다면 Squash나 Rebase 등의 방식으로 브랜치 병합한다
    - *Squash: 통합커밋 딱 하나를 master 브랜치 뒤에 붙여주는 방식*
    - *Rebase: 서브브랜치의 여러 커밋들을 뒤에 붙여주는 방식*

### 작성자
- 작업을 잘게 나누고 코드 리뷰를 한다
    - LOC 400줄 이하 등 PR 사이즈를 최대한 작게 한다
- 나 자신과 나의 코드를 분리하고 이성적으로 받아들인다
- 리뷰 요청시 궁금한 부분을 모두 물어본다

### 리뷰어
- 꼼꼼하게 확인하고 명확하게 피드백한다
- 개선이 필요한 이유를 충분히 설명하기
- 좋은 의도를 전제로 친절하게 말한다
- 비난하지 않는다
- 일부가 아닌 전체를 보고 일관성도 체크한다
- 개발자의 성향을 리뷰하는 것을 지양하기

**(프로젝트 특성에 따라 선택 가능한 규칙)**
- 답을 알려주기 보다는 스스로 고민하고 개선 방법을 선택하도록 유도하기
- 리뷰할 부분이 없는데 흔적을 위해 리뷰하는 것보다는 피드백할 게 없으면 칭찬해주기

## 참고 자료

- [GitHub으로 협업하기: 클론부터 코드 리뷰까지](https://xo.dev/articles/github-collaboration-guide) 👍👍👍
- [효과적인 코드리뷰를 위한 리뷰어의 자세](https://tech.kakao.com/2022/03/17/2022-newkrew-onboarding-codereview/)
- [코딩 실력 향상을 위한 코드 리뷰? (유튜브)](https://www.youtube.com/watch?v=JTEXwh4kq0k) 👍
- [개발자와 리뷰어의 기나긴 싸움😈 (유튜브)](https://www.youtube.com/watch?v=bUY3wNjcVMk) 👍

## 생각

- 페어 프로그래밍도 궁금하다! 한 번 해보고 싶다
- 컨벤션에 관한 리뷰는 자동화 할 수 있다고 하는데 좀 더 알아봐도 좋겠다 (esLint 등)
- 리뷰 코멘트 템플릿을 도입하면 커뮤니케이션 비용이 줄어든다고 하니 정해봐도 좋겠다
    - 참고한 글: [지속가능한 코드리뷰 문화를 만드는 여정](https://blog.hwahae.co.kr/all/tech/12534)
- 최근 두 프로젝트는 데드 라인이 촉박해 코드 리뷰를 진행하기 어려웠지만, 이번엔 공부 하면서 코드 리뷰를 잘 진행해보고싶다!
- 피드백 이성적으로 받아들이기, 명확하게 피드백 하기에 특히 유의해야겠다

**Comment by fkdl0048** [comment]
템플릿을 도입하는 것도 좋은 아이디어 같아요! 저도 몰랐는데 저런 유용한 기능이..

적어주신 규칙도 코드 리뷰전에 읽어보는 시간을? 가져보는 것도 좋을 것 같습니다!
