### ISSUE TITLE
CI/CD 조사

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#24]
# CI/CD

## 정의

CI/CD(Continuous Integration/Continuous Delivery (Deployment))는 애플리케이션 개발 단계부터 배포때까지의 모든 단계를 자동화를 통해 좀 더 효율적이고 빠르게 사용자에게 빈번히 배포할 수 있는 것이다.
- CI: 개발자를 위한 자동화 프로세스인 지속적인 통합
- CD: 지속적인 서비스 제공 및 지속적인 배포

### CI
- 코드의 검증에 들어가는 시간이 줄어든다
- 개발 편의성이 증가한다
- 좋은 코드 퀄리티를 유지할 수 있다
    - 항상 테스트 코드를 통과한 코드만이 레포에 올라가기 때문

### CD

- 개발자는 배포보다는 개발에 더욱 신경쓸 수 있도록 도와준다
- 개발자가 원클릭으로 수작업 없이 빌드, 테스트, 배포까지의 자동화를 할 수 있다

## 사용 방법

Github에서는 Actions으로 CI/CD를 구축할 수 있다.

### 구성요소
1. Workflow
    - 레포에 추가할 수 있는 일련의 자동화된 커맨드 집합
    - 빌드, 테스트, 배포 등 각각의 역할에 맞는 Workflow 추가 가능
    - YAML 형태로 저장
2. Event
    - Workflow를 실행시키는 Push, Pull Request, Commit 등의 특정 행동
    - 외부에서 발생한 이벤트에 의해서도 Workflow 실행 가능
3. Job
    - 동일한 Runner에서 실행되는 여러 Step의 집합
    - 독립적으로 실행되지만, 필요에 따라 의존 관계를 설정하여 순서를 지정할 수 있음
4. Step
    - 커맨드를 실행할 수 있는 각각의 Task
    - Shell 커맨드가 될 수도 있고, 하나의 Action이 될 수도 있음
5. Action
    - Job을 만들기 위해 Step을 결합한 독립적인 커맨드
    - 재사용이 가능한 Workflow의 가장 작은 단위의 블럭
6. Runner
    - Github Actions Workflow 내에 있는 Job을 실행시키기 위한 애플리케이션

### 방법

- 게임 빌드를 자동화(+a)가 목적이기 때문에 GameCI를 이용하여 빌드 자동화한 글을 조금 읽어보았다.
    - [GitActions Unity CI/CD 개발기 - CI 개발](https://note4iffydog.tistory.com/55)
    - [Github Action - GameCI 이용하여 Unity 프로젝트 빌드하기](https://sonseungha.tistory.com/568#game-ci)

## 생각

- 아직은 용어들이 낯설어 어려워 보이지만 한 번 적용해보면 확실히 편할 것 같다
- 물론 직접 사용해보는 게 가장 이해하기 빠르겠지만 내일이 시험이라 빠른 시일 내에 하는 걸로..^^

## 사담(?)

컴퓨터 샀슴다 ^_^
<a href="https://ibb.co/kJCkNWk"><img src="https://i.ibb.co/xYTPxRP/a1.png" alt="a1" border="0"></a> <a href="https://imgbb.com/"><img src="https://i.ibb.co/vVsnc8H/a2.png" alt="a2" border="0"></a>

## 참고 자료

- [CI/CD란 무엇일까?](https://jud00.tistory.com/entry/CICD%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C) 👍
- [CI/CD 5분 개념 정리 (현업에서 쓰는 개발 프로세스) (유튜브)](https://www.youtube.com/watch?v=0Emq5FypiMM&list=WL&index=8)
- [GitHub Actions를 이용한 CI/CD 구축하기](https://ji5485.github.io/post/2021-06-06/build-ci-cd-pipeline-using-github-actions/)
- [GitHub Action으로 CI/CD 구축하기](https://velog.io/@sgwon1996/GitHub-Action%EC%9C%BC%EB%A1%9C-CICD-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0)

**Comment by fkdl0048** [comment]
CI/CD는 저희도 마찬가지로 github action으로 작성할 것 같습니다! 

일단 주어진 템플릿에서 추가되는 작업들을 같이 만들어 나가는 방식으로 진행해보죠!

컴퓨터 초고스펙.. 사이버펑크 하실려고 하시는건지,,?
