### ISSUE TITLE
[QA] QA 작업 (2024.01.01)

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#243]
지금까지 진행된 빌드본을 바탕으로 피드백이나 필요 연출 등에 대해 코멘트로 남긴다.

**Comment by CreatorLDH** [comment]
# QA 피드백

지난 번 정기회의에서 언급되었던 것들은 제외합니다. (NPC 도트 수정 등)
=> 정안님이 따로 요청했을 겁니다!

***
### **[메인]**

- NPC들의 위치나 이런 부분들은 아직 맵이 완성된 버전도 아니므로 배제합니다.
(NPC 위치, 이동 불가 및 가능 지역, 맵의 범위 등)
- 맵의 현재 플레이어 캐릭터의 이동에 따라 좌우 및 상하로 카메라가 이동되게끔 잘 만들어 주셨습니다. 화면에 보이는 맵의 범위도 나쁘지 않고 좋습니다. 추후, 맵을 새로 받아서 적용시킨다면 좌우만 되게끔 카메라의 상하 범위를 맵의 상하와 맞추어 주셨으면 합니다!  (총 4개의 맵 중 3개의 맵), 길 자체가 좌우로만 이어진 길인 점, 추후에 수정될 맵의 상하구조가 한 번에 보였으면 하기에 그렇습니다.
=> **카메라의 크기(화면에 보여지는 크기), 맵의 상하 고정**  / 4개 중 3개 맵 기준
=> 3개의 맵 (플로야드 구역 제외 / GG TOWN 입구, 플로야드 초입, 플로야드 위험구역)

- 듣다보니, 마마고 컴퍼니 BGM 점점 더  맘에 드네요. ㅋㅅㅋ

### **[팩맘]**
- 밸런스 조정 피드백은 나중으로~

이동호 대 팩맘 전적
**9 vs 4 으로 대승리**

**버그?** 
<img width="364" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/5059a859-9715-4868-a231-184fbf27688b">
- 게임 시작 시 라플리가 유령을 집 쪽으로 살짝 밀게 되면, 유령이 저 자리에서 멈춥니다. (원래는 좌측 이동을 해야하는데 못하는 거겠죠?)
=> 이렇게 되면, 유령의 위치 때문에 팩맘 또한 영향을 받기도 하네요!
=> 그렇다고 해당 버그 상황이 자주 나오지 않습니다! 잘 안나와요!

- 게임 시작 시 플레이어와 먼지 유령 2명이 함께 시작되는데, 플레이어 이동 후 각각 10초, 20초 뒤에 출발해 움직이는 것으로 변경 가능할까요? (기존 문서 내 기입하지 못해서, 죄송합니다!, 원작을 따라가고자 합니다!)
=> 그러면, 위 버그 발생 빈도도 매우 낮아질거라 생각합니다.

- 현재, 팩맘이 청소 모드일 때 라플리나 먼지 유령을 잡으면 해당 청소 모드가 끝나기 전까지 나가지 못합니다. 팩맘이 연속으로 청소기를 습득 시에는 갇혀 있는 시간이 계속 늘어나서 초반에는 고쳐야되나 생각이 들었는데 현재의 밸런스적으로 나쁘지 않아서 일단 패스합니다!

- 기타 연출이나, 먼지 유령 이동음 등 추가가 된다면 소리가 비는 순간없이 지속적인 사운드 경험이 나타날 거 같습니다! **(현재 적용된 사운드 저는 의견 없습니다.)**
- **정안님이 넣어주신, 옛날 게임기 볼록렌즈 효과 UI도 같이 적용되었으면 좋겠어요 (이미 회의 때 언급된 내용)**
=> 그러면 UI 가시성이 안 좋아지면 어떡하지라는 걱정이 듭니다.
=> 현재도 게임에 집중하면 UI가 눈에 잘 안 들어옵니다. 유저가 시간이 어느정도 남았지? 내 코인이 몇개지? 이렇게 의도를 가져야 보입니다. 
=> 그래서 수정이 필요하다? No No 아닙니다. 오히려 전 필요에 의해 UI를 보는 방식이 맘에 듭니다. (어찌보면 잊혀진 게임 중 하나이기에)

**그래서 현재 UI 위치 수정에 대한 의견 없습니다.**

***
이슈까지 만들어서 하는 QA는 게임이 좀 더 앞으로 나아간 뒤에 해야할 거 같습니다!
고생많으십니다들.. ㅜ

**Comment by wooyn730** [comment]
> 먼지유령 두 마리 플레이어 이동 후 각각 10초, 20초 뒤에 출발해 움직이는 것으로 변경

이번 주 작업에 포함시키겠습니다!

> 먼지 문 끼임 버그

이거 정안님한테도 들어서 알았어요 ^_ㅠ (저는 몰랏네요..)
고민해보고 수정하겠습니다!!
