### ISSUE TITLE
[CH1 Main]맵 리소스 제작 01

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#249]
**상세**
시작 맵(GG타운 입구, 플로야드1)의 맵 리소스를 제작합니다.

**1.4 수정**
작업일자를 1.6~1.7로 예상했으나 브릿지 MT 이슈가 있는 것을 까먹어서... 월요일까지 완성은 힘들 것 같습니다. 하는 데까지 해보겠습니다

**1.8**
아직 파일 다 뜯어서 올리지는 못했고, 과정샷 남겨놓겠습니다. 쌓인 리소스 더미들 디테일 추가하고, 명암 및 조명 효과 세부조정 후 개별 파일 업로드하겠습니다. (~1.9)

[프리뷰](https://drive.google.com/file/d/1ogkC4rAs2AHktKa5qspmZJy8ktqkmeI_/view?usp=drive_link)

**파일**
[폴더](https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=drive_link)에 투명화 파일 넣어뒀습니다. 

이전에 드렸던 프리뷰에 비해 수정된 점이 몇 가지 있습니다.
-리소스 더미들의 디테일 추가 및 퀄리티 업
-거리감과 빛 표현을 확실히 하기 위해 아래에 있는 물체 명도 변경
-이미지 깔끔하게 마감
-기존에 들어갔던 흰색 외곽선을 모든 물체에 적용하지 않고 강조되어야 하는 물체에만 적용

![변경점](https://github.com/GG-Studio-990001/GameOver/assets/144519956/6388b928-c45e-4fb7-be82-c17142ba91ad)

폴더에 프리뷰 이미지 함께 들어있습니다! 

**1.10**
잠시만요 오류 발견했습니다 수정하고 다시 클로즈 하겠습니다...

**최종**
최종 수정했습니다! 클로즈

**Comment by fkdl0048** [comment]
@royalbluesm 부탁드린 아트 리소스 수정도 작업 부탁드립니다! (issue 생성해주세요)

**Comment by CreatorLDH** [comment]
해당 문서 참고하여 진행해주세요!

[맵 디자인 문서](https://drive.google.com/file/d/1wo2s9TSw7Q8hg6wXxvQF58p07UnYQ2cI/view?usp=drive_link)
- GG TOWN 입구
- 플로야드 초입
- 플로야드
- 플로야드 위험구역

<img width="582" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/48927068-ad5f-422f-9d18-17f4907c7307">

**Comment by CreatorLDH** [comment]
점점 발전하는 모습이라 보기 넘 좋습니다. 너무 고생하셨습니다! 감사합니다.

**Comment by wooyn730** [comment]
옆에 설명 달아주시는 거 너무 좋네요 👍👍
