### ISSUE TITLE
Test Code 조사

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#25]
# Test Code

### 테스트 코드
- 소프트웨어의 기능과 동작을 테스트하는 데 사용되는 코드이다.
- 개발자가 작성한 코드를 실행하고 예상된 결과가 정상적으로 나오는지 확인하는 데 사용된다.
- 단위 테스트(Unit Testing), 통합 테스트(Integration Testing), E2E(End to End Testing) 등의 다양한 종류가 있다.

### 테스트 주도 개발(TDD, Test, Driven Development)
- 테스트 작성 -> 테스트를 통과하는 코드 작성 -> 결과 코드를 리팩터링 하는 3단계 과정을 거친다.
- 애자일 방법론 XP의 12가지 기본 원리 중 하나인 'Testing' 개념에 기반을 두고 단순한 설계를 중요시한다.
- TDD로 하여금 테스트가 더 쉬워지므로 개발자는 간단하고 유지 관리 가능한 코드를 작성할 수 있게 된다.

## 사용 이유

- 디버깅 비용 절감
    - 테스트로 인해 결함을 최소화시켜 디버깅에 소모되는 시간을 줄임으로써, 개발자가 개발에 집중하여 생산성을 향상할 수 있다
- 코드 변경에 대한 불안감 해소
    - 하나의 버그를 고쳤는데 다른 곳에서 여러 개의 버그가 생긴다 ⇒ 회귀 버그
    - 기능은 요소들이 상호작용으로 만들어지기 때문에 회귀 버그는 완전히 차단&예방이 불가하며 관리하고 대처해야한다 ⇒ 회귀 테스트
- 더 나은 문서 자료
    - 테스트를 작성할 때 명세를 작성하며 코드의 실제 동작을 기술함으로써 코드가 어떤 역할을 가졌는지 이해할 수 있다
- 더 좋은 코드
    - 내가 작성한 코드가 테스트 하기 어려운 코드라면 좋지 않은 코드일 가능성이 높다
    - 이를 생각하면서 약한 결합도를 가진 좋은 코드를 작성하려고 노력할 수 있다
- 안정성
    - 테스트 코드가 존재함으로써 버그 발생 확률을 낮추고 소프트웨어의 품질을 높여 프로젝트도 개발자도 안정감을 느낄 수 있다

## 주의 사항

- 과하게 테스트 코드의 중복을 줄이는 것에 집중하여 테스트 간의 결합도를 높이지 않는다
    - 오히려 테스트 간의 격리성과 테스트의 가독성이 떨어질 수 있다
- 테스트는 구현이 아닌 결과를 검증하도록 해야 한다
    - 구현에 의존적이며, 테스트의 목적이 구현에 맞춰져 있으면 안된다
- 읽기 좋은 테스트를 작성해야 한다
    - 좋은 테스트 코드는 읽는 사람 입장에서 이 테스트를 이해하는데 필요한 모든 정보를 테스트 케이스 본문에 담고 있는 테스트이다

## 사용 방법

유니티에서는 Unity Test Runner라는 이름으로 자체 유닛 테스트를 지원하고 있다.
[[Unity] 유니티에서 테스트 주도 개발(TDD) 적용하기](https://everenew.tistory.com/243) 글을 그대로 따라하며 가볍게 진행 방식만 알아보았다.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/L5WKfxs/2023-10-08-185304.png" alt="2023-10-08-185304" border="0"></a>

## 생각

공부를 위해 참고한 글들 중 TDD, Test Code를 처음으로 사용해 본 사람들은 대부분 개발 도서를 읽고 공부를 시작하였다. 최근 개발 도서를 읽어야겠다고 생각하고는 있었지만, 다시 한번 필요성을 느꼈다..

## 질문

1. 전 프로젝트를 진행하실 때 테스트 코드만 사용하셨나요 아니면 TDD도 함께 하셨나요?
2. 이번 프로젝트에 TDD를 적용할 예정인가요?

## 참고 자료

- [테스트 코드를 왜 그리고 어떻게 작성해야 할까?](https://tech.inflab.com/20230404-test-code/) 👍
- [테스트 코드의 필요성](https://www.startupcode.kr/company/blog/archives/17)
- [유니티 테스트 러너(Unity Test Runner)](https://highfence.tistory.com/17)
- [[Unity] 유니티에서 테스트 주도 개발(TDD) 적용하기](https://everenew.tistory.com/243) 👍👍
- [개발자에게 TDD가 주는 의미](https://brunch.co.kr/@freeism/19) 👍

**Comment by fkdl0048** [comment]
1. 테스트코드만 시험적으로 적용했습니다..! TDD는 테스트코드가 익숙해지면 도전할 수 있는 하나의 패러다임이라 생각되기도 하고 생각보다 난이도가 있다고 생각되어서 이후에 논의해보면 좋을 것 같네요!
2. 윗 답변으로 대체합니다!

**Comment by wooyn730** [comment]
아하 답변 감사합니다 ^_^

**Comment by fkdl0048** [comment]
계속 작성 연습하는 느낌으로 같이 맞춰봅시다
