### ISSUE TITLE
[Ch1 SubA][Pacmom] 대사 출력

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#254]
## 생각
01/21(일) 작업 완료

### 쉐이더
쉐이더를 적용하면 대사와 먼지유령B의 디버프 눈이 잘 안보일 수 있음
(어두운 파랑 몸에 보통 파랑 눈일 때)

### 랜덤 대사
현재 랜덤 대사 출력 방식

**초 세기**
(0) 첫 목표시간은 10초
(1) 초를 센다
(1-2) 청소 모드일 때는 초 세기 일시정지
(2) 현재시간이 목표시간을 넘으면 대사 출력

**대사 출력**
(0) 6가지 대사 중에 랜덤 대사 선택됨
(1) 말 할 먼지유령을 둘 중에 랜덤으로 뽑기
(2) 대사 출력
(3) 현재시간은 0으로, 목표시간을 5초\~10초 사이에 랜덤으로 초기화
(4) 초세기 1~2 반복

### 그 외
먼지유령이 잡혔을 때 으악! 같은 대사 출력해도 좋을 듯

가정집 맵에 청소기+먼지 컨셉이니까
재미로 팩맘 괴롭히는 악동 컨셉도 괜찮은듯

---

## 구현

*추후 대사 출력 애니메이션 에셋 적용해야함*
*셋째주에 대사+아웃트로, 넷째주에 보완 예정*

### 인트로 (오프닝)

텍스트(라인 뷰) 한 개만 사용,
화자에 따라 텍스트 위치 이동, 폰트 사이즈 조절

먼지유령 대사 길이에 맞게 말풍선 height 조절

스페이스바 => 넘기기

### 인 게임 (랜덤, 청소모드)

~텍스트(라인 뷰) 두 개 사용 (먼지유령이 동시에 말할 때가 있음)~
=> 라인 뷰 사용 X, 말풍선 찾아서 텍스트에 대사 할당
먼지유령에게 각 텍스트 한 개씩 할당

~먼지유령 우측 상단에 말풍선 배치, 텍스트 배치
(먼지유령이 우측 끝에 있다면 좌상단, 좌측 끝에 있다면 우상단)~
=> 기본적으로 먼지유령A는 좌상단, B는 우상단에 말풍선 배치,
   x축 기준 좌측 끝과 가까우면 우상단, 우측 끝과 가까우면 좌상단에 말풍선 배치

3초 출력 후 자동 넘기기

### 아웃트로 (게임오버)

인 게임과 동일

하지만 넘기기 X

---

## 알게된 것

함수를 정의하려면 DialogueViewBase를 상속한 스크립트를 작성해야함

RunLine도 해당 스크립트에서 오버라이드

## 문제와 해결방법

RunLine 오버라이드 했는데 실행 안됨
알고보니 다이얼로그 뷰에 넣어줘야함

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/6ba1c563-f342-45de-9a40-a1d75407b145)

개오래헤멤 샘플 보고 알아챔

## 고민

![스크린샷 2024-01-15 175043](https://github.com/GG-Studio-990001/GameOver/assets/80298207/cd0fdda0-efb2-45fe-b5b3-8a0765dc3382)
작은 말풍선+텍스트
글씨가 잘 안보임

![스크린샷 2024-01-15 175102](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d66bc005-92c1-46aa-9205-11593a3e8481)
큰 말풍선+텍스트
맵이 너무 가려지는 듯... (특히 두 먼지 다 말하는 중이라면)

대안 => 말풍선 대사 길이 줄이기?

**Comment by wooyn730** [comment]
@2ehdgh17 

[얀 파일 위치](https://github.com/GG-Studio-990001/GameOver/blob/main/Assets/Dialogue/CH1/Pacmom/PacMomDialog.yarn) 입니다

**Comment by CreatorLDH** [comment]
<<if $RandomInt is 1>>
    먼지유령: (꼬르륵)
<<elseif $RandomInt is 2>>>
    먼지유령: 임무 완수!
<<elseif $RandomInt is 3>>>
    먼지유령: 아 힘들어
<<elseif $RandomInt is 4>>>
    먼지유령: 퇴사할까?
<<elseif $RandomInt is 5>>>
    먼지유령: 도망칠까?
<<else>>>
    먼지유령: 쉬는 시간은?
<<endif>>
