### ISSUE TITLE
[Ch1 Main] SFX 작업_1

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#255]
#221 에 따른 Ch1 Main SFX 작업

-----

이번주는 동호님이 올려주신 사운드 SFX 중에 텍스트 입력음과 라플리 발자국 소리를 작업해봤습니다.

텍스트 입력음은 동호님이 레퍼런스로 올려주신 산나비, 언더테일을 참고해서 이번주는 3가지 사운드를 만들어봤습니다.

[텍스트 입력음 1 ](https://drive.google.com/file/d/1MfwtvIkyzsNpO_O22iO8Mlr8cX4dGbeh/view?usp=drive_link)

[텍스트 입력음 2](https://drive.google.com/file/d/1cYwSA3en625q8umFd7CAf8rPn54jGfPq/view?usp=drive_link)

[텍스트 입력음 3](https://drive.google.com/file/d/1RgGahmB77BoeKZ-i6RlEGFL0jlQ-IgHk/view?usp=drive_link)

한 음절에 다닥 하고 나오는게 깔끔할 것 같아서 일단 저렇게 만들어봤는데 혹시 다다닥이 나을 것 같다거나, 소리 타이밍이 더 빨라야 할 것 같다거나 하는 의견 있으시면 언제든지 말씀해주세요!! 

> 적용해봐야 어떻게 수정할 지 알 수 있을 것 같긴 합니댜 ,,

리소스 더미 치운 곳 걷는 라플리 발걸음 [L](https://drive.google.com/file/d/1mbbPNRdzc5-IZd9Uk7cxPX3-acx1g1Vm/view?usp=drive_link), [R](https://drive.google.com/file/d/1Sglt_UqaD1Ip3r3dtt15H51dwGIxdVSB/view?usp=drive_link)

리소스 더미 걷는 라플리 발걸음 [L](https://drive.google.com/file/d/1rLtfv2LL791iITvaeTXnNzFDHX2Hpi_b/view?usp=drive_link), [R](https://drive.google.com/file/d/1jPXmB_UrQA2gUzs60KLKc2MLRbldO5G6/view?usp=drive_link)

리소스 더미 치운 곳에서는 제가 보기에는 딱딱한 소리가 날 것 같아서 딱딱한 바닥을 걷는 스니커즈 사운드로 작업을 해봤습니다.

리소스 더미는 정확하게 어떤 재료들이 들어갈 지 몰라서 일단은 뭔가 밟히는 듯한 소리로 작업을 했는데 제가 임의로 작업해본거라 정해지면 더 세밀하게 수정 해봐야할 것 같습니당. 

피드백 언제든지 환영합니다 -!

**Comment by wooyn730** [comment]
[사운드 최적화](https://blog.naver.com/PostView.naver?blogId=ckdduq2507&logNo=222113891105)
정안님이랑 기화님께 공유드렸던 링크 다시 남깁니다~

나중에 셋이 회의 한 번 해도 좋을 것 같습니다
(사운드-어떤 사전 작업이 필요한지, 어떤 확장자가 적합한지 / 플밍 - 입체 음향 없는 사운드는 채널 합치기, 압축 방식 선택 등)

**Comment by royalbluesm** [comment]
발소리 제가 생각했던 느낌이랑도 비슷해서 좋네요! 타이핑은 말씀하신 것처럼 직접 적용해봐야 알 것 같습니다. 수고하셨습니다~

**Comment by CreatorLDH** [comment]
왼발, 오른발 분류까지 해주셔서 더 이해하기 편했습니다. 추후 테스트 플레이하면서 보면 좋을 거 같아요! 타이핑은 여러 개를 만드신 건 탁월한 선택이십니다. 추후(오랜 뒤, 퀄리티 업 시) 비용이 남으면 주요 캐릭터마다 다르게 설정하는 것도 좋아보일 거 같아요!

수고하셨습니다:D

**Comment by fkdl0048** [comment]
@Songkihwa @Sumindd 현재 1챕터에 발소리는 오히려 BGM을 해치는 용도가 될까요?

사운드분이랑 기획의견이 궁금합니다. 이게 원래 초기에 있던 기능이었는데 현재 적용이 안된 상태라

**Comment by Songkihwa** [comment]
개인적인 취향으로는 발소리 없는게 좋긴 하지만 게임적으로는 있는게 좋을 것 같습니다.
아 만약 발소리가 들어간다면 플로야드에서 걷는 발 소리, 동굴 안에서 발 소리, 마마고 컴퍼니 안에서의 발소리 모두 다르게 들어가야 합니당

**Comment by wooyn730** [comment]
저도 취향으로는 발소리 반대 ^_^

**Comment by roweclaw** [comment]
이미 발소리 없는 거에 적응되어서 그런지 상상했을 때 좀 어색하게 느껴지긴 하네요.
개인적으로도 없어도 된다는 쪽이고요.
그래도 볼륨을 좀 작게 넣어서 BGM이랑 어울리는지 테스트는 해보면 좋을 것 같습니다!
