### ISSUE TITLE
[Ch1 SubA] 팩맘 사운드 믹싱

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#289]
메인 시스템과 비슷한 밸런스로 사운드 믹싱 예정
-----

팩맘 믹스 세밀하게 다시 조정해봤는데 들어보시고 피드백 있으시면 편하게 코멘트 달아주세요ㅎㅎ
피드백 받고 고친 다음 개별파일 구드에 올려두겠습니당 -!

[팩맘 믹스 영상](https://drive.google.com/file/d/1W_tWNkMu0UrLnlzDV0EgEbp8dUdmZRBw/view?usp=drive_link)

**Comment by fkdl0048** [comment]
- [플레이 영상](https://drive.google.com/file/d/1Nmllk7tXOzhvNCooTWpqY43gJAJWCt9m/view?usp=drive_link)

플레이 영상 링크입니다

**Comment by wooyn730** [comment]
*기화님이랑 카톡으로 연락할 때 보냈던 것 공유를 위해 코멘트로 남깁니다!*

1. 기존보다 볼륨이 작은 것 같아서 훨씬 나은 듯?
2. 라플리가 코인 먹는 소리가 유난히 카랑카랑?해서 아예 다른 효과음으로 바꾸는 것도 괜찮을지도..
3. 영상에는 없지만 팩맘이 먼지한테 먹혀서 코인 떨굴 때도 조금 카랑카랑한 느낌
4. 아직 먼지 움직이는 소리 넣기 전인데 팩맘 코인 먹기+라플리 코인 먹기+먼지 움직임 3개가 동시에 날 때 어떨지 모르겠다

4-1. 팩맨이랑 다르게 이미 청소기소리와 라플리 코인 소리가 추가되어있으므로 먼지 움직임 소리를 빼도 되지 않을까
4-2. 아니면 먼지 움직임 소리 대신 먼지가 대사를 칠 때 짧은 말소리 효과음을 넣는 건 어떨지

**Comment by Songkihwa** [comment]
@wooyn730 

구드에 폴더 따로 만들어서 믹스 완료한 파일 모아놨습니다!
확인해보시고 혹시 이상한 점이나 빠진 거 있으면 언제든지 연락 주세용
[0202 믹스 완료 리소스](https://drive.google.com/drive/folders/1D_8Cs6Gva7QSV3yqHEDc1JK2YElmjIKY?usp=drive_link)

말씀해주신 코인 먹는 소리 같은 경우 제가 생각하기로는 저런 류의 게임에서 카랑한 코인 사운드도 중요하다고 생각되어서 일단 그냥 넣었는데 
너무 귀가 찌르는 듯한 느낌이라면 카랑한 느낌이 없는 다른 느낌의 사운드도 따로 보내드리겠습니다!! 
코인 떨굴 때는 레퍼런스대로 만들어본거였는데 너무 카랑한 감이 있긴 합니다ㅠ 이건 적용한 후에 제가 플레이해보고 어떤 사운드가 적합할지 생각해보겠습니다..!!

**Comment by wooyn730** [comment]
넵 목요일에 적용 예정이니 이슈 있으면 말씀드리겠습니다!!

코인 사운드는 아직 저만 그런 피드백을 드린거라 조정된 사운드 적용 후에 천천히 팀원분들 의견 들어보고 더 생각해봐도 될 것 같습니다~

**Comment by wooyn730** [comment]
적용 완료 했습니다!

- 원래 Pacmom_SFX_08였던 파일명이 BGM으로 변경돼서 SFX로 고쳐두었습니다
- 이렇게 볼륨만 변경되고 동일한 리소스는 파일명 수정 안하는 편이 괜찮네요!!
- SFX_13은 없던데 아직 적용은 안했지만 나중에 씬 연결 후 적용할 예정이라 주시면 좋을 것 같습니다!
- 제 기준 사운드가 수정 전은 너무 크고 수정 후는 너무 작게 느껴지네요.....ㅎㅎㅠ 정기 회의 때 빌드 뽑아서 팀원분들 의견 확인해봐야겠습니다...

**Comment by Songkihwa** [comment]
아이코 죄송합니다ㅠㅠ 삭제하고 다시 구드에 올렸습니다!!!

**Comment by Songkihwa** [comment]
메인 시스템 볼륨 밸런스 정도가 좋은 것 같다고 들어서 그 정도로 잡았는데 살짝 작은 감이 있는 것 같긴 합니다... 
빌드본 보고 수정해보도록 하겠습니다 ㅠ ㅠ 

> 아직 감이 없어서 그런가바요 ,,,,

13번도 구드에 방금 올렸습니다!

**Comment by wooyn730** [comment]
> 13번도 구드에 방금 올렸습니다!

=> 확인했습니다!!

메인 시스템 다시 확인해봤는데 저는 메인 시스템 볼륨도 작게 느껴지네요..
*기화님은 죄가 없다..*

다음에 영상 녹화할 때는 유튜브나 다른 게임 사운드도 같이 녹화해서 비교 대상을 추가해보면 더 확실해지지 않을까요?!

저도 다음부터는 더 꼼꼼히 확인하고 자세히 요청하려고 노력해 볼게요.. ^_^b
