### ISSUE TITLE
[ALL] : 기획서 현재 방향에 맞게 수정

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#294]
# [ALL] : 기획서 현재 방향에 맞게 수정

현재 잡혀있는 틀에서 빌드 기준으로 적용, 수정해야 하는 기획 파악 후 수정

0. 간단 요약
1. 메인시스템 맵
2. 시스템 연결 부분
3. NPC대사
4. SUB B

이외에도 빌드 기준으로 적용하는 기획들 수정하여 전달

## 게임 요약 설명

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/434ef74e-4875-4194-b58f-ed42882edc75)

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/bdf08bf2-b82b-4076-bab7-dd91aba040ef)

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/97435de9-218a-4c37-9d36-055796d07f9e)

- 이 게임은 다양한 게임의 집합체로 스토리 + 인터랙티브한 다양한 경험이 핵심
- 잊혀진 게임이 오는 마을에 떨어진 '라플리'를 (게임이자 캐릭터)플레이하는 '나'
- 해당 세계관은 잊혀진 게임이 하늘에서 떨어져 쓰레기 산을 이룬 형태로 지역, 종교, 인종 등의 제한이 없음
- 각 챕터는 장르의 전환으로 이루어짐 1챕터는 탑다운의 2D 도트, 2챕터는 비쥬얼 노벨 등 한 시대의 장르를 따라감
- 각 시스템이나 게임은 유명 고전 게임을 따라가지만 이미테이션, 카피캣의 형태로 쉽게 말해 따라했다가 망해서 잊혀진 게임의 형상을 띔

*자세한 내용은 세계관 기획문서 참고.*

## 기준 재설정

현재 기획 방향에 대해서 다른 작업자간의 이해를 위해 우선순위를 정하고자 함

- 메인시스템의 1의 장르는 과거 라플리의 게임 장르임
  - 따라서 사용되는 UI (대화창, 설정창)등은 챕터간의 이동에도 고정임
- 게임의 세계관에 맞게 몇 가지 규칙들이 있음
  - 잊혀진 게임들이 하늘에서 떨어짐
    - 최근에 떨어진 게임일수록 본연의 형태, 색을 유지함
    - 시간이 지날수록 색을 잃어가고 분해됨
  - 라플리는 게임이지만 플레이어의 형태로 떨어짐 (현재 플레이어가 플레이 중이기에 잊혀지지 않음)
    - 따라서 다른 게임에 접속하거나 활용할 수 있음 (다른 게임의 세계관에 칩임)

*기준은 계속 추가되거나 변경됨 기획 작업 전에 보면서 작업할 것.*

## 메인시스템 맵

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/26dc8165-456c-44cf-b3ae-4738ce336478)

### 현재 맵의 문제점

- 기획서를 아트로 옮기는 과정에서 해상도 변경 이슈로 맵이 생각보다 더 좁아지는 문제 발생
- 좁은 맵에 다양한 시스템의 결합을 생각했기에 문제가 된다고 생각 (너무 좁은 곳에서 많은 형태가 이뤄짐)
- 맵의 직관적인 형태가 아님, 재활용이 어려운 형태

### 수정 방안

1. 기믹들을 재배치, 맵의 확장
2. 마을 형태로 재기획

#### 기믹들을 재배치, 맵의 확장

다른 이슈인 대화중 어떤 NPC인지 힌트를 주기보다 3인 이상의 대화를 지양하고, 대화를 거는 NPC가 직접 다가가서 말을 거는 연출등을 추가하여 직관성을 높이는 방안

지금의 형태에서 수정되어야 할 부분들을 나열해보고 수정하고자 함

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/2ddeb614-8c51-46f1-8e08-932755ddc476)

3Match Puzzle의 영역이 기획서 상에서 존재와 플레이어, 맵의 비율이 생각보다 안 맞았던 것 같음

떨어진 위치와 퍼즐영역의 분리

라플리가 떨어진 위치는 좀 더 독립적인 공간이면 좋을 것 같음

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/c25b886a-43c1-4d43-905d-c5b9a42afb49)

그림의 1번이 라플리가 떨어진 영역이라면 퍼즐과 분리가 되어야 주민과 대화, 퍼즐의 풀이가 겹치지 않음

또한 1번의 경우 뒤쪽에 벽이 아닌 게임요소(리소스)가 쌓여있어야 설며이 될 것 같음

2번은 실제 심마니들이 게임을 찾기 위해 굴을 판 형태

내부에서 3매치 퍼즐이 이루어져야 할 듯

#### 마을 형태로 재기획

1챕터의 진행이 외곽에서의 심마니 활동을 하던 NPC의 진행이라면, NPC가 마을로 초대 이후에 벌어질 수 있도록

## 시스템 연결 부분

각 게임의 접속에 맞게 기획 (이미테이션 게임의 인트로를 참고)

## NPC대사

NPC대사는 단계별 진행으로 수정

최대한 1:1대화를 진행하고 연출 때 여러명의 대화가 필요하다면 라플리를 바라보기, 걸어오기로 처리

## 사건 플로우 수정

- 리소스홀에서 사람이 떨어짐
- 심마니들이 떨어진 라플리(게임 주인공)를 깨우기 시작함.
- 달러(나이 든 엘프여성, 심마니 그룹 리더)가 라플리에게 우리가 당신을 줍고 깨어나게 해주었으니 당신은 우리 것이다라며 소유권을 주장함.
- 그 과정에서, 벗어나고 싶으면 당신의 가치에 맞는 혹은 그 이상의 물품이나 능력을 보여달라고 말함.
- 첫 번째 필드 플레이 진행

**Comment by fkdl0048** [comment]
- 화요일 시험으로 일정 차주로 변경

**Comment by fkdl0048** [comment]
@royalbluesm 

회의전에 조금 이야기를 해보면 좋을 것 같은데 회의 전에 시간 가능 하실까요?

**Comment by royalbluesm** [comment]
@fkdl0048 가능합니다. 한 30분 정도 전에 미리 보면 될까요?

**Comment by fkdl0048** [comment]
넵넵 좋습니다!

**Comment by royalbluesm** [comment]
확인했습니다~

**Comment by Songkihwa** [comment]
작업하시느라 고생하셨습니다!
정안님이 정리한 내용을 보니 제 머리 속에서도 게임 기획과 방향성이 깔끔하게 잡히는 것 같습니다.

가능할 진 잘 모르겠지만 그냥 제 개인적인 의견으로

NPC 대화에서 여러 명이 대화가 진행될 때 동물의 숲에서 주민들이 대화하는 걸 엿듣다가 대화에 끼어들었을 때처럼

1대 1 대화할 땐 원래 탑뷰 시점에서 그 NPC와 라플리를 중심으로 살짝 확대한 뒤 그 옆 사람으로 대화가 넘어갔을 땐 카메라 시점이 다른 NPC 쪽으로 이동하면서 누군지 알려줘도 괜찮을 것 같습니다!!

**Comment by fkdl0048** [comment]
카메라 워킹도 좋네요 한번 적용해보고 같이 이야기 해봅시다
