### ISSUE TITLE
[Ch1 SubA] Pacmom 먼지유령 텍스트

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#301]
먼지유령 텍스트 음 수정/분할하여 업로드 예정

------

[먼지유령 텍스트 음](https://drive.google.com/drive/folders/1zSEc9roYm8pul_jO42yRlmJN1IHMTk_5?usp=drive_link)

먼지유령 텍스트 한 음절씩 분할한 버전 업로드했습니다.
피드백 언제든지 환영입니당

**Comment by Songkihwa** [comment]
@wooyn730 

[팩맘 먼지 유령 텍스트 예시 ](https://drive.google.com/file/d/1pvIwoNSRp0eghCOLRvsRpz9l_dEL0Z9W/view?usp=drive_link)

제가 올린 영상처럼 구현되었으면 좋겠는데 한 음절씩 드리면 이런 식의 구현이 가능할까요?
이렇게 구현하려면 파일을 랜덤하게 재생시켜야할 것 같은데 파일 랜덤 재생도 가능한지 궁금합니다!!

**Comment by wooyn730** [comment]
지금 사용하는 대화 시스템으로 사용하는 Yarn Spinner에 OnCharacterTyped()라고 대사가 타이핑될 때마다 함수를 호출하는 기능이 있습니다.

=> 결론: 한 음절씩, 랜덤으로 재생 가능합니다!
최대한 영상이랑 유사하게 구현해보겠습니다

**Comment by fkdl0048** [comment]
개인적으로 랜덤재생이라면 각각의 음절 사운드마다 너무 큰 차이를 주면 어색할 것 같고 지금 넘어온 동물의 숲 단어 사운드에서 몇 음절만 끊어서 수정해도 좋을 것 같습니다!

**Comment by Songkihwa** [comment]
엇 그러면 어떤식으로 파일을 드려야할까요 ..??

**Comment by fkdl0048** [comment]
> 은 지금 각 사운드가 차이가 너무 크다고 느껴지지 않아서 저는 지금도 괜찮습니다

확인했습니다. 너무 동물의 숲 느낌이 나는 것 같지만? 일단 사운드는 전 보다 자연스러워진 것 같아요

> 라플리 '?'도 사운드 넣는 게 좋을까요??

개인적으로 "치직"과 같은 게임 랙 소리로 대체해도 좋을 것 같은데 회의 때 이야기 해보면 좋을 것 같습니다.

> 예시 영상과 달리 현재 , ? ! 같은 특수문자일 때도 사운드를 출력하는데

크게 이상하다고 안 느껴서 상관 없을 것 같아요
