### ISSUE TITLE
[Ch1 SubA] Pacmom 사운드 정리

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#307]
우연님이 주시는 팩맘 플레이 영상 토대로 사운드 밸런스 총정리

----------

저번주에 작업한 믹스 밸런스를 바탕으로 전체적인 음량을 키워봤습니다.

사운드를 줄여달라는 얘기에 표준 음량을 생각하지 않고 너무 줄인 감이 있던 것 같아서 반성하는 마음으로(ㅠㅠ) 이번주 작업을 했습니다.

제가 작업을 어느정도 음량으로 했는지 설명 드리기 전에 게임 표준 LUFS와 LUFS가 뭔 지부터 최대한.. 알기쉽게 설명드려보겠습니다..!

* LUFS(Loudness Unit Full Scale)란? 사람이 들을 수 있는 가청 주파수 대역(20hz~20Khz) 안에서도 저음은 잘 안 들리지만 고음은 상대적으로 잘 들리는데 이런 사람의 귀를 고려한 전체 소리의 음량을 측정하는 단위입니다. 
 쉽게 말해서 전기적 신호의 세기만을 재는 dB(데시벨)과 달리 평균적인 사람의 귀에 최적화되어있는 소리의 단위라고 생각하시면 될 것 같습니다. 

> 교수님이 설명하실 땐 되게 쉽게 잘 설명해주셨는데 제가 설명하려니 잘 설명한건지 모르겠네요 ....

찾아보니 게임에 대한 표준 LUFS의 기준은 딱히 없고
(드라마나 영화와 달리 효과음 비지엠 등 각 사운드를 플레이어가 조절할 수 있는 기능이 있어서인 것 같아요) 

인디게임 사운드 제작사에서 제작할 경우 LUFS를 모르는 경우도 있고 특별한 기준이 있는 것도 아니라 
게임들의 음량이 들쭉날쭉 할 수 밖에 없는 것 같습니다. 사실 제작사 마음이기도 하구요.

게임과 비슷한 영상 음향을 다루는 매체들의 LUFS를 살펴보면 

**TV의 LUFS는 -24LUFS이고 넷플릭스는 -27LUFS 유튜브는 -14LUFS 입니다.** 

한마디로 저 숫자 이상 넘어가면 알아서 눌러버리는 한계치라고 할 수 있습니다. 

사람들마다 만드는 음량이 각각 달라서 이용자들이 불편을 겪을 수도 있는데,

예를들어 제가 만든 메인 음량과 팩맘 음량을 음량 차이가 많이 나서 여러분들이 음량을 줄이면서 들어가셨던 거 기억하시나요? 
이 불편함을 없애고 사람들의 귀를 보호하기 위해 각 회사에서 정한 LUFS 기준치입니다. 

과연 우리 게임의 표준 음량은 어떻게 정해야할까?에 대해 고민을 하며 큰 게임들의 표준 LUFS에 대해 자료들을 찾아봤고
제 기준에서 제일 신빙성 있는 자료들을 두 개 정도 뽑아봤습니다.

* [Wwise 회사인 Audio kinetik 홈페이지에서 라우드니스에 대해 쓴 글 ](https://www.audiokinetic.com/ko/library/edge/?source=Help&id=loudness_measurement_scopes)

 이 글에서는

_가정용 플랫폼용으로 개발된 게임의 오디오 콘텐츠 Average Loudness Level은 -23 LUFS의 Target Level과 ±2 LU의 오차로 정규화 
휴대용 플랫폼용으로 개발된 게임의 오디오 콘텐츠 Average Loudness Level은 -18 LUFS의 Target Level과 ±2 LU의 오차로 정규화되어야 합니다._

라고 쓰여있습니다. 앞서 말했던 영상 매체들의 LUFS와 얼추 비슷한 거 보이시나요?

* [어떤 분이 공유한 게임 오디오 음량에 대한 글](https://ansoaudio.com/2016/07/27/loudness-and-metering-in-game-audio/)
 이 글에서도

_소니 ASWG-R001
콘솔 타이틀의 평균 음량: -23 LUFS(+/-2)
휴대용 타이틀의 평균 음량: – 18 LUFS
실제 피크 최대값: -1dBTP
Gary Taylor는 인터뷰에서 [Media Molecule](http://www.mediamolecule.com/) 및 [Rockstar](http://www.rockstargames.com/) 와 같은 스튜디오가 평균 음량과 다이나믹 레인지 측면에서 이미 Sony의 사양을 따르고 있다고 언급했습니다. 이는 게임 오디오 음량 표준화 측면에서 느리지만 확실하게 진전이 이루어지고 있음을 나타내는 것으로 보입니다._

라고 나와있습니다. 

우리 게임은 모바일이 아니라 컴퓨터에서 재생될 것이기 때문에 -23LUFS 정도로 맞추는 것이 대기업 게임 업계들의 권장 음량이지만,

우연님이 보내주신 다른 게임들 영상의 Integrated LUFS를 재보니 언더테일은 약 -18LUFS, 두번째 게임은 -11LUFS 였습니다.

제가 듣기에는 두 번째 게임은 음량은 너무 큰 것 같아서 (저 게임 영상은 유튜브에 업로드하면 눌러지는 음량입니닷.)

두 번째 게임보다는 언더테일 정도가 괜찮다고 생각됐고 앞서 설명한 게임 업계가 권장한 LUFS도 고려하여 
일단 Integrated LUFS를 -21 정도로 잡아서 작업했습니다.

여기서 언더테일만큼 키우는 것은 괜찮을 것 같고 그 이상 (두 번째 게임처럼) 키우는 것은 좋지 않을 것 같습니다.
하지만 게임에 적용해본 뒤 사운드 확인 후 그 이상 음량을 키워보는 것도 고려해보겠습니다.

**일단 제가 임의로 작업한 것이기 때문에 팀원들 의견 듣고 더 고쳐보고 마지막 파일 넘겨드리겠습니다!**

[팩맘 0215 믹스 영상](https://drive.google.com/file/d/1F_v5r9dEDIV4fhVwGcyMxT2dOvuKX8AE/view?usp=drive_link)

 추가 수정 사항있으면 다시 업로드하겠습니다!

**Comment by wooyn730** [comment]
회의 끝나고 녹화 떠서 남길게여 O.<

**Comment by wooyn730** [comment]
@Songkihwa 

[플레이 영상](https://drive.google.com/file/d/1BKC-WgV4838oHOvvDRQqqSgdrUiwTOpu/view?usp=drive_link) 이거 보시면 바로 작은 거 체감하실 것 같아요 진짜루

다른 분들은 [빌드 파일](https://github.com/GG-Studio-990001/GameOver/actions/runs/7873404235) 확인 가능하심니다

++
그리고 '팩맘이 코인 떨구는 소리'랑 '팩맘이 잡혔을 때 기절음' 두 가지 사운드가 팩맘이 먼지에게 잡히는 경우에 항상 동시에 나서
떨구는 소리 빼고 기절음만 나와도 된다고 생각하는데 어떠신가요??
저는 두개 동시에 들리니까 별로인 것 같아서요...
지금 빌드 파일에는 코인 떨구는 소리 빠져있는데 필요하시면 이것도 영상 드릴게요

**Comment by fkdl0048** [comment]
영상으로 보니까 다른 게임에 비해 많이 작네요..

저는 크다고 생각해서 기화님에게 전부 줄여달라고 요청했는데, 객관적인 다른 게임과 비교해보니 많이 작은 것 같네요
*다른 분들도 확인 부탁드립니다!*

기화님이 일을 두 번 하시는 것 같아서 죄송합니다..

**Comment by Songkihwa** [comment]
@wooyn730 
저도 하나만 나와도 좋을 것 같습니당 >< 

@fkdl0048 
아니에요ㅠㅠ 저도 부족했는걸요 ,, 
우리 게임을 위해서라면 ,, 재작업 정도 쯤이야 ,,,

제가 설명한 것을 보시면 아시듯이 우연님이 보내주신 게임 음량이 조금 큰 편이긴 합니다! 
하지만 요즘 라우드니스 워라는 말이 생길정도로 누가누가 더 큰가?를 대결하듯 음압을 키워놓기 때문에 
우리 게임도 적절한 기준을 잘 잡아야할 것 같아요.

제가 만들었지만 8Bit 사운드에다가 반복되는 코인 소리에 청소기 비지엠까지 다 같이 나올 때는 듣기좋게 만들기가 쉽지 않네요 .. 
왜 저렇게 만든거지 .. 하면서 욕하면서 작업 중이긴 합니댜 ,,,

어쩌면? 옛날 게임은 귀가 아픈 소리들이 많았어서 사운드 고증이라고 할 수도 있겠지만
개인적으로 혼자 계속 고민해볼 것 같아요.

> + 저번에 우연님이 말씀하셨던 코인 사운드 변경이라던지,, 청소기 BGM에서 하이햇을 빼볼까도 생각 중이에요

**Comment by Songkihwa** [comment]
흑흑 좋게 들어주셔서 감사함미다 ㅠㅠ
눈물은 안 흘렀다니 아쉽네요 ...

아무튼 더 좋은 소리를 향해서 ,,, 열시미 달려보겠습니다

> 저 글만 한 2시간동안 썼다가 고쳤다가 한 것 같애요 ........ㅋㅌㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by royalbluesm** [comment]
글 너무 알기 쉽게 잘 적어주신 것 같아요! 상식 하나 얻어갑니다 >.0
저는 사운드에 예민하지 않은 편이라 큰대로...작으면 작은대로... 플레이하는 편이긴 한데 이번 영상(0215)은 PC의 볼륨을 평소 게임할 때처럼 설정하고 들었을 때 딱 적당한 톤으로 작업이 된 것 같아요! 수고하셨습니다.

**Comment by fkdl0048** [comment]
글 자체가 퀄리티가 높아서 카페에 글로 작성하셔도 좋을 것 같고, 개인 블로그가 있다면 거기에 올려도 좋을 것 같습니다..

저와 우연님이 사운드적으로 차이를 느꼈던 이유도.. 알 수 있어서 좋았습니다.

이런 방식으로 각 파트간의 이해도를 높일 수 있다는게 정말 좋습니다.

감사합니다

**Comment by wooyn730** [comment]
먼지유령 텍스트 1번 파일이 사라졌네요!!?

**Comment by Songkihwa** [comment]
앗 그거 번호가 밀린 것 같습니닷.. 원래 1번이 지금 2번으로 쭈루룩으로 된 것 같아요 🥲

**Comment by wooyn730** [comment]
아항 알겠습니다~~~
