### ISSUE TITLE
[Ch1 Main] 맵 리소스 수정 03

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#308]
**상세**
#293 에 이어 맵 리소스(조명 이펙트)를 수정합니다. 

**파일**
[파일 다운로드](https://drive.google.com/file/d/1BBD8hKzrIpx9g6Bgd5bW2XhqrIo9lB6R/view?usp=sharing)
#310 의 프리뷰와 함께 보시길 권장드립니다. 리소스마다 불투명도 조절이 필요합니다.
이전 리소스 파일이 뭐가 어디에 쓰이는지 알기 어려웠던 관계로 이번엔 배치를 왼쪽부터 순서대로 정렬했습니다. (가장 왼쪽에 있는 빛 파일이 좌측 상단에 있고, 그 뒤로 순서대로 배열되어 있는 식) 빛 기둥과 바닥에 비치는 빛(타원)도 같은 순서로 정렬되어 있습니다. 이전보다 훨씬 알기 쉬울 거라고 생각하는데 그래도 헷갈리시면 언제든 연락주세요

**Comment by wooyn730** [comment]
스프라이트 겹침 없이 직관적인 배치라 좋습니다!

다만 파일 이름이 좀 더 명확하면 좋겠네요
*정안님과 어떤 합의를 했는지는 모르겠지만?*
