### ISSUE TITLE
캐릭터 기획 작업

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#31]
캐릭터 표 작업 (최소 1~2개) 예정 
- 주인공 (필수)
- 심마니 (필수)
- 기획 레퍼런스에 따른, 추가 캐릭터 기획 예정

빠르게 기획 후 전달 예정

https://drive.google.com/drive/folders/1Dyfgohz_Q9LkiHMICLO094bx0fZTD1Qb?usp=sharing

이번 주는 이정도로만 진행했습니다.
메인 캐릭터 / 심마니 집단

차주에 보완 및 추가 작업할 예정입니다.

**Comment by fkdl0048** [comment]
라플리 주인공 이름, 리플리 증후군이 생각나서 다양하게 해석이 가능할 것 같습니다.

**Comment by fkdl0048** [comment]
# 캐릭터 기획 피드백

## 주인공

- 라플리 replay, 리플리 증후군등 다양한 연결 가능

성격, 말이 없었으면 좋겠다.

얼굴 묘사도 적으면 더 좋을 듯

플레이어가 게임이기 때문에 자신이 인식하는 모습에 따라 달라질 수 있는?

좀 더 관념적인 플레이어의 모습이어야 하지 않을까?

대신 현재 기획과 같이 대외적으로 보여줄 이미지가 필요

성격이나 가치관 습관등은 원래 자신의 게임의 형태에서 따오면 좋을 듯

어떤 식으로 전개되어 갈지 모르겠지만, 라플리 자체가 게임

라플리라는 게임이 오래되어 잊혀진 게임이라면 오래된 스타일이 좋을 것 같고

이 GG타운에 리소스홀을 통해 내려온 첫 인간이라는 설졍이라면 원래 어떤 게임이였는지에 대한 구체화가 필요해보임

그 구체화에 따라 캐릭터의 외형적인 모습이 해당 게임의 색을 잘 담고 있다면 좋을 것 같다.

## 심마니

NPC 개개인의 개성도 좋지만 이후에 구체화되면 좋겠다고 생각하는 부분은 신념적인 부분

사회에도 다양한 신념이 존재하듯이, 현 사회에서 누구 맞고 틀리고를 떠나 쉽게 결정하기 어려운 부분이 존재

개인적인 아이디어로 각 NPC마다 ~~주의와 같이 성격적인 부분이나 가치관이 있으면 좋을 것 같다.

- 이데올로기로 성격적 해석을 한다면?
  - NPC1: 자유주의
  - NPC2: 보수주의
  - NPC3: 공산주의
  - NPC4: 민주주의
  - NPC5: 군주제
  - NPC6: 무정부주의
  - NPC7: 이슬람
  - ...

그대로 따라가는게 아닌 참고용으로 성격적 해석을 가져가도 매력적으로 느껴질 것 같다.

- 참고: https://ko.wikipedia.org/wiki/%EC%9D%B4%EB%8D%B0%EC%98%AC%EB%A1%9C%EA%B8%B0_%EB%AA%A9%EB%A1%9D

심마니의 땀수건과 같은 통일적인 부분도 매우 재밌어 보임

- 걱정되는 부분은 너무 한국적인 해석이 되지 않을까?
- ++ 반대로 외국의 심마니처럼 금속탐지기를 들고 다니는 심마니도 있으면 재밌을 듯

모두가 심마니의 형태를 가져가는 통일성도 좋지만 서브 NPC들도 있어야 할 것 같다는 생각 - 같이 논의해보면 좋을 듯

확실이 NPC, 캐릭터 부분은 주관적인 부분이 매우 강해서 기획하기 가장 어려운 부분이라는 생각이..

**다른 게임의 레퍼런스를 참고해서 매력적인 캐릭터들을 분석하는 것도 좋아보임**

주인공의 성격을 죽이고 NPC, 세계관에 집중하기로 한 만큼 이 부분에 있어서는 캐릭터 NPC가 매력적으로 뽑혀야 할 것 같다는 생각

**Comment by CreatorLDH** [comment]
**### 피드백의 피드백**

라플리 증후군 활용하여 게임 내 개연성을 부여할 수 있는 전략이 생각나서 너무 좋은 아이디어인 것 같습니다.

캐릭터에 대한 표를 구성해보니, 입체적인 캐릭터로 변화한 거 같더라구요.
마을과 NPC에 집중하기로 했으니, 성격을 좀 죽여보겠습니다.
=> 아마 게임 내 대사는 없는 걸로 다시 상기해서 가져갈게요.

//

[현재 머릿속 이야기]
현재 라플리 또한 게임이기에 '관념적인 존재'가 맞습니다.
이 관념적인 존재는 본체가 존재하죠. 
본체는 리소스 마운틴 내에 잠들어 있고, 게임의 엔딩 부분에서 깨어납니다.
=> 지금 현재 유저가 플레이하는 게임 또한 잊혀진 게임이므로 라플리라는 존재로 게임을 진행할 수 있었고, 유저의 플레이로 인해 해당 게임(마을)이 점점 살아나는 것이죠.
=> 그로 인해 잠들어 있던 라플리(본체)가 깨어나 플레이어의 라플리(관념적 존재)를 마주하였습니다.
=> GG TOWN(가제)는 본래 동물의 숲과 비슷한 계열의 힐링 마을 게임이었으나, 해당 게임이 유저들에게 금방 잊혀지면서, 주인공이었던 라플리 또한 자신을 가두며 게임과 같이 잊혀져 갔습니다.
그렇게 시간이 지나, 다른 잊혀진 게임들이 떨어지면서 마을이 형성되게 되었습니다.

여기서 여러분이 게임을 실행하게 되었습니다. 하지만, 본래 게임 주인공인 라플리(본체)는 잊혀짐으로 인해 잠에 들었고, 게임은 어쩔 수 없이 라플리의 복사본, 즉 관념적인 존재로 게임에 참여시키고자 했습니다.

그래서 엔딩 크레딧이 올라간다면, GG TOWN이 그레이스케일에서 원래의 색으로 돌아오는 연출을 넣고 싶음.

//

**다시 피드백**

현재 이런 생각을 가지고 있기에, 라플리의 원래 게임은 바로 GG TOWN(가제)이므로, 라플리는 이미테이션 기반의 캐릭터가 아니었으면 합니다.
여기서 과거 GG TOWN은 마을 사람들과 대화하며 나누는 힐링 게임입니다. (짱구 시리즈 중 마을 시스템과 비슷한 맥락)

### **심마니**

물론, 참고용으로 주셨지만 정치적 이데올로기들을 캐릭터 하나하나에 부여한다면,
해당 이데올로기를 공부하는 작업에 대해 시간 비용이 좀 들거 같습니다.

자유주의와 같은 단어적으로 정립되는 가치관이나 성격으로 표에 기입하지 않았지만,
캐릭터의 성격적 방향성을 알 수 있게끔 [성격]-[가치관]이나 다른 부분에 표현은 했습니다. 캐릭터 해석을 보다 하기 편하시게, 좀 더 구체화하겠습니다.
=> 각 NPC마다 다른 가치관과 성격, 행동 특성이 있게끔 이미 설계하고 있다는 내용입니다:D

금속 탐지기 아이디어 좋습니다.

모두가 심마니의 형태를 가져가는 것이 아닌, 챕터 1 초반부터 중반까지 같이 극을 이끌 캐릭터들로 표현했습니다. 주 무대가 잊혀진 게임들이 평야와 같이 구성된 곳이라 그 곳에서 파밍하는 사람들이 우선적으로 등장이 필요해 보였고, '심마니 조직'이라는 컨셉 하에 몇몇 캐릭터를 디자인했습니다.

다른 서브 NPC (상인 계열, 주민 계열, 기타 계열) 들은 필요에 따라 주기적으로 생성 및 폐기 예정입니다.
(금주 마일스톤 내용 포함)

**Comment by fkdl0048** [comment]
말씀해주신 내용 보니 따로 피드백할 내용은 없는 것 같습니다.

세계관과 마찬가지로 캐릭터도 어느정도 방향이 잡혀가고 있어서 챕터 1, 세계관, 캐릭터 기획이 같이 진행되는 느낌이라 좋네요

이후에 좀 더 구체화가 되면 그 때 이야기를 더 나눠도 좋을 것 같습니다.

이후에 구체화 된 내용을 토대로 피드백이나 회의를 잡아보죠

항상 좋은 내용으로 만들어주셔서 감사합니다 동호님!
