### ISSUE TITLE
[Ch1 Main] 맵 프리뷰 제작

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#310]
**상세** 
수정된 기획안으로 플로야드 맵 리소스를 재배치하고, 프리뷰를 제작해옵니다.

**파일**
[프리뷰 보기](https://drive.google.com/file/d/11qKLL-FKE_Z0I1CusOUf2e-PjBZbx-lU/view?usp=sharing)
백그라운드 이미지도 조금 더 완만한 느낌이 나도록 리터치했습니다. 이전 결과물보다 나은 것 같으면 ver2 리소스 바로 업로드하도록 하겠습니다. (빛, 백그라운드 등) 피드백 부탁드립니다!

**Comment by Songkihwa** [comment]
한층 더 게임의 분위기가 사는 것 같아요!
정안님 의견처럼 경계에 리소스가 있는 것도 게임의 분위기를 더 살려줄 수 있을 것 같아요.
작업하시느라 고생하셨습니다 :)

**Comment by yanggang3** [comment]
레이어가 한층 더 생겨 게임의 입체감이 훨씬 좋아진 것 같습니다. 지금 분위기도 정말 좋은데 
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998716/8ddff2c0-e4fe-4b03-b8ce-ce9ede79b69c)
약간 이렇게 앞쪽에도 간단한 실루엣(어두운색인)이 생기면 공간이 더 꽉 찰 것 같아요.!
(세계관 공간에 맞지 않는 설정일 수도 있지만..)

**Comment by wooyn730** [comment]
이전 버전이랑 비교하기 좋게 이전 이슈나 파일 링크도 같이 첨부해주시면 좋을 것 같습니다!! ><
