### ISSUE TITLE
[Ch1 SubA][Pacmom] 코인 UI 배치

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#318]
# [Ch1 SubA][Pacmom] 코인 UI 배치

![스크린샷 2024-02-19 163210](https://github.com/GG-Studio-990001/GameOver/assets/80298207/07e1c54a-f6a5-4ebe-99eb-591334875d7c)
*기존 UI 배치*

## 문제

시연회 때 라플리의 코인 UI와 팩맘의 코인 UI를 헷갈려 한 플레이어가 있었음

원인은 다음과 같이 유추됨
1. 라플리 코인 UI는 좌측하단, 팩맘 코인 UI는 우측상단으로 멀리 떨어져있어 한 눈에 비교할 수 없음
2. 상단에 팩맘 목숨, 타이머, 팩맘 코인 UI가 몰려있어 하단으로 눈길이 가지 않음
3. 팩맘 코인 UI는 'COIN'과 개수만 적혀있어 이것만 본다면 누구의 코인인지 알기 어려움

## 아이디어

코인 UI를 재배치해봄

라플리와 팩맘의 코인 UI를 같이 둘 때 더 명확히 구분되는 점이 있으나 아트적으로(?) 예쁜 배치인지 의문

## 후보

*우측 하단에 버튼 3개는 고려하지 말아주시길 바랍니다*

(1)
![스크린샷 2024-02-19 163359](https://github.com/GG-Studio-990001/GameOver/assets/80298207/59364196-95db-4c91-8e8e-b666b3c1c4e1)

(2)
![스크린샷 2024-02-19 163511](https://github.com/GG-Studio-990001/GameOver/assets/80298207/fcdc06a4-e876-4710-9151-20e550441687)

(3)
![스크린샷 2024-02-19 163559](https://github.com/GG-Studio-990001/GameOver/assets/80298207/538a664f-3dbd-40e8-bd73-f8be14338ec1)

(4)
![스크린샷 2024-02-19 163650](https://github.com/GG-Studio-990001/GameOver/assets/80298207/fbae8cef-1675-4c0e-8d50-77528ca839eb)

(5)
![스크린샷 2024-02-19 163712](https://github.com/GG-Studio-990001/GameOver/assets/80298207/45290dd3-a961-4c12-a552-0a2f7a02f1a1)

(6)
![스크린샷 2024-02-19 163734](https://github.com/GG-Studio-990001/GameOver/assets/80298207/90852104-3af4-43fc-a611-4000d395b163)

후보 중에 어떤 게 괜찮으며 이유는 무엇인지,
아니면 다른 아이디어가 있는지 말씀해주세요~~

**Comment by fkdl0048** [comment]
저는 3번이 제일 통일성?이 있어 보입니다

**Comment by wooyn730** [comment]
> 아니면 시간만 위에 두고 나머지 좌측하단에 lives, 우측하단에 코인개수를 해도 잘 보일 것 같아요!

오 전 이거 괜찮은 거 같기두?!!!

**Comment by wooyn730** [comment]
5번에서 팩맘 목숨을 우측 하단으로 내린 버전으로 픽스 (세화님 코멘트 참고)
