### ISSUE TITLE
사건 플로우 작성

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#32]
앞으로 진행하게 될 게임의 스토리를 간단하게 기승전결로 작성 예정입니다.
추후 이야기의 흐름이나, 챕터를 짤 때 용이하기 위함!

https://drive.google.com/file/d/15-4vAwnJ2Z-Cl-SldwXSXyZJSXwsQkwv/view?usp=sharing

시간 관계상 챕터 1 기획 구체화가 더 중요하다고 판단하여 러프하게 마무리를 한 상태입니다.

사건 플로우를 정확하게 작성하지 못하였지만, 
어떤 유형의 사건을 이용할 지나, 챕터 1 기본 플로우를 어떻게 흘러나갈 지 고민할 수 있었습니다.

(이거 쓰다가 챕터 1 아이디어 생각나서 급하게 작업 변경하는 건 안 비밀...)

**Comment by CreatorLDH** [comment]
본 문서는 챕터 기획을 용이하기 위해 러프하게 작성된 문서이므로 가독성이나 자세한 설명은 생략되어 있다는 점 양해부탁드립니당

다음 마일스톤 때, 공유용으로 다시 만들 겁니다요!!

**Comment by fkdl0048** [comment]
# 사건 플로우 피드백

러프, 미완이지만 벌써 완성도가 느껴짐 특히 사건의 초반 시놉시스

아직 러프라 추가되면 좋은 부분도 보이지만 2차 수정 이후에 회의를 통해 말해도 좋을 듯

- 4의 발단의 A, B, C의 서브시스템 분할부분의 명칭을 분할하여 좋음

해당 형태에 대한 각각의 설명도 있으면 좋을 것 같음

- 6의 위기부분에 등장해야 하는 (필연적으로 리소스 숭배자들과 같은 부분은 필요하다고 생각) 리소스 숭배자들의 가치관이나 설명이 궁금

사건 플로우 부분은 너무 좋음 특히 미니게임 부분의 아이작 오마주 부분(개발 난이도도 간단하고 단순 반복성과 색다른 시스템의 결합으로 해석해도 좋을 듯)

어색한 부분 엘프 여성의 억지? 리소스홀에서 널린게 게임이라면 (물건으로 칭한 주인공) 자신보다 가치가 있는 물건을 찾아 오라는 부분? 좀 더 자연스럽게 설명이 필요할 듯

이상 현상으로 접속이 발생한 부분, 이 부분은 기획 단계에서 좀 더 구체화가 있어야 납득이 가능할 듯

- 만약 엘프 여성이 그런 억지를 부리는 것이 가능한 세계관이라면 문제 없을 듯
  - 이후에 마을에서 보여주는 생활이 위 행동이 납득 가능한 선이라면

주인공이 게임이라면 접속이 가능한 부분을 복선으로 남겨두기 위해서 설명을 지금처럼 이상현상쯤으로 남겨두는 것도 좋은 방법 같음

챕터내 반복적인 요소는 위의 서브시스템일텐데 그에 따른 서브시스템 문서도 따로 만들어야 할 듯

**Comment by CreatorLDH** [comment]
리소스 숭배자들의 가치관이나 설명은 구체적으로 정해진 바 없으며,
[NPC : 달러]와 연관이 깊도록 설정하였기에 해당 문서에 조금 나와 있습니다.
현재 기획상 전체 게임의 중반부터 등장할 세력이기에 천천히 구상하고 있습니다.

해당 사건 플로우는 캐릭터 기획 후 작성된 거라 캐릭터 기획문서에서 표현된 NPC들의 성격적 특성을 가지고 짰기에, 캐릭터에 대한 이해가 있어야 더 이해가 가능하실 것이라 생각합니다.

주인공이 게임이라면 접속이 가능한 부분을 복선으로 남겨두기 위해서 설명을 지금처럼 이상현상쯤으로 남겨두는 것도 좋은 방법 같음 => **정답~!**

캐릭터 기획 구체화 + 챕터 1 기획 구체화 => 챕터 1 기획 구체화에 따른 서브 시스템 기획
이렇게 진행될 예정입니다.

사건 플로우에 대한 수정이 후 순위인 이유는, 현재 사건 플로우 기획의 대부분이 챕터 1 초점이기 때문에 해당 수정 부분은 **[챕터 1 기획]** 문서로 들어갈 것 같습니다.

그로 인한 전체적인 사건 플로우 작성은 후 순위로 밀렸습니다.

**Comment by fkdl0048** [comment]
좋습니다.

가능하다면 작업 순위를 정리해서 받아볼 수 있을까요?

다른 팀원분이나 저도 공유를 받고 작업 순서에 대해서 이야기 해보면 좋을 것 같습니다.

**Comment by CreatorLDH** [comment]
작업 순서를 문서처럼 정리한 상태가 아니여서, 일단 생각해 본 것은.

1순위로 챕터 1 기획을 마무리해야, 챕터2나 기타 총 기획서 작업을 할 때 다른 팀원분들이 챕터 1에 대한 작업을 할 수 있다고 생각합니다.

1. 챕터 1 기획 구체화 
- 챕터 내 NPC / 스토리 라인 및 배경 / 진행 플로우 (상호작용, 퍼즐) [이번주]
- 챕터 시스템 기획 (플로우 차트와 같은 것들) [다음주 시작 예상]
- 챕터 레벨 디자인 (맵 구조 및 상호작용, 퍼즐 위치, UX 등) [다음주 시작 예상]
(필요에 따른 테이블 작성, 대화 테이블 제작)
2.  추가 NPC 기획 [꾸준히 기획 후 사용 및 폐기]
3. 사건 플로우 완성
4. 총 기획서 정리 (챕터 1 내용 정리해서 추가)
5. 기타 (서브 콘텐츠, QA 등)

~ 챕터 2 / 챕터 3 반복.

막 쓰는 것이라, 짜임새 있는 계획은 아닙니다만
이렇게 생각하고 있습니다.

**Comment by CreatorLDH** [comment]
+ 리소스 관련 문서도 짜야하네요
