### ISSUE TITLE
[Title] 시작 타이틀 화면 구상

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#326]
![TitleIdea](https://github.com/GG-Studio-990001/GameOver/assets/144519956/8d2562e7-ec85-486c-90ab-ff7ba30ed53b)
지금 바로 작업을 시작하기보다는 전체적인 분위기를 픽스해놓고 시작하는 것이 더 좋을 것 같아 의견 받습니다.
1안같은 경우는 레퍼런스로 삼았던 언더테일 느낌의 심플한 배경이 될 것 같고요, 게임 로고 쪽에 눈길이 꽂히는 디자인입니다. 고전게임 스타트 화면 같은 효과를 낼 수 있고, 검은 배경에 로고만 있기에 추후 게임 장르가 달라져도 (어느 챕터를 시작해도) 어색함 없다는 장점이 있습니다.
2안의 경우 상대적으로 로고에 힘이 빠지고 게임 세계관에 대한 몰입도를 높이는 디자인이 될 것 같습니다. 딱 게임을 켰을때 오 좀 치는데? 라는 느낌을 줄 수 있는 장점이 있는 것 같습니다.

스타듀 밸리나 포켓몬처럼 전경+게임 로고가 들어간 스타팅 화면도 생각해봤으나 처음부터 끝까지 도트 게임으로 진행되는 것이 아니기 때문에 도트 감성은 의도적으로 좀 덜어내고자 했습니다.

로고 디자인에 대한 구상을 좀 해둘 걸 그랬네요... 3박 4일 여행 이슈로 많이 작업하지 못해 아쉽습니다.

**Comment by wooyn730** [comment]
2가 확실히 완성도 있어보이고 멋지네요!
각 챕터마다 타이틀 이미지가 있어도 좋을 것 같습니다.

바쁠 때가 아니라 이렇게 기획 재점검이 필요한 시기에 여행을 다녀오셔서 오히려 좋다고 생각합니다 ㅋㅋ
(근데 저두 담주 3박 4일 여행감..)

**Comment by royalbluesm** [comment]
챕터마다 타이틀 다르게 하는 아이디어 괜찮은 것 같네요! 만약 그렇게 된다면 각 챕터의 분위기를 살리는 일러스트를 넣을 수 있을 것 같습니다. (여행 잼게 다녀오세요...)
