### ISSUE TITLE
[Title] 시작 타이틀 화면 구체화

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#327]
**상세**
#326 에 이어 시작 타이틀 화면 일러스트를 작업합니다.

**초안**
![TitleIdeapreview](https://github.com/GG-Studio-990001/GameOver/assets/144519956/758cd68e-5df0-4c95-ad7e-fc375cc29f69)
[애니메이션 버전](https://vimeo.com/920103324?share=copy)
이런 형식의 애니메이션이 들어간 타이틀 생각하고 있는데 어떤가요? 리소스홀로부터 라플리가 떨어지는 모습으로부터 1챕터가 시작되면 자연스러울 것 같아 넣어봤습니다. 디테일 작업은 나중에 들어갈테니 느낌 한번 보고 코멘트 주시면 감사하겠습니다.

**Comment by fkdl0048** [comment]
간단하게 회의에 나온 아이디어가 민지님의 색으로 구체화된 모습 그림이 너무 좋습니다. 
한 눈에 게임의 세계관이 잘 설명되는 부분이 너무 좋아요 이 부분은 계속 잃지 않고 이어나가면 더 좋을 것 같습니다. (게임의 핵심이 잘 표현된 것 같습니다.)
지금과 같이 라플리가 떨어지는 모습도 좋지만, 라플리가 떨어지는 애니메이션이 있다면 1챕터의 컨셉에 맞게 뚝뚝 끊어지는 애니메이션이면 더 좋을 것 같습니다. (고전 게임의 느낌이 나게) 해당 세계관을 보여주는 카메라는 동적으로 라플리를 비춰주지만 라플리 자체는 뚝뚝 끊어지는 애니메이션으로 이질감을 줘도 좋을 것 같다는 아이디어입니다.
더 구체화 되었으면 하는 부분은 지금은 front 레이어로 처리된 흑백 오브젝트들이 게임의 리소스/게임의 형태로 보여진다면 더 재밌을 것 같아요. (이게 가능해지면 시작 씬 부터 게임을 이해하고 넘어갈 수 있을 것 같습니다.)
추가로 UI의 색감이나 형태는 좀 더 고민을 해봐야 하겠지만, 민지님의 의도인 UI를 가리는 오브젝트의 연출은 너무 좋습니다. (의도하신거라면 덕분에 세계관에 대한 확장이 더 넓어진 것 같습니다.)
진짜 마지막으로 하나만 더 말해보자면 뒷 배경의 회색 부분도 더 깊이감이 있으면 좋을 것 같습니다. (레이어가 더 많아진다면?)
지금의 피드백이 잘 적용되면 더 좋겠네요.
부족한 아이디어 확장하시느라 고생하셨습니다!

**Comment by royalbluesm** [comment]
1. 뚝뚝 끊어지는 애니메이션의 경우 현재 29.97프레임인데 프레임수를 줄여서 시퀀스를 만드는 방법으로 해결가능할 것 같습니다! 8~16프레임정도로 실험해보겠습니다. 좋은 의견 감사합니다. 라플리 자체에도 2~3프레임 정도로 움직임이 들어가면 좋을 것 같네요
2. 디테일 작업하면서 좀 더 게임 리소스들처럼 보이도록 보완해보겠습니다.
3. 이부분도 게임 로고 제작하면서 좀 더 고민해보겠습니다
4. 확인했습니다! 레이어 추가해서 깊이감을 좀 더 내는 방향으로 디벨롭해보겠습니다. 자세한 피드백 감사합니다!

**Comment by wooyn730** [comment]
잘 봤습니다!
지금도 멋있는데 디테일 작업도 한다니 기대가 됩니다

애니메이션 좋네요~
저는 30초 내로 줄이되 맨 앞과 맨 끝이 이어져서 loop 가능한 형태로 만들면 좋을 것 같습니다!

UI 가려지는 연출 독특하네요!! 매력 있어요
언제든지 버튼 누를 수 있도록 너무 크게만 안가리면 좋을 것 같습니다.

게임명 확정되고 게임 로고 생길 것도 기대되네요 굿~~

**Comment by royalbluesm** [comment]
확인했습니다~ 사이즈 조절해보겠습니다!
