### ISSUE TITLE
[0.0.3] 기획 레퍼런스 창구

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#33]
방금 회의에서 나온 이야기대로,
레퍼런스 창구를 깃헙에도 개설했습니다.

따로 ppt에 기입하시지 않더라도 여기에 남겨주시면 제가 옮기거나 활용하겠습니다.

열심히 하겠습니다 감사합니다:D

https://docs.google.com/presentation/d/1Rsym-yI_SNIOXCTHe5pZ2GWpPMmHCYJAUAcb2fcMF-0/edit?usp=drive_link

**Comment by wooyn730** [comment]
### 아무 생각 조금
- TRPG 캐릭터
   - 요즘 TRPG에 관심이 있는데 (마침 이전 기획에 언급되기도 했고) TRPG는 주사위 숫자에 따라 판정을 하니까 주사위를 굴려서 상호작용하는 TRPG NPC가 있으면 재밌을 것 같습니다
   - ex) 협상을 해야할 때 1\~2: 협상 실패, 3\~4: 어려운 성공, 5~6: 쉬운 성공 요런...
- 맥거핀
   - 중요해보이는 데 아무것도 아닌 거
   - 비싼 황금 열쇠를 파는데 사실 아무 데도 쓸 데가 없다던가..
- 퀴즈할 때 써먹을만한 요소
  - 모스부호, 애너그램, 점자, 진법, 무전기 교신?용어
  - 최현배 선생님의 한글 풀어쓰기 (이거 뭔가 조금은 알아볼 수 있겠으면서도 외계어 느낌 나서 재밌어요 / 근데 현지화 생각하면 못쓸듯 ㅎㅎ)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8c17bb27-a6e3-4b32-b998-821d91f816c4)
- 피아노
  - 밟아서 연주할 수 있는 피아노
  - 오버워치도 대기실에 피아노 있는데 유저들이 치면서 [재밌게(?) 놀아서](https://www.youtube.com/watch?v=Wcl1zHsa9es) 이런 .. 쓸모 없지만 귀여운 요소 싶은 생각 ㅎㅎ

**Comment by fkdl0048** [comment]
## @fkdl0048 

- 기획안의 2D 탑뷰 이후에 마우스를 획득한다면?
  - 마을의 나무나 바닥을 클릭하면 먼지, 나무 흔들림 이펙트 재생
  - 메인 시스템과 마을의 결합을 생각
  - 하스스톤 게임장의 클릭과 같은 느낌

**Comment by Songkihwa** [comment]
**간단한 레퍼 의견(이라고 쓰고 저두 아무 생각입니다)** 

- 파이어 보이와 워터 걸 : 서브시스템으로 넣어도 크게 부담이 없지 않을까 해서 의견 드립니다! 사실 제가 좋아했던 게임이였어서요. 퀘스트 중에 길이나 문을 찾아야한다면 이 게임으로 활용해봐도 좋을 것 같아요.

- PPT 내용 중 GTA 관련 : 이 차는 제껍니다 할 때 차 창문 팔꿈치로 깨는 것도 꼭 들어가면 재밌을 것 같습니다ㅋㅋㅋ 제가 즐겨 했었어서요 ...

- PPT 내용 중 타이쿤 관련 : 내용과는 조금 다르긴 하지만 슈의 라면가게 .. 아시나요? 이것도 비슷하게 들어가면 재밌을 것 같습니다! 그 게임 속 대사라던지 비슷하게 활용하면 누구나 한번쯤 해봤을 어렸을 적 했던 추억 게임이라 다들 좋아하지 않을까 해서 이렇게 의견드려봅니다 ㅎㅎ 

-정안님 의견 관련 : 나무에 올라탈 수 있는 것도 좋을 것 같아요. 나무를 올라타서 나무 안에 숨은 요소들을 찾는다거나, 아니면 나무를 흔들어서 숨겨진 뭔가를 떨어뜨린다거나 하는 것들이요!
