### ISSUE TITLE
[Title] 시작 타이틀 화면 구체화 02

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#338]
**상세**
- #327 

피드백을 적용해 시작 타이틀 화면 리소스를 작업합니다.

**파일**

https://github.com/GG-Studio-990001/GameOver/assets/144519956/b289e0f6-dc1a-4ee1-a33c-8370343a0cc0

[폴더](https://drive.google.com/drive/folders/1t-fEnjDGhnkUUhS2kaeBrgVKMBij9LRa?usp=drive_link)에 백그라운드와 필요 리소스 업로드했습니다. 외에는 영상처럼 먼지가 공간감 있게 둥둥 떠다니는 이펙트가 추가되었으면 좋겠습니다. 최대한 게임 리소스 느낌이 나게 실루엣을 만져봤는데 그렇게 보일런지 잘 모르겠네요?

**Comment by royalbluesm** [comment]
03/17 캐릭터 애니메이션까지 작업 완료했으나 배경 디테일 작업 조금 더 시간이 걸릴 것 같아 3/24까지 작업 연장하겠습니다.

**Comment by royalbluesm** [comment]
신에게 단 하루만 더 주십시오

**Comment by fkdl0048** [comment]
게임 분위기에 정말 잘 어울리기 디자인 하신 것 같습니다.. 게임 이해도가 점점 높아지시는..!

피드백은 실제로 적용된 리소스들을 보고 진행하면 좋을 것 같은데 일요일 회의 전에 플밍끼리 이야기 해보고 들고 갈 수 있으면 들고 가겠습니다!

*중간의 엑스칼리버 같은 검이나, 마리오 통관, 게임에 등장하는 자동차 등 디테일이 보입니다~*

**Comment by wooyn730** [comment]
1)
이전 버전은 UI(타이틀과 시작하려면 키 누르라는 텍스트)가 오브젝트들에 가려져 있는 걸로 되어있었는데, 이번엔 UI가 가장 바깥 레이어인 이유가 있나요?

2)
저희 기준 1920x1080인 걸로 알고있는데, 스프라이트들이 작은 것 같습니다.
아니면 의도하신 걸까요?

3)
리소스는 한 파일로 모아주시는 게 웬만하면 좋은데,
이번 파일의 경우
검은 오브젝트 따로, 라플리 스프라이트 4개 따로, UI 없이 주시면 좋을 것 같습니다.

(라플리는 라플리끼리 모아서 에디터 상에서 4칸으로 잘라달라하는 것이 가장 편하고,
폰트는 둥근모꼴이라면 그냥 텍스트 입력해서 사용해도 될 것 같기 때문입니다.)

4)
저번에는 오브젝트들이 엄청 커서 라플리와 UI를 가리는 구간이 있었는데
현재 버전이 깔끔하고 적당히 가려져서 좋네요!!

5)
저번에는 오브젝트들이 건축 자재 같았다면
이번에는 게임 요소처럼 보이는 부분이 많아져서 좋습니다.
(정안님 코멘트 보고 다시 보니까 더 잘보이네요 ㅎㅎ)

6)
오브젝트 리소스 loop 가능하게 위 아래 연결되어있는거 좋아요 👍

7)
먼지는 파티클 시스템으로 제가 한 번 도전해보겠습니다..!!

**Comment by Sumindd** [comment]
사운드와 아트를 한 번에 감상했는데 서로 너무 잘 어울리고 좋습니다. 검, 통관, 자동차도 눈에 띄고 너무 귀엽습니다!
저도 우연님이 1번에 쓰신 내용인 오브젝트에 의해 타이틀이 가려지는 포인트가 인상적이었어서 민지님의 의견 들어보고 싶습니다. 
완성된 모습이 너무 기대됩니다!!

**Comment by roweclaw** [comment]
게임의 전체적인 분위기를 타이틀 화면에 정말 잘 담아내주셨네요! 퀄리티도 배치도 더 좋아진 거 같고 게임에 적용될 때를 생각했을 때도 잘 어울려보입니다. 특히 실루엣에 검, 자동차 등이 추가되면서 은근한 복선을 깔아두는 것 같아 좋네요~!
