### ISSUE TITLE
240313 브랜드디자인 교수님 피드백 문서

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#345]
브랜드디자인 수업에서 교수님께 피드백받은 내용을 정리한 문서입니다. 우선 타이틀 화면, 플로야드 맵과 마마고 컴퍼니 내부의 스크린샷을 보여드렸고, 펀딩을 통해 상품을 판매하게 될 수도 있다고 말씀드렸습니다.

1. 아트적인 측면
> ![GGtown-Floyard_Preview_Realsize](https://github.com/GG-Studio-990001/GameOver/assets/144519956/d4abd0af-23c7-467d-aa49-3cde56052893)
> 
> ![Mamago_preview](https://github.com/GG-Studio-990001/GameOver/assets/144519956/b25fd2e3-e2b8-4250-a0ce-d0554e1e39a1)
> 
> **두 맵의 스크린샷을 보았을 때 같은 게임으로 느껴지지 않을 만큼 톤앤매너가 다르다.**
> 색감이 조금 비슷할 뿐, 슈퍼마리오처럼 어느 장면을 찍어도 같은 게임으로 느껴질 만큼 통일성이 있어야 한다. 우리 게임이 이질감과 서로 다른 그래픽의 충돌을 중점으로 두고 있다고 해도 일관성이 있어야 하는 부분에는 일관성이 있는 편이 좋다. 따라서 국소적으로 파란색을 사용할 거라면 외부 맵에도 파란색이 드문드문 들어가 있다던가...하는 편이 좋다. 

2. 게임 이름에 대해서
> **게임 오버라는 이름보다는 다른 이름을 생각해보는 것이 좋아보인다.** 
> 게임을 넘어서는 게임이라는 의미에서 게임오버라는 이름을 지었다고 말씀드렸으나 부정적인 이미지가 더욱 강하고 굳이 이 이름이어야 할 당위성이 부족하다는 피드백을 받았습니다. 주인공의 목적이 무엇인가? 라는 질문을 받아서, 어떤 세계에 떨어져서 모험을 거쳐 세계의 비밀을 풀어가는... 오즈의 마법사 같은 이야기입니다. 라고 대답했습니다. (근데 사실 대답을 하면서 저도 애매하다 느껴지긴 했습니다. 모험 자체가 목적인가? 자신의 정체를 깨닫는 것이 목적인가? 게임 자체의 목적은 있어도, 주인공의 목적 의식이 조금 흐릿하다고 느껴졌습니다. 도로시의 "집으로 돌아가야겠다"같은 강렬한 목적 의식 같은 게 있었다면...) 이 점을 확실히 하고, **주인공의 목적의식**과 관련된 제목을 짓거나, **이 세계의 이름**, 주인공의 이름 **RAPLEY**로 이름을 짓는 것을 제안해 주셨습니다.

아트나 게임 이름에 관해서 자유롭게 떠오르는 내용 있으시면 의견 나눠주세요. 참고로 저는 제목으로 '이 세계의 이름'을 사용하기라는 아이디어가 맘에 드는데, GG TOWN이라기엔 이야기가 마을에서만 진행되는 것이 아니기 때문에 게임 세계를 통칭하는 어떤 월드 이름이 있어도 괜찮을 것 같다는 생각이 듭니다. RAPLEY도 괜찮을 것 같아요. 

+추가
라플리의 원본 게임인 GG TOWN이라는 게임 이름을 활용해도 좋을 것 같은데, 아무래도 그... 게임 타이틀로서의 "느낌"이 조금 부족하단 느낌이 들어서 라플리가 주인공인 게임 "GG TOWN"의 명칭을 변경하고, 그걸 제목으로 활용해도 좋을 것 같습니다.

**Comment by royalbluesm** [comment]
신입분들도 자유롭게 코멘트 남겨주세요!! (저흰 신선한 아이디어가 절실한 상황입니다...)

**Comment by fkdl0048** [comment]
> 아트적인 측면

당시의 라플리에 의해 생긴 마마고 컴퍼니라는 내용으로 국소적인 색감을 요청드렸는데, 그레이스케일에 적은 색감(파란색이 눈에 띔)은 확실히 톤앤매너가 넘어가는 느낌이긴 하네요. 맵 전체에 파란색을 섞기보다 모든 장르에서 그러하듯 색감을 그레이스케일로 유지하는 게 좀 더 멀리보면 좋을 것 같습니다.

> 게임 이름에 대해서

저도 GameOver은 확실히 변경해야 할 것 같다고 생각합니다. 다른 게임과 같이 게임의 장르와 목적을 함축적으로 담은 이름이 필요한데, 아직은 좀 더 구체화가 필요한 것 같습니다. RAPLEY나 GG TOWN처럼 현재 게임 세계관처럼 네이밍을 해도 좋을 것 같아요. 개인적으론 RAPLEY가 좀 더 좋을 것 같습니다. (게임 이름 자체도 RAPLEY이며 플레이하는 캐릭터도 RAPLEY..?)

**Comment by royalbluesm** [comment]
게임 이름을 아예 이번주에 정하는 건 어떠신가요? 네이밍 피드백을 받고 싶은 마음도 있고... 신입분들 오시면 정하기로 했었는데 회식 때까지 각자 의견을 정리했다가 모인 김에 이야기 나누면 좋을것 같아요

**Comment by fkdl0048** [comment]
너무 좋은 의견인데요? 신입분들도 기획서 읽어보는게 이번 주 일정으로 지정해드리는 게 좋다고 생각하고 있었는데, 개개인이 기획서 읽어오고 회식 때 게임 이름에 대해서 이야기 해보면 좋을 것 같아요

가벼운 주제이기도 하고 좋은 이야기토픽인 것 같습니다!

**Comment by Sumindd** [comment]
[아트]
플로야드 쪽에 붉은색 자동차가 있어서 전체적으로 그레이스케일에 강렬한 포인트 컬러가 들어간 비주얼이라고 생각했고 제 개인적인 취향으로는 이런 방향도 좋다고 느꼈기 때문에
1)그레이스케일+포인트 컬러
2) 그레이 스케일
이 둘 중에 고르고 좀 더 방향성을 확실하게 가면 통일성에도 좋지 않을까 생각이 듭니다!  

[게임 이름]
저는 RAPLEY 이름 처음 보고 Replay나 Replicant가 떠올랐는데.. 혹시 라플리 이름이 어떤 의도로 지어진 이름인가요? 
이름의 뜻과 관련되게 지어도 좋을 것 같아서 여쭤봅니다.
일단 제목 자체는 RAPLEY도 좋은 것 같고요 RaPLey.. 이런 식으로 좀 변형 줘서 지어보는 것도 괜찮을 것 같습니다!

**Comment by jeongopo** [comment]
저는 아직 기획이나 아트의 의도나 전반적인 시스템을 잘 몰라서 그쪽 부분들은 진행하면서 피드백 해야할것같아요!
다른분들이 해주신 피드백들도 다 좋은 것 같습니다! 새 이름을 짓는 것도 찬성합니다!

다만 there is no game 처럼 게임 전체를 잇는 이름으로 지으면 좋을 것 같은데,
어느정도 틀이 더 잡히고나서 지어도 될 것 같다고 생각해요 ..!
너무 급하게 지을 필요는 없지 않을까 싶습니다 🤔

**Comment by wooyn730** [comment]
> 1. 아트적인 측면

아트가 전체적으로 통일성을 띄어야한다는 의견에 동의합니다.

비용을 생각하면 아예 그레이스케일로 통일시켜도 좋겠으나
"잊혀지며 점점 색을 잃어간다"는 세계관 특징을 생각하면 저는 일부분 색을 섞는 쪽에 조금 더 마음이 갑니다.
(수민님이 언급하신 빨간 자동차가 생각나기도 하네요. 저도 마음에 들었어요!)

마마고의 파란 벽, 초록 식물만 보고 생각하면 채도를 좀 더 낮추면 더 어울리지 않을까 싶기도 하고요..

> 2. 게임 이름에 대해서

게임 이름을 바꿔야 하는 건 맞으나
저도 현정님과 같은 의견으로 급하게 짓지 않았으면 좋겠고, 게임 전체를 관통하는 이름이었으면 좋겠습니다.

개인적으로 라플리는 반대...
라플리는 player의 애너그램(이자 replay의 애너그램) 아이디어로 시작했던 걸로 아는데
GG Town과 라플리 둘 다 게임 제목이 되기엔 아쉬운 느낌입니다.
또한 라플리가 사람인지 게임인지도 나중에 밝혀지는 요소라고 생각했기도 하고요..

이번 주말에 이야기 해보고 좋은 의견이 있으면 픽스하고,
아니면 좀 더 미뤄도 괜찮다고 생각합니다~~ (공모전 전에는 정해지면 좋겠지만)

**Comment by roweclaw** [comment]
> 1. 아트적인 측면

그레이스케일 톤일 때의 장점은 플레이어에게 '색'으로 힌트를 줄 수 있는 것이라고 생각합니다. 
예를 들어 플로야드의 자동차는 주위의 그레이스케일과는 다른 '빨간색'으로 플레이어의 시선을 자연스럽게 끌어내고 추후 퍼즐과도 이어지는 요소이죠.
다만 마마고 컴퍼니에서의 '초록색'인 식물과 '파란색'인 벽은 상호작용 요소가 아니기에 오히려 플레이어에게 '저거로 뭔가 하는 거 아니야?'라는 혼란을 줄 수 있지 않을까 싶습니다...
따라서, 식물과 벽의 색감은 그레이스케일로 맞추어 배경임을 확실히 하고, 조명을 키는 작업을 수행해야 하는 발전기에 색감을 넣는 것이 어떤지 제안해봅니다!

> 2. 게임 이름

저도 게임 전체를 담는 이름이 더 적합해 보입니다.
살짝 생각해본 거 던져보자면 '그리고'와 '더하기'라는 뜻을 가진 영단어 'AND'를 사용해서
- ANDing
- And in G
- And Game
- ANDventure
잊혀졌지만 아직 계속되고 있고 다른 장르들과 더해진 게임을 플레이한다는 의미를 표현하고 싶었습니다,,ㅎㅎ
같이 좀 더 고민하면 괜찮은 이름 나올 거 같아서 회식 때 다양한 의견 들어보면 좋을 거 같아요!

**Comment by royalbluesm** [comment]
챗지피티를 혹사시켜서 이름 후보를 몇개 뽑아봤습니다...
1. Lost Archive: 잃어버린 것들이 기록된 장소라는 뜻...개인적으로 archive라는 단어가 게임 전체를 관통하는 것 같다고 생각해서 가장 마음에 들었습니다. 단점은 줄여 부르면 로아가 됨
2. Knostalgia: 향수라는 뜻의 nostalgia에 묵음 k를 붙인 것. 잊혀진 것들에 대한 애상감을 자아내면서 검색하기도 편한 단어 같습니다.
3. Linker: 잇는 사람이라는 뜻... GG Town에서 모두를 잇는 사람이라는 의미도 되고 기억을 링크시키는 존재라는 의미도 되는것 같아요. 또한 게임 내 리소스들에 접속(link) 할 수 있는 능력이랑도 연관되어있는 것 같습니다.
4.  Gray World: 의미 그대로. 어렵게 생각하지 않고 그냥 심플한 이름이 좋은 느낌을 줄 수도 있을 것 같습니다.

**Comment by wooyn730** [comment]
4번 느낌 좋네요~~
심플하면서도 저희 특징인 그레이스케일톤을 잘 살린 네이밍 같습니다.

4번 좀 더 발전시키면 좋을 것 같습니다!!
(아직 좋은 아이디어는 없지만!)

**Comment by gomgom172** [comment]
> 아트의 톤앤매너 통일성 부분 관련해서

플로야드 맵과 마마고 컴퍼니는 오브젝트의 스케일적인 부분에서도 약간 차이가 있는 것 같습니다. 플로야드 맵은 스케일이 큰 실루엣 오브젝트가 많고, 마마고 컴퍼니는 오브젝트의 세부적인 디테일(컴퓨터, 복사기, 런닝머신 등 물체가 무엇인지 정확히 구별할 수 있는 디테일, 작은 스케일과 검은 아웃라인으로 처리된 아트 스타일)이 돋보이는 듯해서요.

이전 아트 회의에서 1챕터 백그라운드 디테일을 올릴 세부 오브젝트(파괴된 리소스, UI 잔해 등등…) 작업에 대해서 제안해 주셨는데, 제가 세부 오브젝트를 작업하면서 마마고 컴퍼니와의 톤앤매너를 맞춰 보면 어떨까 합니다. (작은 스케일과 검은 아웃라인으로 처리된 아트 스타일의 오브젝트로요)

걱정되는 부분
- 상호작용(조사) 가능한 물체로 보이지 않을지?
- 기존 플로야드 맵과 통일성 있게 어울릴지는 얹어봐야 알 것 같음.

요청드리고 싶은 부분
- 혹시 차후에 타 팀 측에서 1챕터 플로야드 맵에 추가되었으면 하는 오브젝트가 있다면 알려주시면 좋을 것 같습니다.
- 다른 의견 있으시면 편히 말씀 부탁드려요!

> 위 코멘트들 관련해서
- 전체적으로 그레이스케일로 통일하고, 상호작용이 가능한 물체에만 색을 넣자는 의견에 대해 동의합니다! 과감하게 흑백으로 톤을 통일하고 의도를 확실시하는 쪽이 플레이어에게 방향성을 명확하게 해 줄 수 있을 것 같고, 색을 찾는 연출에서도 보다 극적인 효과를 줄 수 있지 않을까 생각했습니다.
- 저도 4번 네이밍이 마음에 듭니다! 관련해서 발전시켜 보면 좋을 것 같습니다.

**Comment by fkdl0048** [comment]
다 좋은 아이디어라 조금 정리하자면..

`And Game`의 뜻인 `그리고`, `더하기`로 해석도 가능하고, `End Game`과 동음이의어로 이어지는 아이디어도 좋습니다.
`Gray World`말 그대로 색감과 아트를 보여주기에도 적합하기도, 그리고 회색지대의 말을 표현하기에도 좋은 것 같습니다. `회색지대` 아무도 하려고 하지 않는, 예매한 등을 어필하여 게임이 버려진 세상에 온 예매하고 기억되지 않는 게임들을 뜻하기에도 좋을 듯 합니다??

아마 만나서 이야기해보면 분명 재밌는 아이디어가 많이 나올 것 같습니다~!

**Comment by wooyn730** [comment]
(1) **Gray + 인간 지칭**

`Gray Wanderer(방랑자)`, `Gray Stranger(낯선 이)`
World, Zone 등 지역을 네이밍과 달리 '라플리'에 초점을 두기

*수빈님이랑 집 가는 길에 이야기해봤던 아이디어*

<br>

(2) **G로 시작하는 단어 + Gray**

`Gone Gray` `Going Gray` `Getting Gray`
줄이면 GG가 되는 이름
방금 떠올림

**Comment by fkdl0048** [comment]
Gray -> 빛이 바랜, 잊혀진, 사람들이 선호하지 않는 (회색지대)

**Comment by royalbluesm** [comment]
240320 3주차 수업 피드백
우선 제 과제물에 활용한 게임 가제는 GRAYED 로 픽스했습니다. 교수님께 통과받아서 이 안으로 진행할 예정입니다. 회색조의 느낌, 빛바랜, 흐려진, Gray였던... 이런 의미를 담고 있는 제목입니다. Gray라는 메인 키워드는 나왔다고 생각하여 우선 이 이슈는 클로즈 해두겠습니다~
