### ISSUE TITLE
폴더 정리

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#346]
구글 드라이브와 유니티 에셋 폴더를 정리합니다.
3/14 목요일 저녁에 시작해 자정 이내에 빠르게 끝내는 것을 목표로 합니다.

폴더는 챕터이름, 서브시스템이름을 가장 큰 분류로 두고
그 아래 각각 기획, 아트, 사운드 폴더를 둡니다.

**Comment by wooyn730** [comment]
24-03-14 21:20

구글 드라이브 1차 정리 완료
하지만 기획, 아트, 사운드에 컨셉 문서나 이전 버전의 문서, 또는 불필요한 문서들이 많음 (특히 기획...)
가능하면 작업자에게 각각 추가 정리를 요청하는 것이 좋아 보임.

또한 기획 문서는 메인 시스템과 서브 시스템을 모두 다루는 문서가 몇몇개 있어서
앞으로는 잘 분리해서 문서화하면 좋을 듯

<br>

현재 큰 분류는 이런 느낌 => [구글 드라이브 링크](https://drive.google.com/drive/folders/1AuqR6TALr7arVGaI9_ECUM91Yrqa6cgL)

*사실 제가 정리를 잘하는 편은 아닙니다
정리 아이디어 있으시면 환영합니다*

**Comment by wooyn730** [comment]
24-03-14 21:50

**유니티 에셋 1차 정리 완료**

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/22634731-10c5-46b1-8d01-277764582024)

드라이브와 마찬가지로 분류(챕터명, 서브시스템명)은 가장 상단에 위치시키기 위해 언더바 사용

폴더 정리만 했지만 혹시 부작용으로 오류가 생기지는 않는지 확인해봐야 할 듯

Scripts 폴더는 어셈블리 정의 파일 이슈로 정리 보류

**Comment by fkdl0048** [comment]
@wooyn730 구드는 확인했습니다.

깔끔하게 정리가 된 것 같은데 가능하면 개별 작업자에게 세부적인 정리, 네이밍을 요청해야 할 것 같네요

**Comment by wooyn730** [comment]
24-03-17 15:50

유니티 에셋 2차 정리 완료

- Prefabs 폴더 정리 (깜빡하고 빼먹음)
- 폴더명 복수형으로 통일
- 테스트씬 제거
- `this diff contains a change in line endings from 'lf' to 'crlf'.` 오류 해결
