### ISSUE TITLE
[CH1] 플로야드 맵 세부 오브젝트

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/GameOver#353]
- 오브젝트 목록 정리 및 작업
향후 챕터에 등장할 수 있는 아이템이나 오브젝트 등 정리하여 개별 투명화 파일로 제작합니다. 맵 위에 얹어본 후 추가 수정 있을 예정입니다.

**240323**

### 진행 상황

![object](https://github.com/GG-Studio-990001/GameOver/assets/162591960/3932740a-8b70-4292-a4a5-27d6b97c71d1)

![preview_ver2-export](https://github.com/GG-Studio-990001/GameOver/assets/162591960/38047dd1-2c0a-4f2b-83a5-9c1de727c878)

(아웃라인 수정본)
![preview_ver2-export](https://github.com/GG-Studio-990001/GameOver/assets/162591960/e144c606-d56d-4fcd-b0bd-33db2b3ad1c0)

스페이스 인베이더 / 마리오 / 갤러그 / 고전RPG (물약, 검, 보물상자, 골드) / 2D 횡스크롤RPG (햄버거 등의 HP 회복 음식) 등을 참고했습니다.

### 아트적 고민

마마고 컴퍼니의 오브젝트를 참고하여 같은 톤앤매너를 유지해 보려 노력하였는데, 아직 맵에 녹아들기에는 자연스럽지 못한 것 같습니다.

버려진 리소스라는 컨셉상 사선으로 꽂혀 있거나 아무렇게나 놓여 있는 구도가 가장 잘 어울리는데, 사선 8방향 테두리가 화면상에서 다소 튀어 보이네요. 조금 더 작업 진행해 보며 조정하겠습니다.

**Comment by wooyn730** [comment]
찾았어요~~~~~ ><

[[231026]세계관 컨셉 아트 속 요소 레퍼런스](https://docs.google.com/presentation/d/1gpxD9g-Yj97qAnwzfCFGxDQ7uzaz1pkcQhOayS9ALhQ/edit#slide=id.p)

**Comment by gomgom172** [comment]
### 진행 상황

![object](https://github.com/GG-Studio-990001/GameOver/assets/162591960/3932740a-8b70-4292-a4a5-27d6b97c71d1)

![preview_ver2-export](https://github.com/GG-Studio-990001/GameOver/assets/162591960/38047dd1-2c0a-4f2b-83a5-9c1de727c878)

스페이스 인베이더 / 마리오 / 갤러그 / 고전RPG (물약, 검, 보물상자, 골드) / 2D 횡스크롤RPG (햄버거 등의 HP 회복 음식) 등을 참고했습니다.

### 아트적 고민

마마고 컴퍼니의 오브젝트를 참고하여 같은 톤앤매너를 유지해 보려 노력하였는데, 아직 맵에 녹아들기에는 자연스럽지 못한 것 같습니다.

버려진 리소스라는 컨셉상 사선으로 꽂혀 있거나 아무렇게나 놓여 있는 구도가 가장 잘 어울리는데, 사선 8방향 테두리가 화면상에서 다소 튀어 보이네요. 조금 더 작업 진행해 보며 조정하겠습니다.

**Comment by fkdl0048** [comment]
일단 어제 회의에서도 그랬지만, 지금은 아트를 맞춰가는 단계라고 생각됩니다. 여러 도전을 해보시는 모습은 너무 배울 점인 것 같아서 아트쪽에서도 여러 시도를 해보는 것은 그대로 가져갔으면 합니다.

다만 지금 그려주신 오브젝트에서 걱정이 되는 부분들은 유저로 하여금 맵에 오브젝트가 위와 같이 등장한다면 (테두리가 명확하게?) 해당 오브젝트를 보고 바로 "게임 리소스구나!"하는 과정이 필요하다고 생각합니다. 그게 이 게임의 핵심이기도 하구요.

지금 검이나 물약의 형태는 충분히 게임 리로스로 인식이 가능하지만, 나머지 오브젝트들은 게임 리소스라기 보다 잔해에 가까운 것 같습니다. 게임의 메타적인? 이데아에 가까운 리소스들로 배치를 해야 게임에서 분해되어 나온 리소스구나에 가깝지 않을까 생각합니다.

또한 뷰에 따라 맵의 디자인이 변경될텐데 맵에 박힌 검 말고는 전부 맵에서 붕 뜨는 느낌이네요. 정확한 원인을 알고 싶은데, 아트가 아니라 문제에 대한 해결책은 제시하지 못할 것 같습니다. @royalbluesm 민지님과 이야기해봐도 좋을 것 같아요!

제 피드백이 도움이 되셨으면 좋겠네요

**Comment by Sumindd** [comment]
제 나름대로 아이디어를 조금 내봤습니다.. 실제로 적용 가능한 아이디어인가는 이우님이 판단해서 가져가시면 될 것 같습니다.

### 1. 각도의 다양화
> 버려진 리소스라는 컨셉상 사선으로 꽂혀 있거나 아무렇게나 놓여 있는 구도가 가장 잘 어울리는데, 사선 8방향 테두리가 화면상에서 다소 튀어 보이네요. 

이우님이 말씀하신 것처럼 아직 작업하신 오브젝트가 대부분 정면이어서 조금 어색해보이는 것 같습니다. **각도가 틀어진 오브젝트도 좀 섞이면** 붕 뜨는 느낌도 좀 줄어들지 않을까 싶은데 확실히 아트 직군인 민지님과 이야기 해보는 게 정확할 것 같네요.

### 2. 시대에 따른 디테일 다양화
**게임마다 시대 혹은 장르에 따라 그래픽 디테일이 다를 것 같아서 디테일도 더 다양하게** 만들어보는 것도 좋을 것 같습니다! 예를 들면 고전 게임은 픽셀 디테일이 적은데 최신에 나온 장르 게임의 리소스는 디테일이 더 자세하다거나.. 이런 식으로 디테일 챙기는 것도 재밌을 것 같습니다. 다만 이렇게 했을 때 통일성이 깨 수도 있을 것 같으니 아트분들의 판단은 필요할 것 같습니다. 아이디어로 참고만 부탁드립니다!

### 3. 리소스 간 크기 비례 무시 & 크기 다양화
전체적으로 크기는 좀 다양한 게 좋을 것 같습니다! 대부분 크기가 좀 작은데 더미의 덩어리는 큰 편이어서 어색해보이는 부분도 있는 것 같습니다. 어차피 다양한 게임에서 나온 리소스이기 때문에 **상대적인 크기 차이에 크게 신경 안 써도 될 것 같습니다.** A게임에서 나온 포션 리소스가 B게임에서 나온 자동차 리소스보다 커도 상관이 없다고 생각합니다. (제 개인적인 의견) 

### 끝내며
전체적으로 맵 기획이 아직 확실하게 나오지 않은 상황이어서 조만간 맵 기획이 나오고 맵 수정이 확정된 이후에 다시 세부 조율해보면 충분히 귀엽게 나올 수 있을 것 같습니다! 리소스 자체는 너무 귀엽습니다. 막막하셨을텐데 너무 고생하셨습니다!!

**Comment by wooyn730** [comment]
## 1. 톤

지금 현재 맵에 오브젝트 쌓여있는 곳이 밝은 곳/어두운 곳으로 나뉘어있는데 오브젝트는 한 톤으로 통일된 게 좀 더 튀어보이는 이유가 아닌가 싶습니다!

예를 들어 밝은 쪽에 배치할 오브젝트는 아웃라인을 밝게(연하게),
어두운 쪽에 배치할 오브젝트는 채우는 색을 어둡게(진하게)
하면 더 자연스러울 것 같습니다.

## 2. 오브젝트 다양성

그리고 저는 너무 게임 같은것만 있는 것 보다 지금처럼 다양하게 있는 게 좋아요!
게임에 '나 게임 오브젝트야'같은 것들만 있는 건 아니니까
지금이 자연스러운 것 같습니다~
(정안님 의견과는 다르게)

## 그 외

쓰다보니까 수민님 코멘트가 올라왔는데
크기가 다양한 거! 재밌고 좋을 것 같아요!!

**Comment by gomgom172** [comment]
다양한 의견 내주셔서 감사합니다!
가이드 없이 작업하다 보니 막막한 마음이 있었는데, 달아주신 코멘트들을 읽고 나니 보다 방향성이 잡히는 것 같습니다.
피드백의 중요성을 무척 실감했습니다…. (저도 좋은 의견 드릴 수 있도록 늘 정진하겠습니다!!)

### 진행 상황
우선 아웃라인과 밝은 곳/어두운 곳에 따른 명도 차이 정도만 적용해보았습니다.

![preview_ver2-export](https://github.com/GG-Studio-990001/GameOver/assets/162591960/e144c606-d56d-4fcd-b0bd-33db2b3ad1c0)

맵에서 붕떠보이는 느낌이나 상호작용 가능한 오브젝트로 인식되는 느낌은 많이 덜해져서, 명도 조절로 해결할 수 있을 것 같습니다.

또한 **밝은 곳 오브젝트, 어두운 곳 오브젝트**를 따로 제작하여 전달드리게 될 것 같습니다! (리소스 자체는 같음, 명도 차이만 O)

### 앞으로의 진행 예정
오늘 회의 진행 후, 말씀해주신 의견들 차용하여 작업 진행해보도록 하겠습니다.
(추가 피드백 언제든 대환영)

감사합니다!

**Comment by roweclaw** [comment]
### 1. 톤앤매너

검이 제일 자연스러워 보이는 이유는 검의 절반만 그려져 있어 맵에 박혀있다는 게 명확하게 다가오기 때문인 것 같아요. 나머지는 맵이랑 같이 봤을 때 따로 분리되는 느낌이 조금 있습니다. 그래서 다른 리소스들도 검처럼 보이지 않는 부분이 있어도 누가 봐도 검이구나! 하게끔 그려지면 더 좋을 거 같아요. 그리고 우연님 의견처럼 아웃라인을 살짝 연하게 한다면 맵이랑 잘 어우러지지 않을까 싶습니다!

### 2. 아이디어 제안

만약 그려야 할 리소스 종류가 너무 많아질 경우, 리소스들이 한데 모여 뭉치처럼 있는 더미를 만들어서 그 위에 오브젝트를 올려두는 것도 방법이 될 것 같습니다. 참고만 해주세요!

### 3. 오브젝트 다양성
저는 정안님 의견에 동의하는데요, 누가봐도 알 수 있는 게임 속 리소스로 구성하는 쪽이 더 좋을 것 같습니다. 떨어진 게임 리소스들은 유저가 파밍을 하거나 접속해야 하는 게임과 함께 맵에 놓여야 하는 오브젝트이기 때문인데요. 리소스를 클릭(상호작용)하게 될 때 '검이 낡게 부식되어 쓸모 없어 보인다...'와 같은 짧은 텍스트를 출력하자는 기획 아이디어가 나오게 되어 이를 가능하게 하기 위해서 입니다. 따라서 검이면 검, 물약이면 물약과 같이 게임 리소스라는 것을 명확히 알 수 있는 오브젝트로 구성하는 것이 어떨지 제안해봅니다!

---

적는 도중에 이우님 리소스가 새로 올라왔네요! 확실히 전과 비교했을 때 밝은 곳, 어두운 곳의 위치별로 리소스 명도가 다르니 더 잘 어울리는 느낌이 확 들어요. 앞으로 더 발전될 모습이 기대가 됩니다~!
