### ISSUE TITLE
[Title] 타이틀 화면 사운드 디자인

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/GameOver#354]
타이틀 화면에 맞는 사운드를 제작합니다.

------

제가 타이틀 화면을 보고 느낀 몽환 + 알 수 없는 + 떨어지지만 뭔가 무중력인 상태의 느낌을 살리고자 했습니다. 
우연님 의견대로 악기를 최소한으로 쓰고 앰비언스 음악 느낌을 살려서 제작해봤습니다!

민지님이 올려주신 애니메이션 영상이랑 보면서 같이 들어주시면 좋을 것 같습니닷

[타이틀 화면 사운드 디자인](https://drive.google.com/file/d/1YrwlMBJKVGbt68rFWz4GYYS1r2VsoX_z/view?usp=drive_link)

>  영상이랑 같이 올리고싶었는데 지금 제 DAW 이슈 때문에 ... 오디오가 같이 안 올라가서 영상이랑 같이 못 올렸어요 흑흑 ㅠ ㅠ 

피드백 받고 더 고쳐나가도록 해보겠습니닷 :)

**Comment by fkdl0048** [comment]
민지님과 마찬가지로 사운드도 적용된 상태로 볼 수 있으면 좋을 것 같네요! 일요일 회의 전에 가능하다면 둘 다 적용된 상태로 한번 보고 다같이 피드백 해보는 시간을 가져봐요!

지금의 몽환적인 사운드, 그리고 앰비언스(이거 맞나요?)가 깔리는 것은 너무 좋습니다. 이 방향성으로 잡으셔서 더욱 마음에 듭니다. 추가적으로 지금의 공허한 느낌에서 과거 작업하셨던 게임 리소스 사운드? (삑삑 거리는)를 넣어도 좋을 것 같습니다. 아주 작게 게임 사운드가 들리면 게임성을 설명하기에 좀 더 매력적일 것 같습니다..!

작업 고생하셨습니다~!

**Comment by wooyn730** [comment]
너무 좋은데요??

아트랑 분위기도 굉장히 잘 어울리고,
중간 중간 볼륨이 작아졌다 커지는 것도 마음에 들어요!

저도 정안님 의견과 동일하게 게임 사운드를 넣으면 좀 더 정체성이 살아날 것 같습니다.
_지금은 우주에 좀 더 가까운 느낌?_

**Comment by Sumindd** [comment]
아트랑 함께 감상해 봤는데 너무 잘 어울려요! 기화님이 느끼셨다는 몽환 + 알 수 없는 + 떨어지지만 뭔가 무중력인 상태의 느낌.. 전부 잘 살리신 것 같습니다.
저도 정안님, 우연님 의견에 대부분 동의하고, 특히 게임 사운드를 조금씩 노이즈처럼 섞어 넣으면 게임이 쌓여 있는 버려진 공간이라는 느낌이 더 살아나 좋을 것 같습니다.

그리고 만약 챕터별 메인화면을 다르게 가는 것이 확정된다면 이스터에그(작은 스포일러?)처럼 각 챕터의 대표 sfx를 살짝 섞어 넣어도 재밌을 것 같습니다!

**Comment by roweclaw** [comment]
몽환적인 느낌과 앰비언스, 그리고 살짝 메아리처럼 어딘가로 울려퍼지는 듯한 느낌이 타이틀 화면과 정말 찰떡입니다!
저도 다른 분들과 마찬가지로 지금 사운드에 게임sfx를 추가하는 의견에 동의합니다. 볼륨은 작게해서 간헐적으로 들리게 하면 좋을 거 같아요!

**Comment by Songkihwa** [comment]
먼저 다들 정성스럽게 피드백 해주셔서 감사합니다!!
좋게 들어주셔서 정말 감사해요 .. 다행이네요 ㅠㅠ

저도 사실 중간 중간 게임 효과음들을 넣을까..? 하다가 일단은 지금 상태가 좋아서 지금 작업물을 올렸는데
모두의 의견이 통일된걸로 보아 게임 사운드가 들어가는게 훨씬 더 좋겠네요!! 

게임 효과음은 넣는걸로 하고 어떻게 이쁘게 잘 묻힐지 고민 열심히 해보고 작업물 업로드 하도록 하겠습니닷 ㅎㅎ

> @wooyn730 네이밍은 바꿔뒀습니다! 저렇게 하면 될까요?!

**Comment by wooyn730** [comment]
편한대로 + 영어면 낫 밷이긴 한데
이왕이면 팩맘 때 네이밍이랑 통일해서
`(분류)_(BGM/SFX)_(번호)`가 어떤가 싶어요!

근데 생각해보니 지금 기획이 챕터마다 타이틀 바뀌는 거니까
사운드도 바뀔 가능성이 크니 네이밍에 챕터를 넣을까요?
`(분류)_(BGM/SFX)_(챕터번호)_(번호)` 이렇게

함 후보를 드리겠습니다!

1 )
`Title_BGM_CH1_01 / `Title_BGM_CH1_01 / `Title_BGM_CH1_01 ...`

숫자 늘려가며 버전 바꾸고 파일 중 파일명 마지막 숫자가 가장 큰 것(최신)만 사용

2 )
`Title_BGM_CH1_Tmp_01 / Title_BGM_Tmp01 / Title_BGM_CH1_Temp_01 ...`

Tmp/Temp로 임시 파일 표시 + 숫자로 버전 표시 후 확정되면

`Title_BGM_CH1` 로 사용

3 )
`Title_BGM_CH1_01 / `Title_BGM_CH1_01 / `Title_BGM_CH1_01 ...`

이렇게 쓰다가 확정되면 맨 끝 번호만 지우고 `Title_BGM_CH1`로 사용
(1번 + 2번)

4 )
`CH1_Title_BGM_01` 이런 식으로 1, 2, 3 중에 챕터번호 앞으로 땡기기

<br>

저는 쓰다보니 3번이 괜찮아보이는데요?? 어때여

++
언더테일은 모든 음악파일이 `mus_`로 시작한다고 합니다.

(근데 사실 저는 파일명으로 검색 잘 안하고 보통 파일에서 꺼내써서 상관 없음)

다른 분들도 의견 있으시면 환영임니다
