### ISSUE TITLE
구글 드라이브 폴더 정리2

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#355]
- #346 (이전 이슈)

<br>

기존 인원은 컨셉 등 현재 사용하지 않는 자료들은 1차로 [임시 폴더](https://drive.google.com/drive/folders/1AbfMAVzElU_xJLwpD-sPrDeSVuFavhw9)로 이동 후 재정리합니다.

정리 완료시 코멘트 남겨주세요!

**Comment by royalbluesm** [comment]
청소 완료했습니다. 실제로 게임에 적용되는 리소스들과 적용할 때 필요한 프리뷰 빼고 모두 임시 내의 안씀 폴더로 이동시켰습니다~

**Comment by wooyn730** [comment]
팩맘 아트 사용 안하는 거 임시폴더로 이동

기획 자료는 일단 남기기로..!!

**Comment by Songkihwa** [comment]
앗 저도 정리 했습니당
