### ISSUE TITLE
프로젝트 선행 작업 조사

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#36]
# 프로젝트 선행 작업 조사

프로젝트 시작 전 선행으로 적용해야 하는 기능 조사

## @fkdl0048 

조금 알아봤는데 현지화는 먼저 해야하는게 명확한데 세이브로드는 좀 더 고민을 해봐야 할 것 같습니다

이후에 보안, 서버, 데이터베이스, 퍼블리싱관련에 대해서 조사하는게 좋을 것 같고 지금은 new InputSystem, 지역화 조사하는게 ... 흠..

### ++ 23-10-14

- Addressables (에셋 데이터, 데이터 로드 등)
- Zenject, Burst (UI, DI부분 가능하면)
- Yarn Spinner(대화 시스템)

## @wooyn730 

- 대사를 어떻게 관리할 건지 (CSV, Yarn Spinner, 구글 시트?) 이야기 나눠보면 좋을 것 같습니다.
- 게임 개발을 최적화 하는 방법도 참고할 부분이 있다면 참고하고요
   - [참고](https://kr.object.ncloudstorage.com/unitykr-ebook/Unity_Games_Optimization%20Best%20Practices%20Folder_Korean_200603.pdf?utm_source=youtube&utm_medium=social&utm_campaign=korea_asuj-live_feb)

### 프로그래밍을 위한 것 외에는
- 폴더 구조와 폴더 네이밍 정하기도 하면 좋을 것 같습니다
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/7a5a9830-888d-43e0-b610-2db48e6b644b)
[좋은 말투??는 아닌데 찾다 보니 이런 글도 참고했습니다..](https://gall.dcinside.com/mgallery/board/view/?id=game_dev&no=61672)
- 아트, 사운드와 리소스 주고 받을 때 파일 네이밍 규칙도 정해야겠네요 (기획이 더 나오면 분류 방법이 더 확실해질 것 같기도 합니다)
- 몇월에는 데모 완성하고 몇월에는 펀딩하자~ 요런 얘기도 (물론 지켜지기 힘들겠지만) 임시적으로라도 일정 이야기 해봐도 좋겠네요! 

*(자꾸 ~하면 좋겠습니다로 문장을 끝내서 고치고 싶은데 쉽지 않네요;;)*

**Comment by wooyn730** [comment]
세이브/로드 고민해 봐야 한다고 하는 이유는 무엇인가요? 방법이 다양해서인가요 아니면 보안, 서버 등의 조사가 먼저 이루어져야 한다고 생각해서인가요?? 아니면 복잡해서?

**Comment by fkdl0048** [comment]
서버는 클라단위라 크게 상관 없을 것 같은데 아직 기획 초기단계라 저장될 데이터나 저장 시점이 불분명해서 그렇게 생각한 것 같습니다!

**Comment by wooyn730** [comment]
아하 알겠습니다~

**Comment by wooyn730** [comment]
조사 완료~

**Comment by fkdl0048** [comment]
https://sam-16930.medium.com/unity-project-structure-a694792cefed
