### ISSUE TITLE
[Title] 타이틀 프로토타입 개발

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#360]
# [Title] 타이틀 프로토타입 개발

## 개요

Title 씬을 생성 후 아트와 사운드를 적용합니다.
일요일 오후 8시 회의 전까지!

## 문제

1. 사운드 임포트 에러 ✅

![스크린샷 2024-03-22 232256](https://github.com/GG-Studio-990001/GameOver/assets/80298207/a78d926d-0750-401c-9742-5383deb44c06)

[해결책 1](https://gall.dcinside.com/mgallery/board/view/?id=game_dev&no=80720): 재부팅 => 안됨
[해결책 2](https://atvs.tistory.com/74): 사이트에서 컨버트 => 됨

_머쥐?_

## 결과

**짧은 버전**

https://github.com/GG-Studio-990001/GameOver/assets/80298207/b43ec222-d025-4d80-bbc0-55f94889aaf8

<br>

**긴 버전**
[구드 링크](https://drive.google.com/drive/folders/1_hBCjH0B1ADUbHD3IOxkYrybF4omqDAe)

_파일이 커서 구드행.. 화질이 별로라면 아직 동영상 처리가 덜 된 것일거에요~_
이건 아트와 사운드 루프 체크하시라고 길게 올렸습니다!

## 생각

사운드 끝날 때 쯤 조용한 부분을 자르면 루프할 때 좀 더 자연스러울 것 같고,
파티클 시스템(먼지)가 좀 더 고루 퍼져있으면 좋을 것 같습니다.

프로토타입이라 금방 만들었는데 파티클 시스템 다 까먹어서 공부 좀 해야 더 이쁘게 나올 것 같네요.
아니면 이 정도 먼지면 오브젝트처럼 스프라이트로 받아서 loop해도 될 것 같기도 하고?

**Comment by fkdl0048** [comment]
@wooyn730 리소스 적용 전에 @royalbluesm, @Songkihwa 두분에게 미리 리소스 전달 형식 다시 한번 확인 하시는게 좋을 것 같습니다?!

**Comment by wooyn730** [comment]
@fkdl0048 
각 이슈에 코멘트를 남기긴 했는데 두분 주말 일정을 모르고, 또 금방 교체 가능해서
상관없이 작업 진행하려고 합니다!

이후에 수정해주시는대로 교체하겠습니다.

**Comment by fkdl0048** [comment]
오 회의 때 빌드를 보고 다같이 이야기 할 수 있는 것이 생겼네요~ 좋습니다.

*가능하시다면 회의 이슈에 해당 버전 달아주시면 좋을 것 같네요*

> 사운드 끝날 때 쯤 조용한 부분을 자르면 루프할 때 좀 더 자연스러울 것 같고, 파티클 시스템(먼지)가 좀 더 고루 퍼져있으면 좋을 것 같습니다.
> 프로토타입이라 금방 만들었는데 파티클 시스템 다 까먹어서 공부 좀 해야 더 이쁘게 나올 것 같네요.
아니면 이 정도 먼지면 오브젝트처럼 스프라이트로 받아서 loop해도 될 것 같기도 하고?

일단 파티클 시스템을 사용하는 것이 좀 더 효율적일 것 같습니다. 변경 가능성도 그렇고, 실제로 활용성도 더 높아서 민지님이 빌드본을 보시고 피드백에 맞게 수정하는 것도 좋을 것 같습니다.
