### ISSUE TITLE
시점 변환 연출 레퍼런스와 장르 재활용 아이디어

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/GameOver#362]
> 시점 변환 연출 레퍼런스

사실 엄청난 연출을 생각한 건 아니고.. 페이드인/아웃 없이 자연스럽게 시점이 변환되는 연출을 좋아해서 적어뒀습니다!
레퍼런스를 찾다 보니 2개의 장르를 통한 시점 변환 게임은 이미 다양하게 나와있는 것 같습니다. 
(★ : 레퍼런스의 중요도)

**1) 슈퍼 페이퍼 마리오 ★★★** 
https://youtu.be/TqaoxSlq_B8?si=6WvqWkyBBKi5eeAI
마리오의 횡스크롤+탑뷰

**2) FEZ ★**
https://youtu.be/tfpKTclOnfI?si=fO-Phi-bja4SCZU9
회전하는(?) 사이드뷰 게임

**3) 무한회랑 ★**
https://youtu.be/GybxIwfU4rI?si=0arou0p3pcCdMnZ_
3D 게임. 시점 변화를 통한 퍼즐

**4) 니어 오토마타 ★★★** 
https://youtu.be/TcUMiblh6K4?si=wZ4-GP8-u3V0Fuu4&t=259
3D 게임인데 시점 변화가 자연스럽게 매우 잦은 게임입니다. 플레이해 봤는데 되게 이질감 없고 자연스러워서 불편함보단 각 상황에 맞는 시점의 장점만 잘 살렸다고 느꼈습니다.
레퍼런스 영상에서도 슈팅게임을 3D로 플레이할 땐 장애물을 피하는 재미에만 집중하고, 사이드뷰로 변환한 이후엔 적의 붉은 공격을 가볍게 피하며 사격하는 것에만 집중하게 했다가, 탑뷰로 변환하고는 뱀서라이크 게임처럼 주변 파괴에 집중하게 만들었습니다. 슈팅 게임이라는 한 장르의 게임으로도 다양한 시점에서의 매력을 체험할 수 있도록 디자인되어 있어 한 번씩 참고 자료로 보시면 좋을 것 같습니다! 

4:25 | 3D -> 사이드뷰
4:50 | 사이드뷰 -> 탑뷰

+레퍼런스 찾아보다가 생각난 것) 유니티를 2D랑 3D 중에 어떤 걸로 세팅했는지 모르지만.. 혹시 3D 요소 (혹은 연출 요소)를 접목할 계획이 있다면 고려해서 세팅하는 것도 필요하지 않을까 싶습니다 (물론 알아서 잘 해주시겠지만!!)

> 서브 장르의 재활용

위에 적어주신 피드백을 읽다가 든 생각을 정리해 보면..
챕터별 서브 장르의 느낌보다는 서브 장르를 모든(혹은 다양한) 챕터를 아우르는 요소로 만들고, 메인 장르의 비중을 높여 메인 장르의 변화를 챕터의 분할 기준점으로 사용해도 좋을 것 같습니다.
서브 장르를 각 챕터에서 일회용으로 사용하기보단 누적으로 사용한다는 개념으로 만들면 될 것 같습니다.
그래서 같은 이야기로.. 수빈 님이 써주신 '귀속' 시스템 너무 좋은 것 같습니다! 이러한 방향으로 엮어서 재활용한다면 서브 게임의 깊이감도 생기고 좀 더 다양한 활용을 생각해 볼 수 있을 것 같습니다.

그리고 '접속'이라는 시스템을 보다 보니 슈퍼마리오64에서 액자 속으로 들어가서 해당 맵을 플레이하는 시스템도 떠오르네요!
https://youtu.be/Jkc33Hgf3xs?si=MjS77-6pDvXqwYxs&t=2495
41:35~42:10

+) 우연님이 적어주신 감상문... 1~2달에 한 번 정도는 기획 리뷰? 느낌으로 가볍게 쓸 수 있다면 써보겠습니다ㅎㅎ 다른 팀원분들은 이야기해 보고... 부담이 되지 않을 선에서! 작성에 생각보다 시간이 좀 많이 걸리긴 합니다ㅠ(저도 6시간 걸렸습니다..) 저는 원래 블로그 쓰는 걸 좋아하기도 하니 쓸 내용이 좀 쌓였을 때 한 번씩 적어서 공유해 볼게요! 깔끔한 기획서도 중요하지만 기획 회의를 항상 모든 팀원들이 참여하는 것은 아니다 보니 어떠한 흐름으로 이러한 기획이 나왔는지 글로 적어서 공유하면 이점이 많을 것 같습니다. 저도 이번에 별생각 없이 감상문을 작성했는데 생각 정리 및 기록도 되고 오히려 작성하면서 나온 아이디어도 많더라고요. 여러모로 느낀 것도 많고 여러분이 적어주신 피드백에 대한 피드백을 보니 좋은 아이디어도 많이 얻어갈 수 있어, 최소한 저에겐 작성에 드는 노력 대비 더 많은 도움이 되는 것 같습니다!

_Originally posted by @Sumindd in https://github.com/GG-Studio-990001/GameOver/issues/349#issuecomment-2015385971_

**Comment by gomgom172** [comment]
### 시점 변환 관련 레퍼런스

니어 오토마타

게임 내 ‘해킹’이라는 시스템도 한 번씩 같이 확인해 보시면 좋을 것 같아 첨부해 둡니다. 저희 게임의 ‘접속’에 가까운 시스템처럼 느껴지기도 하네요. 앞서 이야기하신 3D → 사이드뷰 → 3D와 같은 맥락의 시스템입니다. 
* 게임 내 캐릭터의 능력, 슈팅 게임 기믹을 활용해 대상 기기를 해킹한다는 설정. 특정 기기를 타깃으로 삼고 능력을 발동하면 미니게임이 시작되며 로우 폴리곤 맵으로 이동합니다. 미니게임이 끝나면 본 게임으로 복귀.
플레이 영상 https://youtu.be/5zcVU3L9DYs?si=5YuPAA3UNSCEk9gY

The Plucky Squire

* 이야기책의 페이지를 넘나들며 모험한다는 컨셉의 게임. 페이지마다 다양한 스타일의 게임 플레이를 제공한다고 하네요. 2D-3D 변환이 가장 큰 핵심 시스템이긴 하지만, 참고할 부분이 있는 듯해 달아둡니다! (이것도 ‘접속’ 혹은 슈퍼마리오64의 액자에 가까운 시스템 같네요.)
트레일러 https://youtu.be/RsNzIpp83u8?si=CknTUIyDyKZf2srR


### 별도의 타 레퍼런스

BABA IS YOU

앞선 기획에서 이미 보셨을 수도 있을 것 같지만! 최근 게임 레퍼런스 구경 중 기믹이 흥미로운 게임을 발견하여 덧붙여 둡니다. 덤으로 생각해 주세요.
* 블록을 밀어 진행하는 퍼즐 게임. 블록으로 구성된 게임의 ‘룰’을 새로 만들거나 없애서 진행하는 게임입니다. There is no game의 메타 기믹과도 비슷한 결이 있는 것 같네요!
트레일러 https://youtu.be/z3_yA4HTJfs?si=vSnvwUg_nOX6zniy
플레이 영상 https://youtu.be/wAJvK0ZcMEA?si=4dJ5UEgC343SGyGr


이슈가 생성되어 함께 달아둡니다!
