### ISSUE TITLE
Feat: 현지화(Unity-Localization)

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#37]
# Feat: 현지화(Unity-Localization)

각자 조사 내용 첨부, 실제 프로젝트에서 브랜치 따서 진행

<details><summary>정안</summary>
<p>

관련 영상

- [Localization Document](https://docs.unity3d.com/Packages/com.unity.localization@1.0/manual/index.html)
- [추천 영상](https://www.youtube.com/watch?v=VNhzMEsy7xc)

# 현지화를 위한 작업

- 여러 방법이 있지만 유니티에서 지원해주는 방법을 사용

Localization 패키지(자동으로 바인디되어 어드레서블 패키지도 같이 들어옴)

## 설정

![image](https://github.com/fkdl0048/ToDo/assets/84510455/01602966-6e51-4d3f-bd14-fd5b9043cfc8)

- CommandLine Locale Selector: 커맨드 라인에서 지역을 선택
- System Locale Selector: 해당 시스템(안드로이드에서 선택된 지역)
- **Specific Locale Selector**: 게임내에서 언어를 바꿈

Locale Generator로 사용할 언어파일을 만들 수 있음(따로 세팅)

Project Locale Identifier: 프로젝트에서 기본으로 사용할 언어 설정

Windows -> Asset Manangement -> Localization Table을 통해 테이블 설정 가능

### Table

![image](https://github.com/fkdl0048/ToDo/assets/84510455/5d5e25dc-0f3f-4190-9e7e-9b549134898a)

Localization Table을 통해 테이블을 만들면 설정된 언어에 따라 +1개의 테이블이 만들어짐(관리, 언어당 한개)

구조는 딕셔너리와 같이 Key와 Value로 이루어져 있음

각 언어에 대해서 메타데이터를 설정할 수 있고, 따로 언어의 value마다 하나씩 설정할 수 있음

### 적용 (Event)

![image](https://github.com/fkdl0048/ToDo/assets/84510455/b39d4016-a08b-4ae7-a90c-b0179ff7a98d)

string Reference를 통해 사용할 Key, Table을 설정하고 값을 직접 확인할 수 있음

해당 컴포넌트에서 Update String을 통해 변경할 String값을 이벤트로 설정가능

Runtime Only에서 -> Editor and Runtime으로 변경하면 에디터에서도 확인 가능

RunTime중에 이제는 오른쪽 위에 있는 툴바를 통해 언어를 변경 가능

오브젝트에서 직접 추가도 가능함

### Asset Table

string뿐만 아니라 지역에 따른 다른 Asset을 사용할 수 있음(sprite, audio 등)

해당 에셋의 점 세개의 설정으로 가서 rocalize를 누르면 맞는 이벤트를 생성해줌

### Localization Scene Controls

![image](https://github.com/fkdl0048/ToDo/assets/84510455/fe2473b9-9ad2-44a6-af0c-0e3bfc129e0f)

Windows -> Asset Manangement -> Localization Scene Controls

Editor단계에서도 언어를 변경하여 체크할 수 있음

**중요**

- TrackChange: 언어가 변경되었을 때 이벤트를 발생시킴

자동으로 인스펙터의 변경사항을 저장하여 이벤트로 생성해줌 즉, 에디터 단계의 직접적인 수정을 이벤트로 바인딩하여 기록

편리함

### Smart

내부 스트링에 들어가는 문자열의 경우 값을 받아와서 사용가능한 형태

"(Plaer_name)이 입장하셨습니다"와 같은 형태

만약 싱글플레이의 경우 플레이어를 전역으로 다루기 때문에 사용은 간단함

따로 variables Group을 만들어서 사용하면 된다.

![image](https://github.com/fkdl0048/ToDo/assets/84510455/d9b1742a-d98d-4bf0-95a9-66cbd1fa000f)

### Script

스크립트에서 접근하는 방법은 LocalizationSettings를 통해 접근

```c#
using System.Collections;
using UnityEngine;
using UnityEngine.Localization.Settings;

public class LocaleController : MonoBehaviour
{
    bool isChanging = false;

    public void ChangeLocale(int index)
    {
        if (isChanging)
            return;

        StartCoroutine(ChangeLocaleCoroutine(index));
    }
    
    IEnumerator ChangeLocaleCoroutine(int index)
    {
        isChanging = true;
        
        yield return LocalizationSettings.InitializationOperation;
        LocalizationSettings.SelectedLocale = LocalizationSettings.AvailableLocales.Locales[index];
        
        isChanging = false;
    }
}
```

- 지역화 초기화 기간동안은 변경이 불가능하므로 기다려야함
  - 해당 값은 LocalizationSettings.InitializationOperation으로 확인 가능
- 지정된 지역은 인덱스로 접근하여 변경 가능

다음은 데이터를 가져오는 방법

```c#
LocalizationSettings.StringDatabase.GetLocalizedString("Table", "Key", "current locale");
```

위와 같이 사용은 못하지만 예시로 사용할 Table에서 Key값을 넣고 현재 지역을 넣어주면 해당 값을 가져올 수 있음

## Extentions

가장 중요한 데이터 처리부분

두가지 형태를 지원 csv, google sheet

### CSV

![image](https://github.com/fkdl0048/ToDo/assets/84510455/65f3e6d4-74c2-445c-819d-ac91fec3364c)

- CSV 파일을 만들어서 사용

사용에 매우 간편하지만 보안에 취약하고, 수정이 불편함

이후에 좀 고민해보면 좋을 문제

table자체를 성격에 따라 분리하여 csv로 관리하면 매우 편할 듯 하다.

나중에 대화 시스템을 만들게 된다면 다른 패키지와의 결합이 가장 문제일 듯

</p>
</details>

<details><summary>우연</summary><p>

<details><summary>게임 로컬라이제이션 시 주의할 점</summary><p>

### [[게임번역/게임현지화] 인디게임 개발자가 게임을 현지화 할 때 참고사항 6가지](https://latisglobal.com/blog/%EA%B2%8C%EC%9E%84%EB%B2%88%EC%97%AD-%EA%B2%8C%EC%9E%84%ED%98%84%EC%A7%80%ED%99%94-%EC%9D%B8%EB%94%94%EA%B2%8C%EC%9E%84-%EA%B0%9C%EB%B0%9C%EC%9E%90%EA%B0%80-%EA%B2%8C%EC%9E%84%EC%9D%84-%ED%98%84/)
- 개발자가 사전에 현지화를 고려해야 하는 이유
1. 어떤 것은 특정 문화에서 부적절하거나, 공격적이거나, 심지어 불법일 수 있음
2. 개발 전에 현지화를 고려한다면 시간과 비용을 절약할 수 있음

- 현지화할 때 주의해야하는 사항
1. 모든 유니코드를 지원하는 폰트 사용 (깨질 수 있는 위험 방지)
2. 인게임 텍스트를 하드코딩하지 않기 (텍스트 추출이 어려움)
3. 그래픽 텍스트 사용 자제하기 (추출과정 시간 오래걸리고 번거로울 수 있음)
4. 원본 텍스트 품질에 확인하기 (번역가가 잘 이해할 수 있어야함)
5. 현지화 범위 정하기 (주로 게임 내 텍스트, 음성, 게임설명서 및 패키징)
6. 현지화 작업을 위한 충분한 시간과 비용 투자 (+ 기계번역보다 현지화 전문가에게 의뢰)

### [게임 현지화(Localization)을 하기 전에 알아야 할 모든 것](https://www.ptw.com/ko/lab/campaign-every-question-you-need-to-ask-before-localizing-a-game)
- 현지화는 게임 플레이어 기반을 확장하고 수익을 증진하기 위해 할 수 있는 가장 큰 일
- 현지화에 포함되는 것
   - 그림 변경
   - 새로운 포장 및 설명서 생성
   - 새로운 녹음
   - 사용자 인터페이스 변화
   - 문화적, 법적으로 민감한 부분 편집
- 잘못된 현지화
   - 그 시장 사람들을 불쾌하게 할 수 있음, 또 법적 표준을 위반하면 대상 시장에서 게임이 아예 출시되지 못할 수도 있음
   - 좋지 못한 현지화는 금전적으로, 그리고 회사 평판에 피해를 줌
- 현지화 장점
   - 현지화를 하면 더 많은 수의 대중에게 다가갈 수 있음
   - 더 많은 대중에게 다가갈수록 그 게임은 더 노출되고 유명해지고 많은 수익을 창출할 것임
- 현지화 비용을 절약하려면 변화를 줄여야함
   - 현지화 중에 중요한 게임 아이템 이름을 계속 바꾼다면 코스트 증가

### 가볍게 읽어본 것

- [2020-02-03 기획 정리, Localization 준비](https://team-samoyed.tistory.com/66)
- [게임개발일지 – 첫 실행때 언어선택](https://kyleplanet.com/?p=109) (이거 잼씀)
- [유니티 공식 로컬라이제이션 패키지에 대하여…](https://kyleplanet.com/?p=102)

개념적인 부분은 기획자 동호님도 쓱 읽어보시면
대사 작성 시 좋은 참고가 될 듯?

</p></details>
<details><summary>유니티 로컬라이제이션 패키지 사용 방법</summary><p>

저도 유니티에 가신 골드메탈님 영상을 보고 따라해봤습니다.
정안님이 정리하신거랑 같이 봐서 필기는 거의 안했습니다..^^
하다가 기억할 것들? 만 조금 캡처했습니다.

![화면 캡처 2023-10-14 195906](https://github.com/GG-Studio-990001/GameOver/assets/80298207/4df63288-0c07-47f9-9901-9f2d33a046f4)
피커 해제

![화면 캡처 2023-10-14 201248](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e83c0a6b-50f8-4d22-b776-1a8f414d37bd)
각자 자기의 Text를 할당해줘야되는데 여러개 선택하고 같이 설정하다가 에러남 ㅋㅋ.. (바보)

![화면 캡처 2023-10-14 201649](https://github.com/GG-Studio-990001/GameOver/assets/80298207/11993658-8de3-4c9e-be36-e868f38158da)
인스펙터 창에서 직접 Table Entry 추가도 가능

![화면 캡처 2023-10-14 202520](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0c6ce593-58a6-4fbb-9785-bb3bc1dff7d9)
Asset Table 스프라이트 넣어줄 때 왼쪽 아니고 오른쪽

![화면 캡처 2023-10-14 202744](https://github.com/GG-Studio-990001/GameOver/assets/80298207/7208782d-3ec7-42cb-84f4-f2b95a5e18b3)
Localize 바로 적용 가능

![화면 캡처 2023-10-14 203115](https://github.com/GG-Studio-990001/GameOver/assets/80298207/47e9bf67-dcdd-43d1-843d-199a9cc300e7)
![화면 캡처 2023-10-14 203157](https://github.com/GG-Studio-990001/GameOver/assets/80298207/68346e1d-500e-49ab-8d6a-9de4107271b5)
Editor and Runtime으로 설정하면 Localizaion Scene Controls로 Editor에서도 언어 변경 확인 가능

![화면 캡처 2023-10-14 203402](https://github.com/GG-Studio-990001/GameOver/assets/80298207/2fa4831c-24f0-41e2-a30d-e2800c0060ba)
TrackChange를 통해 언어마다 다른 값 적용 가능
(근데 현지화를 업체에 맡기면 어느정도까지 해주는 지 모르겠다. 텍스트 + UI 안의 텍스트만 번역해주고 이런 값들은 개발자들이 적용하는 건가?)

![화면 캡처 2023-10-14 205307](https://github.com/GG-Studio-990001/GameOver/assets/80298207/027ff840-a37a-4b8c-a60b-dab820dd53ff)
새 컴퓨터로 바꾸고 비주얼 스튜디오 2022 깔았는데 2022라 그런지 (아니면 패키지 추가해서??인가) 코드 추천 엄청 잘해준다
어색한데 적응 되면 편하긴 할 듯

CSV 파일을 사용할 경우 암호화는 어떻게 진행하는지
Google Sheets 사용 시의 단점은 무엇인지 확인해봐야할 듯

</p></details>

</p></details>

**Comment by fkdl0048** [comment]
- 23-10-14 정리, 토이 프로젝트 완료

**Comment by wooyn730** [comment]
질문

1. 커밋 메세지 평소처럼 썼는데 저도 이제부터 깃허브 커밋 컨벤션을 지키도록 해야겠죠?
2. 정안님은 커밋 메세지에 한글 쓰는 걸 지양하시나요??
3. 저 왜 이런 메일이 3개가 와있을까요..
![화면 캡처 2023-10-14 211133](https://github.com/GG-Studio-990001/GameOver/assets/80298207/53a66007-875e-42d5-8161-8698a4ccc839)
4. 브랜치 하나 더 파서 작업중인데 왜 브랜치 링크가 안될까요.. apply 눌러도 반응이 없는디
![화면 캡처 2023-10-14 211143](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9f29791f-cf3e-4c8f-839f-fd4f55ad832a)

**Comment by fkdl0048** [comment]
1. 커밋 컨벤션은 협업자와의 약속이기도 하지만 대부분 본인 스스로 나중에 꼭 필요하다고 생각되기도 합니다!

따라서 지금부터 습관을 잡아두는 것도 매우 좋은 방법이라고 생각됩니다!

메세지 규칙은 저도 아직 잘 지키고 있다고 생각은 안하지만 가장 중요한 작게 쪼개는 습관부터 시작하셨으면 좋겠습니다 (개인적으로)

*나중에 꼭 후회하더라구요..*

2. 넵! 한글을 쓰지 않으려고 합니다!

개인적인 영어 공부 목적도 있고 애초에 char제한 때문에 깨지는 경우도 있고 (현재 브랜치 `현지화`라는 글씨가 실제 동작에서는 /213/123/1232/13/212 이런식으로 깨집니다) 코드 자체가 영어이기 때문에 더욱 그런 것 같습니다.

개인적인 부분이라 한글로 작업하셔도 무방합니다!

3. 저건 CI/CD 작업할 때 아마 작업 실패한 것 같은데 자세하게는 모르겠네여 확인해보겠읍니다

4. gitdesktop인가요? 저도 이유는 모르겠는데 지금도 안되시는거면 디코로 봐드릴 수 있습니다!

**Comment by wooyn730** [comment]
저도 되도록 커밋 컨벤션을 사용하고 한글 사용을 줄여보도록 하겠습니다!

4. 요거는 현재 이슈에서 해보고 있었어요 브랜치는 깃허브 데탑에서 파고요... 
![화면 캡처 2023-10-14 212100](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e1a6b437-e8ad-4160-939f-84b14378f75a)
![화면 캡처 2023-10-14 212116](https://github.com/GG-Studio-990001/GameOver/assets/80298207/6f9d6f3e-2b0e-4c20-920d-07fa8ab2e691)

**Comment by wooyn730** [comment]
23-10-14 [22:00] 정리 완료, 예제 따라해보기 완료!
