### ISSUE TITLE
[Title] 타이틀 프로토타입 수정

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#371]
### 고칠 것
- 파티클 조정
   - 뭉치지 말고 골고루
   - 갑자기 화면 내 여러개 생성됨
   - 속도 일정해야함
- 작은 먼지는 오브젝트에 가려지게 배치
- 해상도 적용 이슈
- 유니티에서 적용하는 스프라이트 loop 확인 (스크립트 말고 기능)
- 오브젝트 스프라이트랑 스프라이트 사이 빈 공간 보임

_프로토타입이라고 작업 너무 대충했나.._

### 추가
- 민지님이 준 먼지 스프라이트 적용
- 아트/사운드 새로 나오면 적용

### 진행
- [x] 새로운 사운드 적용
- [x] 해상도 이슈 => 임시 처리
- [x] 오브젝트 스프라이트 사이에 빈 공간 => 살짝 겹치게 배치해줌 (최선일까?)
- [x] 파티클 조정

파티클A: 사이즈 크게, 속도 빠르게, 레이어 가장 높음
파티클B: 사이즈 작게, 속도 느리게, 오브젝트 이미지 뒤에 배치

++
오브젝트 sprite loop animation => 그냥 animation의 loop 기능을 말하는 건지? animation이 지금보다 나을지

해상도 이슈(16:9 유지, 그 외 검은 배경) => 다음주 작업 (팩맘 포함)

---

### 파티클 공부

처음부터 먼지 존재
=> Prewarn 체크

먼지가 네모로 보이게
=> Renderer - Material: Sprites-Default

화면 내에서 생성/소멸되지 않도록
=> Start Lifetime(입자 생명주기), Start Speed(입자 방출 속도) 조절

안 뭉치게
=> Emission - Rate over Time 값 줄이면 듬성듬성 나옴

[참고](https://flowersayo.tistory.com/22)

### 레이어

오브젝트 이미지가 작은 파티클보다 앞이어야 함

레이어 순서를 정하는 방법
- Pos Z
- Hierarchy 순서
- Sorting Layer
- Order In Layer

**해결 방법**
오브젝트를 이미지에서 스프라이트로 변경 후 Order In Layer 설정
(이게 맞나..)

[참고](https://blog.naver.com/PostView.naver?blogId=yoohee2018&logNo=220791044002)

**Comment by fkdl0048** [comment]
@wooyn730 우연님도 작업하실 내용 상세하게 기록 부탁드리겠습니다~
