### ISSUE TITLE
[Title] 시작 타이틀 리소스 수정

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#372]
**상세**
1. 라플리 애니메이션 프레임을 수정하고
2. 리소스 파일을 정리해 드라이브에 다시 업로드합니다.

**파일**
[Title > Art 폴더](https://drive.google.com/drive/folders/1t-fEnjDGhnkUUhS2kaeBrgVKMBij9LRa?usp=drive_link)에 넣어놨습니다. 기존 3프레임 애니메이션을 4프레임으로 수정하고 움직임을 자연스럽게 보완했습니다. 또한 유니티 엔진 내에서 사이즈 조절을 할 필요 없이 1920x1080 해상도로 리소스를 수정하여 업로드했습니다.

**Comment by wooyn730** [comment]
1.
사이즈 키워주신거 확인했습니다~ 좋아요

<br>

2.
이미지 분리해서 주신 것도 좋습니다.
라플리 스프라이트도 4칸으로 딱 잘 잘리네요.

<br>

3.
라플리 애니메이션 현재 버전은 더 깔끔하고, 자연스러운 느낌이 납니다.

하지만 이전 버전이 좀 역동적이었어서 상대적으로 정적이게 보여서 쪼금 아쉽네요
현재 버전은 떨어지기보다는 하늘에 떠있는 느낌에 가깝게 느껴집니다.
