### ISSUE TITLE
온라인 기획 비정기 회의, 2024-03-28 [20:00]

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/GameOver#373]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84775854/814cbcc6-2e9e-471c-abe0-8f3380b0de59)

- 튜토리얼 세부 플로우를 정리합니다.
- 플로우 중 3번, 6번, 7번, 그리고 장르 변환, 발전기 건설에 관한 자세한 기획을 합니다.
- 기획서 작성툴에 대해 이야기합니다. 
- 28일(목) 8시에 회의를 진행합니다.
- (수빈) 위 사항이 빠르게 마무리 될 경우, [장르변환 당위성 고민](https://drive.google.com/file/d/1NBzgtyJVzBh70mEGDpStOSsdx95RM7BG/view?usp=sharing)을 공유하고 논의합니다.

## 회의록

간단한 체크인

- [피그마](https://www.figma.com/file/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?type=design&node-id=0-1&mode=design&t=aqv2b74vxgpIzVHj-0)
- 세부 플로우 7번 제외 정리 완료. 7번은 마을로 진입하는 과정인데 장르팩과 관련된 사항이라 장르 변환의 당위성과 장르팩에 대한 설정을 기획한 이후에 정리하기로 했습니다. 
![image](https://github.com/GG-Studio-990001/GameOver/assets/84775854/a275f091-59b0-4043-89ce-3839add0206d)
막힌 부분에 대한 이야기와 플로우 정리는 이슈 따로 업로드 할 예정입니다.
- 기획 이야기/장르 변환의 당위성에 대하여 
![image](https://github.com/GG-Studio-990001/GameOver/assets/84775854/0627b124-25fd-44b3-9aee-5579bfa496c8)
'연결' 이라는 키워드로 이야기 해보자는 방향만 잡고 결론이 나지 않아 다음주 목표로 잡을 예정입니다.

**Comment by fkdl0048** [comment]
@Sumindd 수민님 가능하시다면 비정기 회의는 참석자를 위쪽에 Assignees에 등록해주시면 좋습니다! (저랑 수빈님이랑 수민님!)

**Comment by roweclaw** [comment]
장르변환 당위성에 관련한 고민을 본문에 추가하였습니다.
깔끔하게 정리된 문서는 아닙니다.. 저의 생각을 주절주절 적은 거라 읽기 힘드실테지만..
그래도 오늘 회의때 시간이 남으면 같이 논의해보는게 도움이 될 거 같아서요!
가볍게 읽어주시면 감사하겠습니다!!

**Comment by fkdl0048** [comment]
회의 전 내용 생각

라플리는 수동적인 존재 -> 게임이란 원래 수동적임

이 게임을 통해 자신이 게임이라는 것을 자각하게 되는? (라플리에 의해서)
하지만 이 게임도 결국에는 게임이라는 틀

장르란 표현의 양식으로 이 게임에서 사용된다고 본다. 메타적인 부분은 모두가 같은 것을 공유한다고 하더라도 시각에 따라 다른 차이가 존재하듯이 게임도 같은 메커니즘이라도 장르라는 다른 시각? 매개체를 제공함으로써 다르게 볼 수 있다.

이 게임에선 장르를 시각적 장치뿐만 아니라 제한점을 두고 있는데 제한점은 지금까지 플레이어가 살아오면서 경험해본 다양한 게임의 장르로 선사한다.
