### ISSUE TITLE
[CH1] 발전기 시스템

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/GameOver#374]
발전기 시스템 기획안이 2가지가 나와서 각 기획안에 대해 정리 후 피드백 받으려고 합니다.
어떤 기확안이 더 좋은지, 더 좋은 아이디어 혹은 아쉬운 점이 있는지, 자유롭게 피드백 부탁드립니다!
3/28(목) 기획 회의 시작 전까지 올릴 계획입니다. -> 240326 작성 완료
(해당 시스템 기획서는 설명을 위한 임시 기획서입니다. 자세한 시스템 기획서는 튜토리얼 흐름 확정 후 재작성 예정입니다.)

&nbsp;&nbsp;
&nbsp;&nbsp;

### 관련 시스템 : 마마고 컴퍼니 건설 시스템
![image 7](https://github.com/GG-Studio-990001/GameOver/assets/84775854/6e0b76ff-3eda-4c00-902c-fb0aaaa8bdd3)
_기존 기획서 이미지_

서브 장르인 SLG 장르의 UI/시스템을 이용하여 마마고 컴퍼니를 건설한다.
![Group 1](https://github.com/GG-Studio-990001/GameOver/assets/84775854/083e9278-130d-4332-9d66-73f4a027c9f4)
_건설 시스템 레퍼런스 이미지_  
  
&nbsp;  

### 발전기 시스템
**기존 시스템** : 레이싱 UI를 이용하여 라플리가 발전기 위에서 뛰는 애니메이션을 통해 마마고 컴퍼니의 불을 밝힌다.
**변경 시스템** : 튜토리얼 챕터에서 레이싱 장르를 삭제하고 **SLG장르**로 통일하여 발전기를 가동시킨다.

### 1안) 위치를 선정하여 건설
![Group 2](https://github.com/GG-Studio-990001/GameOver/assets/84775854/01433384-c25a-41b4-bc41-ec84a05a292d)
SLG장르의 건설 시스템 중 그리드를 통한 위치 결정 후 건설하는 시스템을 따온다.
다만 범위 이동이 가능한 그리드를 구현하기엔 요구되는 플밍 리소스가 크므로, 1번과 2번 자리 중 선택하여 이미지 좌우 반전만 해주는 가짜 그리드 시스템을 구현한다.
팩맘의 코인을 소비해 마마고 컴퍼니 오피스에 발전기를 설치한다. (발전기 리소스의 아트는 수정 필요할 것 같습니다.)

장점: 선행되는 마마고 컴퍼니 건설과 시스템적 통일감(위치 선택 기능을 추가한 동일 시스템)을 줄 수 있다.
   

&nbsp;&nbsp;
### 2안) 직원 고용
![image](https://github.com/GG-Studio-990001/GameOver/assets/84775854/fbf279a8-0be8-4ea3-bc06-6d8f99235b31)
_고용 시스템 레퍼런스 이미지_

SLG 장르에서 등장하는 고용 시스템을 따온다.
정지된 발전기를 가동시키기 위해 직원 고용을 한다. 팩맘의 코인을 소비해 마마고 컴퍼니 오피스에 앉아있는 앵무새 직원을 채용하고, 직원이 발전기에서 뛰는 애니메이션으로 발전기를 가동한다.

장점: 유머 포인트로 살릴 수 있다.

**Comment by Sumindd** [comment]
발전기 시스템 임시 기획서 작성 완료

**Comment by fkdl0048** [comment]
시스템 별로 이렇게 이슈와 해서 다른 팀원분들 볼 수 있도록 공지하는 것은 너무 좋은 것 같습니다. 계속해서 이렇게 마일스톤에 맞는 다양한 이슈가 생기면 좋겠네요.

제 생각엔 1안의 경우 새로운 리소스가 들어가고 그것에 따른 개발 비용이 들어가는 것이 단점이고, SLG장르를 통일성 있게 1번의 기믹이 아니라 여러번 사용한다는 느낌을 주기에도 좋은 것 같습니다. 2안은 조금 더 간단하게 처리가 가능하다는 것이 장점이 되겠네요! 개인적으로 2안이 좀 더 마음에 듭니다.

저는 회의 때 좀 더 자세하게 설명하겠습니다!

**Comment by roweclaw** [comment]
1안의 경우 SLG 장르의 건설기믹 플레이를 조금 더 이어갈 수 있어서 좋고, 2안의 경우 직원을 고용할 때 유머적인 스토리를 추가할 수 있다는 점이 좋습니다. 걱정되는 건 2안으로 할 때 직원고용이 일회성으로만 등장한다면 아쉬울 거 같아서, 추후 다른 챕터에서 언어팩 등과 관련해서 콘텐츠로 이어갈 수 있게 된다면 2안이 좋을 거 같습니다!!

**Comment by wooyn730** [comment]
저도 2번!

이유는 발전기 위에서 뛰는 앵무새 직원 애니메이션이 귀여울 것 같기 때문입니다 ^_^
개발하기도 좀 더 용이할 것 같고요!

> 직원고용이 일회성으로만 등장한다면 아쉬울 거 같아서

수민님의 이 의견도 동의합니다! 더 활용할 수 있다면 좋겠네요.

**Comment by gomgom172** [comment]
저도 2번이 더 마음에 들어요!
캐릭터성이나 유머코드 어필 쪽으로도 매력적일 것 같고 픽셀아트 UI로 구현되면 고전 타이쿤게임(때부자, 온천왕, 부티나살롱 같은 비비빅 계열 게임)의 향수가 느껴질 것 같아서 마음이 가네요. 한 표 얹어봅니다!

**Comment by Sumindd** [comment]
발전기가 필요한 이유가 레이싱 장르 UI를 활용하기 위함이었기 때문에 오히려 굳이 넣을 필요 없이 깔끔하게 삭제하자는 방향으로 이야기 되었습니다. 다만 2안에 대한 반응도 좋고 아이디어 자체는 활용할 여지가 많은 것 같아 다른 챕터에서 활용 가능하면 활용하는 방향으로 갈 것 같습니다. 피드백 감사합니다!
