### ISSUE TITLE
원샷 게임 후기

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#376]
# 부제: 걸어서 게임 속으로

## 게임 소개
- 게임명
- 게임 한 줄 소개
- 장르
- 핵심 요소 (키워드)
- POG
- 스크린샷

## 게임 돌아보기
- 재미 요소
- 아쉬웠던 요소
- 직군별 게임 분석

## 우리 게임 돌아보기
- 우리 게임과의 공통점
- 참고할만한 요소

**Comment by wooyn730** [comment]
**중요한 인물은 말할 때 초상화 보여줌 + 꽤 자주 등장하는 컷신**
쯔꾸르 게임인데도 감정이나 분위기 표현이 좀 더 잘 됨

**필요한 아이템을 직접적으로 말하지 않음**
(끈적하니 병에 넣을 수 없겠다, 깔때기가 필요하다 => 주사기 사용
(서명을 해야하니 펜(필기도구)를 가져와라 => 깃털과 염료 조합해서 사용)
창의력을 요하는, 좀 더 현실적인 느낌..? (1+1=2이 아닌..)

**맵의 특정 구역으로 가면 이동이 됨**
가장 가장자리가 아닌 중간 쯤에서 이동이 돼서 어색해보임

**빠른 이동 기능 제공**
맵이 매우 넓지만 한 번 가본 곳을 순간 이동할 수 있어서 편의성을 제공
(하지만 세계관에 녹아드는 기능을 아니고 그냥 편의를 위함)

**다양한 메타 요소**
거의 모든 캐릭터들이 유저를 인식함 (유저 == 신)
주인공이 유저의 이름을 계속 언급하며 말을 건다
특정 존재(개발자같은)가 게임 외의 새 창을 띄우고, 마음대로 컴퓨터에 문서를 생성함
(우리 게임에도 이런 요소 있으면 재밌을 듯) 

**뺑글뺑글 도는 양**
너무 귀여움 ㅋㅋ

**Comment by Sumindd** [comment]
### 기획 - 시스템

- 태양(전구)를 들고 있을 때와 들고 있지 않을 때의 차이를 시각적으로 보여주는 것이 재미있었다. 태양을 들고 있으면 새로 발견 가능한 오브젝트가 있다거나, 벽에 안 보였던 글자가 보이는 등. 스크립트/맵 디자인으로 차이를 연출해서 좋았다.
- 색약 모드를 설정창에서 지원하는 점이 좋았다. 좀 더 다양한 유저를 고려하고, 배려하는 것은 컨텐츠 개발자로서 꼭 가져야 할 자세라고 생각한다.
- 메타 게임인만큼 유저의 정보를 컴퓨터에서 수집해서 메타적으로 이용하는 것도 인상적이고 몰입감 있었다. 비밀번호는 게임 밖에 있는 '문서'에 있다는 스크립트를 준 후 실제로 비밀번호가 유저 컴퓨터의 문서 폴더에 생기는 기믹이 흥미로웠다. 
![스크린샷 2024-03-30 150758](https://github.com/GG-Studio-990001/GameOver/assets/84775854/1d6ff956-c106-48d0-9573-beb72d625531)

- 일반적인 스토리 게임에 꼭 등장하는 주인공의 동료롤을 NPC에게 주지 않고 유저에게 주었다고 느꼈다. 주인공인 니코가 유저(나)에게 이름을 부르며 계속 대화를 시도하고, 유저가 선택지를 통해 답변을 하며 소통을 하는 연출이 지속된다. 이 포인트 덕분에 유저가 주인공 니코의 모험에 좀 더 개입하고 집중할 수 있는 요소로 작용했고, 매력적으로 다가왔다.  
- 아이템 조합 시스템을 이용해 오브젝트를 원래 용도와 다르게 사용하게 유도한다. 예를 들면, 필기구가 필요하다는 스크립트를 전달한 후, 맵에서는 깃털고 잉크를 얻게 한 후, 조합해서 잉크펜으로 기믹을 해결할 수 있게 연출했다. 이를 통해 유저가 창의적인 오브젝트 사용 방식에 대해 고민할 수 있게 유도하고, 단순히 오브젝트를 찾는 것에서 그치지 않고 한 번 더 고민하게 만드는 기믹으로 이끌었다.


### 우리 게임과의 공통점
사각형에 다가가면 안 돼 - 색 있는 리소스엔 다가가면 안 돼 -> 역으로 강조하기
팩맘의 휘어있는 화면 연출이 생각났다.
![스크린샷 2024-03-30 141957](https://github.com/GG-Studio-990001/GameOver/assets/84775854/65eeb4f5-7dc7-4383-a5f7-cf1e73891a5c)


### 종합 평가
- '태양' (빛)이라는 요소를 아트/시스템/스토리 전반적으로 잘 녹여냈다고 느꼈다. 설정과 유기적인 시스템 구조를 선호해서 좋았다.
-  Grayed Game도 메타적인 요소를 독특한 시스템으로 잘 풀어낼 수 있으면 좋을 것 같다고 생각했다. 유저의 컴퓨터에 접근해서 정보를 수집하고, 게임에서 상호작용 요소로 활용하는 점이 재밌었다.

**Comment by royalbluesm** [comment]
게임 분석
### 그래픽
RPG 메이커 게임의 특성을 잘 나타내는 픽셀 아트 그래픽. 이미 더 고퀄리티의 개발 툴이 많이 나와있음에도 굳이 알만툴을 선택한 것은 많은 게임들이 그렇듯이 고전게임 감성을 되살리고자 하는 것이 아니었을까... 우리는 더이상 8bit 그래픽에 갇혀 게임을 개발하지 않아도 괜찮지만 많은 사람들이 도트 게임을 선호한다. 픽셀 수로 그래픽을 제한함으로써 유저의 상상력을 자극하고, 현실과 디지털의 경계선을 명확히 긋는 듯한 느낌. 메타픽션의 특성을 극대화하는 것처럼 보인다.

전반적으로 어두침침한 조명을 사용하여 전구나 반딧불 등 빛을 상징하는 요소가 돋보이는 것이 눈에 띄었다. 아무 이유 없이 그래픽을 어둡게 설정한 것이 아니라, 이러한 점들을 강조하기 위해서 선택했다는 점. 색=기억이라는 상징을 강조하기 위해서 이러한 기법을 참고해도 좋을 것 같다. 

어둡고 채도가 높은 색이 많이 들어간 그래픽이었음에도 보기 불쾌하다고 느껴지는 점은 없었다. 언더테일의 워터폴을 생각나게 하는 배경 그래픽. 

### UI
쯔꾸르 기본 제공 UI를 사용하면서 스킨만 정돈한 것이 생각보다 꽤 괜찮았다. UX적으로 불편한 부분이 없는 것은 아니었지만 (전구를 끼우는 방법을 한 눈에 알기 어렵다든가...) 기능 자체가 많지 않아 간결했고, 게임 분위기랑도 잘 어우러지는 그래픽이었다고 생각한다.

### 니코
가 귀엽다.

**Comment by gomgom172** [comment]
<img width="936" alt="스크린샷 2024-03-30 오후 2 15 07" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/33297f95-b0d4-4857-8a50-c72265d8a2d3">
<img width="935" alt="스크린샷 2024-03-30 오후 2 23 54" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/b9e7fa0b-07b2-4155-975f-9ec9c8950ffc">
<img width="824" alt="스크린샷 2024-03-30 오후 2 36 59" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/bb35f0fb-b6a3-4ffe-bb00-058f548c443b">
<img width="834" alt="스크린샷 2024-03-30 오후 3 26 42" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/09a64119-6a86-4c4e-b327-4150657b6ac8">
<img width="695" alt="스크린샷 2024-03-30 오후 3 29 28" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/cf3b32c8-0eb0-4054-9358-a5a156bd538e">
<img width="520" alt="스크린샷 2024-03-30 오후 3 58 06" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/96d994fd-78af-45be-8ed4-8029b9a5c1ac">
<img width="663" alt="스크린샷 2024-03-30 오후 4 20 47" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/c3a5a8c8-8dd2-4816-9dac-a7428a43ba6b">


## 재미 요소
캐릭터가 플레이어를 인지하며 '구원자'라는 역할을 부여하는 흐름이 재밌습니다. 조사 스크립트가 캐릭터가 직접 플레이어에게 말을 거는 방식으로 출력되는 것이 인상적입니다. 인게임과 게임 바깥의 메타적 요소를 번갈아가며 퍼즐을 해결하는 방식이 독특합니다.

## 아쉬웠던 요소
맵이 상당히 큰데, 가장 큰 맵의 톤이 균일한 것은 좋지만 세부 맵이 길을 찾거나 위치를 구분하기에는 오브젝트가 너무 비슷비슷하다는 생각입니다.

## 아트
3군데로 나뉘는 큰 맵의 전체적인 톤과 설정이 마음에 듭니다.
가장 처음 스테이지는 메인 컬러 푸른색, 보라색 발광체를 자원으로 살아가는 세계. 황폐화되어 있는 정도가 심하고 기계 잔해가 대부분.

<img width="824" alt="스크린샷 2024-03-30 오후 2 36 59" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/3c30c29b-6dcb-424a-990d-ae4a7f778bae">

그다음 스테이지는 메인 컬러 녹색, 녹색 발광체를 자원으로 살아가는 세계. 사람과 식물이 남아 있고 목축을 주업으로 삼는 문화가 드러남.

<img width="663" alt="스크린샷 2024-03-30 오후 4 20 47" src="https://github.com/GG-Studio-990001/GameOver/assets/162591960/72380dc2-db38-4d3d-b18a-3b0a6b308dde">

태양이 사라진 세상에서 사람들이 다른 발광체를 대체 생활자원으로 사용하여 살아가는데, 해당 설정으로 자연스럽게 다른 색상 빛을 맵의 꾸밈요소로 사용하여 조화롭게 적용한 점이 인상깊습니다. (맵 전체에 배치되어 있으며 간단한 애니메이션이 들어간 발광 새우의 빛, 맵 전체를 느리게 이동하는 반딧불이의 빛 등) 설정을 녹여내면서도 맵 전체 퀄리티를 끌어올리는 요소로 잘 활용한 듯합니다.

## 우리 게임과의 공통점
플레이어블 캐릭터와 플레이어 간의 연결점. 플레이어의 존재가 캐릭터에게 (스토리적으로) 직접 영향을 끼침.

- 색약 모드가 인상적. 저희도 다양한 플레이어의 환경을 고려해서 게임을 제작하면 좋을 것 같아요!
- 뺑글뺑글 도는 양 너무 귀여워요

**Comment by roweclaw** [comment]
## 재미요소
### 도대체 이 게임을 하는 사람은 누구? 니코? 유저? 컴퓨터?
니코는 게임 세상 속에서 구원자이지만, 그 구원자는 신(유저)의 목소리에 따라 행동한다는 점. 그러나 유저 또한 게임 속 컴퓨터의 목소리나 힌트에 따라서 게임을 어떻게 플레이할지 파악하고 나서 진행이 된다. 이 게임은 대체 누구의 의지로 플레이가 진행되는 것일까? 아직 끝까지 플레이를 하지 못해 스토리를 다 알 수는 없었지만, 그 진상을 파악해나가는 재미가 있다.

## 아쉬웠던 요소
### 알아보기 힘든 맵 내 구역 이동 연출
맵 내에서 구역을 이동할 때 연출이 어디서 어디로 가게 되는 건지 명확하게 알지 못해서 불편했다. 나중에 빠른 이동 기능을 사용할 수 있게 되어서 보완이 되긴 했지만, 맵이 너무 넓고 길을 잘 모르는 사람이라면 매우 헷갈릴 수 있다. (집단지성의 힘아 고마워~)

## 직군별 분석 (기획)
### 인상적인 메타적 시나리오
실제 문서 파일을 컴퓨터에서 찾거나, 바탕화면에 힌트를 주거나, 유저의 이름을 게임 내에서 지칭하는 등 게임과 현실 간의 경계를 오가며 플레이했다. 니코의 대사 또한 자신의 세상 속 태양은 전구처럼 들고 다닐 수 없어서 지구의 태양과 비슷하는 것, 고양이가 아니라 어린 아이라는 점 등 그래픽으로 보여지는 모습과는 다른 존재로서 어딘가 살고 있다는 점을 알려준다. 즉, 게임 플레이와 스토리가 통일성 있게 이어져 깊은 세계관 속에서도 이질적이지 않게 게임 진행을 이끌어나가고 있다는 것이 특징적이다.

**Comment by wooyn730** [comment]
네이버 카페에 문서 업로드하였습니다! [(링크)](https://cafe.naver.com/bridge100/3498)

여러분이 남겨주신 코멘트 조합해서 간단하게 정리했습니다 ><
