### ISSUE TITLE
[All] Feat: new Input

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#38]
# [All] Feat: new Input

<details><summary>과거 기능 정리 및 공부</summary>
<p>

각자 브랜치 + 정리

<details><summary>정안</summary>
<p>

# New Input System

프로젝트 초기 세팅으로 작업하기 위해 정리

## 정리

해당 게임이 다양한 디바이스에 동작할 수 있도록 해주는 래퍼라고 생각하면 됨

설정창에서 설정하고 init하는 과정은 블로그 참고

- Action Maps
  - Scene마다 입력방법이 달라지거나, 캐릭터마다 달라져야 하는 경우
  - 현재 게임에서 챕터마다 달라질 수 있는 키로 지정하면 될 듯
- Action
  - 입력방법
  - 키보드, 마우스, 조이스틱 등
- Properties
  - 입력방법에 대한 세부 설정

## 사용

다양한 Input 바인딩 확인

플랫폼 지원이 후작업으로 가능하기 때문에 키보드만 생각하고 작업해도 좋을 듯

## 참고

- https://d-dl.tistory.com/139

</p>
</details>

<details><summary>우연</summary>
<p>

## New Input System이란?

New Input System은 유니티 2019.1버전부터 제공하기 시작한 말 그대로 새로운 입력 시스템이다.
유니티에 탑재되어있던 기존 InputManager에서는 여러 플랫폼으로 게임을 제작하기 위해 아주 많은 설정이 필요했다. (Jump를 만든다면 키보드 Space에 할당하고, 또 새로 만들어 조이스틱 A에 할당하고, 또 새로 만들어 기타 지원기기의 X에 할당하고…) 하지만 이제는 짧은 코드로 다양한 플랫폼의 입력 환경 지원 가능!

## New Input System 사용해보기

<details><summary>사담</summary><p>
브랜치 38-feat-new-input-woo 에서 작업을 하려고 했는데 정안님 브랜치가 PR돼서 그런지 왜인지 유니티를 켜려고 했더니 Project failed to open - This project is not valid 경고창이 뜨고 안켜졌습니다. 
그래서 그냥 새로 브랜치 38-feat-new-input-1-woo 파서 작업.. ^_^
</p> </details> 

저도 [[Unity] New Input System 입문하기](https://d-dl.tistory.com/139) 이 글을 참고했습니다.
새로 만든 InputActions 이름을 MainInputAction로 지었다는 걸 말 안해준거 빼고 아주 순서가 잘 정리되어 있었습니다.

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/5f9c7bc1-cf8c-4434-84c7-42f6745d47ae)
![화면 캡처 2023-10-14 234209](https://github.com/GG-Studio-990001/GameOver/assets/80298207/04d873e1-b59b-4797-9d58-5e293ce283f6)
2D 화면에서 검은 네모를 qwer과 방향 화살표를 입력받아 움직이는 프로젝트를 만들었습니다.

![화면 캡처 2023-10-14 234046](https://github.com/GG-Studio-990001/GameOver/assets/80298207/bc283a3a-950d-4d2c-a619-242f90ad3e5a)
![화면 캡처 2023-10-14 234107](https://github.com/GG-Studio-990001/GameOver/assets/80298207/a7298bda-00b2-44ac-9adb-bee2c81c21d8)
근데 저는 검색창?이 가려져서 잘 안눌리더라구요 왤까...

[[Unity][Error] InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings. 에러 이슈](https://j1-story.tistory.com/9)
그리고 [Edit] - [Project Settings] - [Player] - [Other Setting] - [Configuration] - [Active Input Handling*]을 Input System Package (New)로 했더니 위 블로그와 같은 오류가 나서 Both로 변경하였습니다..

### 그 외 읽어본 것
[Unity New Input System](https://wlsdn629.tistory.com/entry/Unity-New-Input-System)

### 생각?
유니티 Localization 패키지랑 New Input System 패키지 모두 낯설었지만 간단하게 적용해보니 그렇게 어렵지는 않았다. 한글로 안내하는 글들도 많아서 하면서 크게 어려움을 겪을 일은 없을듯?
근데 지금까지 공부했던 것 보다는 좀 더 많이 자세하게 공부하는 습관을 가져야겠다는 생각이 든다. 현중님 블로그 보고 깜짝 놀랐었음..

</p>
</details> 

</p>
</details> 

## 요구사항

- 현재 Input system의 UI와 Player로 구분되어 있는 Input에서 UI설정에 들어오면 Player Input을 금지해야 함
   - 해당 기능 브랜치 파서 작업
   - [x] #200

**Comment by fkdl0048** [comment]
23-10-24 정리 테스트 완

**Comment by wooyn730** [comment]
23-10-15 [00:30] 정리 완료, 실습 완료!

**Comment by fkdl0048** [comment]
저도 검색창부분이 잘 선택이 안되더라구요 유니티 버전문제인 것 같습니다..

오늘 알아본 작업들 말고도 정리하다 보니 좀 더 미리 적용해야 하는 부분들이 생기고 있어서 나중 회의때 전달 드리겠습니다!

추가로 개인적인 생각이지만 자세하게 공부하는 습관은 정말 좋은 습관이지만 공부하고 정리, 적용하는 과정 또한 하나의 비용이라고 생각하시면 좋을 것 같아요

모든 내용에 있어서 자세하게 공부할 필요는 없습니다. 이미 만들어진 바퀴는 이용만 잘하는게 좋기 때문에 다시 만들 필요는 없죠

따라서 프로젝트에 어디까지 필요한지에 대한 판단을 하는 눈? 기준을 키우는게 좋은 것 같습니다.

지금보다 적용하면서 만나게 되는 벽들이 더 많을 수 밖에 없으니 그 때, 경험적 학습을 다 한 뒤에 정리 하는게 나중에 가서 도움이 많이 되더라구요!

저는 개인적으로 Task로 남겨 두고 따로 어려움을 만날 때 마다 정리하고 있습니다

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/207f3e8e-5dda-4052-b650-fb3584502c30)

정리하자면, 자세하게 공부하는 것은 필요한 부분만 하는 것이 효율적일 수 있다. (학습도 비용이기에)

프로젝트 성격에 맞게 공부하면서 이론적인 부분보다 실제 적용하는 사례에서 오는 경험이 몇 배는 더 좋은 학습이다.

그런 부분을 정리해두고 나중에 보면 되게 도움이 많이 된다.

*물론 이 내용은 지금처럼 라이브러리, API등에 해당되는 이야기일 수 있습니다.*

되게 주관적인 부분이기도 하고 프로그래밍에서 이론이 더 중요한 부분도 있고, 경험이 더 중요한 부분이 있듯이..

강의 듣다가 듣기 싫어서 쓰다 보니 길어졌네요..

**Comment by wooyn730** [comment]
헉 좋은 말씀 정말 감사합니다 ^_^

**Comment by fkdl0048** [comment]
- https://github.com/GG-Studio-990001/GameOver/pull/233

해당 코드 참고
