### ISSUE TITLE
온라인 비정기 아트/기획 회의, 2023-10-13 [23:00]

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#46]
# 온라인 비정기 아트/기획 회의, 2023-10-13 [23:00]

기획회의 11시에 진행 후 11시 30분에 아트, 기획회의 진행

# 컨셉아트 기획

컨셉아트란, 게임속 세계관이나 환경 등에 영향을 받아 만들어지는 그림을 의미

- [블로그 글_1](https://m.blog.naver.com/wnrud948/220803299843)
- [블로그 글_2](https://heeddoen.tistory.com/65)

현재 게임에 컨셉아트가 매우 필요한 이유는 명확하게 존재했던 세계관이나, 유사한 문화가 없기 때문에 창조영역에 가까움

3가지 핵심 요소가 필요함

- 보여주고 싶은 세계관을 담아야함
- 변하지 않을 내용을 담아야함
- 게임의 전체적인 분위기를 담아야함

## 컨셉아트가 필요한 이유

- 분위기 설정
- 참조 포인트(참고)
- 일관성 유지
- 이해관계자에게 설명을 위한 자료

## 컨셉아트를 결정하기 위한 내용

아트 풍은 게임 자체가 장르에 국한되지 않기에 컨셉아트만의 아트스타일로 가져가도 크게 문제 없음

다만, 다음과 같은 사항은 지켜지면 좋음

- 블랙앤 화이트(명도는 조절)
- 게임이 주고자 하는 세계관
- 게임의 분위기

### 1번 아이디어

블랙앤 화이트는 그대로 가져가고 게임이 주고자하는 세계관에 맞게 압도적인 게임산을 보여주는 것

등장인물은 없는 것으로 처리하고 꼭 등장해야 한다면 흑백으로 처리

게임의 요소로 이루어진 산으로 특별한 세계관이 설명 가능하기에

분위기는 등장인물이 없고(있다면 흑백) 게임의 요소, 쓰레기의 산이기 때문에 당연하게 어두울 수 밖에 없음

차라리 압도감을 주는 듯한 느낌을 주는게 좋음

![image](https://github.com/fkdl0048/ToDo/assets/84510455/9f80d8f8-b8cb-4cc8-a43c-f0d0f1c31f39)
#### 문제점

- 너무 큰 비율 인물과 산의 비율이 너무 크게 나와서 그리는 비용이 너무 클 것 같음
- 산 전체를 게임의 요소로 채우기 힘듬
### 2번 아이디어

산에서 눈을 뜬 주인공 시점

리소스 홀에서 떨어진 주인공이 눈을 뜨는 순간

산의 모습을 1인칭 시점으로 보여주는 것

### 3번 아이디어

망가진 게임 UI

게임의 요소 중 하나인 UI창이 망가진 상태의 이미지

![image](https://github.com/fkdl0048/ToDo/assets/84510455/69ca8308-a080-4800-b4fd-61c34352989c)

블랙배경의 땅에 컬러감 있는 UI창의 이질적인 이미지

게임의 요소를 설명하기에 적합해 보임

### 4번 아이디어

![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/0323a35b-d738-414d-aa5f-295cd65ebd27)

저니의 형태로 마을의 형태나 산의 웅장함, 전체적인 비율을 보여주기에도 좋음

### 5번 아이디어

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/e257e72c-36fd-4792-b7a3-3457e7f4bfc3)

좋은 디자인 레퍼런스로 아이디어 자체도 비슷함

구도, 색감, 후처리등을 참고하기 좋음

#### 문제점

너무 이질적인 디자인으로 가면 붕 떠보일 수 있음...?

UI창의 디테일한 부분의 설계 미흡

### ETC

위 아이디어로 퀄리티가 좋게 나온 컨셉아트라면 충분히 활용 가치가 높음

단순하게 쓰고 버려질 느낌보다 지속적으로 활용될 가능성이 매우 큼

- 컨셉아트에 게임의 장르를 담기엔 너무 매몰되는 느낌이 듬
  - 컨셉아트라고 해서 메인시스템의 사이드 뷰나 쿼터, TRPG느낌을 담게 되면 해당 시점에서의 세계관 확장밖에 되지 않을 것 같다는 느낌
  - 세계관을 이해하기 위해선 어느정도 실제와 닮아 있는 것이 좋지 않을까?
  - 반대로 굳이 사용되지도 않을 아트 스타일을 사용해서 그릴 필요가 있나?..

## 회의 정리

컨셉아트 색감은 `그레이스케일`

같은 작업을 두명이서 하기엔 비효율적이라고 판단(화풍의 겹침)

따라서 오늘 기준으로 컨셉아트를 2안으로 나눠작업 세계관, 캐릭터

모든 작업 플로우는 한번에 다 그리는게 아닌 기획과 아트의 논의를 통해 진행

### ex) 세계관 관련

구도가 중요하기 때문에 생각할 수 있는 구도, 연출을 참고하여 러프하게 그림

이후 기획에서 들어가면 좋은 요소나 꼭 추가해야 하는 부분등 피드백을 진행하고 컨셉아트를 구체화함

이 프로세스를 반복하여 완성도를 올림

*현재 작업 프로세스는 위와 같지만 언제든지 변경될 수 있음*

### 작업 분할

- @royalbluesm : 캐릭터 컨셉아트
- @yanggang3 : 세계관 컨셉아트

셰계관은 1, 5번 아이디어로 진행

캐릭터는 기획을 읽고 이야기

### ++

현재까지 나온 컨셉아트 디자인 아이디어도 폐기하지 않고 이후에 구체화 진행

**Comment by wooyn730** [comment]
1. (컨셉아트 관련보다는 기획 관련) 초반에 산을 잘 보여주고 싶으면 사이드 뷰로 시작해도 좋을 것 같아요
2. 컨셉아트 3개라면 세화님 그리셨던 스케치(정안님 1번과 유사하다고 생각) + 정안님 3번 + 동호님 3번째 페이지(전체 마을 형태)

**Comment by CreatorLDH** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/0323a35b-d738-414d-aa5f-295cd65ebd27)

저니 컨셉 아트에서 착안해서,
'멀리서 보이는 높게 쌓인 산의 모습'과 흘러 넘친 게임들이 평야처럼 구성된 땅 (저니 아트에서는 모래 부분) 위에 서 있는 한 사람

**Comment by royalbluesm** [comment]
흑백인지, 그레이스케일인지

매몰된다는게 정확히 무슨뜻인지...이해가 안감

1안: 그리는것 자체는 가능하나 그린다고 해도 효과가 미미하다는 쪽에 가까움. 비용에 비해 효과가 좋지 않음

산을 져니처럼 표현한다고 해서 나쁜것같지않음. 멀리서 봤을때는 게임이라는 생각이 안들지만, 알고보면 게임이기에 웅장한 느낌은 그대로 가져감.

UI가 등장하는 컨셉아트는 존재하는 이유가 무엇인지? 컨셉아트인지, 게임 내 등장하는 컷신인지...

**Comment by CreatorLDH** [comment]
<img width="418" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/850d6d82-6cd9-4695-9b1b-7788235e586b">

3번 아이디어 평면에 평면보단 이런 입체적인 이질감은 어떨까요

**Comment by royalbluesm** [comment]
![컨셉아트구도아이디어](https://github.com/GG-Studio-990001/GameOver/assets/144519956/36c67ca4-d857-4481-ad84-56d49ce8fc66)
살짝올려둡니다~~

**Comment by Songkihwa** [comment]
4번 아이디어와 5번 아이디어로 진행하는 것도 좋아보이네요!
4번으로 전체적인 느낌을 보여주고 5번 구도로 버려진 게임 요소들을 클로즈업한 상태로 보여주면 우리가 원하는 느낌을 보여줄 수 있을 것 같다는 생각이 듭니당..!

**Comment by fkdl0048** [comment]
4번이 전체적인 느낌을 보여주기 적합해서 이후 기획이 좀 더 탄탄해지면 마을의 전체적인 느낌이나 쓰레기 산의 전체적인 형태를 보여주기 적합한 형태로 이야기가 된 것 같습니다! 이번 컨셉아트 기획안은 5번으로 정리가 되었는데 다른 아이디어도 괜찮아서 계속 디벨롭될 예정입니다!

**Comment by Songkihwa** [comment]
아하 -! 점점 틀이 잡혀가는 것 같아서 더 기대되네요 ㅎㅎ!!
