### ISSUE TITLE
캐릭터 구체화, 추가 NPC 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#50]
1. 전 주에 제작한 '라플리' 캐릭터 등 추가 기획 및 보완
2. 추가로 활용할 NPC 들 자료조사 후 기획 표 작성 (마을 주민, 상인 등)

https://drive.google.com/drive/folders/1Dyfgohz_Q9LkiHMICLO094bx0fZTD1Qb?usp=share_link

메인 캐릭터 라플리 / 게임 심마니 캐릭터 보완 완료
- 라플리 배경 설정 추가
- 게임 심마니 '달러' 레퍼런스 추가
기타 텍스트 보완 및 행동양식 추가

추가 NPC
- 게이머 컨셉의 상인 및 보조 NPC "트루커"추가 
- 광신도 컨셉의 일반 NPC "미카엘" 추가 

아마 챕터 1 후반, 2부터 극을 이끌 확률 높음.

추가 NPC 기획은 챕터 1 구체화 및 사건 플로우 추가 정리 후 기획 예정

**Comment by CreatorLDH** [comment]
**[비주얼 노벨 레퍼런스] / 그림체 참고용으로만 해주세요.**
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/75b2108e-428d-494f-bf0c-43a79b43f438)
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/ae8ea1b6-4972-4128-8e07-11e83bba9153)
![image](https://github.com/GG-Studio-990001/GameOver/assets/145998697/dc70b2e1-2cdc-4025-a8ef-d2721becddb2)

레퍼 찾기가 힘드네요(?)
좀 더 제대로 고려해보고 추가로 찾으면 올려드릴게요!
(안 올리더라도, 민지님 포폴에 있는 애니메이션 그림체도 좋아요..ㅎㅎ)

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/586a0049-2527-4076-b119-4a78e894104e)
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/09929352-ed72-489f-b140-239432a2cf97)
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/01b1bdf4-736a-48c5-86bf-dc3a48699031)

**Comment by CreatorLDH** [comment]
NPC 컨셉 아트를 인게임에서도 활용한다면 그레이스케일로 표현되면 좋겠네요. (특히 정안님 2번째꺼가 맘에 듦니다)
