### ISSUE TITLE
Feat: Addressables

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#54]
# Feat: Addressables

사용하게 될 필수 라이브러리 조사 후 토이 프로젝트 작업 해야함

<details><summary>Jeonglee</summary>
<p>

# Task: Addressable

리소스 -> 에셋번들 -> 어드레서블

기존 에셋관리 시스템은 해당 에섯의 위치를 중심으로 작동 ex) Resource.Load

기존의 에셋번들을 더 편하게 사용할 수 있는 툴이라고 생각하면 된다.

사용법은 key를 가진 group을 만들어서 쉽게 사용가능하나 이후에 반환을 위해 핸들에 캐싱하여 사용하는 것이 중요

두 가지 방법

```c#
Addressables.LoadAssetAsync<GameObject>("Assets/Prefabs/AddressablePrefab.prefab").Completed += OnLoadDone;
```

직접 주소를 참조하여 비동기로 불러오기가 완료된다면 이벤트를 등록하여 호출

```c#
[SerializeField] AssetReference prefabReference;

prefabReference.InstantiateAsync(this.transform); // 좀 더 간단
```

AssetReference를 통해 인스펙터에서 지정한 레퍼런스를 불러오는 방식

</p>
</details> 

<details><summary>Woo</summary>
<p>

<details><summary>Asset Bundle</summary>
<p>

어드레서블 에셋 시스템은 에셋 번들의 상위 호환(?)이라고 할 수 있는데
내가 에셋 번들에 대한 이해가 없었기 때문에 에셋 번들에 대해 먼저 알아보았다.
유튜브 영상이 정말 이해가 쉽고 도움이 많이 되었다.

### Asset Bundle이란?

에셋 번들은 에셋들을 일정한 규칙으로 묶어서 정리한 것.
에셋 번들은 따로 빌드하고, 에셋 번들에 포함되지 않는 나머지는 프로젝트 빌드 시 포함된다.
=> 최종적으로 빌드했을 때 총 용량이 줄어듦.

이렇게 빌드한 것은 최초 실행시 곧장 실행할 수 는 없고,
에셋 번들을 다운로드 해야한다.
=> 빌드 파일과 에셋 번들을 합쳐야 완성됨. 

플레이스토어에서 게임 다운로드 후 실행시 패치 파일 다운로드 받는 게 그 예시

### Asset Bundle의 장점

에셋 번들 사용 시 다음과 같은 과정을 거쳐야 한다.
에셋 번들 정리 -> 에셋 번들 빌드 -> 설치 후 에셋 번들 다운로드

과정은 번거로워 보일 수 있겠으나 이러한 장점들이 있다.
1. 용량
  - 스토어 용량 제한 등으로부터 자유로워짐
2. 패치
  - 통째로 빌드하게 되면 수정사항이나 추가패치가 필요할 때마다 완전히 재설치 필요
  - 하지만 에셋 번들 사용시 에셋 번들만 다운로드하면 변경사항 손쉽게 적용 가능

### Asset Bundle 사용 방법

1 )
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0320f8b0-d028-4966-9e3e-7ac003071e52)
Inspector 하단 부분에 Asset Labels를 누르면 Asset Bundle 설정 가능

2 )
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b5d91f7c-5574-488d-840c-78628716b7c2)
AssetBundleManager 스크립트 작성
이후 에셋 번들 빌드

3 )
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/aedf16db-79b9-42dd-ac90-118c1d4c94a0)
Hierarchy 창에 있는 오브젝트를 에셋 번들로부터 로드해서 사용하는 방식으로 변경
(Hierarchy에 존재하면 결국 빌드에 포함되게 됨)

4 )
번들 업로드, 다운로드 로직도 짜야한다...

+) 주의 사항
에셋 번들을 불러오면 메모리에 할당된다.
따라서 사용 후 게임 오브젝트 파괴 뿐만 아니라 메모리에 할당되어 있는 것을 수동으로 해제해야한다.
안하면 에셋 번들을 사용할수록 메모리가 가득 차서 프로젝트 다운 될 위험이 있다.
에셋 번들 사용했다면 **Unload 과정**도 필요

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/20b7ccb0-358b-4cc4-b92c-8be6d852f287)
*게임 프로그래밍 수업을 들을 때 SDL 라이브러리를 사용해서 C++로 게임을 만들었었는데 제출 전날 밤 샜는데도 메모리 누수 원인을 찾지 못해 감점을 받았던 무시무시한 기억이 떠오릅ㄴㅣ다..*

### 참고자료

- [초보자를 위한 에셋번들 - 개념 설명 및 기본 구현](https://www.youtube.com/watch?v=mC2d94bfI2w&ab_channel=%EC%98%A4%EB%8A%98%EC%BD%94%EB%94%A9)

</p>
</details>

<details><summary>Addressable Asset System</summary>
<p>

리소스 폴더 -> 에셋 번들 -> 어드레서블 에셋

어드레서블 에셋 = 에셋 번들의 장점(빌드와 번들의 분리) + 리소스 폴더의 장점(비교적 편리함)

### Addressable이란?

- 2018.2 이상의 버전부터 지원, Asset Bundle 기반
- Assets을 좀 더 효율적으로 관리하기 위해 새롭게 나온 시스템
  - 완전히 새로운 것 X 에셋 번들의 편의성을 개선하기 위한 시스템 O
- 에셋 번들과의 가장 큰 차이는 저장소로부터 에셋을 가져오는 방식
  - 에셋 번들은 로드 시 경로와 파일명 string으로 매칭하므로 변경에 취약함
  - 어드레서블은 에셋에 Address 부여(중개자 역할), 이를 이용하면 에셋 위치에 상관 없이 참조 가능

### Addressable 장점

- 에셋 빌드와 배포의 단순화
- 효율적 에셋 관리
   - 중복 에셋으로 메모리 낭비 방지
- 초기 빌드 볼륨 최소화
- 런타임 중 편리한 에셋 관리
- 개발의 편의성
  - 주소로 지정되기 때문에 코드 변경사항 줄어듦
- 빌트인 에셋으로부터 필요한 에셋을 업데이트하는 증분 업데이트 가능 (DLC)

###  Addressable 사용 방법

유튜브 썸네일에 유니티 중급자 이상!이라고 써있어서 쫄았는데(ㅋㅋ) 좋은 유튜브 영상 0~3편 참고해서 간단하게 따라해봤습니다.

![스크린샷 2023-10-22 190229](https://github.com/GG-Studio-990001/GameOver/assets/80298207/783f563d-e71b-4d66-be8d-f6b462d63217)
![스크린샷 2023-10-22 190239](https://github.com/GG-Studio-990001/GameOver/assets/80298207/058fb58a-39d7-4d5c-939f-bc715e105b76)
이미지 하나 Addressable로 설정하고 Load/Unload 해보기

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/3a504580-3cb5-4a3c-9f1d-ccbd9657c839)

![스크린샷 2023-10-22 185816](https://github.com/GG-Studio-990001/GameOver/assets/80298207/569f0b0c-b317-4847-8e3d-82e10aa64e13)
![스크린샷 2023-10-22 185917](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8c33e4e1-5d17-4f4b-bc56-1251f505499f)
![스크린샷 2023-10-22 185944](https://github.com/GG-Studio-990001/GameOver/assets/80298207/af066e75-3f0c-44d7-ae10-ca4dbf6ac731)
Window-Asset Management-Addressables에서
Settings에서 Send Profiler Event체크하고
Event Viewer 선택헤서 실행하면 에셋이 메모리에 올라가고 내려가는거 확인 가능

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b11314ab-24e7-4c74-9eb0-7a049b256be5)
프리팹 만들어두고 InstantiateAsync로도 생성 가능

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/64432fce-7ff1-4d90-80e0-dfa08eae8828)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b5ce9335-b37f-43ea-8d72-9f470ceda4e9)
ReleaseInstance 함수로 지우기

실행한 두 가지 방법은 [여기](https://planek.tistory.com/30)에서 1번, 3번에 해당
(어드레서블명으로 로드하기, AssetReference 클래스로 로드하기) (정안님이 적어둔 두 가지 방법과도 동일)

### 참고자료

- [어드레서블 에셋의 모든 것](https://devshovelinglife.tistory.com/398) 👍👍
- [Unity Addressable Asset System](https://young-94.tistory.com/47)
- [Addressable asset 기본 개념](https://codinggom-daily.tistory.com/43)
- [unity addressable asset(어드레서블) (유튜브)](https://www.youtube.com/watch?v=GsKofci_HSg&ab_channel=%EA%B0%90%EA%B7%A4%EC%98%A4%EB%A0%8C%EC%A7%80) 👍👍

</p>
</details> 

</p>
</details>

**Comment by fkdl0048** [comment]
23-10-29 조금 얇게 공부 적용 완

**Comment by wooyn730** [comment]
23-10-22 공부 적용 완료

**Comment by fkdl0048** [comment]
23-10-22일 개인 사정때문에 내일 작업
