### ISSUE TITLE
챕터 1 세부 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#58]
이제 시험 기간이 곧 종료가 되기에, 챕터 1에 대한 **진심 기획 예정**입니다.

1. 시스템 요소 확립
2. 상호작용 및 퍼즐 요소 확립
3. 사용할 아이템 및 세이브 포인트 등 생각할 수 있는 범위에 대한 기획
4. 그에 따른 유저 진행 플로우 작성
5. 챕터1 대화 및 퍼즐이 들어간 시나리오 작성

https://drive.google.com/file/d/18h3QgHHI9ZEIrd6daXnvZQNfaSpu5zCg/view?usp=share_link

흠 진신 기획을 했는 지는 모르겠지만,
챕터1에 대한 진행 방법이나 플로우는 확립했습니다.

픽스가 되면, 사용되는 시스템이나 퍼즐 방식을 위한 레벨 디자인과 시스템 기획에 들어갈 것 같습니다.
5번 대화 및 퍼즐이 들어간 시나리오는 사건 플로우로 대체했습니다. 왜냐하면 이해를 돋구기 위해 소설처럼 쓰려고 했으나 픽스가 난 후에 하면 좋지 않을까 싶어서 그랬습니다.

**Comment by fkdl0048** [comment]
@CreatorLDH 동호님 회의 잡아야할 것 같으면 연락주세요

@fkdl0048

**Comment by wooyn730** [comment]
방금 읽어봤는데 궁금한 점

1. NPC들은 자연 생성되는 건가요 아니면 다 리소스홀에서 떨어진건가요? 저는 후자인 줄 알았는데(NPC도 게임 요소 중 하나라고 생각해서) 후자라면 심마니는 모든 사람들을 인질로 잡는건지??

2. 게임 화면 크기에 대해 생각하시거나 정안/아트분들이랑 이야기 하신 적 있나요??

**Comment by fkdl0048** [comment]
인게임의 그레이스케일

게임에서는 색감이 있으면 좋을 것 같음, 라플리는 그대로 채도가 없는 그레이스케일이어도 좋을 듯

잊혀진 오래된 빛이 바랜 마을은 그레이스케일 형태, 접속한 게임 내부에서는 색감, 사용하는 UI, 게임 요소는 채도가 존재

1-1-3의 최대한 자유도를 주고 싶은 부분 동의

우리가 선형적 플레이, 강제적 플레이로 개발되어도 플레이어는 자유도를 느끼는게 중요하다고 생각

이어서 마찬가지로 튜토리얼을 최대한 쉽게, 유저가 직접 알아볼 수 있는 형태로 되면 좋을 듯

1-4의 비밀스러운 이스터에그 같은 부분을 이후에 설정하려면 적어둔 대로 모든 것을 보여줄 필요 없이 선형적 구조로 설계 후 이후에 추가 작업하는게 유리해보임

서브시스템의 접속 부분,

초기 기획은 서브 시스템이 메인과 완전히 분리된 형태라고 생각했는데 라플리의 특별한 능력이라면 메인시스템과 상호작용이 더 재밌어 보임

대신 더 세부적인, 디테일한 기획과 개발이 필요함

++ 더 재미있을 것 같긴 하다는 생각

서브시스템이라는 (게임에 라플리가 접속) -> 즉, 현재 GG도 라플리가 게임에 접속한 형태라는? 복선이 될 수 있을 것 같다는 생각

해당 서브시스템(_미니게임_)에서 라플리의 존재가 각인, 게임의 플로우에 맞게 등장인물이 되는. 색다른 연출이 필요

개인적인 세이브 시스템에 관한 생각은 큰 사건 위주로 저장이 되면 좋을 것 같음, 피로도가 없는 선에서 나름의 난이도와 클리어 가능한 선에 줄타기..

대화시스템은 개발 레벨에서 이미 라이브러리 사용 확정

기본 조작도 마찬가지로 다양한 키에 대응되도록 설정 완

- 소지품
	- 이 부분이 가장 예매한 부분이라 새로운 UI, 새로운 시스템에 대한 생각이 필요해 보임

그래픽 스타일은 개인적으로 도트

어느정도 보여주지만 보이지 않는 부분을 설계하기 위해 도트가 좋다고 생각

이번 기획양이 매우 많아서 비정기 기획 회의를 무족권 잡아야 겠네요.

너무 기대됩니다.

### 정리

1챕터는 총 3개의 서브시스템으로 구성

탑다운 시스템에서 팩맨(재화 코인), UI(마우스, 타이쿤), 로그라이크(전투)

작업 분배나 시스템 기획, 레벨디자인 관련은 회의가 필요해 보임

- 1챕터 내용이 잘 정리되고, 소설(시놉시스) 형태로 정리되면 이후에 활용하기도 좋을 것 같습니다 (대외적으로는, 스토리는 1챕터만 노출되니..?)

**Comment by CreatorLDH** [comment]
우연님 코멘트에 대한 피드백

1. NPC들은 버려진 게임에서 극히 드믄 확률로 생성되어 떠돌다가 마을에 합류한 경우도 있고, 본래 근처 거주민이 이주한 것일 수 있습니다. NPC들의 기원은 개개인이 다다릅니다. 

리소스홀에서 떨어진 캐릭터는 플레이어 캐릭터만이 유일무이합니다.

본래 심마니 집단은 가족이 없는 사람들끼리 모여 서로가 가족처럼 지낼 수 있게 도와주는 집단입니다. (그래서 캐릭터 설정을 다들 '혼자'로 칭함) 처음 플레이어 캐릭터는 리소스홀에서 떨어진 존재였기에 호기심이 강해졌으며, 추가로 마을 외적인 존재에 대한 거리감을 표현한 것일 수 있습니다. 그래서 인질(?)로 느껴지게끔 장난치는 거 같습니다. 추후에는 플레이어의 마을 정착을 도와주는 집단으로 보여집니다. (심마니 활동을 플레이어 캐릭터가 할 수 있는지에 대한 선행 미션같은 개념-> 추후 신입 심마니로 인정함)

2. 구체적으로 게임 화면 크기에 대한 이야기는 하지 않았네요. 일반적으로 사용되는 16:9 / 16:10 생각하고 있습니다만, 논의가 필요할 거 같습니다!

**Comment by Songkihwa** [comment]
저두 그냥 개인적으로 궁금한 점입니다!!

1. 팩맨 게임에서 얻는 동전이 마을 내에서도 쭉 사용하는 재화인가요 아니면 뒤에 나온 다른 게임처럼 그냥 UI를 획득한 개념인가요? 둘 다인가요..??!! 
2. 번역팩을 활용해 기계어를 번역해서 듣는다고 쓰여있는데 정말 플레이어에게 들리는건가요 아니면 화면에 번역된 글자가 나와서 보여지는건가요?
3. 게임을 한번에 클리어하지 못할 시 생기는 패널티 같은 것도 생각하고 계시나요?

**Comment by CreatorLDH** [comment]
기화님 피드백
1. 팩맨 게임에서 얻게된 동전 재화는 자연스럽게 시뮬레이션 게임에서 건축할 때 사용되는 재화로 소비되게끔 구상했습니다.
(추후 영향 없어짐)

2. 번역된 글자가 나오는 걸로 생각하고 있습니다.
기존 : 삐삐ㅣ지기지ㅣㄱㄱ기 QWER 직깁기기
번역 : 제대로 움직이려면 QWER를 눌러
=> 이 언어팩을 옵션에서 수정하면, 모든 NPC의 언어가 바뀌는 이스터에그 또한 구상하고 있습니다.
=> 가오갤 패러디, 아이엠 그루트 언어팩도 있을 예정.

3. 시스템 플로우 차트에서 확립된 후 설명드리겠습니다. 현재는 상황에 따라 게임오버 창이 뜨고 아니게끔 생각하고 있습니다.
팩맨 이미테이션 게임에서는 게임 오버 시, 기존 접속했던 게임 팩에서 던져서 나온 연출이 나오고 자연스러운 재도전이 가능하게끔 구현하고 싶습니다. 추후 로그라이크에서는 게임 오버가 정식으로 되지 않을까 생각합니다.

한 번에 클리어 못할 시에 대한 패널티는 현재 없습니다.
게임 오버 시는 자연스럽게 재도전을 유도하거나, 이전 세이브 포인터로 가게끔 설계 예정입니다.

**Comment by wooyn730** [comment]
[제가 이해한 기획 정리](https://woos-workspace.notion.site/b32e0a6ffe834b30a2b1feaea755c3cf?pvs=4)

@CreatorLDH 동호님 제가 이해한 기획을 정리해봤는데요,
시간 여유 되실 때 한 번 확인해주시고 편하신 방법으로 코멘트 주시면 감사하겠습니다.
(노션 댓글이라거나 따로 코멘트로 말씀해주시거나!)

방금 플밍 비정기 회의를 통해 정안님이 조금 말씀해주신 건 파란 글씨로 적어두었습니다. (받아적은거라 정확하진 않습니다...)

**Comment by CreatorLDH** [comment]
@wooyn730 

여깄습니다. 가독성이 좋을 지 의문이네요.

### **세계관**
- 우연님이 써주신 내용 맞습니다. 
- 아직 스토리 뒷부분과 옛날 이야기를 확립하지 못해서 100% 정답은 아니지만
1. 우연님말대로 오버플로우 등, 떨어지는 게임 요소들이 많아짐에 따라 위험성이 부각됨
2. 자원숭배조직과의 대립으로 인한 과거의 사상자 발생으로 인한 거주민들의 접근성 하락
위 이유들로 심마니조직이 주로 파밍하게 되었습니다!

### **심마니와 리소스 숭배자**
- 해당 부분은 추후에 디밸롭할 계획입니다.
자원 숭배자들은 '하늘에서 떨어지는 게임의 요소'를 축복으로 여기고 있습니다.
많이 내려오는 현재도, 축복이 많아졌다! 뒤섞임이나 관련 문제들도 그들이 내리는 축복이며, 메시지이다.
=> 축복이며 신의 메시지라고 생각하기에 해당 자원을 잘 사용하지 않는 세력으로 바뀌어 감.

그래서 이러한 자원을 막 사용하고, 개인 사리사욕에 사용하는 일반 거주민들을 배척하기 시작하며 분쟁이 일어남.

=> 그들은 점점 강경하게 행동하며, 이에 따라 여러 사건들이 발생됨.
=> 달러와 남은 거주민 무리들이 합심하여, 자원 숭배자 조직 잔당을 처리하고 그들을 마을 구석으로 몰아 넣음.

그 후로도, 자원을 주로 파밍하는 구역 플로야드(평야)에 자원 숭배자들이 들어와서 방해하고 분쟁을 일으킴.
달러가 대표로 내세워, 파밍 시간대를 나누기로 하며 조약을 맺음.

=> 추후 그들(자원 숭배 조직)의 세력을 하나로 규합한 하나의 캐릭터를 설정해서 게임 내 메인 스토리 이벤트로 연결할 계획.

//

### **1챕터 스토리 궁금한 점**
- 파머가 게임 스토리 상에서는 엄청난 힘캐입니다. 해당 캐릭터를 일부러 리타이어시켜 로그라이크(오류로 생긴 괴물) 처치에 활용되지 못하도록 설정했습니다. 
=> 과거 이런 현상이 일어났을 때 파머가 처리해주었으나, 파머가 어디있는 지 몰라 라플리가 나서서 처리한다는 설정

심마니의 일원은 주민의 일원도 함께 인정된다는 이야기입니다.
보통 자연스레 거주민이 되고 심마니가 되고 싶으면 그에 따른 테스트를 받고 심마니가 됩니다. (혹은 달러의 캐스팅)
라플리는 특이하게 마을로 들어왔기에 이 순서가 바꼈습니다.

엔딩 이야기는 많이 바뀔 거 같습니다.
원래는 본래 GG TOWN이라는 게임으로 되돌아오며 색을 되찾는 해피 엔딩으로 생각하고 있으나, 열린 결말이면 좋겠다는 의견이 많아 수정할 계획입니다~!

### **세이브**
- GG TOWN만의 UI를 최대한 배제해야 한다는 의견이 있기에 우연님 파란 글씨말대로 진행될 거 같습니다.

### **아트**
- 일단 아트 스타일도 계속 바뀌는 걸 희망하고 있습니다.
- 개인적으로는 언더테일과 민지님 도트 스타일로 희망하고 있습니다. (2등신 이하의 찐도트면 좋겠다는 의견도 있어 보이나, 아트팀의 의견도 필요할 듯 합니다.)
=> 추후 쯔꾸르 기믹을 활용할 때 쯔꾸르는 찐 도트로 될 거 같아서. (확정X)

### **컬러**
- 마을 주민들은 색이 없습니다. 그레이 스케일입니다.
플레이어가 라플리가 되어서 하고 있는 게임(GG TOWN)은 본래 그레이 스케일의 게임이기 떄문입니다.
위에서 떨어지는 게임은 기존과 다른 게임이었기에 색을 조금 나타낼 수 있지만, 시간이 지나면서 GG TOWN 게임 내 요소로 들어가기에 그레이 스케일이 되는 것이죠.

### **카메라**
- 맵 바깥은 배경의 확장으로 작게나마 보여줄 수 있지만, 지금은 우연님이 이해한대로가 맞습니다.

**Comment by wooyn730** [comment]
이해하는 데 큰 도움이 되었습니다 감사합니다!
