### ISSUE TITLE
Feat: Yarn Spinner

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/GameOver#59]
# Feat: Yarn Spinner

현재 Localization 관련해서 CSV파일 파싱이 가능한지 조사

다른 CSV형식의 대화 라이브러리 vs Yarn Spinner에서 자체 csv파싱 중 비용이 유리한 쪽으로 생각

### Yarn Spinner란?

게임 개발을 위해 만들어진 일종의 문법과 툴이다. 시나리오 라이터들에게도 쉽고 프로그래머에게도 강력한 기능을 제공한다.

게임 전체 시나리오를 대화식으로 간단히 표현하면 인게임에 바로 적용되도록 만들 수 있으며, 선택지, 변수 조작, 조건문, 다국어 번역, 마크업 문법, 음성 추가 기능까지 지원한다고 한다.

대표작은 Night in the Woods이며 MIT 라이센스 조항에 따른 오픈 소스이므로 무료 및 상업용 게임 모두 사용 가능하다.

### 조사하는 이유

좋은 대화 시스템을 만들기 위해 어떤 툴을 사용해야 좋을 지 조사해보는 과정을 겪고 있기 때문이다. 

Yarn Spinner는 슬쩍 봐도 쉬운 문법을 가지고 있는데, 유니티의 Localization 패키지는 CSV 형식을 지원하기 때문에 다음과 같은 것들을 고려해보고자 한다.

1. Yarn Spinner => CSV 파싱이 가능한지 (+ 쉬운지/적게 비용이 드는 지)
2. 파싱이 가능하지 않다면 Yarn Spinner에는 어떤 현지화 방법을 사용할 수 있는지
3. Yarn Spinner 외에도 다른 좋은 대화 시스템이 있는지
4. 결론적으로 어떤 대화 + 현지화 시스템을 선택하는 게 가장 좋을지

*보통 읽기 쉽게 한글로 된 포스팅을 주로 참고하여 공부하는데 한글 자료가 많이 없는 Yarn Spinner 조사하려니까 머리가 굳는다 흑흑*

### Yarn Spinner와 Unity Localization 함께 사용하기

참고자료의 (2)번 영상을 참고했다.
예상보다 그렇게 어렵진 않았다.

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/55d75665-be1c-42fd-bd40-f8c7801ac8d6)
Yarn 프로젝트에서 Use Unity Localization System도 가능하게 만들어두었고
3개월 전에 올라온 공식 안내 영상도 있었기 때문이다.

요약하면
1) Use Unity Localization System 체크 후 Yarn Project에 String Table 할당
2) String Table을 열면 이미 작성된 텍스트가 Base Language에 채워져있음
3) String Table을 CSV 파일로 Export
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/a5b4f9c7-a11f-46c9-aa51-9ae9c98dab1c)
4) CSV 파일에 다른 언어 채워넣기
5) String Table에 CSV파일 다시 Import

### 사용 방법

(1) 포스팅을 참고해서 따라갔다.
대부분 따라가기 쉬웠으나 현재 더 높은 버전이 나와서 다른 부분은 좀 헤맸다.
아직 Continue Action Type은 현재 버전에서 어디있는지 못 찾아서 일단 자동으로 넘어가게 설정해뒀다 흑흑...

### 결론

방법이 꽤나 쉬워서 Yarn Spinner + Unity Localization System을 사용해도 될 듯하다.
대신 Yarn Spinner 자체에 대한 공부가 더 필요하다.

### 기타

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0dc3959d-710f-45ce-ae6e-efb74b19e7ae)

VS Code에 Yarn Spinner extension 있음

### 참고 자료

(1) [[Unity] 선택지 있는 대화 시스템 Yarn Spinner 튜토리얼](https://d-dl.tistory.com/129)
(2) [Use Unity Localisation with Yarn Spinner 2.3!](https://www.youtube.com/watch?v=70DZ3UrUDec&ab_channel=YarnSpinner)
(3)[Upgrade Your Yarn Projects For Yarn Spinner 2.3!](https://www.youtube.com/watch?v=PQ24SOxytts&ab_channel=YarnSpinner)

**Comment by fkdl0048** [comment]
## 대안

- https://www.youtube.com/playlist?list=PLOZ3CbLbuxPwQvkDMBiIe4v1pTwAE380z
그래프로 표현하여 사용하기 좋을 듯 함

**Comment by wooyn730** [comment]
23-10-22 공부&적용 완료

Yarn Spinner랑 Unity Localization 함께 사용해도 좋을 거 같스니당

**Comment by fkdl0048** [comment]
1. 위 yml형식의 파일이 csv로 변형이 가능한건가요? 대사 자체를 엑셀로 관리하는게 좋다고 생각했는데 선택지 때문에 셀이 많이 늘어나거나 가독서이 오히려 떨어진다면 vscode로 작업해도 좋을 것 같네요! 좀 더 이야기? 우연님에게 설명을 듣는 게 좋아보입니다..
2. 적어주신 대로 Yarn Spinner가 생각보다 더 많은 기능을 지원해줍니다.. 저희 게임에 유용하다고 판단되는데 sample을 받아보시면 비쥬얼 노벨, 탑다운 등등 다양한 장르에서 사용할 수 있는 예제가 있어서 그걸 참고 하면 좋을 것 같습니다.
3. 최근 업데이트에서 저렇게 유용하게 지원하는지 몰랐는데 감사합니다. 버전이 오픈소스라 매우 빠르게 업데이트 되는데 만약 실제 개발이 시작된다면 버전을 fix 하는게 좋아보이네요. (개발기간 중 업데이트에 따라 충돌 문제가 생길 수 있으니)
4. 말씀해주신대로 Yarn Spinner을 잘 활용할 수록 개발 코스트가 적어지는 이점이 있어서 좀 더 뜯어보는게 좋을 것 같습니다. (현재 게임에서 가장 많이 사용될 듯 하고, 가장 고정된 형태라)
5. 가능하다면 현재 자동 빌드버전이 위 Yarn Spinner버전으로 열리면 좋을 것 같습니다. localization interation가능한 버튼으로 지역 변경도 가능하게 하여 회의 때 보여줄 수 있으면 좋을 것 같습니다. ++ 선택지도..

**Comment by fkdl0048** [comment]
++ 공부, 적용하시면서 문제가 되는 단점이 있었을까요? 대부분 라이브러리 플러그인의 이점도 좋지만 단점을 파악하는 것도 중요해서 궁금합니다!

**Comment by wooyn730** [comment]
1. 마지막 사진의 .yarn 파일을 말씀하시는 거면 맞습니다! 테이블에 한 번 넣고 export하면서 csv 파일로 변환 가능합니다.
2. 대사를 엑셀로 관리하는 게 좋다고 생각하신 거나  vscode로 작업해도 좋을 것 같다는 의견은 기획자님 기준 작업을 말씀하시는 건가요?
3. 아직 Yarn Spinner에 대해 잘 몰라서 단점도 크게 와닿지는 않는데 우선은 공부 자료 (특히 한글로 된 것)이 적다는 게 단점 같습니다. 다른 장단점은 더 공부해봐야 알겠습니다...

회의 때 보여줄 수 있도록 설정하고 PR 올리겠습니다~

**Comment by fkdl0048** [comment]
1. 오오.. export된 csv파일 형태는 중간의 사진과 같나요? 이 방식 두 번을 거쳐야 하는 거라면 자동화를 하는게 좋을 듯 하네요
2. 네 맞습니다. 저희는 파일 단위로 다루니 전혀 상관 없지만 대사가 매우매우 많아질 예정이라 가독성에서 뭐가 더 유리할지 고민이네요 선택지가 많다면 vscode로 보여줘서 문단을 줄여야 할 것 같고, 엑셀로 다루는 이점도 충분히 있어서 같이 고민해봐야 할 문제인 것 같습니다
3. 저도 사용할 때 자료가 적어서 sample이나 공식문서 보고 사용했는데.. 사용자 정의로 컨트롤 하는 부분만 충족된다면 문제 없겠네요!

**Comment by wooyn730** [comment]
맞습니다
![스크린샷 2023-10-23 011047](https://github.com/GG-Studio-990001/GameOver/assets/80298207/c7e88988-224a-4eeb-8851-22919c27c47f)
![스크린샷 2023-10-23 011054](https://github.com/GG-Studio-990001/GameOver/assets/80298207/688bc7b5-aff8-4635-9c8a-5420b62d8e8d)

자동화도 좋을 것 같습니다 근데 변환은 다른 언어가 번역이 완료된 후에 작업할 거라고 생각하면 먼 이야기 같기도 합니다

**Comment by wooyn730** [comment]
![스크린샷 2023-10-23 014033](https://github.com/GG-Studio-990001/GameOver/assets/80298207/50221888-a21a-48c5-b78f-18926ce832b5)
근데 지금 자동 빌드하면 이렇게 뜨네요...

![스크린샷 2023-10-23 014226](https://github.com/GG-Studio-990001/GameOver/assets/80298207/85e7181c-2848-4f2b-8e79-340062acfe33)
직접 빌드한 exe 파일 열면 이렇게 잘 뜹니다 ㅠ

어드레서블 에셋 빌드도 자동화 과정에 넣어줘야하는 걸까요?>
[참고 링크](https://hyeokjunjjang.tistory.com/entry/UNITY-Package-Localization-%EA%B0%84%EB%8B%A8-%EC%82%AC%EC%9A%A9%EB%B2%95) 이거 보고 에셋 빌드 따로 해주고 빌드했는데..

일단 GameOver/GameOverProject에 GameOverProject.exe로 실행파일도 같이 올리긴 했습니다 (실수지만)

![스크린샷 2023-10-23 013805](https://github.com/GG-Studio-990001/GameOver/assets/80298207/10a7d960-ecf1-4ded-a60e-7541aa50b163)
~내가 만든 게 바이러스라니~

**Comment by fkdl0048** [comment]
지금 확인해볼께요! 잠시만요

**Comment by wooyn730** [comment]
정안님 오늘 시험 아니신가요.. 안돼.......

**Comment by fkdl0048** [comment]
빌드만 확인했습니다..! 저도 똑같이 뜨네요 이거 Bug로 이슈 만들어주시고 다음 주 Task에서 해결합시다

**Comment by wooyn730** [comment]
네!!!!!!!!!!!!!!!!
