### ISSUE TITLE
Fix: NewControls.cs 중복 에러

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#65]
![스크린샷 2023-10-22 173007](https://github.com/GG-Studio-990001/GameOver/assets/80298207/2f090566-a71a-44da-8782-0cd96eb73777)

별건 아니고 Assets\Scripts\Runtime 폴더랑 Assets\Presets 폴더에 모두 NewControls 스크립트가 있어서 생긴 에러였습니다.

동일한 파일인 것 같아 Presets에 있는 파일 삭제하여 해결했습니다.
(함부로 지우기가 꺼려져서 한 번 여쭤봤었습니다)

프로젝트 구조 잘 정리해두셔서 저도 이거 다시 읽어봐야겠습니다.
[Unity — Project Structure Best Practices!](https://sam-16930.medium.com/unity-project-structure-a694792cefed)

**Comment by fkdl0048** [comment]
++ 좋은 구조에서 저번에 말한 것과 같이 이야기 하면서 계속 바꿔나가면 좋을 것 같습니다!

PR로 빼서 작업해주셔서 감사합니다! 

Lable은 bug만들어 둘테니 bug나 오류 있으면 lable걸고 나중에 취합해서 봐도 좋을 것 같아요!
