### ISSUE TITLE
Fix: Missing localisation ...

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#70]
- #59
comment 참고

직접 빌드한 exe 파일 실행시 오류 X
근데 자동 빌드 하면 다른 테이블은 괜찮은데 yarn spinner에 localisation 적용한 것만 missing 발생

(마일스톤 일단 이번 걸로 해두겠습니다)

**Comment by fkdl0048** [comment]
@wooyn730 간단한 tip인데 #59 양식 앞에 `-` 붙여주면 좀 더 이쁘게? 가독성 좋게 뜹니다.

- #59

**Comment by wooyn730** [comment]
헉 그렇게 쓰고싶었는데 앞에 - 를 안붙여서 숫자만 달랑 있던거였군요

감사합니다 ^_^

**Comment by wooyn730** [comment]
23-10-28 해결 완료!

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9b49af53-295c-494f-b1aa-47b2f84d84ec)

0. CI, Addressable, Localization 뒤져보다가 Yarn Spinner도 다시 봄
1. Add Line Tags to Scripts 버튼을 안눌렀다고 Warning이 떠있는 거 발견
2. 누르고 PR 했더니 한글은 되고 영어는 안됨
3. 그냥 yarn 파일로 테이블 다시 만듦
4. 됨

Add Line Tags to Scripts 버튼은 새로 만드니까 자동으로 눌려있더라고요?
Yarn 동영상과 포스팅에서도 누르는 과정은 없었는데
저번에 왜 안눌려있었고 왜 이번에는 자동으로 눌렸고 왜 안눌러도 프로젝트에서 빌드하면 되는지... 는 모르겠지만

1시간 반만에 해결해서 기분이 좋습니다

근데 그냥 테이블 새로 만들었어도 금방 해결 됐을 듯... ㅎㅎ

**Comment by fkdl0048** [comment]
자동 빌드에도 문제 없나요?

**Comment by wooyn730** [comment]
넵넵 자동 빌드로도 이상 없게 하는 것이 이번 목표였습니다
