### ISSUE TITLE
캐릭터 컨셉 아트 제작(NPC)

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/GameOver#72]
비정기 기획회의 후 NPC 캐릭터 3인 아이디어 스케치 
- #50 
- #76 
https://drive.google.com/file/d/1DJLkX4VT4BZbRURSoqh_Eo918sMs0qx_/view?usp=drive_link
마찬가지로 픽스되지 않은 아이디어 상태이며, 피드백과 보완을 거쳐 최종 형태가 나올 예정입니다.

**Comment by fkdl0048** [comment]
아트 피드백이 제일 어렵네요. 너무 미적인 영역이라 쉽게 말을 못하겠습니다.
*매일 코드나 기획만 피드백 하다보니..*

민지님은 어떤식의 피드백이 도움이 되시나요?
