### ISSUE TITLE
챕터 1 레벨디자인

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#75]
금주 비정기 회의 내용 바탕으로 진행 예정

1. 레벨 디자인 툴 확립 (러프하게 할 때는, 혼자 노트에 그려보면서 할 예정)
2. 맵 구조 및 오브젝트 위치 설계 (퍼즐 / NPC 위치 / 맵 이동 구역)
3. 맵 진행 방식 설정

//

[레벨디자인 + 마을 지도 변경안](https://drive.google.com/file/d/1pDm1MiGl8ZlmaRHdSLb7HGrWIxt8U8eY/view?usp=drive_link)

**주의 '러프'**

- 레벨 디자인 툴은 일단 이렇게 재량껏 나아가기로 했습니다.

이제 시스템 / 진행 플로우에 맞게 레벨 디자인도 같이 보완될 것 같습니다.

**Comment by fkdl0048** [comment]
- 마을을 탑뷰로 봐서 혹시 층고? 높이는 어떻게 생긴지 알면 좋을 것 같습니다?
- 대략 이해는 되었는데 자잘한 부분에 대한 궁금증은 회의 때 여쭤보겠읍니다..!

**Comment by CreatorLDH** [comment]
<img width="461" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/162e8132-492c-4f2e-8f1c-8f3814366749">

플레이어의 접근을 막는 형태의 높은 리소스 더미 지형은 이런 원근감을 주는 형식으로 생각하고 있습니다.

***

<img width="175" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/bad10683-0be0-44d5-b6b4-22e99193efa3">

<img width="430" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/ba621cf4-ca84-4342-ac83-eac62ad78787">

레벨 디자인 속 첫 3개의 맵 형태에서는 심마니들이 인위적으로 치어논 길이 존재하는데, 이는 위 사진(잔디와 흙길)처럼 연결되어 있을 겁니다.

더불어 R2-Mon 혹은 파머가 나오는 3, 5번째 레벨 디자인은 위 사진(잔디, 흙 대비)처럼 리소스더미가 있는 구역, 살짝 파서 치운 구역이 표현될 것이라 생각합니다.

***

알맞는 이미지를 찾지 못했는데,
리소스 더미를 판 자리를 표현 하고 싶었습니다. 아래 그림 참고

<img width="716" alt="image" src="https://github.com/GG-Studio-990001/GameOver/assets/145998697/4d39a3c8-f22b-49eb-8f61-77165c6b97d8">

이걸 위에서 본다면, 원근을 활용해.. 할 수 있지 않을까 생각이 듭니다.
(그레이 색 차이, 명암 등)
