### ISSUE TITLE
챕터 1 시스템 기획

### ISSUE THREAD

**Issue by CreatorLDH** [GG-Studio-990001/GameOver#77]
1. 기본 시스템 기획 (많이 할 건 없는 거 같은데 생각하기)
2. 서브 시스템 1(팩맘) 기획 
3. 서브 시스템 2(SLG 장르) 기획 => 퍼즐 부분이 강해서, 레벨 디자인 쪽과 연결될 예정
4. 서브 시스템 3 (로그라이크) 기획 => 아마 이게 많은 시간을 할애할 듯 합니다.

[챕터1 시스템 기획](https://drive.google.com/file/d/1_D_IsA__o-QPBjvJHx2ZBPLavR8Pqmwt/view?usp=drive_link)

시간관계상 PPT 디자인은 없으며,
추가로 로그라이크 장르의 몬스터 디자인은 차주로 넘어갔습니다.

감사합니다.
피드백을 받고, 개발용으로 수정 예정이고 부족한 부분 보완할 예정입니다.

**Comment by fkdl0048** [comment]
# 피드백

피드백을 할 때 사실 결과물에 대한 평가와 대안이 되는 요소나 다른 방향을 제시해야 하는데 모든 내용에 포함할 수 없어서 생략한 부분이 많습니다.

- 세이브-> 저번 회의와 같이 잊혀짐에 관한 요소로 해석되는게 좋은 방향인 것 같음 다만 언더테일의 오마주로 보일 수 있지만, 따라한 느낌이 날까봐 걱정. 
  - 아이디어: 플레이어가 라플리니 "플레이어가 라플리를 기억했다?"
- 마우스를 얻는 시기가 궁금합니다 (경로), 초기 지급인지?
- 명칭 정리는 회의 때 한번 공지 부탁드립니다
- 미니게임 시스템(A)는 아트적으로 얼마나 기존 팩맨과 다른 느낌을 주는지가 중요할 듯 (해당 미니게임의 세계관이 좀 더 구체화 된다면 유령, 타일의 컨셉이 정해질 듯)
  - 팩맘에 맞는?, 라플리가 게임에 접속했다는 느낌을 주기 위한 문서와 같이 라플리의 모습이 유령에 입혀진?
- A는 현재 기획서상으로도 완성도가 높으니 A쪽 컨셉 사운드 제작 Task
- B는 점점 방향이 잘 잡혀지고 있어서 너무 좋습니다. 최대한 방탈출 느낌이 나지 않도록 설계하는게 중요할 것 같네요
  - 이부분은 또 다시 회의를 통해서 좀 더 이야기 필요해보임
- 옵션 UI가 한개로 쭉 가는 방향을 생각중인지 옵션 UI도 변형이 있을 예정인지 ?
- 메인확장 시스템(C)의 경우 너무 많은 UI의 결합이라 플레이가 제대로 가능할지? 현재 시스템의 다양한 결합은 너무 좋지만 활용로를 플레이어가 인지하고 그에 따른 필수적인 요소가 필요해보임, 오히려 로그라이크에 집중하게 하는 방법도 좋을 것 같음 반대로 다양한 결합이 자연스럽게 진행되고 플레이요소에 필수적이라면 재밌을 것 같음
-  C의 경우 마찬가지로 로그라이크로 변환 (0.5변환? 뷰는 변하지 않지만 장르자체는 변환되는, 이후 챕터 2는 1변환 장르 자체의 변환)을 어떻게 보여줄 건지에 대한 연출이 가장 중요해보임
- 보스몹,일반몹은 그림이 안보이는데 아직 없는 거 맞나여?
- C 방어진지 아이디어 확장으로 터렛 설치도 좋아보임

**Comment by CreatorLDH** [comment]
### **[빠른 피드백 감사합니다]**
* * *
**피드백의 피드백**

1. 세이브 : 정안님이 말해주신대로 잊혀짐에 관한 요소로 짜고 있습니다. 지금은 라플리가 이 순간을 기억하기 시작했다처럼, 라플리가 자체적으로 기억하게 되어서 다음 접속 때 라플리가 기억한 지점에서 플레이하는 걸 전제로 하고 있었습니다.
=> 따로 UI나 대화창을 사용하지 않고, 상하단 여백에 "자동 저장중" 문구가 나오는 여타 게임처럼 "이 순간을 기억하는 중"이라는 문구가 나오게끔 생각하고 있습니다.
=> 문구가 나온다면, 세이브 때 문구가 나온 것이 아닌 '로드'할 때 문구가 나오는 걸로 특이점을 준다면 어떨까요?
"라플리가 지금 순간을 기억해냈다!" 처럼...

2. 마우스는 기본 지급되어 있습니다. 키보드처럼 일반 Iuput이죠. 하지만 사용하기 위한 마우스 포인터는 시뮬레이션 UI 획득 시 같이 생성됩니다. (마우스 아이콘 바꾸는 내용을 빼먹었군요!)

3. 명칭 정리 공지하겠습니다!

4. '이미테이션'이라는 느낌에 집중해서 그런지 미니게임의 세계관에 집중하진 않았습니다. 일반적으로 따라해서 색감을 바꾼 도트 그래픽을 그대로 따라가는 것으로 계획했습니다. 솔직히 팩맘이라고 해서, 유령대신 아이들로 대체하고 싶기도 했고 그에 따른 아이디어도 많았는데 그러면 미니 게임이 너무 확장되고 이미테이션했다는 느낌을 주기 어려울 거 같았습니다. 이미테이션 게임을 이상하게 만들어서 게임이 금방 잊혀졌다라는 느낌을 주고 싶었죠. 그래서 게임의 규칙이나 그런 부분이 어설프게 짜인 부분 또한 있습니다.

5. 컨셉 사운드 레츠 기릿

6. 소지품 관련 내용은 배제했고, 너무 선형적인 느낌이 강하긴 합니다만 실제 레벨 디자인을 해서 유저 경로나 순서 등을 고민하다보면 더 나아질 거 같습니다.

7. 옵션 UI는 변형이 없습니다. 그 때 받은 걸 쭈욱 갈 예정입니다. 

8. 억지로 합친 느낌이 저도 강하게 듭니다. 그렇다고 로그라이크의 추가적인 아이템 및 스킬, 몬스터 설계에 힘을 써서 로그라이크 느낌을 강하게 하는 것보다, 기존 사용했던 UI 및 방식을 재활용해서 나아가면 좀 더 효율적이지 않을까란 생각을 했습니다. 로그라이크 또한 게임 내에서 10분 이내로 짧게 즐기는 것이므로... (맵은 재활용합니다.)

신선한(?) 느낌이 들 수도 있어요. 마우스랑 키보드를 같이 쓰는 로그라이크.. 하지만 그만큼, 접근성이나 난이도가 어려워지기에 레벨 디자인하면서 좀 더 고민해보겠습니다!

9. 로그라이크가 가미되었다는 연출은 일단 영화적 연출을 생각하고 있습니다. 그에 따라 달려 있던 UI가 화면 밖으로 밀려나오고 자연스레 UI 변경 또한 유도할 수 있다고 생각합니다. 

챕터 2로의 변환은
1. 마을로 복귀해서 심마니들이 이번 탐사 때 모은 물건을 모아 놓다가 뒤섞임이 발생해 그래픽이 바뀜.
2. 로그라이크 플레이 이후, 마을 사람들에 환영을 받은 주인공은 휴유증으로 쓰러지게 되고 눈떠보니 장르가 변화되어 있음.
=> 챕터 2는 2D 비주얼 노벨 + @ / 챕터 3 횡스크롤 플랫포머 (사이드뷰) 예상중입니다.

10. 창의력 이슈로 쓰러졌습니다. 시간 관계상, 레벨 디자인 이후 금주 시간이 남을 시 들어갈 예정입니다. 아니면 다음주 이슈에 들어갈 거 같습니다.

11. 시뮬레이션 UI랑 알맞는 게 디펜스 계열이라 터렛 설치 저도 생각이 났습니다. 그래서 탄막 슈팅 형식의 로그라이크에서 '핵 앤 슬래시'나 '설치 디펜스 계열'로의 변경 또한 고민하고 있습니다.

**Comment by fkdl0048** [comment]
### 피드백의 피드백의 피드백

> 세이브 : 정안님이 말해주신대로 잊혀짐에 관한 요소로 짜고 있습니다. 지금은 라플리가 이 순간을 기억하기 시작했다처럼, 라플리가 자체적으로 기억하게 되어서 다음 접속 때 라플리가 기억한 지점에서 플레이하는 걸 전제로 하고 있었습니다.
=> 따로 UI나 대화창을 사용하지 않고, 상하단 여백에 "자동 저장중" 문구가 나오는 여타 게임처럼 "이 순간을 기억하는 중"이라는 문구가 나오게끔 생각하고 있습니다.
=> 문구가 나온다면, 세이브 때 문구가 나온 것이 아닌 '로드'할 때 문구가 나오는 걸로 특이점을 준다면 어떨까요?
"라플리가 지금 순간을 기억해냈다!" 처럼...

동의 완전 동의.. 저장의 경우 자동 세이브니 순간을 기억하는 중 너무 좋습니다. 로드도 너무 좋습니다. 갓벽

> 마우스는 기본 지급되어 있습니다. 키보드처럼 일반 Iuput이죠. 하지만 사용하기 위한 마우스 포인터는 시뮬레이션 UI 획득 시 같이 생성됩니다. (마우스 아이콘 바꾸는 내용을 빼먹었군요!)

확인 했습니다

> '이미테이션'이라는 느낌에 집중해서 그런지 미니게임의 세계관에 집중하진 않았습니다. 일반적으로 따라해서 색감을 바꾼 도트 그래픽을 그대로 따라가는 것으로 계획했습니다. 솔직히 팩맘이라고 해서, 유령대신 아이들로 대체하고 싶기도 했고 그에 따른 아이디어도 많았는데 그러면 미니 게임이 너무 확장되고 이미테이션했다는 느낌을 주기 어려울 거 같았습니다. 이미테이션 게임을 이상하게 만들어서 게임이 금방 잊혀졌다라는 느낌을 주고 싶었죠. 그래서 게임의 규칙이나 그런 부분이 어설프게 짜인 부분 또한 있습니다.

조금 초기 기획과 달라진 부분이 있지만, 키워드 중심으로 서브 시스템을 생각한다면, 사람들에게서 잊혀진 게임(유명 게임을 모티브로 이미테이션 했기 때문에), 병 맛, 라플리가 해당 세계관에 접속등을 생각할 수 있을 것 같습니다.

하지만 서브시스템 또한 이 게임에서 되게 중요한 부분이라고 생각합니다.

이미테이션 게임이라고 완성도가 낮다는 걸 유저에게 설명하기 보다 병맛적인 성향이 강해서 잊혀졌다가 좀 더 재밌을 것 같습니다.

미니게임 자체에 너무 무게를 두는게 아니냐? 라고 할 수 있지만 그래도 해당 시스템에서도 완성도가 높았으면 합니다..!

따라서 좀 더 특이한? 완성된 시스템, 웃긴 기능등이 있으면 좋을 것 같습니다.

GameOver에는 그게 좀 더 어울리는 것 같아요

> 소지품 관련 내용은 배제했고, 너무 선형적인 느낌이 강하긴 합니다만 실제 레벨 디자인을 해서 유저 경로나 순서 등을 고민하다보면 더 나아질 거 같습니다.

같이 계속 고민해보죠, 분명 한번은 방탈출이라는 매너리즘에 빠지게 될 텐데 무조건 해결할 수 있다고 생각합니다.

>  옵션 UI는 변형이 없습니다. 그 때 받은 걸 쭈욱 갈 예정입니다.

그렇다면 인터랙티브 UI 쪽은 받으면 고정되고 인게임 UI쪽만 일회성으로 교체되는 건가요?

개인적으로 인터랙티비 UI도 다른 게임의 장르에 맞게 바뀌면 좋을 것  같긴한데 조금 먼 이야기네요

> 억지로 합친 느낌이 저도 강하게 듭니다. 그렇다고 로그라이크의 추가적인 아이템 및 스킬, 몬스터 설계에 힘을 써서 로그라이크 느낌을 강하게 하는 것보다, 기존 사용했던 UI 및 방식을 재활용해서 나아가면 좀 더 효율적이지 않을까란 생각을 했습니다. 로그라이크 또한 게임 내에서 10분 이내로 짧게 즐기는 것이므로... (맵은 재활용합니다.)

단순 걱정이라 마찬가지로 제작해보고 생각하는 것도 좋아 보입니다.

아직은 초기 기획이니까 계속 변동성을 생각하고 작업해보면 될 것 같아요

> 로그라이크가 가미되었다는 연출은 일단 영화적 연출을 생각하고 있습니다. 그에 따라 달려 있던 UI가 화면 밖으로 밀려나오고 자연스레 UI 변경 또한 유도할 수 있다고 생각합니다.

저도 연출에 조금 힘을 써서 제작하는 편이 좋습니다. 영화적 연출, 연극 연출 다 좋습니다.

> 마을로 복귀해서 심마니들이 이번 탐사 때 모은 물건을 모아 놓다가 뒤섞임이 발생해 그래픽이 바뀜.
로그라이크 플레이 이후, 마을 사람들에 환영을 받은 주인공은 휴유증으로 쓰러지게 되고 눈떠보니 장르가 변화되어 있음.

요 부분은 나중에 1챕터 마무리되고 해당 기획서 보고 피드백 하겠읍니다.

> 창의력 이슈로 쓰러졌습니다. 시간 관계상, 레벨 디자인 이후 금주 시간이 남을 시 들어갈 예정입니다. 아니면 다음주 이슈에 들어갈 거 같습니다.

확인입니다!

**Comment by wooyn730** [comment]
팩맘 위주 질문 쪼금 드립니다
1. 대화 넘기는 키를 마우스 우클릭으로 지정한 이유가 있는지 (다른건 키보드 키라)
2. 팩맘이 죽으면(목숨 0개 시) 라플리는 자유롭게 움직이는 건지
3. 유령들끼리는 통과(충돌 무시), 유령과 라플리는 통과 불가 인건지
4. 라플리랑 팩맘의 코인 개수가 같은 케이스가 있는지 (없다면 코인이 홀수인거겠죠?)
5. 라플리가 팩맘을 잡으면 팩맘이 모아둔 코인을 흡수하는 건지

++
저도 서브A는 좀 더 과감하게(?) 가도 될 것 같습니다
저는 아이들(대가리만?)도 괜찮다구 생각 ^_^..

++
> 폰트는 최대한 따라하기 (손글씨 추천)

👆 이거 보고 생각났는데 동호님도 게임 현지화 전에 알아야할 것들 한 번 정도만 읽어주시면 좋을 것 같습니다. (손글씨가 손으로 그리라는 건지 손글씨같은 폰트를 쓰라는 건지는 모르겠지만... 근데 SCORE과 LIVES 같은 건 현지화에 고려안해도 될만한 요소일수도 있겠네요)

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/25e611c1-96c9-4cf9-a86b-7650bf073986)
- #37

**Comment by CreatorLDH** [comment]
의견 감사합니다.

1. 키보드키와 우클릭 혼합사용으로 생각했습니다.
=> 게임 진행중에 키보드와 마우스를 같이 사용하는 경우가 다소 많다고 생각해 유저의 편의성을 고려했습니다.
더불어 키보드와 마우스 우클릭을 같이 사용하는 비주얼 노벨, RPG와 같은 장르 또한 사용할 수 있기에 미리 고려했습니다.

2. 네 맞습니다. 팩맘을 빠르게 죽으면, 남은 코인(자원)을 라플리가 다 먹을 수 있겠죠! 그럼 더 쉽게 게임을 이길 수 있습니다.

3. 네 맞습니다.

4. 좋은 의견 감사합니다. 홀수로 나아가야겠네요! 

5. 이 점은 팩맘 구체화할 때 기입하려고 했던 내용입니다. 
- 반(코인이 홀수면 내림)을 흡수하는 것
- 반정도가 임의로 필드에 재생성되는 것

고민중입니다.

++
고려하겠습니다. 그럼 유령들이 팩맘을 '잡는다'는 의미 또한 다시 생각해볼게요!
아트 부분이 강하니, 시스템 변경상 거의 없게끔 고려하겠습니다.

맞습니다.
Coin Score lives 와 같은 용어만 손글씨(실제 아트분의 영어글씨)입니다!


현지화 내용 감사합니다. 다시 한번 검토하겠습니다.
