### ISSUE TITLE
Feat: Pac-man clone coding

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#86]
# Feat: Pac-man clone coding

## 설명

팩맘의 원본인 팩맨 클론 코딩!

**목표**
Milestone 0.0.5: 맵과 움직임 구현
Milestone 0.0.6: 클론 코딩 완성

[참고](https://github.com/zigurous/unity-pacman-tutorial)

## 기능

**Milestone 0.0.5**
- [x] 팩맨 맵 구현
- [x] 팩맨 움직임 구현

**Milestone 0.0.6**
- [x] 팩맨 동전 먹기 구현
- [x] 유령 구현

## 메모

**Milestone 0.0.5**
### 카메라

Projection(투영 방식)엔 Perspective 방식과 Orthographic 방식이 있음.

Perspective: 카메라 위치에서부터 투영선이 벌어짐. 사물에 대한 원근감과 공간감 효현
Orthographic: 투영선이 평행을 이룸. 멀리 있든 가까이 있는 게임 오브젝트 사이즈만큼 보임. size가 커지면 더 넓은 화면을 보여주고 오브젝트가 작게 보임.

[참고](https://angliss.cc/unity-camera-projection/)

### 회전
```
float angle = Mathf.Atan2(movement.direction.x, movement.direction.y);
this.transform.rotation = Quaternion.AngleAxis(angle * Mathf.Rad2Deg * -1 + 90, Vector3.forward);
```
atan(아크탄젠트) 함수는 좌표평면에서 수평축으로부터 한 점까지의 각도를 구할 때 쓰임

Mathf.atan(y/x) 함수로 쉽고 간단하게 각도를 구할 수 있음
하지만 x좌표값이 0이라면 y/0이 되어 버그 발생

atan2 함수는 인자를 y, x 두개를 받아 계산상에서 오류가 발생할 일이 없음

Mathf.Atan2(y 벡터값, x 벡터값) 함수에 넣으면 Radian값(float형)을 구할 수 있는데,
그렇게 구한 Radian 값에 Mathf.Rad2Deg 를 곱셈 연산을 하면 Degree 값으로 변환하여 사용할 수 있음

AngleAxis() 메서드는 axis를 중심으로 angle(˚)만큼 회전시킨 Quaternion을 반환

[참고1](https://devruby7777.tistory.com/entry/Unity-Atan-%ED%95%A8%EC%88%98%EC%99%80-Atan2-%ED%95%A8%EC%88%98%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90) [참고2](https://blog.naver.com/happybaby56/221324822755) [참고3](https://blog.naver.com/baek2sm/220945756736)

*근데 참고 영상은 angle \* Mathf.Rad2Deg인데 나는 angle \* Mathf.Rad2Deg \* -1 + 90 해야 정상적으로 보이는지 모르겠음..*

**Milestone 0.0.6**

### InvokeRepeating

Invoke(string methodName, float time)
지연 호출
time초 뒤에 methodName을 실행시켜라

InvokeRepeating(string methodName, float time, float repeatRate)
지연 반복 호출
time초 뒤에 methodName을 repeatRate초마다 실행시켜라

### Pixels Per Unit

Unit: Scene의 격자 네모 한 칸

Pixels Per Unit: 한 유닛의 몇 pixel을 보여줄건지 설정하는 값

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/e12cc106-46ee-4cec-940f-03489a1c3a22)

[참고1](https://hohola.tistory.com/3) [참고2](https://a6ly.dev/96)

### Active

A.activeSelf : A.SetActive(bool)에 영향을 받는다.

A.activeInHierarchy : A.SetActive(bool)에 따라 변하며, 또한 A의 부모가 있다면 부모의 SetActive(bool)에 영향을 받는다. 자신보다 부모상태를 먼저 따른다.

[참고](https://devmae.tistory.com/402)

### 인스펙터 Debug mode

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/922667f0-082e-4f3b-87b1-8a3b41985665)

[참고](https://learnandcreate.tistory.com/1662)

### yield return null

[참고](https://bloodstrawberry.tistory.com/980)

yield return null은 Update 후 호출
++
WaitForFixedUpdate는 FixedUpdate가 종료된 후 호출
WaitForEndOfFrame은 프레임이 종료된 후 호출

라이프사이클에 대해 더 알아보기

### 읽어본 글

[Raycast](https://ssabi.tistory.com/29)

[{ get; private set; }](https://bloodstrawberry.tistory.com/732)

[다형성](https://ansohxxn.github.io/c%20sharp/ch5-5/)

[[Unity3D] 벡터의 길이(크기)와 활용 / Vector3.magnitude](https://m.blog.naver.com/os2dr/221576752200)

[isKinematic](https://docs.unity3d.com/ScriptReference/Rigidbody-isKinematic.html)

### 그 외

- 클론 코딩 이후 키 입력 new input으로 바꿔보기 + Test code 작성

**Comment by wooyn730** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/5b2c2641-23b7-484f-9225-a40b95b38e01)

왜 타일맵이 3x3으로 찍힐가요...

**Comment by fkdl0048** [comment]
이거 설명 가능한데 지금 지하철이라 집 가서 코멘트 달겠으빈다

**Comment by fkdl0048** [comment]
8 * 3 = 24 픽셀로 보시면 됩니다.

격자 사이즈 한 칸이 그럼 8 * 8 사이즈네요 해당 스프라이트 한 단위당? 그래서 이미지 크기에 따라 지정할 수 있게 통일되게 할 수 있는 기능이 저 pixles per unit입니당

**Comment by wooyn730** [comment]
아~ Pixel Per Unit이 뭔지 이제 알았네요
영상에서도 일부 스프라이트는 크기 따라 수치를 조정하네요
꼼꼼히 보고 잘 검색하는 습관을 가져야겠습니다
감사밥니다!

**Comment by wooyn730** [comment]
23-10-28 마일스톤 0.0.5 Task 완료

**Comment by fkdl0048** [comment]
혹시 해당 브랜치에서 작업한거라면 저도 확인해봐도 될까요?

**Comment by wooyn730** [comment]
넴

**Comment by fkdl0048** [comment]
클론 코딩이라 코드 리뷰나 피드백을 주는게 크게 의미가 없지만, 궁금한 부분과 오류부분만 적었습니다!

- 스크립트는 클론 프로젝트라 Script폴더로 일부러 옮기지 않은건지 (현재 presets)
- 현재 Pacman 애니메이션 방식에 대한 생각 궁금
- 쓰시는 IDE UTF-8 설정에 대해서 맞추는 게 좋아보입니다.
- 추가로 Newinput로 변환하실 때 테스트 코드도 같이 짜보면 좋을 것 같습니다

![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/dc31ed9b-588f-4c19-82a9-0a311c873875)

**Comment by wooyn730** [comment]
1. 넵 pacman 폴더 나중에 통째로 지우려고 했습니다 (근데 지금은 그냥 presets에 넣었는데 samples 폴더 같은거 만들어서 넣어놓는게 낫겠다는 생각도 드네요)
2. 이거 안보고 했으면 그냥 애니메이션 만들고 애니메이터 연결했을 것 같습니다
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/74857c8d-c7a4-4d6a-a7c1-b78cf23fe1b3)
*대충 이렇게*
3. 알겠습니다 .editorconfig 파일 추가하고 파일 UTF-8로 저장해두었습니다!
4. 넵!! (조금 두렵지만..)
5. 네 맞네요.... 폴더도 그렇고 서브시스템 많아질수록 구조 관리를 잘 해야할 거 같슴다

**Comment by fkdl0048** [comment]
1. 좋습니다. 토이 프로젝트는 PR 자체를 안하는 방법도 있고, 병합한다면 Sample쪽에 모아두고 나중에 쉽게 삭제하면 좋을 듯 하네요
2. 애니메이터가 좀 더 하이레벨이라면 현재는 코드로만 작업한 부분이라 뭐가 더 이득일지 아직 감이 잘 안서지만, 코드는 에셋이 줄어든다는 장점이 있지만, 그만큼 수정(이벤트, 액션등에 따라) 달라질 수 있어서 지금 생각엔 애니메이터로 하는게 효율적일 것 같습니다?
3. 넵 -> 요거는 이 브랜치말고 따로 issue파서 기록해주세요
4. 좋습니다! (테스트와 리뷰는 항상 베이스라는 거)
5. 이것도 다음 비정기 때 이야기 해봅시다

**Comment by wooyn730** [comment]
넵넵 3번 이슈도 정기 회의 전에 파서 처리하겠습니다

**Comment by wooyn730** [comment]
23-11-06

유령과 발판 사이 충돌 문제 때문에 딜레이...

- 유령과 발판이 충돌 감지는 되어야하지만 유령과 발판은 물리 충돌이 일어나면 안되는데 일어남
- isTrigger가 체크 되어있으면 충돌 감지 O, 물리 충돌 X로 알고 있음
- 발판은 콜라이더가 있고 isTrigger 체크, 유령은 콜라이더와 rigidbody가 있고 isTrigger 체크 X
- (몇명한테 물어봤는데 아직 모르겠음)
- 팩맨 프로젝트를 다운받아서 뜯어보거나 동영상 다시 볼 예정...

**Comment by fkdl0048** [comment]
회의 끝나고 잠깐 보면 좋을 것 같아요! 아니면 그냥 바로 디코나 카톡으로 연락주셔도 됩니다 ㅠㅠㅠ!

**Comment by wooyn730** [comment]
UI 배치 제외하고 클론 코딩 완료

벌써 일요일이라 프로토타입은 하루 안에 가능한 범위로 최대한 해 볼 예정...
![흑흑](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSJf-BWPQAiVtHxl8ykFHcfiKX2_haYjYvWPN7VuG4g&s)

++ 사담

![스크린샷 2023-11-10 195744](https://github.com/GG-Studio-990001/GameOver/assets/80298207/4fc9c55d-5abe-4861-8c53-b472183ee23c)
유니티 커스텀 하이어라키 작업하다가 갑자기 바뀌어가지고(?) 버튼 잘못누른건가 했는데 정안님이 추가하신 것 같더라고요
이쁩니다 좋네요

요즘 날씨 벌써 영하까지 떨어지던데 추워서 손시렺고 자꾸 오타가 나더라고요
보일러를 틀어야겠어요 다들 추위 조심하세요 ㅠ

**Comment by fkdl0048** [comment]
- https://github.com/GG-Studio-990001/GameOver/issues/127

해당 이슈에 영상있습니다! 바인딩된 PR확인하셔도 되고 영상 참고하시면 좋아용

**Comment by wooyn730** [comment]
아 저게 그거였군요 감사합니다!

**Comment by fkdl0048** [comment]
프로토타입 너무 무리하지 마시고 계획을 먼저 상세하게 잡아보시는 걸 추천합니다.

동호님 팩맘 개발자 문서를 보고 요구사항을 개발 순서에 맞게 이슈로 세분화해서 정리해보면 오히려 개발이 쉬워질겁니당

**Comment by wooyn730** [comment]
넵!!!!!!!!!!!!!!!
