### ISSUE TITLE
Feat: Yarn Spinner Sample Study

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#90]
# Feat: Yarn Spinner Sample Study

## 설명

플밍 비정기 회의를 통해 제공되는 Sample을 뜯어보고 실제 활용 방법 등을 보는 좋은 공부 방법을 알게 됨.

그래서 이번 마일스톤엔 Yarn Spinner 샘플을 뜯어보면서 추가적으로 공부해 볼 것!

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9b02b049-656e-4289-a886-18954de29bc9)

### 선택하려는 선택지 강조

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/713bb727-a7c5-4ce5-a4cf-b0df3a3c095b)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f97a586e-8517-40c6-86d8-f887912989bf)

Option View에서 Transition을 Sprite Swap으로 설정하고
Target Grapic 할당 후 Select Sprite 지정 (캡처에서는 기본 스프라이트 투명, 선택 스프라이트 >)

마우스 커서가 캡처가 안되었지만 위 선택지에 올리고 있음

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8a2b6de8-de81-4b00-9c01-0f9e328c8230)

Color Tint도 가능

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8ddcd758-e4a4-4ccc-996a-e1eff3c28f7c)

Option View 스크립트에서 구현되어있기 때문

### 대사에 맞는 오디오 재생

<details><summary>샘플 오류</summary><p>

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/5a058691-f82f-405e-ba97-baeb5eee8944)

*샘플 씬 중 하나를 다운받으면 이런 오류가 뜨는데*

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/d60daf46-8cea-43b6-bb7f-3ddca88c9b56)

*Yarn project의 inspector에서 아무거나 만지면 오류 사라짐... 이후 같은 샘플 삭제하고 다시 로드해도 오류 안뜸 왜인지는 모르겠음;;;*

*오류 원인 찾으려고 이것저것 오래 뒤져봤는데 어이가 업네요*

</p></details>

[참고 영상](https://www.youtube.com/watch?v=hFfxpLMVJhE&t=108s&ab_channel=HenryMead)
1. 폴더 만들고 사운드 넣기
2. Yarn Project에 Localisation 설정 후 Asset Folder 연결
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/b3e3c96c-dd7d-4732-8b60-61391022e328)
3. Yarn Script 라인 끝에 #line: '오디오 클립 이름' 작성
4. 게임 오브젝트에 Audio Line Provider 삽입 (Voice Over View가 있는 게임오브젝트나 Dialogue Runner 있는 게임 오브젝트나 ㄱㅊ)
5. Dialogue Runner의 Line Provider에 Audio Line Provider가 있는 게임 오브젝트 연결

### 카메라 움직임

```
newPosition.x = Mathf.Clamp(newPosition.x, minPosition, maxPosition);
```

Clamp(클램프): 최소 / 최대값 을 설정하여 float 값이 범위 이외의 값을 넘지 않도록 함

Yarn Spinner 기능 관련은 아닌데 몰랐어요 신기...

### YarnCommand

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f32c38cf-4f2d-4192-ad42-3d294df656b1)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8aa10aec-3c32-4db4-bb6c-d29fbee283ff)

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/047ebe8e-d52f-4765-ab83-38f2e9f974a6)

Yarn Command로 스프라이트를 바꿔주는 부분인데 왜 setsprite happy가 아닌지 모르겠다
=> [참고](https://yarnspinner.dev/api/yarn.unity/yarncommandattribute/)
YarnCommandAttribute는 해당 스크립트가 담겨있는 게임오브젝트를 먼저 호출해줘야하는 거였음!!!

코맨드 만드는 종류는
1. YarnCommand attribute
```
[YarnCommand("setsprite")]
public void UseSprite(string spriteName) { ... }
```

2. AddCommandHandler() function
```
runner.AddCommandHandler<string>("Scene", DoSceneChange );
...
public void DoSceneChange(string spriteName) { ... }
```

두 가지인듯.
근데 1번은 얀 스피너 1.0 문서에서 설명하는 걸로 보니 옛날에 쓰던 거고 요즘은 2번 쓰는 듯...??? 

### Tooltip

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0e33facf-d307-499a-95cf-b65759d4fbca)

```
[Tooltip("설명")]
public GameObject 변수;
```

inspector창에서 변수 위에 마우스를 가져다대면, Tooltip에 작성한 내용이 보인다.
해당 변수가 어떤 기능을 하는지 찾아보기 위해 스크립트를 뒤적거리지 않아도 된다.

[참고1](https://codingmania.tistory.com/191) [참고2](https://velog.io/@rmscjf2002/Unity-%EA%B8%B0%EC%B4%88-tooltip)

### RequireComponent

```
[RequireComponent(typeof(속성명))] // 클래스 선언 전
public class 클래스명
```

RequireComponent속성은 요구되는 컴포넌트를 종속성으로 자동으로 추가해준다.
설정 오류를 방지하는데 유용하다.

[참고1](https://artiper.tistory.com/105)

++

샘플을 뜯어보는 과정은 Yarn Spinner의 기능 뿐만 아니라 유니티 몰랐던 기능과 함수들을 공부하는데 유용했다.
앞으로도 공부할 때 샘플이나 완성본의 코드를 뜯어보는 것을 잘 활용해야겠다!!

**Comment by wooyn730** [comment]
23-10-30 완료

근데 다 못해서 다음 주 조금만 더 공부하겠습니다..
(사유: 금요일 회의 때 브머라 모임 깜빡하고 이틀치 이슈 생성..ㅎㅎ)

**Comment by fkdl0048** [comment]
- 대부분 라이브러리에서 버전은 올리는데 샘플은 업데이트를 안해서 샘플에 오류가 있는 경우가 많습니다.
- 선택지 강조같은 기능이나, 현재 작성된 기획안을 토대로 feature를 뜯어보고, 기획에게 계속 사용하게 될 기능에 대해 물어보는 것이 좋습니다.
- clamp는 그 클램프라는 목공 기구가 있는데 그걸로 기억하면 쉽습니다. 고정시키는 건데 위 아래로 꽉 조여서 못 움직이게 하는걸 함수로 표현한 재밌는 수학함수랍니다..^^
- 과거에 안쓰는건 대부분 주석이나 애트리뷰트로 표현해주니 파악하시면 좋습니다.
- 타이핑 효과 관련 에셋인데 이거 사용해야 할 것 같네요 [에셋](https://prf.hn/click/camref:1101l7zGS/destination:https://assetstore.unity.com/packages/slug/254677)

**Comment by wooyn730** [comment]
정말정말 도움이 되는 코멘트 감사함니다.. 👍

동호님한테 대화 시스템에 대해 한 번 정리해서 여쭤보면 필요한 것만 공부하기 좋겠네요!!

에셋에 귀여운 애니메이션이 많네요 ^_^ 사용 확정인가여?

**Comment by fkdl0048** [comment]
- 대사중에 localization은 필요 없을 것 같습니다.

지역화설정은 대부분 초반에 1회만 사용하니 생각안하고 작업해도 될 것 같아요 후순위라서

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/13e1d7e2-4b31-4057-8332-b14dc5c32cde)

위에서 말한 Text Animation 구매 했습니다..!
