### ISSUE TITLE
[Bug] Fix: 한글 주석 깨짐

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#95]
# BUG: 한글 주석 깨짐

## Description

- #86 comment 참고
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9dcc88be-39c2-48cd-a9f2-f90fd0a44565)
한글 주석이 깨지는 현상

## Solution

기본으로 ANSI 파일로 저장하게 되어있어서 한글 주석이 깨짐.
.editorconfig 파일 추가 후
```
[*]
charset = utf-8
```
쓰기

일부 파일은 직접 utf-8로 직접 다시 저장해줌

## ETC

이슈 이름과 브랜치 이름 통일하는게 좋겠죠..?
이슈 이름 영어로 바꿀까요..?

**Comment by fkdl0048** [comment]
- 지금도 좋습니다, 이슈는 알아보기 쉽게 한글로 하고 브랜치는 영어로 해도 좋아요 다만, 사용했던 브랜치는 무조건 삭제 해주셔야 합니다..!
![image](https://github.com/GG-Studio-990001/GameOver/assets/84510455/423363a6-374d-4e14-b871-fd16c1166ebd)

**Comment by wooyn730** [comment]
Fix 외에도 사용 완료한 브랜치는 다 지우면 될까요??

**Comment by fkdl0048** [comment]
네 Feature작업 기준 완료된 브랜치는 삭제입니다.

이후에 Reopen헤서 작업하더라도 새로운 브랜치로 작업하시면 됩니다.
